import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  en: {
    fields: {
      "mode": "What to do",
      "unit": "Unit",
      "price": "Pack price, $",
      "amount": "Amount in the pack",
      "priceA": "Price of pack A, $",
      "amountA": "Amount in pack A",
      "priceB": "Price of pack B, $",
      "amountB": "Amount in pack B",
    },
    options: {
      "single": "price per unit",
      "compare": "compare two packs",
      "kg": "kilogram",
      "l": "litre",
      "pcs": "piece",
    },
    results: {
      "Цена за единицу": "Price per unit",
      "Упаковка A": "Pack A",
      "Цена упаковки": "Pack price",
      "Количество в упаковке": "Amount in the pack",
      "Упаковка B": "Pack B",
      "Выгоднее": "Cheaper option",
      "Переплата за единицу": "Overpayment per unit",
      "Проверьте данные": "Check the values",
    },
    values: {
      "₽": "$",
      "за кг": "per kg",
      "за л": "per l",
      "за шт": "per pcs",
      "A": "A",
      "B": "B",
      "одинаково": "the same",
      "Количество должно быть больше нуля": "The amount must be greater than zero",
      "Цена должна быть больше нуля": "The price must be greater than zero",
    },
  },
  uk: {
    fields: {
      "mode": "Що робимо",
      "unit": "Одиниця",
      "price": "Ціна упаковки, ₴",
      "amount": "Кількість в упаковці",
      "priceA": "Ціна упаковки A, ₴",
      "amountA": "Кількість в упаковці A",
      "priceB": "Ціна упаковки B, ₴",
      "amountB": "Кількість в упаковці B",
    },
    options: {
      "single": "ціна за одиницю",
      "compare": "порівняти дві упаковки",
      "kg": "кілограм",
      "l": "літр",
      "pcs": "штука",
    },
    results: {
      "Цена за единицу": "Ціна за одиницю",
      "Упаковка A": "Упаковка A",
      "Цена упаковки": "Ціна упаковки",
      "Количество в упаковке": "Кількість в упаковці",
      "Упаковка B": "Упаковка B",
      "Выгоднее": "Вигідніше",
      "Переплата за единицу": "Переплата за одиницю",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "₽": "₴",
      "за кг": "за кг",
      "за л": "за л",
      "за шт": "за шт",
      "A": "A",
      "B": "B",
      "одинаково": "однаково",
      "Количество должно быть больше нуля": "Кількість має бути більшою за нуль",
      "Цена должна быть больше нуля": "Ціна має бути більшою за нуль",
    },
  },
};
