import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was zu tun ist',
      'unit': 'Einheit',
      'price': 'Preis der Packung, €',
      'amount': 'Inhalt der Packung',
      'priceA': 'Preis der Packung A, €',
      'amountA': 'Inhalt der Packung A',
      'priceB': 'Preis der Packung B, €',
      'amountB': 'Inhalt der Packung B',
    },
    options: {
      'single': 'Preis je Einheit',
      'compare': 'zwei Packungen vergleichen',
      'kg': 'Kilogramm',
      'l': 'Liter',
      'pcs': 'Stück',
    },
    results: {
      'Цена за единицу': 'Preis je Einheit',
      'Упаковка A': 'Packung A',
      'Цена упаковки': 'Preis der Packung',
      'Количество в упаковке': 'Inhalt der Packung',
      'Упаковка B': 'Packung B',
      'Выгоднее': 'Günstiger',
      'Переплата за единицу': 'Mehrpreis je Einheit',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      '₽': '€',
      'за кг': 'je kg',
      'за л': 'je l',
      'за шт': 'je Stk',
      'A': 'A',
      'B': 'B',
      'одинаково': 'gleich',
      'Количество должно быть больше нуля': 'Der Inhalt muss größer als null sein',
      'Цена должна быть больше нуля': 'Der Preis muss größer als null sein',
    },
  },
  en: {
    fields: {
      "mode": "What to do",
      "unit": "Unit",
      "price": "Pack price, $",
      "amount": "Amount in the pack",
      "priceA": "Price of pack A, $",
      "amountA": "Amount in pack A",
      "priceB": "Price of pack B, $",
      "amountB": "Amount in pack B",
    },
    options: {
      "single": "price per unit",
      "compare": "compare two packs",
      "kg": "kilogram",
      "l": "litre",
      "pcs": "piece",
    },
    results: {
      "Цена за единицу": "Price per unit",
      "Упаковка A": "Pack A",
      "Цена упаковки": "Pack price",
      "Количество в упаковке": "Amount in the pack",
      "Упаковка B": "Pack B",
      "Выгоднее": "Cheaper option",
      "Переплата за единицу": "Overpayment per unit",
      "Проверьте данные": "Check the values",
    },
    values: {
      "₽": "$",
      "за кг": "per kg",
      "за л": "per l",
      "за шт": "per pcs",
      "A": "A",
      "B": "B",
      "одинаково": "the same",
      "Количество должно быть больше нуля": "The amount must be greater than zero",
      "Цена должна быть больше нуля": "The price must be greater than zero",
    },
  },
  uk: {
    fields: {
      "mode": "Що робимо",
      "unit": "Одиниця",
      "price": "Ціна упаковки, ₴",
      "amount": "Кількість в упаковці",
      "priceA": "Ціна упаковки A, ₴",
      "amountA": "Кількість в упаковці A",
      "priceB": "Ціна упаковки B, ₴",
      "amountB": "Кількість в упаковці B",
    },
    options: {
      "single": "ціна за одиницю",
      "compare": "порівняти дві упаковки",
      "kg": "кілограм",
      "l": "літр",
      "pcs": "штука",
    },
    results: {
      "Цена за единицу": "Ціна за одиницю",
      "Упаковка A": "Упаковка A",
      "Цена упаковки": "Ціна упаковки",
      "Количество в упаковке": "Кількість в упаковці",
      "Упаковка B": "Упаковка B",
      "Выгоднее": "Вигідніше",
      "Переплата за единицу": "Переплата за одиницю",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "₽": "₴",
      "за кг": "за кг",
      "за л": "за л",
      "за шт": "за шт",
      "A": "A",
      "B": "B",
      "одинаково": "однаково",
      "Количество должно быть больше нуля": "Кількість має бути більшою за нуль",
      "Цена должна быть больше нуля": "Ціна має бути більшою за нуль",
    },
  },
};
