import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  en: {
    fields: { "formula": "Chemical formula" },
    options: {},
    results: {
      "Молярная масса": "Molar mass",
      "Атомов всего": "Atoms in total",
      "Элементов": "Elements",
      "Масса одной молекулы": "Mass of one molecule",
      "Состав вещества": "Composition",
      "Элемент": "Element",
      "Атомов": "Atoms",
      "Атомная масса": "Atomic mass",
      "Вклад в массу": "Contribution to mass",
      "Доля массы": "Share of mass",
      "Проверьте данные": "Check the values",
    },
    values: {
      "г/моль": "g/mol",
      "·10⁻²⁴ г": "·10⁻²⁴ g",
      "Атомные массы — стандартные атомные веса IUPAC в сокращённой записи.": "Atomic masses are IUPAC standard atomic weights in abridged form.",
      "Введите химическую формулу": "Enter a chemical formula",
      "Лишняя закрывающая скобка": "Unmatched closing bracket",
      "Не хватает закрывающей скобки": "A closing bracket is missing",
      "Множитель группы не может быть нулём": "A group multiplier cannot be zero",
    },
  },
  uk: {
    fields: { "formula": "Хімічна формула" },
    options: {},
    results: {
      "Молярная масса": "Молярна маса",
      "Атомов всего": "Атомів усього",
      "Элементов": "Елементів",
      "Масса одной молекулы": "Маса однієї молекули",
      "Состав вещества": "Склад речовини",
      "Элемент": "Елемент",
      "Атомов": "Атомів",
      "Атомная масса": "Атомна маса",
      "Вклад в массу": "Внесок у масу",
      "Доля массы": "Частка маси",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "г/моль": "г/моль",
      "·10⁻²⁴ г": "·10⁻²⁴ г",
      "Атомные массы — стандартные атомные веса IUPAC в сокращённой записи.": "Атомні маси — стандартні атомні ваги IUPAC у скороченому записі.",
      "Введите химическую формулу": "Введіть хімічну формулу",
      "Лишняя закрывающая скобка": "Зайва закривна дужка",
      "Не хватает закрывающей скобки": "Бракує закривної дужки",
      "Множитель группы не может быть нулём": "Множник групи не може бути нулем",
    },
  },
  de: {
      fields: {
        'formula': 'Summenformel',
      },
      options: {},
      results: {
        'Молярная масса': 'Molare Masse',
        'Атомов всего': 'Atome insgesamt',
        'Элементов': 'Elemente',
        'Масса одной молекулы': 'Masse eines Moleküls',
        'Состав вещества': 'Zusammensetzung',
        'Элемент': 'Element',
        'Атомов': 'Atome',
        'Атомная масса': 'Atommasse',
        'Вклад в массу': 'Massenbeitrag',
        'Доля массы': 'Massenanteil',
        'Проверьте данные': 'Prüfe die Werte',
      },
      values: {
        'г/моль': 'g/mol',
        '·10⁻²⁴ г': '·10⁻²⁴ g',
        'Атомные массы — стандартные атомные веса IUPAC в сокращённой записи.': 'Die Atommassen sind die abgekürzten Standard-Atomgewichte der IUPAC.',
        'Введите химическую формулу': 'Gib eine Summenformel ein',
        'Лишняя закрывающая скобка': 'Überzählige schließende Klammer',
        'Не хватает закрывающей скобки': 'Es fehlt eine schließende Klammer',
        'Множитель группы не может быть нулём': 'Ein Gruppenfaktor darf nicht null sein',
      },
  },
};
