import type { CalculatorCopy } from '../../lib/platform/types';

export const cacCopyEn: CalculatorCopy = {
  "name": "Customer acquisition cost calculator",
  "slug": "customer-acquisition-cost",
  "shortDescription": "Average acquisition spend per new customer and lifetime revenue divided by CAC.",
  "seoTitle": "CAC calculator — customer acquisition cost and LTV to CAC",
  "seoDescription": "Calculate acquisition spend per new customer and lifetime revenue divided by CAC, without a profitability rating.",
  "h1": "Customer acquisition cost calculator",
  "keywords": [
    "customer acquisition cost",
    "CAC",
    "LTV to CAC"
  ],
  "longDescription": "CAC measures the average spend to acquire one new customer. Compare channels only when their cost scope and definition of a new customer match. The optional input here is expected revenue over the whole customer relationship. Dividing that revenue by CAC shows revenue coverage, but does not establish profit: a ratio of 4.5 from revenue of 9,000 and CAC of 2,000 leaves production, service, refunds and the timing of cash out of the calculation.",
  "howItWorks": "CAC = acquisition spend ÷ new customers. If CAC and supplied lifetime revenue are positive, the ratio = lifetime revenue per customer ÷ CAC. Retention, margin and discounting are not estimated. Zero spend with customers gives CAC 0; the revenue ratio then requires division by zero and cannot be calculated. Blank lifetime revenue or 0 omits that row. Ordinary CAC amounts retain whole currency-unit rounding; amounts below one unit use decimals.",
  "howToUse": [
    "Match acquisition spend to the customers from the same cohort; account for the delay between spending and closing a long sales cycle.",
    "Enter nonnegative spend and a positive whole customer count, at most 9,007,199,254,740,991.",
    "Optionally enter revenue per customer over the entire relationship, rather than revenue for one month.",
    "Use one currency for all money inputs. The locale symbol is a display convention; no exchange rate is applied. The ratio receives no health rating."
  ],
  "example": "Spend of 100,000 for 50 new customers gives CAC = 100,000 ÷ 50 = 2,000. Lifetime revenue of 9,000 gives 9,000 ÷ 2,000 = 4.50 : 1. With zero spend and the same 50 customers, CAC is 0 and the ratio cannot be calculated.",
  "faq": [
    {
      "q": "Which costs belong in acquisition spend?",
      "a": "Choose a consistent scope: advertising, agency fees, salaries and tools for the part of marketing and sales that acquires new customers. Serving existing customers uses a different cost base. Compare channels using the same cost scope."
    },
    {
      "q": "Does a 3 : 1 ratio prove profitability?",
      "a": "No. This input is lifetime revenue, rather than profit or contribution margin. Even a high ratio may fail to cover production and service costs. The calculator applies no universal 3 : 1 threshold."
    },
    {
      "q": "How should a long sales cycle be handled?",
      "a": "Match costs to the customer cohort with the appropriate delay. Dividing this month’s spending by customers generated by an older campaign can move CAC in either direction; matching calendar dates alone is insufficient."
    },
    {
      "q": "Should organic customers be included?",
      "a": "For blended CAC, include all new customers and the corresponding costs. For a paid channel’s CAC, use that channel’s customers and costs. Both scopes can be useful, but should not be mixed when comparing results."
    },
    {
      "q": "What does zero CAC mean?",
      "a": "The entered spend is zero. It does not prove acquisition was free if costs were omitted. With positive revenue the ratio stays “—”, because it would require division by zero."
    },
    {
      "q": "Can fractional attribution credits be entered as customers?",
      "a": "This tool accepts the actual whole count of new customers. Fractional attribution credits use a different measurement base and should not be silently rounded into people."
    }
  ],
  "disclaimer": "Acquisition spend and a ratio to supplied lifetime revenue. Does not calculate profit, payback time or currency exchange."
};
