import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'targetIncome': 'Zieleinkommen netto je Monat, €',
      'workDays': 'Arbeitstage je Monat',
      'hoursPerDay': 'Arbeitsstunden je Tag',
      'billablePct': 'Abrechenbarer Anteil der Stunden, %',
      'expenses': 'Betriebskosten je Monat, €',
      'taxPct': 'Steuersatz, %',
    },
    results: {
      'Ставка за час': 'Stundensatz',
      'Оплачиваемых часов': 'Abrechenbare Stunden',
      'Нужно выставить счетов': 'Zu stellende Rechnungen',
      'Ставка за день': 'Tagessatz',
      'Расходы на работу': 'Betriebskosten',
      'Налог': 'Steuer',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      '₽': '€',
      'ч': 'h',
      'Желаемый доход должен быть больше нуля': 'Das Zieleinkommen muss größer als null sein',
      'Число рабочих дней должно быть больше нуля': 'Die Zahl der Arbeitstage muss größer als null sein',
      'Число часов в дне должно быть больше нуля': 'Die Zahl der Stunden je Tag muss größer als null sein',
      'Оплачиваемая доля должна быть больше нуля': 'Der abrechenbare Anteil muss größer als null sein',
      'Расходы не могут быть отрицательными': 'Die Kosten können nicht negativ sein',
      'Ставка налога должна быть меньше 100 %': 'Der Steuersatz muss unter 100 % liegen',
    },
  },
  en: {
    fields: {
      "targetIncome": "Target take-home per month, $",
      "workDays": "Working days per month",
      "hoursPerDay": "Working hours per day",
      "billablePct": "Billable share of hours, %",
      "expenses": "Business costs per month, $",
      "taxPct": "Tax rate, %",
    },
    options: {},
    results: {
      "Ставка за час": "Hourly rate",
      "Оплачиваемых часов": "Billable hours",
      "Нужно выставить счетов": "Must invoice",
      "Ставка за день": "Day rate",
      "Расходы на работу": "Business costs",
      "Налог": "Tax",
      "Проверьте данные": "Check the values",
    },
    values: {
      "₽": "$",
      "ч": "h",
      "Желаемый доход должен быть больше нуля": "The target income must be greater than zero",
      "Число рабочих дней должно быть больше нуля": "The number of working days must be greater than zero",
      "Число часов в дне должно быть больше нуля": "The number of hours per day must be greater than zero",
      "Оплачиваемая доля должна быть больше нуля": "The billable share must be greater than zero",
      "Расходы не могут быть отрицательными": "Costs cannot be negative",
      "Ставка налога должна быть меньше 100 %": "The tax rate must be below 100%",
    },
  },
  uk: {
    fields: {
      "targetIncome": "Бажаний дохід на руки за місяць, ₴",
      "workDays": "Робочих днів на місяць",
      "hoursPerDay": "Робочих годин на день",
      "billablePct": "Частка оплачуваних годин, %",
      "expenses": "Витрати на роботу за місяць, ₴",
      "taxPct": "Ставка податку, %",
    },
    options: {},
    results: {
      "Ставка за час": "Ставка за годину",
      "Оплачиваемых часов": "Оплачуваних годин",
      "Нужно выставить счетов": "Треба виставити рахунків",
      "Ставка за день": "Ставка за день",
      "Расходы на работу": "Витрати на роботу",
      "Налог": "Податок",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "₽": "₴",
      "ч": "год",
      "Желаемый доход должен быть больше нуля": "Бажаний дохід має бути більшим за нуль",
      "Число рабочих дней должно быть больше нуля": "Кількість робочих днів має бути більшою за нуль",
      "Число часов в дне должно быть больше нуля": "Кількість годин на день має бути більшою за нуль",
      "Оплачиваемая доля должна быть больше нуля": "Частка оплачуваних годин має бути більшою за нуль",
      "Расходы не могут быть отрицательными": "Витрати не можуть бути від'ємними",
      "Ставка налога должна быть меньше 100 %": "Ставка податку має бути меншою за 100 %",
    },
  },
  es: {
    fields: {
      "targetIncome": "Ingresos netos objetivo al mes, €",
      "workDays": "Días de trabajo al mes",
      "hoursPerDay": "Horas de trabajo al día",
      "billablePct": "Parte facturable de las horas, %",
      "expenses": "Gastos del negocio al mes, €",
      "taxPct": "Tipo impositivo, %",
    },
    options: {},
    results: {
      "Ставка за час": "Tarifa por hora",
      "Оплачиваемых часов": "Horas facturables",
      "Нужно выставить счетов": "Hay que facturar",
      "Ставка за день": "Tarifa por día",
      "Расходы на работу": "Gastos del negocio",
      "Налог": "Impuesto",
      "Проверьте данные": "Revisa los datos",
    },
    values: {
      "₽": "€",
      "ч": "h",
      "Желаемый доход должен быть больше нуля": "Los ingresos objetivo deben ser mayores que cero",
      "Число рабочих дней должно быть больше нуля": "El número de días de trabajo debe ser mayor que cero",
      "Число часов в дне должно быть больше нуля": "El número de horas al día debe ser mayor que cero",
      "Оплачиваемая доля должна быть больше нуля": "La parte facturable debe ser mayor que cero",
      "Расходы не могут быть отрицательными": "Los gastos no pueden ser negativos",
      "Ставка налога должна быть меньше 100 %": "El tipo impositivo debe ser inferior al 100 %",
    },
  },
};
