// СГЕНЕРИРОВАНО. Не редактировать руками.
// Общие фразы результата, отобранные под наследственный калькулятор calorie-calculator.
// Перегенерировать: npm run calculators:generate

import type { CalculatorLocalization } from '../../../../lib/platform/types';

export const shared: CalculatorLocalization = {
  en: {
    results: {
      'Проверьте данные': 'Check inputs',
      'Результат': 'Result',
      'Из': 'From',
      'В': 'To',
      'Дневная оценка энергии': 'Daily energy estimate',
      'Расход энергии в покое (REE)': 'Resting energy expenditure (REE)',
      'Белки': 'Protein',
      'Жиры': 'Fat',
      'Углеводы': 'Carbs',
      'Изменение': 'Change',
      'Поддержание веса (TDEE)': 'Weight maintenance (TDEE)',
    },
    values: {
      'Выберите мужскую или женскую формулу': 'Select the male or female equation',
      'Выберите цель расчёта': 'Select a calculation goal',
      'Введите возраст от 19 до 78 лет, конечные рост и вес больше нуля': 'Enter age 19–78 and finite positive height and weight',
      'Выберите коэффициент активности из списка': 'Select an activity multiplier from the list',
      'Изменение калорий должно быть от 0 до 30 процентов': 'Calorie adjustment must be 0–30 percent',
      'Доли белков и жиров должны быть от 10 до 60 процентов каждая и в сумме не больше 100': 'Protein and fat must each be 10–60 percent and sum to no more than 100',
      'Результат выходит за числовой диапазон': 'The result exceeds the numeric range',
      'Это сценарий оценки расхода и распределения энергии. Коэффициент активности, процент изменения и доли БЖУ — выбранные допущения, а не индивидуальное назначение или прогноз скорости изменения веса.': 'This scenario estimates energy expenditure and allocation. Activity, adjustment and macro percentages are chosen assumptions, not an individual prescription or weight-change-rate forecast.',
    },
  },
  uk: {
    results: {
      'Проверьте данные': 'Перевірте дані',
      'Результат': 'Результат',
      'Из': 'З',
      'В': 'У',
      'Дневная оценка энергии': 'Денна оцінка енергії',
      'Расход энергии в покое (REE)': 'Витрати енергії у спокої (REE)',
      'Белки': 'Білки',
      'Жиры': 'Жири',
      'Углеводы': 'Вуглеводи',
      'Изменение': 'Зміна',
      'Поддержание веса (TDEE)': 'Підтримання ваги (TDEE)',
    },
    values: {
      'Выберите мужскую или женскую формулу': 'Оберіть чоловічу або жіночу формулу',
      'Выберите цель расчёта': 'Оберіть мету розрахунку',
      'Введите возраст от 19 до 78 лет, конечные рост и вес больше нуля': 'Введіть вік 19–78, скінченні додатні зріст і масу',
      'Выберите коэффициент активности из списка': 'Оберіть коефіцієнт активності зі списку',
      'Изменение калорий должно быть от 0 до 30 процентов': 'Зміна калорій має бути 0–30 відсотків',
      'Доли белков и жиров должны быть от 10 до 60 процентов каждая и в сумме не больше 100': 'Білки й жири мають бути по 10–60 відсотків і разом не більше 100',
      'Результат выходит за числовой диапазон': 'Результат виходить за числовий діапазон',
      'Это сценарий оценки расхода и распределения энергии. Коэффициент активности, процент изменения и доли БЖУ — выбранные допущения, а не индивидуальное назначение или прогноз скорости изменения веса.': 'Сценарій оцінки витрат і розподілу енергії. Активність, зміна та частки БЖВ — обрані припущення, не призначення чи прогноз швидкості зміни маси.',
    },
  },
  de: {
    results: {
      'Проверьте данные': 'Prüfe die Werte',
      'Результат': 'Ergebnis',
      'Из': 'Von',
      'В': 'Nach',
      'Дневная оценка энергии': 'Tagesenergieschätzung',
      'Расход энергии в покое (REE)': 'Ruheenergieverbrauch (REE)',
      'Белки': 'Eiweiß',
      'Жиры': 'Fett',
      'Углеводы': 'Kohlenhydrate',
      'Изменение': 'Veränderung',
      'Поддержание веса (TDEE)': 'Gewicht halten (TDEE)',
    },
    values: {
      'Выберите мужскую или женскую формулу': 'Männliche oder weibliche Formel wählen',
      'Выберите цель расчёта': 'Berechnungsziel auswählen',
      'Введите возраст от 19 до 78 лет, конечные рост и вес больше нуля': 'Alter 19–78 und endliche positive Größe und Masse eingeben',
      'Выберите коэффициент активности из списка': 'Aktivitätsfaktor aus der Liste auswählen',
      'Изменение калорий должно быть от 0 до 30 процентов': 'Kalorienänderung muss 0–30 Prozent betragen',
      'Доли белков и жиров должны быть от 10 до 60 процентов каждая и в сумме не больше 100': 'Protein und Fett jeweils 10–60 Prozent, zusammen höchstens 100',
      'Результат выходит за числовой диапазон': 'Das Ergebnis überschreitet den Zahlenbereich',
      'Это сценарий оценки расхода и распределения энергии. Коэффициент активности, процент изменения и доли БЖУ — выбранные допущения, а не индивидуальное назначение или прогноз скорости изменения веса.': 'Szenario für Energieverbrauch und Verteilung. Aktivität, Änderung und Makroanteile sind Annahmen, keine persönliche Verordnung oder Prognose der Gewichtsänderungsrate.',
    },
  },
  es: {
    results: {
      'Проверьте данные': 'Revisa los datos',
      'Результат': 'Resultado',
      'Из': 'De',
      'В': 'A',
      'Дневная оценка энергии': 'Estimación de energía diaria',
      'Расход энергии в покое (REE)': 'Gasto energético en reposo (REE)',
      'Белки': 'Proteínas',
      'Жиры': 'Grasas',
      'Углеводы': 'Hidratos de carbono',
      'Изменение': 'Variación',
      'Поддержание веса (TDEE)': 'Mantenimiento del peso (GET)',
    },
    values: {
      'Выберите мужскую или женскую формулу': 'Selecciona fórmula masculina o femenina',
      'Выберите цель расчёта': 'Selecciona un objetivo',
      'Введите возраст от 19 до 78 лет, конечные рост и вес больше нуля': 'Introduce edad 19–78 y estatura y peso finitos positivos',
      'Выберите коэффициент активности из списка': 'Elige factor de actividad de la lista',
      'Изменение калорий должно быть от 0 до 30 процентов': 'El ajuste calórico debe ser 0–30 por ciento',
      'Доли белков и жиров должны быть от 10 до 60 процентов каждая и в сумме не больше 100': 'Proteína y grasa deben ser 10–60 por ciento cada una y sumar como máximo 100',
      'Результат выходит за числовой диапазон': 'El resultado excede el rango numérico',
      'Это сценарий оценки расхода и распределения энергии. Коэффициент активности, процент изменения и доли БЖУ — выбранные допущения, а не индивидуальное назначение или прогноз скорости изменения веса.': 'Escenario de gasto y reparto energético. Actividad, ajuste y macros son supuestos, no prescripción personal ni pronóstico de ritmo de cambio de peso.',
    },
  },
};
