import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'items': 'Abonnements: Name, Preis und Zeitraum in Monaten je Zeile',
    },
    results: {
      'В месяц': 'Im Monat',
      'В год': 'Im Jahr',
      'Подписок': 'Abonnements',
      'Самая дорогая': 'Teuerstes',
      'Её вклад в месяц': 'Sein Anteil im Monat',
      'Подписки в пересчёте на месяц': 'Abonnements auf den Monat gerechnet',
      'Подписка': 'Abonnement',
      'Цена': 'Preis',
      'Месяцев': 'Monate',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      '₽': '€',
      'Нужны название, цена и период в месяцах в строке:': 'In der Zeile werden Name, Preis und Zeitraum in Monaten gebraucht:',
      'Цена и период должны быть числами в строке:': 'Preis und Zeitraum müssen Zahlen sein, in der Zeile:',
      'Период в месяцах должен быть больше нуля в строке:': 'Der Zeitraum in Monaten muss größer als null sein, in der Zeile:',
      'Цена не может быть отрицательной': 'Der Preis kann nicht negativ sein',
      'Введите хотя бы одну подписку': 'Trage mindestens ein Abonnement ein',
    },
  },
  en: {
    fields: { "items": "Subscriptions: name, price and period in months per line" },
    options: {},
    results: {
      "В месяц": "Per month",
      "В год": "Per year",
      "Подписок": "Subscriptions",
      "Самая дорогая": "Most expensive",
      "Её вклад в месяц": "Its share per month",
      "Подписки в пересчёте на месяц": "Subscriptions per month",
      "Подписка": "Subscription",
      "Цена": "Price",
      "Месяцев": "Months",
      "Проверьте данные": "Check the values",
    },
    values: {
      "₽": "$",
      "Нужны название, цена и период в месяцах в строке:": "Name, price and period in months are required on the line:",
      "Цена и период должны быть числами в строке:": "Price and period must be numbers on the line:",
      "Период в месяцах должен быть больше нуля в строке:": "The period in months must be greater than zero on the line:",
      "Цена не может быть отрицательной": "The price cannot be negative",
      "Введите хотя бы одну подписку": "Enter at least one subscription",
    },
  },
  uk: {
    fields: { "items": "Підписки: назва, ціна і період у місяцях у рядку" },
    options: {},
    results: {
      "В месяц": "На місяць",
      "В год": "На рік",
      "Подписок": "Підписок",
      "Самая дорогая": "Найдорожча",
      "Её вклад в месяц": "Її внесок на місяць",
      "Подписки в пересчёте на месяц": "Підписки в перерахунку на місяць",
      "Подписка": "Підписка",
      "Цена": "Ціна",
      "Месяцев": "Місяців",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "₽": "₴",
      "Нужны название, цена и период в месяцах в строке:": "Потрібні назва, ціна і період у місяцях у рядку:",
      "Цена и период должны быть числами в строке:": "Ціна і період мають бути числами в рядку:",
      "Период в месяцах должен быть больше нуля в строке:": "Період у місяцях має бути більшим за нуль у рядку:",
      "Цена не может быть отрицательной": "Ціна не може бути від'ємною",
      "Введите хотя бы одну подписку": "Введіть хоча б одну підписку",
    },
  },
};
