import type { CalcFunction } from '../../lib/types';
import { fmtNumber } from '../../lib/format';
import { integer, number, text } from '../../lib/platform/scalarInputDisplay';
import { formatMeasure, formatQuantity } from '../../lib/platform/measurement';
import { positiveRatio } from '../../lib/platform/scaledPositiveRatio';
import { unicodeWords } from '../../lib/platform/unicodeWords';
const clock=(seconds:number)=>seconds<0.5?`${formatQuantity(seconds,fmtNumber)} с`:`${Math.floor(Math.round(seconds)/60)} мин ${Math.round(seconds)%60} с`;
const minutesText=(n:number)=>n<1e-7||n>=1e12?formatQuantity(n,fmtNumber):formatMeasure(n,fmtNumber);
export const compute:CalcFunction=inputs=>{
 const fail=(message:string)=>({primary:{label:'Время чтения',value:'—'},secondary:[{label:'Проверьте данные',value:message,accent:'red' as const}]});
 const mode=inputs.mode===undefined?'words':inputs.mode;
 if(mode!=='words'&&mode!=='text')return fail('Выберите поддерживаемый режим расчёта');
 const wpm=number(inputs.wpm),speechWpm=number(inputs.speechWpm);
 if(wpm===null||speechWpm===null)return fail('Введите корректные числовые данные');
 const words=mode==='text'?(typeof inputs.text==='string'?unicodeWords(inputs.text).length:0):integer(inputs.words);
 if(words===null)return fail('Количество должно быть целым в допустимом диапазоне');
 if(!(words>0))return fail(mode==='text'?'Вставьте текст — в нём не найдено ни одного слова':'Число слов должно быть больше нуля');
 if(!(wpm>0))return fail('Скорость чтения должна быть больше нуля');
 if(!(speechWpm>0))return fail('Скорость речи должна быть больше нуля');
 const readSeconds=positiveRatio([words,60],[wpm]),speechSeconds=positiveRatio([words,60],[speechWpm]);
 const readMinutes=positiveRatio([words],[wpm]),speechMinutes=positiveRatio([words],[speechWpm]);
 if(![readSeconds,speechSeconds,readMinutes,speechMinutes].every(n=>Number.isFinite(n)&&n>0)||readSeconds>Number.MAX_SAFE_INTEGER||speechSeconds>Number.MAX_SAFE_INTEGER)return fail('Результат вне допустимого диапазона');
 return{primary:{label:'Время чтения',value:clock(readSeconds)},secondary:[{label:'Время вслух',value:clock(speechSeconds)},{label:'Чтение в минутах',value:minutesText(readMinutes)},{label:'Речь в минутах',value:minutesText(speechMinutes)},{label:'Слов',value:text(words,0)}]};
};
