import type { CalculatorDef } from '../../lib/types';
type Copy = Pick<CalculatorDef, 'longDescription' | 'howToUse' | 'howItWorks' | 'example' | 'faq' | 'disclaimer'>;

export const contractContent: Record<'ru' | 'en' | 'uk' | 'de' | 'es', Copy> = {
  ru: {
    longDescription: 'Срок окупаемости отвечает, когда введённые денежные поступления покрывают начальное вложение. Простой срок использует постоянный годовой поток, дисконтированный уменьшает стоимость будущих потоков по введённой годовой ставке. Это расчёт равномерного потока, начинающегося в первом году, без ограничения срока жизни проекта. Поэтому найденный срок нужно сопоставить с реальной продолжительностью поступлений.',
    howToUse: ['Введите положительное первоначальное вложение и положительный чистый денежный поток за год в одной валюте.', 'Поток означает поступления минус денежные расходы проекта; бухгалтерская амортизация сама по себе не является денежной выплатой.', 'Для простого срока достаточно ставки 0 %. При положительной ставке используйте согласованную с потоком годовую ставку дисконтирования.', 'Прочитайте метод дробного года: это линейная доля последнего дисконтированного годового потока, а не календарная дата поступления.', 'Сверьте результат со сроком жизни проекта. Неравные, отложенные или отрицательные потоки требуют отдельного графика.'],
    howItWorks: 'Простой срок = I / C. При r = ставка / 100 приведённая сумма n годовых потоков равна C/r × (1 − (1+r)^−n). Если C/r ≤ I, положительная ставка не допускает конечной дисконтированной окупаемости. Иначе логарифмы определяют последний год, а его поток учитывается линейной долей. У сумм дисконтирование на конец каждого года; показанная дробь не означает фактический платёж внутри года. Фиксированного предела 1 000 лет нет. Выход за числовую точность сообщается отдельно; сроки меньше 100 лет обычно отображаются до тысячных, от 100 лет — до сотых; для меньших величин точность увеличивается.',
    example: 'Вложение 1 000 000 при потоке 300 000 и ставке 0 % даёт 3,333 года, или 40 месяцев. При вложении 5 000 000, потоке 1 200 000 и 10 % простой срок 4,167, дисконтированный 5,666 года. Граница I = 100 000, C = 10 000, r = 10 % не имеет конечного дисконтированного срока. Пограничный пример: I = 100 000, C = 100,001, ставка 0,1 % даёт конечный срок около 11 518,69 года.',
    faq: [
      { q: 'Почему годовой поток отличается от бухгалтерской прибыли?', a: 'Окупаемость использует денежные поступления и выплаты. Начисленная амортизация меняет прибыль, но сама не является выплатой; налоги и инвестиционные платежи нужно учитывать в согласованном графике, которого в этой упрощённой форме нет.' },
      { q: 'Как читать дробную часть дисконтированного срока?', a: 'Она линейно распределяет приведённый поток последнего года. Если деньги фактически приходят единственным платежом в конце года, возврат наступает в конце этого целого года. Форма не принимает даты поступлений.' },
      { q: 'Почему равенство C/r = I тоже не даёт конечного срока?', a: 'При положительной ставке конечная сумма потоков меньше предела бесконечного ряда. К пределу она приближается, но не достигает его за конечное число лет. Числовой предел вычисления не означает такого математического равенства.' },
      { q: 'Откуда берётся ставка дисконтирования для этой формы?', a: 'Она задаётся пользователем, а не выводится из результата. Согласуйте годовую ставку, номинальные или реальные потоки и выбранную оценку стоимости капитала. Автоматически складывать инфляцию с рисковой надбавкой калькулятор не предлагает.' },
      { q: 'Можно ли выбрать лучший проект только по окупаемости?', a: 'Срок не учитывает вклад денежных потоков после окупаемости и не заменяет NPV или доходность. Два проекта с одним сроком могут различаться продолжительностью, риском и суммарным денежным результатом.' },
    ],
    disclaimer: 'Модель одного начального вложения и постоянного положительного годового потока. Нет срока жизни, переменных потоков, дат платежей или автоматической налоговой и инфляционной модели. Очень большие сроки — математические результаты допущений, а не прогноз существования проекта.',
  },
  en: {
    longDescription: 'Payback asks when the supplied cash receipts cover an initial investment. Simple payback uses a constant annual flow; discounted payback reduces future flows at the annual rate you enter. Receipts begin in year one and the model has no project-life field. A calculated payback duration must therefore be compared with how long the real cash flows are expected to continue.',
    howToUse: ['Enter a positive initial investment and positive annual net cash flow in the same currency.', 'Use cash receipts less cash expenses. Accounting depreciation is not itself a cash payment.', 'A zero discount rate gives the simple duration. A positive rate must be annual and consistent with the cash-flow basis.', 'Read the fractional-year convention: the final discounted annual flow is interpolated linearly, rather than assigned an actual receipt date.', 'Compare with project life. Unequal, delayed or negative flows require a separate cash-flow schedule.'],
    howItWorks: 'Simple duration = I / C. With decimal annual rate r, present value through year n is C/r × (1 − (1+r)^−n). If C/r ≤ I, no finite discounted payback exists at a positive rate. Otherwise logarithms locate the final year and a linear share of that year’s discounted flow is used. Annual values are discounted to each year-end; the displayed fraction is not an actual payment date. There is no fixed 1,000-year cutoff. Numerical precision/range limits are reported separately; durations below 100 years normally use up to three decimals, those from 100 years use up to two, and smaller values retain more digits.',
    example: 'Investment 1,000,000, annual flow 300,000 and 0% give 3.333 years or 40 months. Investment 5,000,000, flow 1,200,000 and 10% give simple payback 4.167 and discounted payback 5.666 years. At investment 100,000, flow 10,000 and 10%, finite discounted payback does not exist. Near the recovery boundary, investment 100,000, flow 100.001 and 0.1% give finite discounted payback of about 11,518.69 years.',
    faq: [
      { q: 'Why should the flow be cash rather than accounting profit?', a: 'Payback counts receipts and payments. Depreciation changes accounting profit but is not a cash outflow in itself. Taxes and investment payments need a consistent cash-flow schedule, which this simplified form does not construct.' },
      { q: 'What does the fraction of the final discounted year mean?', a: 'It spreads that year’s discounted annual flow linearly. If the money actually arrives as one payment at year-end, recovery occurs at the end of that whole year. The form has no receipt dates.' },
      { q: 'Why does a perpetual value exactly equal to investment not pay back?', a: 'At a positive rate each finite series is below its infinite-series limit. It approaches the investment but never reaches it in a finite year. Reaching a numerical calculation limit is a different condition.' },
      { q: 'How is the discount rate chosen here?', a: 'You supply it. Keep the annual rate consistent with nominal or real cash flows and the cost-of-capital basis you chose. The calculator does not automatically equate a rate to inflation plus a risk premium.' },
      { q: 'Can payback alone rank the better investment?', a: 'It omits the contribution of flows after recovery and does not replace NPV or a return measure. Projects with equal payback can have different lives, risks and total cash outcomes.' },
    ],
    disclaimer: 'One initial investment and a constant positive annual flow. Project life, varying flows, payment dates and automatic tax or inflation adjustments are absent. Extremely long durations describe mathematical assumptions rather than a forecast of project survival.',
  },
  uk: {
    longDescription: 'Строк окупності показує, коли введені грошові надходження покривають початкове вкладення. Простий строк використовує постійний річний потік, дисконтований враховує введену річну ставку. Надходження починаються з першого року, а строк життя проєкту у формі не заданий. Отриманий строк слід зіставити з реальною тривалістю надходжень.',
    howToUse: ['Уведіть додатне початкове вкладення та додатний чистий річний потік в одній валюті.', 'Потік — це надходження мінус грошові витрати; бухгалтерська амортизація сама по собі не є виплатою.', 'За ставки 0 % обидва строки збігаються. Додатну річну ставку узгодьте з основою грошових потоків.', 'Дробова частина — лінійна частка останнього дисконтованого річного потоку, а не дата платежу.', 'Перевірте строк життя проєкту. Нерівні, відкладені або від’ємні потоки потребують окремого графіка.'],
    howItWorks: 'Простий строк = I / C. Для r = ставка / 100 приведена сума n річних потоків дорівнює C/r × (1 − (1+r)^−n). За C/r ≤ I скінченна дисконтована окупність за додатної ставки неможлива. Інакше логарифми визначають останній рік, а його потік враховується лінійною часткою. Річні суми дисконтовано на кінець року; дробова відповідь не означає реальної виплати всередині року. Межі 1 000 років немає; обмеження числової точності повідомляється окремо. Строки менші за 100 років зазвичай показано до тисячних, від 100 років — до сотих; для малих значень точність збільшується.',
    example: 'Вкладення 1 000 000, потік 300 000 і ставка 0 % дають 3,333 року або 40 місяців. Вкладення 5 000 000, потік 1 200 000 і 10 % дають простий строк 4,167 та дисконтований 5,666 року. За I = 100 000, C = 10 000 і 10 % скінченного дисконтованого строку немає. Біля межі окупності I = 100 000, C = 100,001 і ставка 0,1 % дають скінченний строк близько 11 518,69 року.',
    faq: [
      { q: 'Чому грошовий потік не дорівнює бухгалтерському прибутку?', a: 'Окупність рахує надходження та виплати. Амортизація змінює прибуток, але сама не є грошовою виплатою. Податки й інвестиційні платежі потребують узгодженого графіка, якого ця спрощена форма не створює.' },
      { q: 'Що означає частка останнього дисконтованого року?', a: 'Вона лінійно розподіляє приведений річний потік. Якщо надходження насправді є одним платежем наприкінці року, повернення відбувається в кінці цього цілого року. Дат платежів у формі немає.' },
      { q: 'Чому рівність C/r = I не дає скінченної окупності?', a: 'За додатної ставки кожна скінченна сума менша за межу нескінченного ряду. Вона наближається до вкладення, але не досягає його за скінченну кількість років. Межа точності обчислення — інша причина відсутності числової відповіді.' },
      { q: 'Як задано ставку дисконтування?', a: 'Її вводить користувач. Річну ставку слід узгодити з номінальними або реальними потоками та обраною оцінкою вартості капіталу. Автоматичного додавання інфляції й надбавки за ризик тут немає.' },
      { q: 'Чи визначає окупність найвигідніший проєкт?', a: 'Строк не враховує внесок потоків після повернення вкладення та не замінює NPV або дохідність. За однакового строку проєкти можуть мати різні тривалість, ризик і загальний грошовий результат.' },
    ],
    disclaimer: 'Модель одного вкладення та постійного додатного річного потоку. Строк життя, змінні потоки, дати платежів, автоматичні податки й інфляційні поправки не задані. Дуже довгі строки — наслідок математичних припущень, а не прогноз існування проєкту.',
  },
  de: {
    longDescription: 'Die Amortisationsdauer fragt, wann eingegebene Zahlungsüberschüsse die Anfangsinvestition decken. Die einfache Dauer verwendet einen konstanten Jahresstrom; die abgezinste Dauer bewertet spätere Ströme mit dem eingegebenen Jahreszinssatz. Zuflüsse beginnen im ersten Jahr. Eine Projektlaufzeit wird nicht eingegeben, deshalb muss das Ergebnis mit der tatsächlichen Dauer der Zuflüsse verglichen werden.',
    howToUse: ['Investition und jährlicher Nettozahlungsstrom müssen positiv sein und dieselbe Währung verwenden.', 'Verwende Einzahlungen abzüglich Auszahlungen. Buchhalterische Abschreibung ist selbst keine Auszahlung.', 'Bei 0 % stimmen beide Dauern überein. Ein positiver Jahreszinssatz muss zur Basis der Zahlungsströme passen.', 'Die Jahresfraktion interpoliert den letzten abgezinsten Jahresstrom linear und ist kein Zahlungstermin.', 'Prüfe die Projektlaufzeit. Unterschiedliche, verspätete oder negative Ströme benötigen einen eigenen Zahlungsplan.'],
    howItWorks: 'Einfache Dauer = I / C. Bei dezimalem Jahreszinssatz r beträgt der Barwert bis Jahr n: C/r × (1 − (1+r)^−n). Ist C/r ≤ I, gibt es bei positivem r keine endliche abgezinste Amortisation. Sonst bestimmen Logarithmen das letzte Jahr; dessen abgezinster Strom wird als linearer Anteil berücksichtigt. Jahreswerte werden jeweils zum Jahresende abgezinst, die Fraktion beschreibt keinen tatsächlichen Zahlungstag. Eine feste Grenze von 1 000 Jahren gibt es nicht. Numerische Grenzen werden gesondert gemeldet; Dauern unter 100 Jahren haben üblicherweise bis zu drei Nachkommastellen, ab 100 Jahren bis zu zwei; kleine Werte behalten mehr Stellen.',
    example: 'Investition 1 000 000, Jahresstrom 300 000 und 0 % ergeben 3,333 Jahre oder 40 Monate. Mit 5 000 000, 1 200 000 und 10 % sind es einfach 4,167 und abgezinst 5,666 Jahre. Bei I = 100 000, C = 10 000 und 10 % ist die abgezinste Dauer nicht endlich. Nahe der Amortisationsgrenze ergeben I = 100 000, C = 100,001 und 0,1 % eine endliche Dauer von etwa 11 518,69 Jahren.',
    faq: [
      { q: 'Warum ist Zahlungsstrom nicht gleich Buchgewinn?', a: 'Amortisation zählt Einzahlungen und Auszahlungen. Abschreibung verändert den Gewinn, ist aber für sich keine Zahlung. Steuern und Investitionszahlungen brauchen einen konsistenten Plan, den diese vereinfachte Eingabe nicht erstellt.' },
      { q: 'Was bedeutet der Anteil des letzten abgezinsten Jahres?', a: 'Der Barwert des Jahresstroms wird darin linear verteilt. Geht das Geld tatsächlich als einzelne Zahlung am Jahresende ein, erfolgt die Rückzahlung am Ende dieses ganzen Jahres. Zahlungstermine werden nicht eingegeben.' },
      { q: 'Warum reicht ein Grenzwert C/r = I nicht aus?', a: 'Bei positivem Zinssatz liegt jede endliche Summe unter dem Grenzwert der unendlichen Reihe. Sie nähert sich der Investition, erreicht sie aber nicht in einem endlichen Jahr. Numerische Genauigkeitsgrenzen sind ein anderer Sachverhalt.' },
      { q: 'Wer legt den Abzinsungssatz fest?', a: 'Du gibst ihn ein. Jahreszinssatz, nominale oder reale Ströme und gewählte Kapitalkostenbasis müssen zusammenpassen. Inflation und Risikoaufschlag werden nicht automatisch zu einer Rate addiert.' },
      { q: 'Ersetzt die Dauer einen Vergleich der Kapitalwerte?', a: 'Ströme nach der Amortisation tragen nicht mehr zur Dauer bei. Sie ersetzt weder Kapitalwert noch Rendite. Projekte mit gleicher Dauer können unterschiedliche Laufzeit, Risiken und gesamten Zahlungsüberschuss haben.' },
    ],
    disclaimer: 'Eine Anfangsinvestition und ein konstanter positiver Jahresstrom. Projektende, veränderliche Ströme, Zahlungstermine sowie automatische Steuer- oder Inflationsanpassungen fehlen. Sehr lange Dauern sind mathematische Modellergebnisse und keine Prognose für den Fortbestand eines Projekts.',
  },
  es: {
    longDescription: 'El plazo de recuperación indica cuándo los flujos introducidos cubren la inversión inicial. El plazo simple usa un flujo anual constante y el descontado reduce el valor de los flujos futuros con el tipo anual indicado. Los cobros empiezan en el primer año. No hay un campo de vida del proyecto, por lo que la duración obtenida debe compararse con la continuidad real de sus flujos.',
    howToUse: ['Introduce una inversión inicial positiva y un flujo anual neto positivo en la misma moneda.', 'Usa entradas menos salidas de caja. La amortización contable no es por sí misma un pago.', 'El 0 % da el plazo simple. Un tipo positivo debe ser anual y coherente con la base de los flujos.', 'La fracción final distribuye linealmente el último flujo anual descontado; no es una fecha de cobro.', 'Contrasta con la vida del proyecto. Los flujos variables, retrasados o negativos requieren un calendario aparte.'],
    howItWorks: 'Plazo simple = I / C. Con tipo anual decimal r, el valor presente hasta el año n es C/r × (1 − (1+r)^−n). Si C/r ≤ I, con r positivo no existe recuperación descontada finita. En otro caso los logaritmos localizan el último año y se usa una fracción lineal de su flujo descontado, como interpolación del último año. Los valores anuales se descuentan al cierre de cada año; la fracción no representa un cobro real dentro del año. No hay límite fijo de 1 000 años. Los límites numéricos se comunican por separado; los plazos inferiores a 100 años suelen usar hasta tres decimales y los de 100 años o más hasta dos; las magnitudes pequeñas conservan más cifras.',
    example: 'Inversión 1 000 000, flujo 300 000 y 0 % dan 3,333 años o 40 meses. Con 5 000 000, 1 200 000 y 10 %, el plazo simple es 4,167 y el descontado 5,666 años. Con I = 100 000, C = 10 000 y 10 % no hay plazo descontado finito. Cerca del límite de recuperación, I = 100 000, C = 100,001 y 0,1 % dan un plazo finito de unos 11 518,69 años.',
    faq: [
      { q: '¿Por qué el flujo de caja difiere del beneficio contable?', a: 'La recuperación utiliza cobros y pagos. La depreciación contable modifica el beneficio, pero no es por sí sola una salida de caja. Impuestos y pagos de inversión necesitan un calendario coherente que esta forma simplificada no crea.' },
      { q: '¿Qué significa la fracción del último año descontado?', a: 'Distribuye linealmente el flujo anual descontado. Si el dinero llega como un único cobro al cierre del año, la recuperación ocurre al final de ese año completo. No se introducen fechas de cobro.' },
      { q: '¿Por qué la igualdad C/r = I tampoco da un plazo finito?', a: 'Con tipo positivo, toda suma finita queda por debajo del límite de la serie infinita. Se acerca a la inversión sin alcanzarla en un número finito de años. Un límite de precisión numérica es una condición distinta.' },
      { q: '¿De dónde sale el tipo de descuento de esta forma?', a: 'Lo introduce el usuario. Debe ser anual y coherente con flujos nominales o reales y con la base elegida de coste de capital. La forma no suma automáticamente inflación y prima de riesgo.' },
      { q: '¿Basta el plazo para escoger el mejor proyecto?', a: 'No mide la aportación de flujos posteriores a la recuperación y no sustituye al VAN ni a una tasa de rentabilidad. Proyectos con igual plazo pueden diferir en vida, riesgo y caja total.' },
    ],
    disclaimer: 'Una inversión inicial y un flujo anual positivo constante. Excluye vida del proyecto, flujos variables, fechas y ajustes automáticos de impuestos o inflación. Los plazos muy largos son resultados de supuestos matemáticos, no previsiones de supervivencia del proyecto.',
  },
};
