import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  en: {
    fields: {
      "mode": "What to find",
      "m": "Mass, kg",
      "V": "Volume, m³",
      "rho": "Density, kg/m³",
      "V2": "Volume, m³",
      "m2": "Mass, kg",
      "rho2": "Density, kg/m³",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "the mass",
      "rho": "the density",
      "V": "the volume",
    },
    results: {
      "Плотность": "Density",
      "Масса": "Mass",
      "Объём": "Volume",
      "В граммах на кубический сантиметр": "In grams per cubic centimetre",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "кг/м³": "kg/m³",
      "кг": "kg",
      "г/см³": "g/cm³",
      "Объём должен быть больше нуля": "The volume must be greater than zero",
      "Масса должна быть больше нуля": "The mass must be greater than zero",
      "Плотность должна быть больше нуля": "The density must be greater than zero",
    },
  },
  uk: {
    fields: {
      "mode": "Що знайти",
      "m": "Маса, кг",
      "V": "Об’єм, м³",
      "rho": "Густина, кг/м³",
      "V2": "Об’єм, м³",
      "m2": "Маса, кг",
      "rho2": "Густина, кг/м³",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "масу",
      "rho": "густину",
      "V": "об’єм",
    },
    results: {
      "Плотность": "Густина",
      "Масса": "Маса",
      "Объём": "Об’єм",
      "В граммах на кубический сантиметр": "У грамах на кубічний сантиметр",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "кг/м³": "кг/м³",
      "кг": "кг",
      "г/см³": "г/см³",
      "Объём должен быть больше нуля": "Об’єм має бути більшим за нуль",
      "Масса должна быть больше нуля": "Маса має бути більшою за нуль",
      "Плотность должна быть больше нуля": "Густина має бути більшою за нуль",
    },
  },
  de: {
      fields: {
        'mode': 'Was gesucht ist',
        'm': 'Masse, kg',
        'V': 'Volumen, m³',
        'rho': 'Dichte, kg/m³',
        'V2': 'Volumen, m³',
        'm2': 'Masse, kg',
        'rho2': 'Dichte, kg/m³',
      },
      options: {
        'mm': 'Millimeter',
        'cm': 'Zentimeter',
        'm': 'die Masse',
        'rho': 'die Dichte',
        'V': 'das Volumen',
      },
      results: {
        'Плотность': 'Dichte',
        'Масса': 'Masse',
        'Объём': 'Volumen',
        'В граммах на кубический сантиметр': 'In Gramm je Kubikzentimeter',
        'Проверьте данные': 'Prüfe die Werte',
      },
      values: {
        'мм': 'mm',
        'см': 'cm',
        'м': 'm',
        'мм²': 'mm²',
        'см²': 'cm²',
        'м²': 'm²',
        'мм³': 'mm³',
        'см³': 'cm³',
        'м³': 'm³',
        'кг/м³': 'kg/m³',
        'кг': 'kg',
        'г/см³': 'g/cm³',
        'Объём должен быть больше нуля': 'Das Volumen muss größer als null sein',
        'Масса должна быть больше нуля': 'Die Masse muss größer als null sein',
        'Плотность должна быть больше нуля': 'Die Dichte muss größer als null sein',
      },
  },
};
