import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was gesucht ist',
      'F': 'Kraft, N',
      's': 'Weg, m',
      'W': 'Arbeit, J',
      'angleDeg': 'Winkel zwischen Kraft und Weg, °',
    },
    options: {
      'mm': 'Millimeter',
      'cm': 'Zentimeter',
      'm': 'Meter',
      'W': 'die Arbeit',
      's': 'der Weg',
    },
    results: {
      'Работа': 'Arbeit',
      'Сила': 'Kraft',
      'Перемещение': 'Weg',
      'Косинус угла': 'Kosinus des Winkels',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'мм': 'mm',
      'см': 'cm',
      'м': 'm',
      'мм²': 'mm²',
      'см²': 'cm²',
      'м²': 'm²',
      'мм³': 'mm³',
      'см³': 'cm³',
      'м³': 'm³',
      'Дж': 'J',
      'Н': 'N',
      'Сила не может быть отрицательной': 'Die Kraft kann nicht negativ sein',
      'Перемещение не может быть отрицательным': 'Der Weg kann nicht negativ sein',
      'Работа не может быть отрицательной': 'Die Arbeit kann nicht negativ sein',
      'Сила должна быть больше нуля, иначе перемещение не определено': 'Die Kraft muss größer als null sein, sonst ist der Weg nicht bestimmt',
      'При прямом угле сила работы не совершает, и перемещение из неё не выводится': 'Im rechten Winkel verrichtet die Kraft keine Arbeit, und der Weg lässt sich daraus nicht ableiten',
    },
  },
  en: {
    fields: {
      "mode": "What to find",
      "F": "Force, N",
      "s": "Displacement, m",
      "W": "Work, J",
      "angleDeg": "Angle between force and displacement, °",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "metres",
      "W": "the work",
      "s": "the displacement",
    },
    results: {
      "Работа": "Work",
      "Сила": "Force",
      "Перемещение": "Displacement",
      "Косинус угла": "Cosine of the angle",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Дж": "J",
      "Н": "N",
      "Сила не может быть отрицательной": "The force cannot be negative",
      "Перемещение не может быть отрицательным": "The displacement cannot be negative",
      "Работа не может быть отрицательной": "The work cannot be negative",
      "Сила должна быть больше нуля, иначе перемещение не определено": "The force must be greater than zero, otherwise the displacement is undetermined",
      "При прямом угле сила работы не совершает, и перемещение из неё не выводится": "At a right angle the force does no work, so no displacement follows from it",
    },
  },
  uk: {
    fields: {
      "mode": "Що знайти",
      "F": "Сила, Н",
      "s": "Переміщення, м",
      "W": "Робота, Дж",
      "angleDeg": "Кут між силою і переміщенням, °",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "метри",
      "W": "роботу",
      "s": "переміщення",
    },
    results: {
      "Работа": "Робота",
      "Сила": "Сила",
      "Перемещение": "Переміщення",
      "Косинус угла": "Косинус кута",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Дж": "Дж",
      "Н": "Н",
      "Сила не может быть отрицательной": "Сила не може бути від’ємною",
      "Перемещение не может быть отрицательным": "Переміщення не може бути від’ємним",
      "Работа не может быть отрицательной": "Робота не може бути від’ємною",
      "Сила должна быть больше нуля, иначе перемещение не определено": "Сила має бути більшою за нуль, інакше переміщення не визначене",
      "При прямом угле сила работы не совершает, и перемещение из неё не выводится": "За прямого кута сила роботи не виконує, і переміщення з неї не виводиться",
    },
  },
};
