import type { TranslatedLocale } from './types';

// Literal shared units and errors; no subject copy or numerical behavior.
export const geometryScalarValues: Readonly<Record<TranslatedLocale, Readonly<Record<string, string>>>> = {
  "en": {
    "мм": "mm",
    "см": "cm",
    "м": "m",
    "мм²": "mm²",
    "см²": "cm²",
    "м²": "m²",
    "мм³": "mm³",
    "см³": "cm³",
    "м³": "m³",
    "Введите конечные числа во все активные поля": "Enter finite numbers in every active field",
    "Выберите поддерживаемый режим расчёта": "Choose a supported calculation mode",
    "Выберите миллиметры, сантиметры или метры": "Choose millimetres, centimetres or metres",
    "Результат выходит за числовой диапазон; измените масштаб фигуры": "The result is outside the numeric range; change the scale of the figure",
    "Боковые стороны не могут быть отрицательными": "The legs cannot be negative",
    "Для периметра введите обе положительные боковые стороны или оставьте обе пустыми": "For perimeter enter both positive legs, or leave both blank",
    "Боковая сторона не может быть короче высоты": "A leg cannot be shorter than the height",
    "Основания, высота и боковые стороны не образуют одну трапецию": "The bases, height and legs do not form one consistent trapezoid"
  },
  "uk": {
    "мм": "мм",
    "см": "см",
    "м": "м",
    "мм²": "мм²",
    "см²": "см²",
    "м²": "м²",
    "мм³": "мм³",
    "см³": "см³",
    "м³": "м³",
    "Введите конечные числа во все активные поля": "Введіть скінченні числа в усі активні поля",
    "Выберите поддерживаемый режим расчёта": "Виберіть підтримуваний режим розрахунку",
    "Выберите миллиметры, сантиметры или метры": "Виберіть міліметри, сантиметри або метри",
    "Результат выходит за числовой диапазон; измените масштаб фигуры": "Результат виходить за числовий діапазон; змініть масштаб фігури",
    "Боковые стороны не могут быть отрицательными": "Бічні сторони не можуть бути від’ємними",
    "Для периметра введите обе положительные боковые стороны или оставьте обе пустыми": "Для периметра введіть обидві додатні бічні сторони або залиште обидві порожніми",
    "Боковая сторона не может быть короче высоты": "Бічна сторона не може бути коротшою за висоту",
    "Основания, высота и боковые стороны не образуют одну трапецию": "Основи, висота й бічні сторони не утворюють одну узгоджену трапецію"
  },
  "de": {
    "мм": "mm",
    "см": "cm",
    "м": "m",
    "мм²": "mm²",
    "см²": "cm²",
    "м²": "m²",
    "мм³": "mm³",
    "см³": "cm³",
    "м³": "m³",
    "Введите конечные числа во все активные поля": "Gib in alle aktiven Felder endliche Zahlen ein",
    "Выберите поддерживаемый режим расчёта": "Wähle einen unterstützten Rechenmodus",
    "Выберите миллиметры, сантиметры или метры": "Wähle Millimeter, Zentimeter oder Meter",
    "Результат выходит за числовой диапазон; измените масштаб фигуры": "Das Ergebnis liegt außerhalb des Zahlenbereichs; ändere den Maßstab der Figur",
    "Боковые стороны не могут быть отрицательными": "Die Schenkel dürfen nicht negativ sein",
    "Для периметра введите обе положительные боковые стороны или оставьте обе пустыми": "Gib für den Umfang beide positiven Schenkel ein oder lass beide leer",
    "Боковая сторона не может быть короче высоты": "Ein Schenkel darf nicht kürzer als die Höhe sein",
    "Основания, высота и боковые стороны не образуют одну трапецию": "Grundseiten, Höhe und Schenkel bilden kein geometrisch stimmiges Trapez"
  },
  "es": {
    "мм": "mm",
    "см": "cm",
    "м": "m",
    "мм²": "mm²",
    "см²": "cm²",
    "м²": "m²",
    "мм³": "mm³",
    "см³": "cm³",
    "м³": "m³",
    "Введите конечные числа во все активные поля": "Introduce números finitos en todos los campos activos",
    "Выберите поддерживаемый режим расчёта": "Elige un modo de cálculo admitido",
    "Выберите миллиметры, сантиметры или метры": "Elige milímetros, centímetros o metros",
    "Результат выходит за числовой диапазон; измените масштаб фигуры": "El resultado queda fuera del rango numérico; cambia la escala de la figura",
    "Боковые стороны не могут быть отрицательными": "Los lados laterales no pueden ser negativos",
    "Для периметра введите обе положительные боковые стороны или оставьте обе пустыми": "Para el perímetro introduce ambos lados laterales positivos, o deja los dos vacíos",
    "Боковая сторона не может быть короче высоты": "Un lado lateral no puede ser menor que la altura",
    "Основания, высота и боковые стороны не образуют одну трапецию": "Bases, altura y lados laterales no forman un trapecio compatible"
  }
};
