// СГЕНЕРИРОВАНО. Не редактировать руками.
// Общие фразы результата, отобранные под наследственный калькулятор bmi-calculator.
// Перегенерировать: npm run calculators:generate

import type { CalculatorLocalization } from '../../../../lib/platform/types';

export const shared: CalculatorLocalization = {
  en: {
    results: {
      'Проверьте данные': 'Check inputs',
      'Результат': 'Result',
      'Из': 'From',
      'В': 'To',
      'ИМТ': 'BMI',
      'Категория': 'Category',
      'Комментарий': 'Note',
      'Рост': 'Height',
      'Вес': 'Weight',
      'Ориентир здорового веса': 'Healthy weight reference',
    },
    values: {
      'Категория ИМТ не определяет диагноз или необходимое лечение.': 'A BMI category does not determine a diagnosis or required treatment.',
      ' и < ': ' and < ',
      'Взрослые категории рассчитаны для возраста от 20 лет. Категория выбирается до округления ИМТ; границы диапазона веса округлены. ИМТ не измеряет состав тела и не задаёт индивидуальную цель веса.': 'Adult categories apply from age 20. The category uses BMI before rounding; weight interval boundaries are rounded. BMI does not measure body composition or set an individual weight goal.',
      'Результат выходит за числовой диапазон': 'The result exceeds the numeric range',
      'Норма': 'Healthy range',
      'Недостаток веса': 'Underweight',
      'Выраженный дефицит': 'Severely underweight',
      'Избыточный вес': 'Overweight',
      'Ожирение I степени': 'Obesity class I',
      'Ожирение II степени': 'Obesity class II',
      'Ожирение III степени': 'Obesity class III',
      'Введите рост и вес': 'Enter height and weight',
    },
  },
  uk: {
    results: {
      'Проверьте данные': 'Перевірте дані',
      'Результат': 'Результат',
      'Из': 'З',
      'В': 'У',
      'ИМТ': 'ІМТ',
      'Категория': 'Категорія',
      'Комментарий': 'Коментар',
      'Рост': 'Зріст',
      'Вес': 'Вага',
      'Ориентир здорового веса': 'Орієнтир здорової ваги',
    },
    values: {
      'Категория ИМТ не определяет диагноз или необходимое лечение.': 'Категорія ІМТ не визначає діагнозу чи потрібного лікування.',
      ' и < ': ' і < ',
      'Взрослые категории рассчитаны для возраста от 20 лет. Категория выбирается до округления ИМТ; границы диапазона веса округлены. ИМТ не измеряет состав тела и не задаёт индивидуальную цель веса.': 'Дорослі категорії від 20 років. Категорія визначається до округлення ІМТ; межі маси округлені. ІМТ не вимірює склад тіла й не задає особисту ціль маси.',
      'Результат выходит за числовой диапазон': 'Результат виходить за числовий діапазон',
      'Норма': 'Нормальний діапазон',
      'Недостаток веса': 'Недостатня вага',
      'Выраженный дефицит': 'Виражений дефіцит ваги',
      'Избыточный вес': 'Надмірна вага',
      'Ожирение I степени': 'Ожиріння I ступеня',
      'Ожирение II степени': 'Ожиріння II ступеня',
      'Ожирение III степени': 'Ожиріння III ступеня',
      'Введите рост и вес': 'Введіть зріст і вагу',
    },
  },
  de: {
    results: {
      'Проверьте данные': 'Prüfe die Werte',
      'Результат': 'Ergebnis',
      'Из': 'Von',
      'В': 'Nach',
      'ИМТ': 'BMI',
      'Категория': 'Kategorie',
      'Комментарий': 'Hinweis',
      'Рост': 'Körpergröße',
      'Вес': 'Gewicht',
      'Ориентир здорового веса': 'Richtwert für gesundes Gewicht',
    },
    values: {
      'Категория ИМТ не определяет диагноз или необходимое лечение.': 'Eine BMI-Kategorie bestimmt weder Diagnose noch erforderliche Behandlung.',
      ' и < ': ' und < ',
      'Взрослые категории рассчитаны для возраста от 20 лет. Категория выбирается до округления ИМТ; границы диапазона веса округлены. ИМТ не измеряет состав тела и не задаёт индивидуальную цель веса.': 'Erwachsenen-Kategorien gelten ab 20. Die Kategorie wird vor BMI-Rundung gewählt; Gewichtsgrenzen sind gerundet. BMI misst keine Körperzusammensetzung und setzt kein persönliches Ziel.',
      'Результат выходит за числовой диапазон': 'Das Ergebnis überschreitet den Zahlenbereich',
      'Норма': 'Normalbereich',
      'Недостаток веса': 'Untergewicht',
      'Выраженный дефицит': 'Starkes Untergewicht',
      'Избыточный вес': 'Übergewicht',
      'Ожирение I степени': 'Adipositas Grad I',
      'Ожирение II степени': 'Adipositas Grad II',
      'Ожирение III степени': 'Adipositas Grad III',
      'Введите рост и вес': 'Trage Größe und Gewicht ein',
    },
  },
  es: {
    results: {
      'Проверьте данные': 'Revisa los datos',
      'Результат': 'Resultado',
      'Из': 'De',
      'В': 'A',
      'ИМТ': 'IMC',
      'Категория': 'Categoría',
      'Комментарий': 'Comentario',
      'Рост': 'Estatura',
      'Вес': 'Peso',
      'Ориентир здорового веса': 'Intervalo de peso saludable',
    },
    values: {
      'Категория ИМТ не определяет диагноз или необходимое лечение.': 'Una categoría de IMC no determina diagnóstico ni tratamiento necesario.',
      ' и < ': ' y < ',
      'Взрослые категории рассчитаны для возраста от 20 лет. Категория выбирается до округления ИМТ; границы диапазона веса округлены. ИМТ не измеряет состав тела и не задаёт индивидуальную цель веса.': 'Categorías adultas desde 20 años. Se eligen antes de redondear IMC; límites de peso redondeados. El IMC no mide composición ni fija meta personal.',
      'Результат выходит за числовой диапазон': 'El resultado excede el rango numérico',
      'Норма': 'Normal',
      'Недостаток веса': 'Bajo peso',
      'Выраженный дефицит': 'Delgadez severa',
      'Избыточный вес': 'Sobrepeso',
      'Ожирение I степени': 'Obesidad de grado I',
      'Ожирение II степени': 'Obesidad de grado II',
      'Ожирение III степени': 'Obesidad de grado III',
      'Введите рост и вес': 'Introduce la estatura y el peso',
    },
  },
};
