// СГЕНЕРИРОВАНО. Не редактировать руками.
// Общие фразы результата, отобранные под наследственный калькулятор bmi-calculator.
// Перегенерировать: npm run calculators:generate

import type { CalculatorLocalization } from '../../../../lib/platform/types';

export const shared: CalculatorLocalization = {
  en: {
    results: {
      'Проверьте данные': 'Check inputs',
      'Из': 'From',
      'В': 'To',
      'ИМТ': 'BMI',
      'Категория': 'Category',
      'Комментарий': 'Note',
      'Рост': 'Height',
      'Вес': 'Weight',
      'Ориентир здорового веса': 'Healthy weight reference',
    },
    values: {
      'Норма': 'Healthy range',
      'Недостаток веса': 'Underweight',
      'Выраженный дефицит': 'Severely underweight',
      'Избыточный вес': 'Overweight',
      'Ожирение I степени': 'Obesity class I',
      'Ожирение II степени': 'Obesity class II',
      'Ожирение III степени': 'Obesity class III',
      'Поддерживайте текущий режим.': 'Keep your current routine.',
      'Стоит набрать немного массы.': 'Consider gaining some weight.',
      'Рекомендуется снизить вес.': 'Consider reducing your weight.',
      'Обратитесь к специалисту.': 'Consult a healthcare professional.',
      'Необходима консультация врача.': 'A medical consultation is recommended.',
      'Срочно к врачу.': 'Seek medical advice promptly.',
      'Срочно обратитесь к врачу.': 'Seek medical advice promptly.',
      'ИМТ — ориентировочный показатель для взрослых. Он может быть менее точным для спортсменов, беременных и людей старшего возраста.': 'BMI is a screening measure for adults. It can be less accurate for athletes, pregnant people, and older adults.',
      'Введите рост и вес': 'Enter height and weight',
    },
  },
  uk: {
    results: {
      'Проверьте данные': 'Перевірте дані',
      'Из': 'З',
      'В': 'У',
      'ИМТ': 'ІМТ',
      'Категория': 'Категорія',
      'Комментарий': 'Коментар',
      'Рост': 'Зріст',
      'Вес': 'Вага',
      'Ориентир здорового веса': 'Орієнтир здорової ваги',
    },
    values: {
      'Норма': 'Нормальний діапазон',
      'Недостаток веса': 'Недостатня вага',
      'Выраженный дефицит': 'Виражений дефіцит ваги',
      'Избыточный вес': 'Надмірна вага',
      'Ожирение I степени': 'Ожиріння I ступеня',
      'Ожирение II степени': 'Ожиріння II ступеня',
      'Ожирение III степени': 'Ожиріння III ступеня',
      'Поддерживайте текущий режим.': 'Підтримуйте поточний режим.',
      'Стоит набрать немного массы.': 'Варто трохи збільшити масу тіла.',
      'Рекомендуется снизить вес.': 'Рекомендується знизити вагу.',
      'Обратитесь к специалисту.': 'Зверніться до фахівця.',
      'Необходима консультация врача.': 'Рекомендована консультація лікаря.',
      'Срочно к врачу.': 'Якнайшвидше зверніться до лікаря.',
      'Срочно обратитесь к врачу.': 'Якнайшвидше зверніться до лікаря.',
      'ИМТ — ориентировочный показатель для взрослых. Он может быть менее точным для спортсменов, беременных и людей старшего возраста.': 'ІМТ є орієнтовним показником для дорослих. Він може бути менш точним для спортсменів, вагітних і людей старшого віку.',
      'Введите рост и вес': 'Введіть зріст і вагу',
    },
  },
  de: {
    results: {
      'Проверьте данные': 'Prüfe die Werte',
      'Из': 'Von',
      'В': 'Nach',
      'ИМТ': 'BMI',
      'Категория': 'Kategorie',
      'Комментарий': 'Hinweis',
      'Рост': 'Körpergröße',
      'Вес': 'Gewicht',
      'Ориентир здорового веса': 'Richtwert für gesundes Gewicht',
    },
    values: {
      'Норма': 'Normalbereich',
      'Недостаток веса': 'Untergewicht',
      'Выраженный дефицит': 'Starkes Untergewicht',
      'Избыточный вес': 'Übergewicht',
      'Ожирение I степени': 'Adipositas Grad I',
      'Ожирение II степени': 'Adipositas Grad II',
      'Ожирение III степени': 'Adipositas Grad III',
      'Поддерживайте текущий режим.': 'Behalte deine derzeitige Routine bei.',
      'Стоит набрать немного массы.': 'Etwas zuzunehmen wäre sinnvoll.',
      'Рекомендуется снизить вес.': 'Eine Gewichtsabnahme ist ratsam.',
      'Обратитесь к специалисту.': 'Wende dich an eine Fachkraft.',
      'Необходима консультация врача.': 'Eine ärztliche Beratung ist nötig.',
      'Срочно к врачу.': 'Suche zeitnah ärztlichen Rat.',
      'Срочно обратитесь к врачу.': 'Suche zeitnah ärztlichen Rat.',
      'ИМТ — ориентировочный показатель для взрослых. Он может быть менее точным для спортсменов, беременных и людей старшего возраста.': 'Der BMI ist ein Orientierungswert für Erwachsene. Bei Sportlern, Schwangeren und älteren Menschen kann er weniger genau sein.',
      'Введите рост и вес': 'Trage Größe und Gewicht ein',
    },
  },
};
