// СГЕНЕРИРОВАНО. Не редактировать руками.
// Общие фразы результата, отобранные под наследственный калькулятор usd-to-mdl.
// Перегенерировать: npm run calculators:generate

import type { CalculatorLocalization } from '../../../../lib/platform/types';

export const shared: CalculatorLocalization = {
  en: {
    results: {
      'Результат': 'Result',
      'Курс': 'Rate',
      'Из': 'From',
      'В': 'To',
      'Тип курса': 'Rate type',
      'Дата курса': 'Rate date',
      'Дата обновления': 'Update date',
      'Статус обновления': 'Update status',
      'Последняя попытка обновления': 'Last update attempt',
      'Источник': 'Source',
      'Ошибка': 'Error',
    },
    values: {
      'официальный справочный': 'official reference rate',
      'Это не курс в реальном времени. Используются официальные справочные курсы центральных банков на указанную дату. Банки и обменные пункты могут использовать другие курсы и комиссии.': 'These are not real-time rates. The calculation uses official central-bank reference rates for the displayed date. Banks and exchange services may use different rates and fees.',
      'Курсы успешно обновлены при последней сборке сайта.': 'Rates were updated successfully during the latest site build.',
      'Дата курса старше четырёх дней. Данные могут быть устаревшими.': 'The reference-rate date is more than four days old. The data may be stale.',
      'Не удалось обновить курсы при последней сборке. Используются последние сохранённые данные.': 'The latest build could not update the rates. The last saved data is being used.',
      'Европейский центральный банк': 'European Central Bank',
      'Национальный банк Украины': 'National Bank of Ukraine',
      'Национальный банк Молдовы': 'National Bank of Moldova',
      'Exchange Rate API': 'Exchange Rate API',
      'Резервный источник': 'Fallback source',
      'Основной источник был недоступен, курс получен из резервного.': 'The primary source was unavailable, so this rate came from the fallback source.',
      'Курсы обновлены при последней сборке; часть валют получена из резервного источника.': 'Rates were updated during the latest build; some currencies came from the fallback source.',
      'Доллар США': 'US dollar',
      'Евро': 'Euro',
      'Молдавский лей': 'Moldovan leu',
      'Румынский лей': 'Romanian leu',
      'Гривна': 'Ukrainian hryvnia',
      'Польский злотый': 'Polish zloty',
      'Фунт стерлингов': 'Pound sterling',
      'Швейцарский франк': 'Swiss franc',
      'Турецкая лира': 'Turkish lira',
      'Неизвестная валюта': 'Unknown currency',
    },
  },
  uk: {
    results: {
      'Результат': 'Результат',
      'Курс': 'Курс',
      'Из': 'З',
      'В': 'У',
      'Тип курса': 'Тип курсу',
      'Дата курса': 'Дата курсу',
      'Дата обновления': 'Дата оновлення',
      'Статус обновления': 'Статус оновлення',
      'Последняя попытка обновления': 'Остання спроба оновлення',
      'Источник': 'Джерело',
      'Ошибка': 'Помилка',
    },
    values: {
      'официальный справочный': 'офіційний довідковий',
      'Это не курс в реальном времени. Используются официальные справочные курсы центральных банков на указанную дату. Банки и обменные пункты могут использовать другие курсы и комиссии.': 'Це не курс у реальному часі. Розрахунок використовує офіційні довідкові курси центральних банків на вказану дату. Банки та обмінні сервіси можуть застосовувати інші курси й комісії.',
      'Курсы успешно обновлены при последней сборке сайта.': 'Курси успішно оновлено під час останнього складання сайту.',
      'Дата курса старше четырёх дней. Данные могут быть устаревшими.': 'Дата довідкового курсу старша за чотири дні. Дані можуть бути застарілими.',
      'Не удалось обновить курсы при последней сборке. Используются последние сохранённые данные.': 'Під час останнього складання не вдалося оновити курси. Використовуються останні збережені дані.',
      'Европейский центральный банк': 'Європейський центральний банк',
      'Национальный банк Украины': 'Національний банк України',
      'Национальный банк Молдовы': 'Національний банк Молдови',
      'Exchange Rate API': 'Exchange Rate API',
      'Резервный источник': 'Резервне джерело',
      'Основной источник был недоступен, курс получен из резервного.': 'Основне джерело було недоступне, тому курс отримано з резервного.',
      'Курсы обновлены при последней сборке; часть валют получена из резервного источника.': 'Курси оновлено під час останнього складання; частину валют отримано з резервного джерела.',
      'Доллар США': 'Долар США',
      'Евро': 'Євро',
      'Молдавский лей': 'Молдовський лей',
      'Румынский лей': 'Румунський лей',
      'Гривна': 'Українська гривня',
      'Польский злотый': 'Польський злотий',
      'Фунт стерлингов': 'Фунт стерлінгів',
      'Швейцарский франк': 'Швейцарський франк',
      'Турецкая лира': 'Турецька ліра',
      'Неизвестная валюта': 'Невідома валюта',
    },
  },
  de: {
    results: {
      'Результат': 'Ergebnis',
      'Курс': 'Wechselkurs',
      'Из': 'Von',
      'В': 'Nach',
      'Тип курса': 'Art des Kurses',
      'Дата курса': 'Kursdatum',
      'Дата обновления': 'Stand vom',
      'Статус обновления': 'Stand der Aktualisierung',
      'Последняя попытка обновления': 'Letzter Aktualisierungsversuch',
      'Источник': 'Quelle',
      'Ошибка': 'Fehler',
    },
    values: {
      'официальный справочный': 'amtlicher Referenzkurs',
      'Это не курс в реальном времени. Используются официальные справочные курсы центральных банков на указанную дату. Банки и обменные пункты могут использовать другие курсы и комиссии.': 'Das sind keine Echtzeitkurse. Verwendet werden die amtlichen Referenzkurse der Zentralbanken zum angezeigten Datum. Banken und Wechselstuben können andere Kurse und Gebühren ansetzen.',
      'Курсы успешно обновлены при последней сборке сайта.': 'Die Kurse wurden beim letzten Bau der Website erfolgreich aktualisiert.',
      'Дата курса старше четырёх дней. Данные могут быть устаревшими.': 'Das Kursdatum liegt mehr als vier Tage zurück. Die Daten können veraltet sein.',
      'Не удалось обновить курсы при последней сборке. Используются последние сохранённые данные.': 'Beim letzten Bau ließen sich die Kurse nicht aktualisieren. Verwendet werden die zuletzt gespeicherten Daten.',
      'Европейский центральный банк': 'Europäische Zentralbank',
      'Национальный банк Украины': 'Nationalbank der Ukraine',
      'Национальный банк Молдовы': 'Nationalbank der Republik Moldau',
      'Exchange Rate API': 'Exchange Rate API',
      'Резервный источник': 'Ersatzquelle',
      'Основной источник был недоступен, курс получен из резервного.': 'Die Hauptquelle war nicht erreichbar, der Kurs stammt aus der Ersatzquelle.',
      'Курсы обновлены при последней сборке; часть валют получена из резервного источника.': 'Die Kurse wurden beim letzten Bau aktualisiert; ein Teil der Währungen stammt aus der Ersatzquelle.',
      'Доллар США': 'US-Dollar',
      'Евро': 'Euro',
      'Молдавский лей': 'Moldauischer Leu',
      'Румынский лей': 'Rumänischer Leu',
      'Гривна': 'Hrywnja',
      'Польский злотый': 'Polnischer Złoty',
      'Фунт стерлингов': 'Pfund Sterling',
      'Швейцарский франк': 'Schweizer Franken',
      'Турецкая лира': 'Türkische Lira',
      'Неизвестная валюта': 'Unbekannte Währung',
    },
  },
};
