import type { CalculatorLocalization } from '../../lib/platform/types';

// Единицы принадлежат калькулятору: центральный словарь единиц трогать нельзя,
// это вернуло бы ручную регистрацию. Подстановка идёт по самому длинному ключу,
// поэтому « моль/л» выигрывает у « моль», а « г/моль» — у « г».
const RESULTS_EN = {
  'Концентрация': 'Concentration',
  'Масса растворителя': 'Mass of solvent',
  'В миллионных долях': 'In parts per million',
  'Масса на литр': 'Mass per litre',
  'Проверьте данные': 'Check the values',
};
const RESULTS_UK = {
  'Концентрация': 'Концентрація',
  'Масса растворителя': 'Маса розчинника',
  'В миллионных долях': 'У мільйонних частках',
  'Масса на литр': 'Маса на літр',
  'Проверьте данные': 'Перевірте дані',
};

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Form der Konzentration',
      'solute': 'Masse des Stoffes, g',
      'solution': 'Masse der Lösung, g',
      'volume': 'Volumen der Lösung, ml',
    },
    options: {
      'ww': 'Massenprozent',
      'wv': 'Masse je Volumen',
    },
    results: {
      'Концентрация': 'Konzentration',
      'Масса растворителя': 'Masse des Lösungsmittels',
      'В миллионных долях': 'In Teilen je Million',
      'Масса на литр': 'Masse je Liter',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      ' моль/л': ' mol/l',
      ' г/моль': ' g/mol',
      ' моль': ' mol',
      ' г/л': ' g/l',
      ' г': ' g',
      ' мл': ' ml',
      ' л': ' l',
      ' кПа': ' kPa',
      ' атм': ' atm',
      ' Па': ' Pa',
      ' К': ' K',
      ' ppm': ' ppm',
      'Дж/(моль·К)': 'J/(mol·K)',
      'Масса вещества должна быть больше нуля': 'Die Masse des Stoffes muss größer als null sein',
      'Объём раствора должен быть больше нуля': 'Das Volumen der Lösung muss größer als null sein',
      'Масса раствора должна быть больше нуля': 'Die Masse der Lösung muss größer als null sein',
      'Вещества не может быть больше, чем раствора': 'Es kann nicht mehr Stoff als Lösung geben',
    },
  },
  en: {
    fields: { mode: 'Form of concentration', solute: 'Mass of substance, g', solution: 'Mass of solution, g', volume: 'Volume of solution, mL', },
    options: { ww: 'per cent by mass', wv: 'mass per volume', },
    results: RESULTS_EN,
    values: {
      ' моль/л': ' mol/L',
      ' г/моль': ' g/mol',
      ' моль': ' mol',
      ' г/л': ' g/L',
      ' г': ' g',
      ' мл': ' mL',
      ' л': ' L',
      ' кПа': ' kPa',
      ' атм': ' atm',
      ' Па': ' Pa',
      ' К': ' K',
      ' ppm': ' ppm',
      'Дж/(моль·К)': 'J/(mol·K)',
      'Масса вещества должна быть больше нуля': 'The mass of the substance must be greater than zero',
      'Объём раствора должен быть больше нуля': 'The volume of the solution must be greater than zero',
      'Масса раствора должна быть больше нуля': 'The mass of the solution must be greater than zero',
      'Вещества не может быть больше, чем раствора': 'There cannot be more substance than solution',
    },
  },
  uk: {
    fields: { mode: 'Форма концентрації', solute: 'Маса речовини, г', solution: 'Маса розчину, г', volume: 'Об’єм розчину, мл', },
    options: { ww: 'відсоток за масою', wv: 'маса на об’єм', },
    results: RESULTS_UK,
    values: {
      ' моль/л': ' моль/л',
      ' г/моль': ' г/моль',
      ' моль': ' моль',
      ' г/л': ' г/л',
      ' мл': ' мл',
      ' кПа': ' кПа',
      ' атм': ' атм',
      ' Па': ' Па',
      ' К': ' К',
      'Дж/(моль·К)': 'Дж/(моль·К)',
      'Масса вещества должна быть больше нуля': 'Маса речовини має бути більшою за нуль',
      'Объём раствора должен быть больше нуля': 'Об’єм розчину має бути більшим за нуль',
      'Масса раствора должна быть больше нуля': 'Маса розчину має бути більшою за нуль',
      'Вещества не может быть больше, чем раствора': 'Речовини не може бути більше, ніж розчину',
    },
  },
};
