import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'value': 'Menge',
      'unit': 'Einheit des Volumens',
      'product': 'Zutat',
      'direction': 'Richtung',
    },
    options: {
      'water': 'Wasser',
      'milk': 'Milch',
      'flour': 'Mehl',
      'sugar': 'Zucker',
      'salt': 'Salz',
      'rice': 'Reis',
      'oil': 'Pflanzenöl',
      'honey': 'Honig',
      'butter': 'Butter',
      'ml': 'Milliliter',
      'l': 'Liter',
      'cup': 'Tassen (240 ml)',
      'tbsp': 'Esslöffel (15 ml)',
      'tsp': 'Teelöffel (5 ml)',
      'toGrams': 'Volumen in Gramm',
      'toVolume': 'Gramm in Volumen',
    },
    results: {
      'Результат': 'Ergebnis',
      'Плотность продукта': 'Dichte der Zutat',
      'В миллилитрах': 'In Millilitern',
      'Исходное значение': 'Ausgangswert',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'г/мл': 'g/ml',
      'мл': 'ml',
      'Неизвестный продукт': 'Unbekannte Zutat',
      'Неизвестная единица объёма': 'Unbekannte Einheit des Volumens',
      'Неизвестное направление': 'Unbekannte Richtung',
      'Значение не может быть отрицательным': 'Der Wert kann nicht negativ sein',
      'Чашка здесь метрическая, 240 мл. Плотности сыпучих продуктов зависят от того, как их насыпали: разброс до четверти — обычное дело.': 'Die Tasse ist hier metrisch, 240 ml. Die Dichte streufähiger Zutaten hängt davon ab, wie sie eingefüllt wurden: eine Streuung bis zu einem Viertel ist gewöhnlich.',
    },
  },
  en: {
    fields: {
      "value": "Amount",
      "unit": "Unit of volume",
      "product": "Product",
      "direction": "Direction",
    },
    options: {
      "water": "Water",
      "milk": "Milk",
      "flour": "Flour",
      "sugar": "Sugar",
      "salt": "Salt",
      "rice": "Rice",
      "oil": "Vegetable oil",
      "honey": "Honey",
      "butter": "Butter",
      "ml": "Millilitres",
      "l": "Litres",
      "cup": "Cups (240 ml)",
      "tbsp": "Tablespoons (15 ml)",
      "tsp": "Teaspoons (5 ml)",
      "toGrams": "Volume to grams",
      "toVolume": "Grams to volume",
    },
    results: {
      "Результат": "Result",
      "Плотность продукта": "Density of the product",
      "В миллилитрах": "In millilitres",
      "Исходное значение": "Input value",
      "Проверьте данные": "Check the values",
    },
    values: {
      "г/мл": "g/ml",
      "мл": "mL",
      "Неизвестный продукт": "Unknown product",
      "Неизвестная единица объёма": "Unknown unit of volume",
      "Неизвестное направление": "Unknown direction",
      "Значение не может быть отрицательным": "The value cannot be negative",
      "Чашка здесь метрическая, 240 мл. Плотности сыпучих продуктов зависят от того, как их насыпали: разброс до четверти — обычное дело.": "The cup here is metric, 240 ml. Densities of dry goods depend on how they were poured: a quarter either way is normal.",
    },
  },
  uk: {
    fields: {
      "value": "Кількість",
      "unit": "Одиниця об’єму",
      "product": "Продукт",
      "direction": "Напрямок",
    },
    options: {
      "water": "Вода",
      "milk": "Молоко",
      "flour": "Борошно",
      "sugar": "Цукор",
      "salt": "Сіль",
      "rice": "Рис",
      "oil": "Олія",
      "honey": "Мед",
      "butter": "Масло",
      "ml": "Мілілітри",
      "l": "Літри",
      "cup": "Склянки (240 мл)",
      "tbsp": "Столові ложки (15 мл)",
      "tsp": "Чайні ложки (5 мл)",
      "toGrams": "Об’єм у грами",
      "toVolume": "Грами в об’єм",
    },
    results: {
      "Результат": "Результат",
      "Плотность продукта": "Густина продукту",
      "В миллилитрах": "У мілілітрах",
      "Исходное значение": "Вхідне значення",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "г/мл": "г/мл",
      "мл": "мл",
      "Неизвестный продукт": "Невідомий продукт",
      "Неизвестная единица объёма": "Невідома одиниця об’єму",
      "Неизвестное направление": "Невідомий напрямок",
      "Значение не может быть отрицательным": "Значення не може бути від’ємним",
      "Чашка здесь метрическая, 240 мл. Плотности сыпучих продуктов зависят от того, как их насыпали: разброс до четверти — обычное дело.": "Склянка тут метрична, 240 мл. Густина сипких продуктів залежить від того, як їх насипали: розбіжність до чверті — звична річ.",
    },
  },
};
