import type { CalcFunction } from '../../lib/types';
import { fmtInt } from '../../lib/format';
import { add, exact, evaluated, finite, INPUT, integer, INTEGER, mode, MODE, optional, positive, quotient, RANGE, read, scalar, times } from '../engine-displacement/automotiveNumeric';
const money = (value: number) => `${scalar(value)} ₽`;
export const compute: CalcFunction = inputs => {
  const distance = read(inputs.distance), consumption = read(inputs.consumption), fuelPrice = read(inputs.fuelPrice), tolls = optional(inputs.tolls);
  const passengers = integer(inputs.passengers), roundTrip = mode(inputs.roundTrip, 'no', ['no', 'yes']);
  const fail = (message: string) => ({ primary: { label: 'Стоимость поездки', value: '—' }, secondary: [{ label: 'Проверьте данные', value: message, accent: 'red' as const }] });
  if (!roundTrip) return fail(MODE);
  if (!finite(distance, consumption, fuelPrice, tolls)) return fail(INPUT);
  if (!(distance > 0)) return fail('Расстояние должно быть больше нуля');
  if (!(consumption > 0)) return fail('Расход должен быть больше нуля');
  if (!(fuelPrice > 0)) return fail('Цена топлива должна быть больше нуля');
  if (tolls < 0) return fail('Плата за дороги не может быть отрицательной');
  if (Number.isSafeInteger(passengers) && passengers < 1) return fail('Пассажиров должно быть не меньше одного');
  if (!Number.isSafeInteger(passengers)) return fail(INTEGER);
  const wayExact = times(exact(distance), exact(roundTrip === 'yes' ? 2 : 1));
  const litresExact = times(wayExact, exact(consumption)), fuelExact = times(litresExact, exact(fuelPrice));
  const totalExact = add(fuelExact, times(exact(tolls), exact(100)));
  const way = evaluated(wayExact), litres = evaluated(litresExact, exact(100)), fuel = evaluated(fuelExact, exact(100)), total = evaluated(totalExact, exact(100));
  const share = evaluated(totalExact, times(exact(100), exact(passengers)));
  if (!positive(way, litres, fuel, total, share)) return fail(RANGE);
  const secondary = [ { label: 'Топливо', value: money(fuel) }, { label: 'Израсходовано литров', value: `${scalar(litres)} л` }, { label: 'Пройденное расстояние', value: `${scalar(way, 0)} км` } ];
  if (tolls > 0) secondary.push({ label: 'Платные дороги', value: money(tolls) });
  if (passengers > 1) secondary.push({ label: 'На человека', value: money(share) }, { label: 'Пассажиров', value: fmtInt(passengers) });
  return { primary: { label: 'Стоимость поездки', value: money(total) }, secondary };
};
