import type { CalculatorDef } from '../../lib/types';
type Copy = Pick<CalculatorDef, 'longDescription' | 'howToUse' | 'howItWorks' | 'example' | 'faq' | 'disclaimer'>;
export const contractContent: Record<'ru' | 'en' | 'uk' | 'de' | 'es', Copy> = {
  ru: {
    longDescription: 'ROAS делит выручку, отнесённую к рекламе, на рекламные расходы. Выручка не равна прибыли: заданная маржа показывает, какая её доля остаётся после учтённых затрат до рекламы. Калькулятор вычитает рекламу из этой суммы и находит выручку, достаточную для её покрытия. Полученный остаток ещё не является чистой прибылью, если постоянные расходы, налоги или другие затраты не включены в модель.',
    howToUse: ['Введите неотрицательную выручку и положительные рекламные расходы для согласованного периода и окна атрибуции.', 'Укажите маржу до рекламных расходов от 0 до 100 %. Не вычитайте одну и ту же рекламу и в марже, и отдельным расходом.', 'Используйте сопоставимую выручку с учётом принятой политики возвратов и налогов.', 'Все деньги задаются в одной валюте. Отдельно проверьте накладные расходы и сроки поступления средств.'],
    howItWorks: 'Пусть R — выручка, C > 0 — реклама, m — маржа в долях. ROAS = R/C; ROAS в процентах = 100R/C. Сумма до рекламы = Rm, остаток после неё = Rm − C, доходность рекламного расхода = 100(Rm/C − 1). При m > 0 порог выручки = C/m, порог ROAS = 1/m. При m = 0 конечного порога нет. Это доходность относительно рекламы, а не бухгалтерский ROI по всем затратам.',
    example: 'Выручка 480 000 денежных единиц, реклама 120 000 и маржа 40 %: ROAS 4,00×, сумма до рекламы 192 000, остаток 72 000 и доходность рекламного расхода 60,00 %. Порог выручки 300 000 соответствует ROAS 2,50×. При выручке 120 000 и той же марже остаток −72 000, доходность −60 %. Маржа 0 % даёт остаток −120 000 без конечного порога.',
    faq: [
      { q: 'Означает ли ROAS 4× доходность 300 процентов?', a: 'Только если вся выручка до рекламы остаётся доступной, то есть маржа равна 100 %, и рассматривается этот упрощённый знаменатель. При марже 40 % рекламная доходность здесь равна 60 %. Полный ROI требует полного состава затрат.' },
      { q: 'Какую маржу вводить перед рекламным расходом?', a: 'Долю выручки после затрат, которые вы учитываете до рекламы. Опишите эту базу в своём отчёте. Если рекламные расходы уже вычтены при вычислении маржи, отдельное вычитание создаст двойной учёт.' },
      { q: 'Почему ROAS выше единицы может давать отрицательный остаток?', a: 'Потому что себестоимость и другие затраты уменьшают доступную выручку. При марже 25 % для покрытия рекламы нужен ROAS 4×; больше единицы самого по себе недостаточно.' },
      { q: 'Что означает отсутствие порога при нулевой марже?', a: 'Ни одна положительная сумма выручки не оставляет денег на рекламу по введённой модели. Остаток равен минус рекламные расходы, доходность −100 %; конечную выручку покрытия показать нельзя.' },
      { q: 'Можно ли сравнить разные окна атрибуции по одному ROAS?', a: 'Сначала согласуйте окно, каналы, возвраты и правила распределения выручки. Высокий ROAS не доказывает, что вся продажа вызвана рекламой, и не гарантирует ту же доходность после увеличения бюджета.' },
    ],
    disclaimer: 'Модель атрибутированной выручки и маржи до рекламы. Остаток исключает неучтённые накладные расходы, налоги и стоимость времени; это не чистая прибыль или полный ROI.',
  },
  en: {
    longDescription: 'ROAS divides revenue attributed to advertising by advertising spend. Revenue is not profit: the supplied margin specifies the share remaining after included costs before advertising. The calculator subtracts ad spend from that amount and finds the revenue needed to cover it. The remainder is not net profit when overhead, taxes or other costs remain outside the model.',
    howToUse: ['Enter nonnegative revenue and positive ad spend with a matched period and attribution window.', 'Supply a margin before advertising between 0 and 100%. Avoid counting the same advertising cost inside the margin and again as spend.', 'Use a consistent revenue basis for refunds and taxes.', 'Use one currency throughout. Review overhead and cash timing separately.'],
    howItWorks: 'Let R be revenue, C > 0 ad spend and m the margin share. ROAS = R/C; percentage ROAS = 100R/C. Amount before ads = Rm; remainder after ads = Rm − C; return on ad spend = 100(Rm/C − 1). With m > 0, break-even revenue = C/m and break-even ROAS = 1/m. At m = 0 there is no finite threshold. This return uses advertising as its denominator, rather than all costs required for accounting ROI.',
    example: 'Revenue 480,000 monetary units, ad spend 120,000 and margin 40% give ROAS 4.00×, amount before ads 192,000, remainder 72,000 and ad-spend return 60.00%. Break-even revenue 300,000 corresponds to ROAS 2.50×. Revenue 120,000 at that margin gives remainder −72,000 and return −60%. Margin 0% gives remainder −120,000 with no finite break-even revenue.',
    faq: [
      { q: 'Does ROAS 4× imply a three-hundred-percent return?', a: 'Only with margin 100% before ads and this simplified denominator. At margin 40%, the ad-spend return here is 60%. A full ROI needs the complete cost basis.' },
      { q: 'Which margin belongs before the advertising deduction?', a: 'The revenue share left after costs included before ads. Document that basis in your report. If advertising has already reduced the margin, subtracting it again would double-count the cost.' },
      { q: 'Why can ROAS above one still leave a negative remainder?', a: 'Production and other included costs reduce the revenue available to pay for ads. At margin 25%, ROAS 4× is needed just to cover advertising; ROAS above one alone is insufficient.' },
      { q: 'Why is there no break-even revenue at zero margin?', a: 'No revenue amount leaves money for ads under that assumption. The remainder is minus ad spend and the return is −100%; a finite covering revenue cannot be calculated.' },
      { q: 'Can ROAS compare campaigns with different attribution windows?', a: 'Align windows, channels, refunds and revenue allocation first. A high ROAS does not prove every sale was caused by advertising or promise the same return after increasing the budget.' },
    ],
    disclaimer: 'Attributed-revenue model with a margin before advertising. Unincluded overhead, taxes and time value remain outside; the remainder is not net profit or full ROI.',
  },
  uk: {
    longDescription: 'ROAS ділить віднесений до реклами виторг на рекламні витрати. Виторг не є прибутком: задана маржа визначає частку після врахованих витрат до реклами. Калькулятор віднімає рекламу від цієї суми та знаходить виторг для її покриття. Залишок ще не є чистим прибутком, якщо накладні витрати, податки або інші витрати лишилися поза моделлю.',
    howToUse: ['Введіть невід’ємний виторг і додатні рекламні витрати з узгодженими періодом та вікном атрибуції.', 'Маржу до реклами задайте від 0 до 100 %. Не враховуйте ту саму рекламу і в маржі, і окремим видатком.', 'Використовуйте спільні правила щодо повернень і податків у виторгу.', 'Усі суми мають спільну валюту. Окремо перевірте накладні витрати та час надходження коштів.'],
    howItWorks: 'R — виторг, C > 0 — реклама, m — частка маржі. ROAS = R/C, у відсотках = 100R/C. Сума до реклами = Rm; залишок після неї = Rm − C; дохідність рекламних витрат = 100(Rm/C − 1). За m > 0 поріг виторгу = C/m, поріг ROAS = 1/m. За m = 0 скінченного порога немає. Це дохідність відносно реклами, а не бухгалтерський ROI за всіма витратами.',
    example: 'Виторг 480 000 грошових одиниць, реклама 120 000 і маржа 40 % дають ROAS 4,00×, суму до реклами 192 000, залишок 72 000 та дохідність реклами 60,00 %. Поріг виторгу 300 000 відповідає ROAS 2,50×. Виторг 120 000 за цієї маржі дає залишок −72 000 і дохідність −60 %. За маржі 0 % залишок −120 000 без скінченного порога.',
    faq: [
      { q: 'Чи означає ROAS 4× дохідність триста відсотків?', a: 'Лише за маржі 100 % до реклами та такого спрощеного дільника. За маржі 40 % дохідність реклами тут становить 60 %. Повний ROI потребує повної бази витрат.' },
      { q: 'Яку маржу задавати перед відніманням реклами?', a: 'Частку виторгу після витрат, врахованих до реклами. Опишіть цю базу у звіті. Якщо реклама вже зменшила маржу, її окреме віднімання двічі врахує один видаток.' },
      { q: 'Чому ROAS понад одиницю може лишити від’ємний результат?', a: 'Собівартість та інші враховані витрати зменшують гроші для реклами. За маржі 25 % потрібен ROAS 4× лише для покриття реклами; самої одиниці недостатньо.' },
      { q: 'Що означає відсутність порога за нульової маржі?', a: 'За цієї умови жоден виторг не залишає коштів на рекламу. Залишок дорівнює мінус рекламні витрати, дохідність −100 %; скінченний виторг покриття не обчислюється.' },
      { q: 'Чи можна порівнювати різні вікна атрибуції одним ROAS?', a: 'Спершу узгодьте вікна, канали, повернення та розподіл виторгу. Високий ROAS не доводить, що всі продажі спричинила реклама, й не гарантує такий самий результат після збільшення бюджету.' },
    ],
    disclaimer: 'Модель атрибутованого виторгу та маржі до реклами. Невраховані накладні витрати, податки й вартість часу виключено; залишок не є чистим прибутком або повним ROI.',
  },
  de: {
    longDescription: 'ROAS teilt der Werbung zugerechneten Umsatz durch Werbeausgaben. Umsatz ist kein Gewinn: Die angegebene Marge beschreibt den Anteil nach berücksichtigten Kosten vor Werbung. Der Rechner zieht Werbung davon ab und ermittelt den zur Deckung nötigen Umsatz. Der Rest ist kein Nettogewinn, wenn Gemeinkosten, Steuern oder andere Kosten außerhalb des Modells bleiben.',
    howToUse: ['Gib nicht negativen Umsatz und positive Werbeausgaben mit gleichem Zeitraum und Attributionsfenster ein.', 'Die Marge vor Werbung liegt zwischen 0 und 100 %. Zähle dieselben Werbeausgaben nicht zugleich in der Marge und als eigenen Abzug.', 'Verwende übereinstimmende Regeln für Erstattungen und Steuern im Umsatz.', 'Alle Beträge nutzen dieselbe Währung. Gemeinkosten und Zahlungszeitpunkte werden separat geprüft.'],
    howItWorks: 'R ist Umsatz, C > 0 Werbeausgaben und m der Margenanteil. ROAS = R/C, in Prozent = 100R/C. Betrag vor Werbung = Rm; Rest danach = Rm − C; Rendite der Werbeausgaben = 100(Rm/C − 1). Bei m > 0 ist der Deckungsumsatz C/m und der erforderliche ROAS 1/m. Bei m = 0 gibt es keinen endlichen Schwellenwert. Der Nenner umfasst Werbung statt sämtlicher Kosten eines vollständigen ROI.',
    example: '480 000 Geldeinheiten Umsatz, 120 000 Werbung und 40 % Marge ergeben ROAS 4,00×, 192 000 vor Werbung, 72 000 Rest und 60,00 % Werberendite. Der Deckungsumsatz 300 000 entspricht ROAS 2,50×. Umsatz 120 000 mit derselben Marge ergibt −72 000 Rest und −60 % Rendite. Bei Marge 0 % bleibt −120 000 ohne endlichen Deckungsumsatz.',
    faq: [
      { q: 'Bedeutet ROAS 4× eine Rendite von dreihundert Prozent?', a: 'Nur bei 100 % Marge vor Werbung und diesem vereinfachten Nenner. Bei 40 % Marge beträgt die Werberendite hier 60 %. Ein vollständiger ROI benötigt alle berücksichtigten Kosten.' },
      { q: 'Welche Marge gehört vor den Werbeabzug?', a: 'Der Umsatzanteil nach den Kosten, die vor Werbung berücksichtigt werden. Dokumentiere die Grundlage. Sind Werbeausgaben schon darin enthalten, würde der erneute Abzug sie doppelt zählen.' },
      { q: 'Warum kann ROAS über eins dennoch einen negativen Rest ergeben?', a: 'Herstellung und weitere Kosten verringern den für Werbung verfügbaren Umsatz. Bei 25 % Marge ist ROAS 4× nötig, um allein Werbung zu decken; mehr als eins reicht nicht aus.' },
      { q: 'Warum fehlt bei null Marge ein Deckungsumsatz?', a: 'Unter dieser Annahme lässt kein Umsatz Geld für Werbung übrig. Der Rest ist minus Werbeausgaben, die Rendite −100 %. Ein endlicher Deckungsumsatz ist nicht berechenbar.' },
      { q: 'Lassen sich unterschiedliche Attributionsfenster per ROAS vergleichen?', a: 'Gleiche Fenster, Kanäle, Erstattungen und Umsatzzuordnung sind zuerst festzulegen. Ein hoher ROAS beweist keine alleinige Werbewirkung und garantiert keine gleichbleibende Rendite bei größerem Budget.' },
    ],
    disclaimer: 'Modell mit zugeordnetem Umsatz und Marge vor Werbung. Nicht berücksichtigte Gemeinkosten, Steuern und Zeitwert fehlen; der Rest ist kein Nettogewinn oder vollständiger ROI.',
  },
  es: {
    longDescription: 'ROAS divide los ingresos atribuidos a la publicidad entre el gasto publicitario. Ingresos no significa beneficio: el margen indicado representa la parte restante tras los costes incluidos antes de publicidad. Se resta la publicidad de ese importe y se calcula el ingreso necesario para cubrirla. El resto no es beneficio neto si gastos generales, impuestos u otros costes quedan fuera del modelo.',
    howToUse: ['Introduce ingresos no negativos y gasto publicitario positivo del mismo periodo y ventana de atribución.', 'Indica un margen anterior a publicidad entre 0 y 100 %. No incluyas el mismo gasto publicitario en el margen y otra vez como deducción.', 'Usa criterios coherentes para devoluciones e impuestos en los ingresos.', 'Mantén una moneda común y revisa por separado gastos generales y fechas de cobro.'],
    howItWorks: 'R son ingresos, C > 0 gasto publicitario y m la fracción del margen. ROAS = R/C; en porcentaje = 100R/C. Importe antes de publicidad = Rm; resto después = Rm − C; rentabilidad del gasto publicitario = 100(Rm/C − 1). Con m > 0 el ingreso de cobertura es C/m y el ROAS necesario 1/m. Con m = 0 no hay umbral finito. El denominador es publicidad, no todos los costes de un ROI contable completo.',
    example: 'Ingresos 480 000 unidades monetarias, publicidad 120 000 y margen 40 % dan ROAS 4,00×, 192 000 antes de publicidad, resto 72 000 y rentabilidad publicitaria 60,00 %. El ingreso de cobertura 300 000 corresponde a ROAS 2,50×. Ingresos 120 000 con ese margen dan resto −72 000 y rentabilidad −60 %. Margen 0 % deja −120 000 sin ingreso finito de cobertura.',
    faq: [
      { q: '¿ROAS 4× equivale a una rentabilidad del trescientos por ciento?', a: 'Solo con margen del 100 % antes de publicidad y este denominador simplificado. Con margen del 40 %, la rentabilidad publicitaria aquí es 60 %. Un ROI completo requiere todos los costes.' },
      { q: '¿Qué margen se indica antes de descontar publicidad?', a: 'La proporción de ingresos restante tras los costes incluidos antes de publicidad. Documenta esa base. Si la publicidad ya redujo el margen, restarla de nuevo duplicaría el gasto.' },
      { q: '¿Por qué ROAS mayor que uno puede dejar un resto negativo?', a: 'Producción y otros costes reducen el ingreso disponible para publicidad. Con margen del 25 %, hace falta ROAS 4× solo para cubrir anuncios; superar uno no basta.' },
      { q: '¿Por qué no hay ingreso de cobertura con margen cero?', a: 'Ningún ingreso deja dinero para anuncios bajo esa suposición. El resto equivale al gasto publicitario negativo y la rentabilidad es −100 %; no se puede calcular una cobertura finita.' },
      { q: '¿ROAS compara campañas con distintas ventanas de atribución?', a: 'Antes deben coincidir ventanas, canales, devoluciones y asignación de ingresos. Un ROAS alto no demuestra que toda venta sea causada por anuncios ni garantiza igual rentabilidad al ampliar el presupuesto.' },
    ],
    disclaimer: 'Modelo de ingresos atribuidos y margen anterior a publicidad. Excluye gastos generales no incluidos, impuestos y valor temporal; el resto no es beneficio neto ni ROI completo.',
  },
};
