import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'unit': 'Längeneinheit',
      'r': 'Grundradius',
      'h': 'Höhe',
    },
    options: {
      'mm': 'Millimeter',
      'cm': 'Zentimeter',
      'm': 'Meter',
    },
    results: {
      'Объём': 'Volumen',
      'Образующая': 'Seitenhöhe',
      'Боковая поверхность': 'Mantelfläche',
      'Полная поверхность': 'Gesamtoberfläche',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'мм': 'mm',
      'см': 'cm',
      'м': 'm',
      'мм²': 'mm²',
      'см²': 'cm²',
      'м²': 'm²',
      'мм³': 'mm³',
      'см³': 'cm³',
      'м³': 'm³',
      'Радиус должен быть больше нуля': 'Der Radius muss größer als null sein',
      'Высота должна быть больше нуля': 'Die Höhe muss größer als null sein',
    },
  },
  en: {
    fields: {
      "unit": "Length unit",
      "r": "Base radius",
      "h": "Height",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "metres",
    },
    results: {
      "Объём": "Volume",
      "Образующая": "Slant height",
      "Боковая поверхность": "Lateral surface",
      "Полная поверхность": "Total surface",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Радиус должен быть больше нуля": "The radius must be greater than zero",
      "Высота должна быть больше нуля": "The height must be greater than zero",
    },
  },
  uk: {
    fields: {
      "unit": "Одиниця довжини",
      "r": "Радіус основи",
      "h": "Висота",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "метри",
    },
    results: {
      "Объём": "Об’єм",
      "Образующая": "Твірна",
      "Боковая поверхность": "Бічна поверхня",
      "Полная поверхность": "Повна поверхня",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Радиус должен быть больше нуля": "Радіус має бути більшим за нуль",
      "Высота должна быть больше нуля": "Висота має бути більшою за нуль",
    },
  },
};
