import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'current': "Strom",
      'length': "Einfache Länge",
      'section': "Leiterquerschnitt",
      'material': 'Leitermaterial',
      'phase': 'Versorgung',
      'voltage': "Nennspannung",
    },
    options: {
      'copper': 'Kupfer',
      'aluminium': 'Aluminium',
      'single': 'Einphasig',
      'three': 'Dreiphasig',
    },
    results: {
      "Сопротивление одной жилы": "Widerstand eines Leiters",
      'Падение напряжения': 'Spannungsfall',
      'Доля от номинала': 'Anteil der Nennspannung',
      'Напряжение у нагрузки': 'Spannung an der Last',
      'Сопротивление линии': 'Leitungswiderstand',
      'Потери мощности': 'Verlustleistung in der Leitung',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      "Неизвестный режим расчёта": "Unbekannter Berechnungsmodus",
      "Введите конечные числа для выбранного режима": "Gib endliche Zahlen für den gewählten Modus ein",
      "Результат выходит за числовой диапазон": "Das Ergebnis überschreitet den Zahlenbereich",
      "Ток и длина неотрицательны; сечение и напряжение должны быть больше нуля": "Strom und Länge müssen nichtnegativ, Querschnitt und Spannung positiv sein",
      "Падение превышает напряжение питания: проверьте ток, длину и сечение": "Der Spannungsfall überschreitet die Versorgungsspannung: prüfe Strom, Länge und Querschnitt",
      "Резистивная модель при 20 °C и cos φ = 1. Нагрев, реактивность и контакты не учтены; сопротивление указано для одной жилы в один конец.": "Ohmsches Modell bei 20 °C und cos φ = 1. Erwärmung, Reaktanz und Kontakte fehlen; der Widerstand gilt für einen Leiter der einfachen Strecke.",

      'В': 'V',
      'Ом': 'Ω',
      'Вт': 'W',
      'Неизвестный материал проводника': 'Unbekanntes Leitermaterial',
      'Неизвестная схема питания': 'Unbekannte Versorgungsart',
      'Ток, длина, сечение и напряжение должны быть больше нуля': 'Strom, Länge, Querschnitt und Spannung müssen alle größer als null sein',
      'Удельное сопротивление взято при 20 °C. Нагретый проводник сопротивляется сильнее, поэтому в работе падение будет чуть больше расчётного.': 'Der spezifische Widerstand gilt bei 20 °C. Ein warmer Leiter setzt mehr Widerstand entgegen, im Betrieb fällt der Spannungsfall deshalb etwas größer aus als berechnet.',
    },
  },
  en: {
    fields: {
      "current": "Current", "length": "One-way run", "section": "Conductor cross-section",
      "material": "Conductor material", "phase": "Supply", "voltage": "Nominal voltage",
    },
    options: { "copper": "Copper", "aluminium": "Aluminium", "single": "Single-phase", "three": "Three-phase" },
    results: {
      "Сопротивление одной жилы": "One-conductor resistance",
      "Падение напряжения": "Voltage drop",
      "Доля от номинала": "Share of nominal",
      "Напряжение у нагрузки": "Voltage at the load",
      "Сопротивление линии": "Line resistance",
      "Потери мощности": "Power lost in the cable",
      "Проверьте данные": "Check the values",
    },
    values: {
      "Неизвестный режим расчёта": "Unknown calculation mode",
      "Введите конечные числа для выбранного режима": "Enter finite numbers for the selected mode",
      "Результат выходит за числовой диапазон": "The result exceeds the numerical range",
      "Ток и длина неотрицательны; сечение и напряжение должны быть больше нуля": "Current and length must be nonnegative; cross-section and voltage must be positive",
      "Падение превышает напряжение питания: проверьте ток, длину и сечение": "The drop exceeds supply voltage: check current, length and cross-section",
      "Резистивная модель при 20 °C и cos φ = 1. Нагрев, реактивность и контакты не учтены; сопротивление указано для одной жилы в один конец.": "Resistive model at 20 °C and power factor 1. Heating, reactance and contacts are excluded; resistance is for one conductor on the one-way run.",

      "В": "V", "Ом": "Ω", "Вт": "W",
      "Неизвестный материал проводника": "Unknown conductor material",
      "Неизвестная схема питания": "Unknown supply type",
      "Ток, длина, сечение и напряжение должны быть больше нуля": "Current, length, cross-section and voltage must all be greater than zero",
      "Удельное сопротивление взято при 20 °C. Нагретый проводник сопротивляется сильнее, поэтому в работе падение будет чуть больше расчётного.": "Resistivity is taken at 20 °C. A warm conductor resists more, so the drop in service will be a little larger than calculated.",
    },
  },
  uk: {
    fields: {
      "current": "Струм", "length": "Довжина в один бік", "section": "Переріз жили",
      "material": "Матеріал жили", "phase": "Живлення", "voltage": "Номінальна напруга",
    },
    options: { "copper": "Мідь", "aluminium": "Алюміній", "single": "Однофазне", "three": "Трифазне" },
    results: {
      "Сопротивление одной жилы": "Опір однієї жили",
      "Падение напряжения": "Падіння напруги",
      "Доля от номинала": "Частка від номіналу",
      "Напряжение у нагрузки": "Напруга на навантаженні",
      "Сопротивление линии": "Опір лінії",
      "Потери мощности": "Втрати потужності в кабелі",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "Неизвестный режим расчёта": "Невідомий режим розрахунку",
      "Введите конечные числа для выбранного режима": "Введіть скінченні числа для обраного режиму",
      "Результат выходит за числовой диапазон": "Результат виходить за числовий діапазон",
      "Ток и длина неотрицательны; сечение и напряжение должны быть больше нуля": "Струм і довжина невід’ємні; переріз і напруга мають бути додатними",
      "Падение превышает напряжение питания: проверьте ток, длину и сечение": "Падіння перевищує напругу живлення: перевірте струм, довжину та переріз",
      "Резистивная модель при 20 °C и cos φ = 1. Нагрев, реактивность и контакты не учтены; сопротивление указано для одной жилы в один конец.": "Резистивна модель за 20 °C і cos φ = 1. Нагрів, реактивність і контакти не враховано; опір указано для однієї жили в один бік.",

      "В": "В", "Ом": "Ом", "Вт": "Вт",
      "Неизвестный материал проводника": "Невідомий матеріал жили",
      "Неизвестная схема питания": "Невідома схема живлення",
      "Ток, длина, сечение и напряжение должны быть больше нуля": "Струм, довжина, переріз і напруга мають бути більшими за нуль",
      "Удельное сопротивление взято при 20 °C. Нагретый проводник сопротивляется сильнее, поэтому в работе падение будет чуть больше расчётного.": "Питомий опір узято за 20 °C. Нагріта жила чинить більший опір, тож у роботі падіння буде трохи більшим за розрахункове.",
    },
  },
  es: {
    fields: {
      "current": "Corriente",
      "length": "Longitud de ida",
      "section": "Sección del conductor",
      "material": "Material del conductor",
      "phase": "Alimentación",
      "voltage": "Tensión nominal",
    },
    options: {
      "copper": "Cobre",
      "aluminium": "Aluminio",
      "single": "Monofásica",
      "three": "Trifásica",
    },
    results: {
      "Сопротивление одной жилы": "Resistencia de un conductor",
      "Падение напряжения": "Caída de tensión",
      "Доля от номинала": "Proporción de la nominal",
      "Напряжение у нагрузки": "Tensión en la carga",
      "Сопротивление линии": "Resistencia de la línea",
      "Потери мощности": "Potencia perdida en el cable",
      "Проверьте данные": "Revisa los datos",
    },
    values: {
      "Неизвестный режим расчёта": "Modo de cálculo desconocido",
      "Введите конечные числа для выбранного режима": "Introduce números finitos para el modo elegido",
      "Результат выходит за числовой диапазон": "El resultado supera el rango numérico",
      "Ток и длина неотрицательны; сечение и напряжение должны быть больше нуля": "Corriente y longitud deben ser no negativas; sección y tensión deben ser positivas",
      "Падение превышает напряжение питания: проверьте ток, длину и сечение": "La caída supera la tensión de alimentación: revisa corriente, longitud y sección",
      "Резистивная модель при 20 °C и cos φ = 1. Нагрев, реактивность и контакты не учтены; сопротивление указано для одной жилы в один конец.": "Modelo resistivo a 20 °C y cos φ = 1. No incluye calentamiento, reactancia ni contactos; la resistencia corresponde a un conductor de ida.",

      "В": "V",
      "Ом": "Ω",
      "Вт": "W",
      "Неизвестный материал проводника": "Material del conductor desconocido",
      "Неизвестная схема питания": "Tipo de alimentación desconocido",
      "Ток, длина, сечение и напряжение должны быть больше нуля": "La corriente, la longitud, la sección y la tensión deben ser mayores que cero",
      "Удельное сопротивление взято при 20 °C. Нагретый проводник сопротивляется сильнее, поэтому в работе падение будет чуть больше расчётного.": "La resistividad se toma a 20 °C. Un conductor caliente resiste más, así que en servicio la caída será algo mayor que la calculada.",
    },
  },
};
