import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  en: {
    fields: {
      "monthly": "Monthly contribution, $",
      "months": "Months",
      "startPrice": "Starting price per unit, $",
      "priceGrowthPct": "Monthly price change, %",
    },
    options: {},
    results: {
      "Итоговая стоимость": "Final value",
      "Вложено всего": "Total invested",
      "Куплено единиц": "Units bought",
      "Средняя цена": "Average price",
      "Результат": "Result",
      "Цена последней покупки": "Last purchase price",
      "По месяцам": "Month by month",
      "Месяц": "Month",
      "Цена": "Price",
      "Куплено": "Bought",
      "Накоплено": "Accumulated",
      "Проверьте данные": "Check the values",
    },
    values: {
      "Показаны первые 12 месяцев расчёта.": "Showing the first 12 months of the calculation.",
      "₽": "$",
      "Взнос должен быть больше нуля": "The contribution must be greater than zero",
      "Число месяцев должно быть не меньше единицы": "The number of months must be at least one",
      "Число месяцев должно быть целым": "The number of months must be a whole number",
      "Начальная цена должна быть больше нуля": "The starting price must be greater than zero",
      "Падение цены не может достигать ста процентов": "A price drop cannot reach a hundred percent",
    },
  },
  uk: {
    fields: {
      "monthly": "Внесок на місяць, ₴",
      "months": "Місяців",
      "startPrice": "Початкова ціна за одиницю, ₴",
      "priceGrowthPct": "Зміна ціни на місяць, %",
    },
    options: {},
    results: {
      "Итоговая стоимость": "Підсумкова вартість",
      "Вложено всего": "Вкладено разом",
      "Куплено единиц": "Куплено одиниць",
      "Средняя цена": "Середня ціна",
      "Результат": "Результат",
      "Цена последней покупки": "Ціна останньої покупки",
      "По месяцам": "За місяцями",
      "Месяц": "Місяць",
      "Цена": "Ціна",
      "Куплено": "Куплено",
      "Накоплено": "Накопичено",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "Показаны первые 12 месяцев расчёта.": "Показано перші 12 місяців розрахунку.",
      "₽": "₴",
      "Взнос должен быть больше нуля": "Внесок має бути більшим за нуль",
      "Число месяцев должно быть не меньше единицы": "Кількість місяців має бути щонайменше одиниця",
      "Число месяцев должно быть целым": "Кількість місяців має бути цілою",
      "Начальная цена должна быть больше нуля": "Початкова ціна має бути більшою за нуль",
      "Падение цены не может достигать ста процентов": "Падіння ціни не може сягати ста відсотків",
    },
  },
};
