import type { CalculatorDef } from '../../lib/types';
type Copy = Pick<CalculatorDef, 'longDescription' | 'howToUse' | 'howItWorks' | 'example' | 'faq' | 'disclaimer'>;

export const contractContent: Record<'ru' | 'en' | 'uk' | 'de' | 'es', Copy> = {
  ru: {
    longDescription: 'Маржинальный доход на единицу показывает, какая часть цены остаётся после введённых переменных затрат. Эта сумма участвует в покрытии постоянных расходов и лишь затем в прибыли. Доля в цене помогает сопоставлять товары, а абсолютная сумма и объём показывают их денежный вклад. Здесь цена и переменные затраты на единицу считаются постоянными для введённого объёма.',
    howToUse: ['Введите положительную цену продажи за одну выбранную единицу.', 'Укажите неотрицательные переменные затраты на ту же единицу и в той же валюте.', 'Объём необязателен: пустое поле или 0 скрывают сумму на объём. Дробный объём допустим, например для килограммов или часов.', 'Отделите переменные расходы от постоянных в пределах рассматриваемого объёма; учтите скидки, налоги и дополнительные затраты в исходных суммах по своему правилу.'],
    howItWorks: 'Маржа на единицу M = P − V, где P — цена, V — переменные затраты. Доля = 100 × M / P. Для положительного объёма Q общая маржа = M × Q. P > 0, V ≥ 0 и Q ≥ 0; V выше цены допустимо и даёт отрицательную маржу. Деньги рассчитаны без промежуточного округления, обычный результат показывается целыми денежными единицами; очень малые значения сохраняются показательной записью.',
    example: 'Цена 500 и переменные затраты 300 дают 200 на единицу и 40 %. При объёме 10 сумма равна 2 000. На границе V = 500 маржа равна 0 и доля 0 %. При V = 650 результат −150 и −30 %; объём 2,5 при обычной марже 200 даёт сумму 500.',
    faq: [
      { q: 'Как определить переменные затраты именно для этого объёма?', a: 'Выберите расходы, меняющиеся вместе с продажей выбранной единицы: это могут быть материалы, упаковка или комиссия. Зарплата, доставка и аренда не имеют универсальной классификации — она зависит от договора, периода и диапазона деятельности.' },
      { q: 'Когда смотреть долю, а когда маржу в деньгах?', a: 'Доля сопоставляет вклад относительно цены, сумма показывает вклад каждой единицы, а маржа на объём — совокупный вклад. Ни один из трёх показателей сам по себе не заменяет оценку спроса и постоянных расходов.' },
      { q: 'Почему затраты выше цены принимаются, а отрицательные затраты нет?', a: 'Положительные затраты выше цены описывают отрицательный вклад продажи и выводятся с предупреждением. Отрицательные затраты противоречат неотрицательному полю этой модели; возвраты или субсидии нужно учитывать в согласованной отдельной модели.' },
      { q: 'Чем это отличается от валовой и чистой прибыли?', a: 'Валовая прибыль зависит от состава себестоимости продаж, который может включать постоянные производственные расходы. Здесь вычитаются только введённые переменные затраты. Чтобы получить прибыль, нужно дополнительно учесть постоянные и прочие расходы.' },
      { q: 'Достаточна ли положительная маржа для дополнительного заказа?', a: 'Нет. Проверяют доступную мощность, стоимость отказа от другой продажи и новые постоянные или ступенчатые расходы. Предположение о неизменной цене и переменных затратах может перестать действовать при росте объёма.' },
    ],
    disclaimer: 'Линейная модель одной позиции при постоянных цене и переменных затратах на единицу. Не рассчитывает чистую прибыль, налоги или загрузку мощности. Все денежные поля используют одну валюту, её отображение не выполняет обмен.',
  },
  en: {
    longDescription: 'Unit contribution is what remains from the selling price after the entered variable cost. It helps cover fixed costs before a profit can arise. The percentage describes contribution relative to price; the amount and sales volume describe the monetary contribution. This form assumes an unchanged unit price and unit variable cost throughout the supplied volume.',
    howToUse: ['Choose the unit being sold and enter a positive selling price for it.', 'Enter nonnegative variable cost for that same unit in the same currency.', 'Volume is optional: blank or zero hides the total-volume result. Fractions are valid for measured quantities such as kilograms or hours.', 'Classify costs for the period and activity range you are assessing; incorporate discounts, taxes and any chosen costs consistently in the input amounts.'],
    howItWorks: 'Unit contribution M = P − V, where P is unit price and V is unit variable cost. Contribution percentage = 100 × M / P. For positive volume Q, total contribution is M × Q. Price is positive; cost and volume are nonnegative. Cost above price is valid and produces negative contribution. Intermediate values are unrounded. Ordinary monetary results use whole units and very small values retain scientific notation.',
    example: 'Price 500 and variable cost 300 give unit contribution 200 and 40%. Selling 10 units contributes 2,000. Cost equal to 500 gives zero contribution and 0%. At cost 650, contribution is −150 and −30%. A measured volume of 2.5 with unit contribution 200 contributes 500.',
    faq: [
      { q: 'Which expenses are variable for my chosen unit?', a: 'Use expenses that change with selling that unit within the relevant activity range. Materials, packaging or a sales commission may qualify. Wages, delivery and rent need classification by their actual contracts and time horizon.' },
      { q: 'Should percentage replace the monetary contribution?', a: 'No. Percentage compares contribution with price; the monetary amount describes one unit’s contribution, and the volume total describes the aggregate. Demand and fixed costs remain important in all three interpretations.' },
      { q: 'Why allow cost above price but reject negative cost?', a: 'A positive cost above the price describes a sale with negative contribution and is shown explicitly. Negative cost contradicts this form’s nonnegative-cost domain; rebates or subsidies need a consistent separate treatment.' },
      { q: 'Is contribution the same as gross or net profit?', a: 'Gross profit follows the costs included in cost of sales, which may include fixed production costs. This calculation subtracts the entered variable costs only. Net profit also requires fixed and other expenses.' },
      { q: 'Does positive contribution justify taking another order?', a: 'Not by itself. Capacity, the opportunity cost of another sale and additional fixed or step costs may matter. Unit price and unit variable cost may also change outside the activity range assumed here.' },
    ],
    disclaimer: 'Single-item linear model with constant unit price and variable cost. Net profit, taxes and capacity use are not calculated. All monetary inputs share one currency; the displayed currency symbol does not perform an exchange conversion.',
  },
  uk: {
    longDescription: 'Маржинальний дохід на одиницю — частина ціни після введених змінних витрат. Вона покриває постійні витрати, перш ніж утворюється прибуток. Частка показує відношення до ціни, сума — внесок однієї одиниці, а добуток на обсяг — загальний внесок. Розрахунок припускає незмінні ціну та змінні витрати на одиницю для заданого обсягу.',
    howToUse: ['Визначте одиницю продажу й уведіть її додатну ціну.', 'Задайте невід’ємні змінні витрати на ту саму одиницю та в тій самій валюті.', 'Обсяг необов’язковий: порожнє поле або 0 приховують сумарну маржу. Дробовий обсяг доречний для кілограмів чи годин.', 'Класифікуйте витрати для обраного строку й діапазону діяльності; знижки, податки та склад витрат задавайте послідовно у вихідних сумах.'],
    howItWorks: 'Маржа на одиницю M = P − V: P — ціна, V — змінні витрати. Частка = 100 × M / P. За додатного обсягу Q сумарна маржа = M × Q. P > 0, V ≥ 0, Q ≥ 0. Витрати вище ціни допустимі й дають від’ємний результат. Проміжні значення не округлюються; звичайні грошові підсумки показуються цілими одиницями, дуже малі — у показниковій формі.',
    example: 'Ціна 500 і змінні витрати 300 дають 200 на одиницю та 40 %. Для обсягу 10 сума становить 2 000. За витрат 500 маржа й частка нульові. За витрат 650 результат −150 та −30 %. Обсяг 2,5 за звичайної маржі 200 дає суму 500.',
    faq: [
      { q: 'Які витрати змінюються разом із моєю одиницею продажу?', a: 'Визначайте їх у конкретному діапазоні діяльності: це можуть бути матеріали, пакування чи комісія. Зарплата, доставка та оренда не завжди належать до одного типу витрат; важливі договір і часовий горизонт.' },
      { q: 'Чи варто замінити суму маржі її відсотковою часткою?', a: 'Частка порівнює внесок із ціною, сума показує внесок однієї одиниці, а підсумок на обсяг — загальний внесок. Для рішення потрібні також попит і постійні витрати; жоден показник не замінює решту.' },
      { q: 'Чому збиткова позиція допустима, а від’ємні витрати ні?', a: 'Додатні змінні витрати вище ціни описують від’ємний внесок продажу. Їх показано з попередженням. Від’ємні витрати виходять за межі невід’ємного поля; субсидії чи повернення потребують узгодженої окремої моделі.' },
      { q: 'Чим маржинальний дохід відрізняється від прибутку?', a: 'Валова прибутковість залежить від складу собівартості продажів, де можуть бути постійні виробничі витрати. Тут віднято лише введені змінні витрати. Для прибутку треба врахувати постійні й інші витрати.' },
      { q: 'Чи достатньо додатної маржі для нового замовлення?', a: 'Потрібно ще перевірити потужність, альтернативну вартість іншого продажу та нові постійні або ступінчасті витрати. За збільшення обсягу ціна й витрати на одиницю можуть змінитися.' },
    ],
    disclaimer: 'Лінійна модель однієї позиції з незмінними ціною та змінними витратами на одиницю. Чистий прибуток, податки й потужність не розраховуються. Усі суми використовують одну валюту; її знак не означає обмін за курсом.',
  },
  de: {
    longDescription: 'Der Deckungsbeitrag je Einheit ist der Verkaufspreis nach Abzug der eingegebenen variablen Kosten. Er dient zunächst zur Deckung fixer Kosten. Der Prozentanteil beschreibt den Beitrag im Verhältnis zum Preis; Betrag und Absatzmenge zeigen den Geldbeitrag. Der Rechner nimmt für die gesamte Menge einen unveränderten Stückpreis und unveränderte variable Stückkosten an.',
    howToUse: ['Lege die Verkaufseinheit fest und gib einen positiven Preis dafür ein.', 'Gib variable Kosten von mindestens null für dieselbe Einheit und Währung ein.', 'Die Menge ist optional. Leer oder null blendet den Gesamtbeitrag aus; Bruchteile sind für Kilogramm oder Stunden möglich.', 'Ordne Kosten für den betrachteten Zeitraum und Tätigkeitsbereich zu. Rabatte, Steuern und Kostenbestandteile müssen in den Eingaben einheitlich behandelt werden.'],
    howItWorks: 'Stückbeitrag M = P − V, mit Preis P und variablen Stückkosten V. Prozentanteil = 100 × M / P. Bei positiver Menge Q gilt Gesamtbeitrag = M × Q. P > 0, V ≥ 0 und Q ≥ 0. Kosten über dem Preis sind zulässig und ergeben einen negativen Beitrag. Zwischenwerte bleiben ungerundet; übliche Geldbeträge erscheinen in ganzen Einheiten, sehr kleine Werte in wissenschaftlicher Schreibweise.',
    example: 'Preis 500 und variable Kosten 300 ergeben 200 je Einheit und 40 %. Für 10 Einheiten beträgt der Beitrag 2 000. Bei Kosten 500 sind Beitrag und Anteil null. Kosten 650 ergeben −150 und −30 %. Eine gemessene Menge von 2,5 mit Stückbeitrag 200 ergibt insgesamt 500.',
    faq: [
      { q: 'Welche Kosten ändern sich mit meiner Verkaufseinheit?', a: 'Das wird im relevanten Tätigkeitsbereich beurteilt. Material, Verpackung oder Verkaufsprovision können dazugehören. Löhne, Lieferung und Miete hängen von Vertrag und Zeitraum ab und sind nicht stets derselben Kostenart zuzuordnen.' },
      { q: 'Soll der Prozentanteil den Geldbetrag ersetzen?', a: 'Der Anteil vergleicht den Beitrag mit dem Preis, der Betrag zeigt den Beitrag einer Einheit und die Mengensumme den gesamten Beitrag. Nachfrage und Fixkosten bleiben für alle drei Betrachtungen erforderlich.' },
      { q: 'Warum sind Kosten über dem Preis erlaubt?', a: 'Sie beschreiben einen Verkauf mit negativem Beitrag und werden als solcher gezeigt. Negative Kosten passen dagegen nicht zum nicht negativen Kostenfeld. Rückvergütungen oder Zuschüsse benötigen eine konsistente eigene Behandlung.' },
      { q: 'Ist der Deckungsbeitrag mit Brutto- oder Nettogewinn gleichzusetzen?', a: 'Der Bruttogewinn richtet sich nach den in den Umsatzkosten enthaltenen Bestandteilen, gegebenenfalls einschließlich fixer Produktionskosten. Hier werden nur die eingegebenen variablen Kosten abgezogen. Für Gewinn fehlen noch fixe und weitere Kosten.' },
      { q: 'Rechtfertigt ein positiver Beitrag einen zusätzlichen Auftrag?', a: 'Nicht allein. Kapazität, der entgangene Beitrag einer anderen Bestellung sowie zusätzliche fixe oder sprungfixe Kosten können entscheidend sein. Außerhalb des angenommenen Bereichs können sich Stückpreis und Stückkosten ändern.' },
    ],
    disclaimer: 'Lineares Modell einer Position mit konstantem Stückpreis und variablen Stückkosten. Nettogewinn, Steuern und Kapazitätsauslastung werden nicht ermittelt. Alle Geldwerte verwenden eine Währung; das Währungssymbol führt keinen Umtausch durch.',
  },
  es: {
    longDescription: 'La contribución por unidad es lo que queda del precio después del coste variable introducido. Primero ayuda a cubrir costes fijos antes de formar beneficio. El porcentaje compara la contribución con el precio; el importe y el volumen muestran su aportación monetaria. Se supone que precio y coste variable unitarios permanecen constantes para todo el volumen indicado.',
    howToUse: ['Define la unidad vendida e introduce un precio positivo por unidad.', 'El coste variable debe ser no negativo, por la misma unidad y en la misma moneda.', 'El volumen es opcional: vacío o cero oculta la contribución total. Se admiten fracciones para cantidades medidas en kilogramos u horas.', 'Clasifica los costes para el periodo y rango de actividad analizado; trata de forma coherente descuentos, impuestos y los componentes incluidos.'],
    howItWorks: 'Contribución unitaria M = P − V, siendo P el precio y V el coste variable por unidad. Porcentaje = 100 × M / P. Con volumen positivo Q, contribución total = M × Q. P > 0, V ≥ 0 y Q ≥ 0. Un coste superior al precio es válido y genera contribución negativa. Los valores intermedios no se redondean; los importes habituales usan unidades enteras y los muy pequeños pueden usar notación científica.',
    example: 'Precio 500 y coste variable 300 dejan 200 por unidad y un 40 %. Con volumen 10 la contribución suma 2 000. Un coste de 500 da contribución y porcentaje cero. Coste 650 da −150 y −30 %. Un volumen medido de 2,5 con contribución unitaria 200 suma 500.',
    faq: [
      { q: '¿Qué gastos cambian con mi unidad de venta?', a: 'Se determinan dentro del rango de actividad relevante. Materiales, embalaje o una comisión pueden formar parte. Salarios, entrega y alquiler dependen del contrato y del horizonte temporal; no tienen una clasificación universal.' },
      { q: '¿El porcentaje sustituye a la contribución en dinero?', a: 'El porcentaje compara con el precio; el importe describe una unidad y el total describe el volumen. Demanda y costes fijos siguen siendo necesarios para decidir. Ninguna de esas perspectivas basta por sí sola.' },
      { q: '¿Por qué se admite un coste mayor que el precio?', a: 'Describe una venta con contribución negativa y se muestra expresamente. Un coste negativo queda fuera del campo no negativo de este modelo. Reembolsos o subvenciones requieren un tratamiento separado y coherente.' },
      { q: '¿Coincide la contribución con el beneficio bruto o neto?', a: 'El beneficio bruto depende de los componentes del coste de ventas, que pueden incluir producción fija. Aquí solo se resta el coste variable introducido. Para obtener beneficio faltan costes fijos y otros gastos.' },
      { q: '¿Una contribución positiva justifica otro pedido?', a: 'También deben revisarse capacidad, el coste de oportunidad de otra venta y nuevos costes fijos o escalonados. Precio y coste por unidad pueden variar fuera del rango asumido.' },
    ],
    disclaimer: 'Modelo lineal de una sola posición con precio y coste variable unitarios constantes. No calcula beneficio neto, impuestos ni uso de capacidad. Todos los importes comparten una moneda; el símbolo mostrado no aplica un cambio de divisas.',
  },
};
