import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  en: {
    fields: {
      "mode": "What is known",
      "unit": "Length unit",
      "r": "Radius",
      "d": "Diameter",
      "c": "Circumference",
      "area": "Area",
    },
    options: {
      mm: "millimetres",
      cm: "centimetres",
      m: "metres",
      "radius": "the radius",
      "diameter": "the diameter",
      "circumference": "the circumference",
      "area": "the area",
    },
    results: {
      "Площадь": "Area",
      "Радиус": "Radius",
      "Диаметр": "Diameter",
      "Длина окружности": "Circumference",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Радиус должен быть больше нуля": "The radius must be greater than zero",
      "Диаметр должен быть больше нуля": "The diameter must be greater than zero",
      "Длина окружности должна быть больше нуля": "The circumference must be greater than zero",
      "Площадь должна быть больше нуля": "The area must be greater than zero",
      "Значение слишком велико для расчёта": "The value is too large to calculate",
    },
  },
  uk: {
    fields: {
      "mode": "Що відомо",
      "unit": "Одиниця довжини",
      "r": "Радіус",
      "d": "Діаметр",
      "c": "Довжина кола",
      "area": "Площа",
    },
    options: {
      mm: "міліметри",
      cm: "сантиметри",
      m: "метри",
      "radius": "радіус",
      "diameter": "діаметр",
      "circumference": "довжина кола",
      "area": "площа",
    },
    results: {
      "Площадь": "Площа",
      "Радиус": "Радіус",
      "Диаметр": "Діаметр",
      "Длина окружности": "Довжина кола",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Радиус должен быть больше нуля": "Радіус має бути більшим за нуль",
      "Диаметр должен быть больше нуля": "Діаметр має бути більшим за нуль",
      "Длина окружности должна быть больше нуля": "Довжина кола має бути більшою за нуль",
      "Площадь должна быть больше нуля": "Площа має бути більшою за нуль",
      "Значение слишком велико для расчёта": "Значення завелике для розрахунку",
    },
  },
};
