import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  en: {
    fields: {
      "mode": "What to find",
      "F": "Force, N",
      "A": "Area, m²",
      "p": "Pressure, Pa",
      "A2": "Area, m²",
      "F2": "Force, N",
      "p2": "Pressure, Pa",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "metres",
      "p": "the pressure",
      "F": "the force",
      "A": "the area",
    },
    results: {
      "Давление": "Pressure",
      "Сила": "Force",
      "Площадь": "Area",
      "В атмосферах": "In atmospheres",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Па": "Pa",
      "Н": "N",
      "атм": "atm",
      "Площадь должна быть больше нуля": "The area must be greater than zero",
      "Сила должна быть больше нуля": "The force must be greater than zero",
      "Давление должно быть больше нуля": "The pressure must be greater than zero",
    },
  },
  uk: {
    fields: {
      "mode": "Що знайти",
      "F": "Сила, Н",
      "A": "Площа, м²",
      "p": "Тиск, Па",
      "A2": "Площа, м²",
      "F2": "Сила, Н",
      "p2": "Тиск, Па",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "метри",
      "p": "тиск",
      "F": "силу",
      "A": "площу",
    },
    results: {
      "Давление": "Тиск",
      "Сила": "Сила",
      "Площадь": "Площа",
      "В атмосферах": "В атмосферах",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Па": "Па",
      "Н": "Н",
      "атм": "атм",
      "Площадь должна быть больше нуля": "Площа має бути більшою за нуль",
      "Сила должна быть больше нуля": "Сила має бути більшою за нуль",
      "Давление должно быть больше нуля": "Тиск має бути більшим за нуль",
    },
  },
};
