import type { CalculatorLocalization } from '../../lib/platform/types';

// Единицы принадлежат калькулятору: центральный словарь единиц трогать нельзя,
// это вернуло бы ручную регистрацию. Подстановка идёт по самому длинному ключу,
// поэтому « моль/л» выигрывает у « моль», а « г/моль» — у « г».
const RESULTS_EN = {
  'Давление': 'Pressure',
  'Объём': 'Volume',
  'Газовая постоянная': 'Gas constant',
  'Температура': 'Temperature',
  'Количество вещества': 'Amount of substance',
  'Проверьте данные': 'Check the values',
};
const RESULTS_UK = {
  'Давление': 'Тиск',
  'Объём': 'Об’єм',
  'Газовая постоянная': 'Газова стала',
  'Температура': 'Температура',
  'Количество вещества': 'Кількість речовини',
  'Проверьте данные': 'Перевірте дані',
};

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'solve': 'Was gesucht ist',
      'n': 'Stoffmenge, mol',
      'tempUnit': 'Einheit der Temperatur',
      't': 'Temperatur',
      'volumeUnit': 'Einheit des Volumens',
      'v': 'Volumen',
      'pressureUnit': 'Einheit des Drucks',
      'p': 'Druck',
    },
    options: {
      'p': 'der Druck',
      'v': 'das Volumen',
      'k': 'Kelvin',
      'c': 'Grad Celsius',
      'm3': 'Kubikmeter',
      'l': 'Liter',
      'pa': 'Pascal',
      'kpa': 'Kilopascal',
      'atm': 'Atmosphären',
    },
    results: {
      'Давление': 'Druck',
      'Объём': 'Volumen',
      'Газовая постоянная': 'Gaskonstante',
      'Температура': 'Temperatur',
      'Количество вещества': 'Stoffmenge',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      ' моль/л': ' mol/l',
      ' г/моль': ' g/mol',
      ' моль': ' mol',
      ' г/л': ' g/l',
      ' г': ' g',
      ' мл': ' ml',
      ' л': ' l',
      ' кПа': ' kPa',
      ' атм': ' atm',
      ' Па': ' Pa',
      ' К': ' K',
      ' ppm': ' ppm',
      'Дж/(моль·К)': 'J/(mol·K)',
      'Температура не может быть ниже абсолютного нуля': 'Die Temperatur kann nicht unter dem absoluten Nullpunkt liegen',
      'Количество вещества должно быть больше нуля': 'Die Stoffmenge muss größer als null sein',
      'Объём должен быть больше нуля': 'Das Volumen muss größer als null sein',
      'Давление должно быть больше нуля': 'Der Druck muss größer als null sein',
      'Температура должна быть больше нуля': 'Die Temperatur muss größer als null sein',
    },
  },
  en: {
    fields: { solve: 'What to find', n: 'Amount of substance, mol', tempUnit: 'Temperature unit', t: 'Temperature', volumeUnit: 'Volume unit', v: 'Volume', pressureUnit: 'Pressure unit', p: 'Pressure', },
    options: { p: 'the pressure', v: 'the volume', k: 'kelvin', c: 'degrees Celsius', m3: 'cubic metres', l: 'litres', pa: 'pascals', kpa: 'kilopascals', atm: 'atmospheres', },
    results: RESULTS_EN,
    values: {
      ' моль/л': ' mol/L',
      ' г/моль': ' g/mol',
      ' моль': ' mol',
      ' г/л': ' g/L',
      ' г': ' g',
      ' мл': ' mL',
      ' л': ' L',
      ' кПа': ' kPa',
      ' атм': ' atm',
      ' Па': ' Pa',
      ' К': ' K',
      ' ppm': ' ppm',
      'Дж/(моль·К)': 'J/(mol·K)',
      'Температура не может быть ниже абсолютного нуля': 'The temperature cannot be below absolute zero',
      'Количество вещества должно быть больше нуля': 'The amount of substance must be greater than zero',
      'Объём должен быть больше нуля': 'The volume must be greater than zero',
      'Давление должно быть больше нуля': 'The pressure must be greater than zero',
      'Температура должна быть больше нуля': 'The temperature must be greater than zero',
    },
  },
  uk: {
    fields: { solve: 'Що знайти', n: 'Кількість речовини, моль', tempUnit: 'Одиниця температури', t: 'Температура', volumeUnit: 'Одиниця об’єму', v: 'Об’єм', pressureUnit: 'Одиниця тиску', p: 'Тиск', },
    options: { p: 'тиск', v: 'об’єм', k: 'кельвіни', c: 'градуси Цельсія', m3: 'кубометри', l: 'літри', pa: 'паскалі', kpa: 'кілопаскалі', atm: 'атмосфери', },
    results: RESULTS_UK,
    values: {
      ' моль/л': ' моль/л',
      ' г/моль': ' г/моль',
      ' моль': ' моль',
      ' г/л': ' г/л',
      ' мл': ' мл',
      ' кПа': ' кПа',
      ' атм': ' атм',
      ' Па': ' Па',
      ' К': ' К',
      'Дж/(моль·К)': 'Дж/(моль·К)',
      'Температура не может быть ниже абсолютного нуля': 'Температура не може бути нижчою за абсолютний нуль',
      'Количество вещества должно быть больше нуля': 'Кількість речовини має бути більшою за нуль',
      'Объём должен быть больше нуля': 'Об’єм має бути більшим за нуль',
      'Давление должно быть больше нуля': 'Тиск має бути більшим за нуль',
      'Температура должна быть больше нуля': 'Температура має бути більшою за нуль',
    },
  },
};
