import type { CalculatorDef } from '../../lib/types';
type Content = Pick<CalculatorDef, 'longDescription' | 'howToUse' | 'howItWorks' | 'example' | 'faq' | 'disclaimer'>;

export const contractContent: Record<'ru' | 'en' | 'uk' | 'de' | 'es', Content> = {
  ru: {
    longDescription: 'Калькулятор определяет ISO-неделю и отдельно её ISO-год, порядковый день календарного года и число дней после выбранной даты до 31 декабря. Неделя идёт с понедельника по воскресенье и целиком относится к году своего четверга. Поэтому 31 декабря может уже принадлежать первой неделе следующего ISO-года. Используется григорианский календарь для дат от 0001-01-01 до 9999-12-31, продолженный назад по тем же правилам: это календарная модель, а не реконструкция исторических календарей разных стран.',
    howToUse: ['Укажите существующую дату в диапазоне 0001–9999 годов.', 'Читайте номер недели вместе с ISO-годом: на границе декабря и января календарный год может отличаться.', 'Порядковый день и оставшиеся дни относятся к календарному году самой даты; выбранный день не входит в остаток.', 'Для расписания с воскресным началом недели проверьте правила своей системы: здесь используется именно ISO-нумерация.'],
    howItWorks: 'ISO-неделя 1 содержит 4 января, то есть первый четверг года. Понедельник имеет номер 1, воскресенье — 7. Предварительный номер равен floor((порядковый день − ISO-день недели + 10) / 7); номера у границы года переводятся в соседний ISO-год. Порядковый день считается от 1 января включительно, остаток равен 365 или 366 минус этот номер. Високосны годы, кратные 4, кроме кратных 100, если они не кратны 400. Расчёт работает с датой, без времени и часового пояса.',
    example: '18 августа 2026 года: вторник, ISO 2026-W34, день 230, осталось 135 дней. 31 декабря 2024 года: вторник, ISO 2025-W01, день 366 календарного 2024 года, осталось 0 дней. 1 января 2023 года относится к ISO 2022-W52. Для 0001-01-01 результат — ISO 1-W01 и день 1.',
    faq: [
      { q: 'Почему первая январская дата может показывать прошлый ISO-год?', a: 'Если четверг её недели находится в декабре, вся неделя относится к предыдущему ISO-году. Например, 1 января 2023 года — воскресенье недели 2022-W52. Это не ошибка года выбранной даты.' },
      { q: 'При каких условиях ISO-год содержит 53 недели?', a: 'Когда 1 января приходится на четверг либо високосный год начинается в среду. В остальных случаях в ISO-году 52 недели; число календарных дней при этом остаётся 365 или 366.' },
      { q: 'Подойдёт ли этот номер для календаря с воскресеньем первым днём?', a: 'Такой календарь может использовать другие правила первой недели и года. ISO-нумерация здесь всегда начинается с понедельника; номер для другой системы автоматически не пересчитывается.' },
      { q: 'Как 29 февраля меняет порядковый день?', a: 'В високосном году 29 февраля — день 60, а 1 марта — день 61. В 1900 году 29 февраля нет, в 2000 году есть. День 31 декабря — 365-й или 366-й, независимо от ISO-года недели.' },
      { q: 'Можно ли использовать результат как историческую дату или момент времени?', a: 'Нет: правила григорианского календаря применяются одинаково ко всем допустимым годам. Местные даты перехода с юлианского календаря, пропущенные гражданские дни и часовые пояса не моделируются. Ввод — календарная дата, а не временная метка.' },
    ],
    disclaimer: 'ISO-нумерация в продолженном григорианском календаре, годы 0001–9999. Исторические местные календари, праздничные и рабочие недели, часовые пояса и системы с другим началом недели не учитываются.',
  },
  en: {
    longDescription: 'Find the ISO week together with its ISO year, the ordinal day within the date’s calendar year and the days remaining after that date through 31 December. An ISO week runs Monday to Sunday and belongs to the year of its Thursday. A December date can therefore already be in the next ISO year. The model applies Gregorian calendar rules consistently from 0001-01-01 through 9999-12-31; it does not reconstruct countries’ historical calendar changes.',
    howToUse: ['Enter an existing calendar date in years 0001–9999.', 'Read the week number together with the ISO year, especially around New Year.', 'The ordinal and remaining days use the date’s calendar year. The selected day is excluded from the remainder.', 'Check your scheduling system if its week starts on Sunday: this result follows ISO week rules.'],
    howItWorks: 'ISO week 1 contains 4 January, equivalently the year’s first Thursday. Monday is weekday 1 and Sunday weekday 7. The initial week is floor((ordinal day − ISO weekday + 10) / 7), with boundary weeks assigned to the adjacent ISO year. The ordinal starts at 1 on 1 January; remaining days equal 365 or 366 minus that ordinal. Leap years are divisible by 4, except century years unless divisible by 400. This is a date-only calculation, independent of time of day or timezone.',
    example: '18 August 2026 is Tuesday in ISO 2026-W34: ordinal day 230, with 135 days remaining. 31 December 2024 is Tuesday in ISO 2025-W01, but ordinal day 366 of calendar year 2024 with 0 days remaining. 1 January 2023 belongs to ISO 2022-W52. The lower boundary, 0001-01-01, is ISO 1-W01 and ordinal day 1.',
    faq: [
      { q: 'Why can an early January date show the previous ISO year?', a: 'Its whole week belongs to the year containing that week’s Thursday. For example, Sunday 1 January 2023 belongs to 2022-W52. The calendar year of the selected date has not changed.' },
      { q: 'When does an ISO year have 53 weeks?', a: 'When 1 January is Thursday, or when a leap year starts on Wednesday. Otherwise the ISO year has 52 weeks. The calendar year still contains 365 or 366 days.' },
      { q: 'Does this number apply to a Sunday-first calendar?', a: 'A Sunday-first system can define both its first week and week year differently. This calculator always uses Monday-first ISO weeks and does not convert the result to another numbering system.' },
      { q: 'How does 29 February affect the ordinal day?', a: 'In a leap year, 29 February is day 60 and 1 March is day 61. There is no 29 February in 1900, whereas 2000 is a leap year. December 31 is day 365 or 366 regardless of the ISO week year.' },
      { q: 'Can this result represent a historical civil date or a timestamp?', a: 'It applies the Gregorian rules to every supported year. Local switches from the Julian calendar, skipped civil dates and timezone transitions are outside the model. The input is a calendar date rather than an instant.' },
    ],
    disclaimer: 'ISO weeks in the proleptic Gregorian calendar, years 0001–9999. Local historical calendars, holidays, working weeks, timezones and other week numbering systems are outside this model.',
  },
  uk: {
    longDescription: 'Калькулятор показує ISO-тиждень разом із його ISO-роком, порядковий день календарного року й кількість днів після вибраної дати до 31 грудня. ISO-тиждень триває від понеділка до неділі та належить року свого четверга. Через це груднева дата може вже потрапити до першого тижня наступного ISO-року. Для дат 0001-01-01–9999-12-31 однаково застосовуються правила григоріанського календаря; історичні переходи окремих країн між календарями не відтворюються.',
    howToUse: ['Введіть наявну календарну дату в межах 0001–9999 років.', 'Читайте номер тижня разом з ISO-роком, особливо на межі грудня та січня.', 'Порядковий день і залишок днів стосуються календарного року дати. Сам вибраний день до залишку не входить.', 'Якщо ваше планування починає тиждень у неділю, перевірте його правила: тут використовується ISO-нумерація.'],
    howItWorks: 'Перший ISO-тиждень містить 4 січня, тобто перший четвер року. Понеділок — день тижня 1, неділя — 7. Початковий номер дорівнює floor((порядковий день − ISO-день тижня + 10) / 7); граничні тижні відносяться до сусіднього ISO-року. Порядковий день починається з 1 на 1 січня, а залишок дорівнює 365 або 366 мінус цей номер. Високосні роки кратні 4, крім кратних 100, якщо вони не кратні 400. Обчислюється лише дата, без часу доби чи часового поясу.',
    example: '18 серпня 2026 року — вівторок, ISO 2026-W34, день 230, залишилося 135 днів. 31 грудня 2024 року — вівторок, ISO 2025-W01, день 366 календарного 2024 року, залишилося 0 днів. 1 січня 2023 року належить ISO 2022-W52. Для нижньої межі 0001-01-01 результат — ISO 1-W01 і день 1.',
    faq: [
      { q: 'Чому дата на початку січня може мати попередній ISO-рік?', a: 'Увесь тиждень належить року, у якому розташований його четвер. Наприклад, неділя 1 січня 2023 року належить 2022-W52. Календарний рік вибраної дати від цього не змінюється.' },
      { q: 'Коли ISO-рік має 53 тижні?', a: 'Коли 1 січня припадає на четвер або високосний рік починається в середу. В інших випадках ISO-рік має 52 тижні. У календарному році залишається 365 або 366 днів.' },
      { q: 'Чи підходить номер для календаря з неділею на початку?', a: 'У такій системі можуть відрізнятися правила першого тижня та його року. Тут тиждень завжди починається з понеділка за ISO; перерахунку до іншої системи немає.' },
      { q: 'Як 29 лютого змінює порядковий день?', a: 'У високосному році 29 лютого — день 60, а 1 березня — день 61. У 1900 році 29 лютого немає, у 2000 році він є. 31 грудня має номер 365 або 366 незалежно від ISO-року тижня.' },
      { q: 'Чи є результат історичною цивільною датою або часовою міткою?', a: 'Правила григоріанського календаря застосовуються однаково до всіх допустимих років. Місцеві переходи з юліанського календаря, пропущені цивільні дні та зміни часових поясів не моделюються. Вводиться календарна дата, а не момент часу.' },
    ],
    disclaimer: 'ISO-тижні у продовженому григоріанському календарі, роки 0001–9999. Історичні місцеві календарі, свята, робочі тижні, часові пояси й інші системи нумерації тижнів не враховуються.',
  },
  de: {
    longDescription: 'Der Rechner ermittelt die ISO-Kalenderwoche mit ihrem ISO-Jahr, den laufenden Tag des Kalenderjahres und die nach dem gewählten Datum bis zum 31. Dezember verbleibenden Tage. Eine ISO-Woche reicht von Montag bis Sonntag und gehört zum Jahr ihres Donnerstags. Deshalb kann ein Dezemberdatum bereits im nächsten ISO-Jahr liegen. Für Daten von 0001-01-01 bis 9999-12-31 gelten durchgehend die Regeln des gregorianischen Kalenders; historische Kalenderwechsel einzelner Länder werden nicht nachgebildet.',
    howToUse: ['Wähle ein gültiges Datum in den Jahren 0001–9999.', 'Lies Kalenderwoche und ISO-Jahr zusammen, besonders am Jahreswechsel.', 'Der laufende Tag und die verbleibenden Tage beziehen sich auf das Kalenderjahr des Datums. Der gewählte Tag zählt nicht zum Rest.', 'Prüfe die Regeln deines Planungssystems, wenn dessen Woche am Sonntag beginnt: hier gelten ISO-Wochen.'],
    howItWorks: 'ISO-Woche 1 enthält den 4. Januar und damit den ersten Donnerstag des Jahres. Montag ist Wochentag 1, Sonntag Wochentag 7. Der vorläufige Wert ist floor((laufender Tag − ISO-Wochentag + 10) / 7); Randwochen werden dem benachbarten ISO-Jahr zugeordnet. Der laufende Tag beginnt am 1. Januar mit 1, die verbleibenden Tage sind 365 beziehungsweise 366 minus diesem Wert. Schaltjahre sind durch 4 teilbar; volle Jahrhundertjahre nur, wenn sie auch durch 400 teilbar sind. Die Berechnung betrifft ein Datum ohne Uhrzeit oder Zeitzone.',
    example: 'Der 18. August 2026 ist ein Dienstag in ISO 2026-W34: Tag 230, noch 135 Tage im Kalenderjahr. Der 31. Dezember 2024 ist ein Dienstag in ISO 2025-W01, bleibt aber Tag 366 des Kalenderjahres 2024 mit 0 verbleibenden Tagen. Der 1. Januar 2023 liegt in ISO 2022-W52. Die untere Grenze 0001-01-01 ergibt ISO 1-W01 und Tag 1.',
    faq: [
      { q: 'Warum kann ein Januardatum noch das vorherige ISO-Jahr anzeigen?', a: 'Die gesamte Woche gehört zum Jahr ihres Donnerstags. Sonntag, der 1. Januar 2023, liegt zum Beispiel in 2022-W52. Das Kalenderjahr des ausgewählten Datums ändert sich dadurch nicht.' },
      { q: 'Wann enthält ein ISO-Jahr 53 Wochen?', a: 'Wenn der 1. Januar ein Donnerstag ist oder wenn ein Schaltjahr am Mittwoch beginnt. Sonst hat das ISO-Jahr 52 Wochen; das Kalenderjahr umfasst weiterhin 365 oder 366 Tage.' },
      { q: 'Gilt die Kalenderwoche auch für eine Woche ab Sonntag?', a: 'Ein anderes System kann Wochenbeginn, erste Woche und Wochenjahr anders festlegen. Hier beginnt jede ISO-Woche am Montag. Eine Umrechnung in andere Nummerierungen findet nicht statt.' },
      { q: 'Wie verändert der 29. Februar den laufenden Tag?', a: 'In Schaltjahren ist der 29. Februar Tag 60 und der 1. März Tag 61. Das Jahr 1900 hat keinen 29. Februar, das Jahr 2000 dagegen schon. Der 31. Dezember ist unabhängig vom ISO-Wochenjahr Tag 365 oder 366.' },
      { q: 'Bildet das Ergebnis historische Ortsdaten oder Zeitstempel ab?', a: 'Die gregorianischen Regeln gelten für alle unterstützten Jahre. Lokale Wechsel vom julianischen Kalender, übersprungene bürgerliche Kalendertage und Zeitzonenwechsel sind nicht enthalten. Eingabe und Ergebnis sind Kalenderdaten, keine Zeitpunkte.' },
    ],
    disclaimer: 'ISO-Wochen im durchgehend gregorianischen Kalender, Jahre 0001–9999. Historische Ortskalender, Feiertage, Arbeitswochen, Zeitzonen und andere Wochensysteme sind nicht enthalten.',
  },
  es: {
    longDescription: 'La calculadora muestra la semana ISO con su año ISO, el día ordinal del año civil y los días que quedan después de la fecha elegida hasta el 31 de diciembre. Una semana ISO va de lunes a domingo y pertenece al año de su jueves. Por eso una fecha de diciembre puede formar parte del siguiente año ISO. Se aplican las reglas gregorianas de forma continua desde 0001-01-01 hasta 9999-12-31; no se reconstruyen los cambios históricos de calendario de cada país.',
    howToUse: ['Introduce una fecha válida de los años 0001–9999.', 'Lee el número de semana junto con el año ISO, especialmente al cambiar de año.', 'El día ordinal y los días restantes pertenecen al año civil de la fecha. El día seleccionado no cuenta entre los restantes.', 'Comprueba las reglas de tu agenda si la semana empieza en domingo: aquí se usa la numeración ISO.'],
    howItWorks: 'La semana ISO 1 contiene el 4 de enero, es decir, el primer jueves del año. El lunes es el día semanal 1 y el domingo el 7. El número inicial es floor((día ordinal − día ISO de la semana + 10) / 7); las semanas de los extremos se asignan al año ISO correspondiente. El ordinal empieza en 1 el 1 de enero y los días restantes son 365 o 366 menos ese número. Son bisiestos los años divisibles por 4, salvo los siglos que no sean divisibles por 400. El cálculo utiliza una fecha sin hora ni zona horaria.',
    example: 'El 18 de agosto de 2026 es martes en ISO 2026-W34: día 230 y 135 días restantes. El 31 de diciembre de 2024 es martes en ISO 2025-W01, pero sigue siendo el día 366 del año civil 2024, con 0 días restantes. El 1 de enero de 2023 pertenece a ISO 2022-W52. En el límite inferior, 0001-01-01 corresponde a ISO 1-W01 y al día 1.',
    faq: [
      { q: '¿Por qué una fecha de enero puede mostrar el año ISO anterior?', a: 'Toda la semana pertenece al año de su jueves. Por ejemplo, el domingo 1 de enero de 2023 está en 2022-W52. Esto no cambia el año civil de la fecha seleccionada.' },
      { q: '¿Cuándo tiene un año ISO 53 semanas?', a: 'Cuando el 1 de enero cae en jueves o cuando un año bisiesto empieza en miércoles. En los demás casos hay 52 semanas ISO; el año civil sigue teniendo 365 o 366 días.' },
      { q: '¿Sirve el número para un calendario que comienza en domingo?', a: 'Ese sistema puede definir de otra manera la primera semana y el año de la semana. Aquí siempre se usan semanas ISO que empiezan en lunes; no se convierte el resultado a otra numeración.' },
      { q: '¿Cómo afecta el 29 de febrero al día ordinal?', a: 'En un año bisiesto, el 29 de febrero es el día 60 y el 1 de marzo el 61. El año 1900 no tiene 29 de febrero; el 2000 sí. El 31 de diciembre es el día 365 o 366, con independencia del año ISO de su semana.' },
      { q: '¿Representa el resultado una fecha civil histórica o un instante?', a: 'Las reglas gregorianas se aplican a todos los años admitidos. Quedan fuera los cambios locales desde el calendario juliano, las fechas civiles omitidas y las transiciones de zona horaria. La entrada es una fecha del calendario, no una marca de tiempo.' },
    ],
    disclaimer: 'Semanas ISO en el calendario gregoriano proléptico, años 0001–9999. No se incluyen calendarios históricos locales, festivos, semanas laborales, zonas horarias ni otras numeraciones semanales.',
  },
};
