import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  en: {
    fields: { date: 'Date' },
    results: {
      'Номер недели': 'Week number',
      'Неделя относится к году': 'Week belongs to year',
      'День года': 'Day of year',
      'Всего дней в году': 'Days in the year',
      'День недели': 'Day of week',
      'Осталось дней до конца года': 'Days left in the year',
      'Високосный год': 'Leap year',
      'Проверьте данные': 'Check the values',
    },
    values: {
      'Укажите корректную дату': 'Enter a valid date',
      'понедельник': 'Monday', 'вторник': 'Tuesday', 'среда': 'Wednesday', 'четверг': 'Thursday',
      'пятница': 'Friday', 'суббота': 'Saturday', 'воскресенье': 'Sunday',
      'да': 'yes', 'нет': 'no',
    },
  },
  uk: {
    fields: { date: 'Дата' },
    results: {
      'Номер недели': 'Номер тижня',
      'Неделя относится к году': 'Тиждень належить до року',
      'День года': 'День року',
      'Всего дней в году': 'Усього днів у році',
      'День недели': 'День тижня',
      'Осталось дней до конца года': 'Залишилось днів до кінця року',
      'Високосный год': 'Високосний рік',
      'Проверьте данные': 'Перевірте дані',
    },
    values: {
      'Укажите корректную дату': 'Вкажіть коректну дату',
      'понедельник': 'понеділок', 'вторник': 'вівторок', 'среда': 'середа', 'четверг': 'четвер',
      'пятница': 'пʼятниця', 'суббота': 'субота', 'воскресенье': 'неділя',
      'да': 'так', 'нет': 'ні',
    },
  },
  de: {
      fields: {
        'date': 'Datum',
      },
      options: {},
      results: {
        'Номер недели': 'Kalenderwoche',
        'Неделя относится к году': 'Woche gehört zum Jahr',
        'День года': 'Tag des Jahres',
        'Всего дней в году': 'Tage im Jahr',
        'День недели': 'Wochentag',
        'Осталось дней до конца года': 'Verbleibende Tage im Jahr',
        'Високосный год': 'Schaltjahr',
        'Проверьте данные': 'Prüfe die Werte',
      },
      values: {
        'Укажите корректную дату': 'Gib ein gültiges Datum ein',
        'понедельник': 'Montag',
        'вторник': 'Dienstag',
        'среда': 'Mittwoch',
        'четверг': 'Donnerstag',
        'пятница': 'Freitag',
        'суббота': 'Samstag',
        'воскресенье': 'Sonntag',
        'да': 'ja',
        'нет': 'nein',
      },
  },
  es: {
    fields: {
      "date": "Fecha",
    },
    options: {},
    results: {
      "Номер недели": "Número de semana",
      "Неделя относится к году": "La semana pertenece al año",
      "День года": "Día del año",
      "Всего дней в году": "Días del año",
      "День недели": "Día de la semana",
      "Осталось дней до конца года": "Días que quedan hasta fin de año",
      "Високосный год": "Año bisiesto",
      "Проверьте данные": "Revisa los datos",
    },
    values: {
      "Укажите корректную дату": "Indica una fecha válida",
      "понедельник": "lunes",
      "вторник": "martes",
      "среда": "miércoles",
      "четверг": "jueves",
      "пятница": "viernes",
      "суббота": "sábado",
      "воскресенье": "domingo",
      "да": "sí",
      "нет": "no",
    },
  },
};
