import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was gesucht ist',
      'W': "Arbeit",
      't': "Zeit",
      'W2': "Arbeit",
      'P': "Leistung",
      'P2': "Leistung",
      't2': "Zeit",
    },
    options: {
      'mm': 'Millimeter',
      'cm': 'Zentimeter',
      'm': 'Meter',
      'P': "die Leistung",
      't': "die Zeit",
      'W': "die Arbeit",
    },
    results: {
      'Мощность': 'Leistung',
      'Работа': 'Arbeit',
      'Время': 'Zeit',
      'В метрических лошадиных силах': 'In metrischen Pferdestärken',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      "Неизвестный режим расчёта": "Unbekannter Berechnungsmodus",
      "Введите конечные числа для выбранного режима": "Gib endliche Zahlen für den gewählten Modus ein",
      "Результат выходит за числовой диапазон": "Das Ergebnis überschreitet den Zahlenbereich",

      'мм': 'mm',
      'см': 'cm',
      'м': 'm',
      'мм²': 'mm²',
      'см²': 'cm²',
      'м²': 'm²',
      'мм³': 'mm³',
      'см³': 'cm³',
      'м³': 'm³',
      'Вт': 'W',
      'Дж': 'J',
      'с': 's',
      'л.с.': 'PS',
      'Время должно быть больше нуля': 'Die Zeit muss größer als null sein',
      'Работа не может быть отрицательной': 'Die Arbeit kann nicht negativ sein',
      'Мощность должна быть больше нуля, иначе время не определено': 'Die Leistung muss größer als null sein, sonst ist die Zeit nicht bestimmt',
      'Мощность не может быть отрицательной': 'Die Leistung kann nicht negativ sein',
    },
  },
  en: {
    fields: {
      "mode": "What to find",
      "W": "Work",
      "t": "Time",
      "W2": "Work",
      "P": "Power",
      "P2": "Power",
      "t2": "Time",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "metres",
      "P": "the power",
      "t": "the time",
      "W": "the work",
    },
    results: {
      "Мощность": "Power",
      "Работа": "Work",
      "Время": "Time",
      "В метрических лошадиных силах": "In metric horsepower",
      "Проверьте данные": "Check the values",
    },
    values: {
      "Неизвестный режим расчёта": "Unknown calculation mode",
      "Введите конечные числа для выбранного режима": "Enter finite numbers for the selected mode",
      "Результат выходит за числовой диапазон": "The result exceeds the numerical range",

      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Вт": "W",
      "Дж": "J",
      "с": "s",
      "л.с.": "PS",
      "Время должно быть больше нуля": "The time must be greater than zero",
      "Работа не может быть отрицательной": "The work cannot be negative",
      "Мощность должна быть больше нуля, иначе время не определено": "The power must be greater than zero, otherwise the time is undetermined",
      "Мощность не может быть отрицательной": "The power cannot be negative",
    },
  },
  uk: {
    fields: {
      "mode": "Що знайти",
      "W": "Робота",
      "t": "Час",
      "W2": "Робота",
      "P": "Потужність",
      "P2": "Потужність",
      "t2": "Час",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "метри",
      "P": "потужність",
      "t": "час",
      "W": "роботу",
    },
    results: {
      "Мощность": "Потужність",
      "Работа": "Робота",
      "Время": "Час",
      "В метрических лошадиных силах": "У метричних кінських силах",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "Неизвестный режим расчёта": "Невідомий режим розрахунку",
      "Введите конечные числа для выбранного режима": "Введіть скінченні числа для обраного режиму",
      "Результат выходит за числовой диапазон": "Результат виходить за числовий діапазон",

      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Вт": "Вт",
      "Дж": "Дж",
      "с": "с",
      "л.с.": "к.с.",
      "Время должно быть больше нуля": "Час має бути більшим за нуль",
      "Работа не может быть отрицательной": "Робота не може бути від’ємною",
      "Мощность должна быть больше нуля, иначе время не определено": "Потужність має бути більшою за нуль, інакше час не визначений",
      "Мощность не может быть отрицательной": "Потужність не може бути від’ємною",
    },
  },
  es: {
    fields: {
      "mode": "Qué hallar",
      "W": "Trabajo",
      "t": "Tiempo",
      "W2": "Trabajo",
      "P": "Potencia",
      "P2": "Potencia",
      "t2": "Tiempo",
    },
    options: {
      "P": "la potencia",
      "t": "el tiempo",
      "W": "el trabajo",
      "mm": "milímetros",
      "cm": "centímetros",
      "m": "metros",
    },
    results: {
      "Мощность": "Potencia",
      "Работа": "Trabajo",
      "Время": "Tiempo",
      "В метрических лошадиных силах": "En caballos de vapor",
      "Проверьте данные": "Revisa los datos",
    },
    values: {
      "Неизвестный режим расчёта": "Modo de cálculo desconocido",
      "Введите конечные числа для выбранного режима": "Introduce números finitos para el modo elegido",
      "Результат выходит за числовой диапазон": "El resultado supera el rango numérico",

      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Вт": "W",
      "Дж": "J",
      "с": "s",
      "л.с.": "CV",
      "Время должно быть больше нуля": "El tiempo debe ser mayor que cero",
      "Работа не может быть отрицательной": "El trabajo no puede ser negativo",
      "Мощность должна быть больше нуля, иначе время не определено": "La potencia debe ser mayor que cero; de lo contrario el tiempo queda indeterminado",
      "Мощность не может быть отрицательной": "La potencia no puede ser negativa",
    },
  },
};
