import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was gesucht ist',
      'W': 'Arbeit, J',
      't': 'Zeit, s',
      'W2': 'Arbeit, J',
      'P': 'Leistung, W',
      'P2': 'Leistung, W',
      't2': 'Zeit, s',
    },
    options: {
      'mm': 'Millimeter',
      'cm': 'Zentimeter',
      'm': 'Meter',
      'P': 'die Leistung',
      't': 'die Zeit',
      'W': 'die Arbeit',
    },
    results: {
      'Мощность': 'Leistung',
      'Работа': 'Arbeit',
      'Время': 'Zeit',
      'В метрических лошадиных силах': 'In metrischen Pferdestärken',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'мм': 'mm',
      'см': 'cm',
      'м': 'm',
      'мм²': 'mm²',
      'см²': 'cm²',
      'м²': 'm²',
      'мм³': 'mm³',
      'см³': 'cm³',
      'м³': 'm³',
      'Вт': 'W',
      'Дж': 'J',
      'с': 's',
      'л.с.': 'PS',
      'Время должно быть больше нуля': 'Die Zeit muss größer als null sein',
      'Работа не может быть отрицательной': 'Die Arbeit kann nicht negativ sein',
      'Мощность должна быть больше нуля, иначе время не определено': 'Die Leistung muss größer als null sein, sonst ist die Zeit nicht bestimmt',
      'Мощность не может быть отрицательной': 'Die Leistung kann nicht negativ sein',
    },
  },
  en: {
    fields: {
      "mode": "What to find",
      "W": "Work, J",
      "t": "Time, s",
      "W2": "Work, J",
      "P": "Power, W",
      "P2": "Power, W",
      "t2": "Time, s",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "metres",
      "P": "the power",
      "t": "the time",
      "W": "the work",
    },
    results: {
      "Мощность": "Power",
      "Работа": "Work",
      "Время": "Time",
      "В метрических лошадиных силах": "In metric horsepower",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Вт": "W",
      "Дж": "J",
      "с": "s",
      "л.с.": "PS",
      "Время должно быть больше нуля": "The time must be greater than zero",
      "Работа не может быть отрицательной": "The work cannot be negative",
      "Мощность должна быть больше нуля, иначе время не определено": "The power must be greater than zero, otherwise the time is undetermined",
      "Мощность не может быть отрицательной": "The power cannot be negative",
    },
  },
  uk: {
    fields: {
      "mode": "Що знайти",
      "W": "Робота, Дж",
      "t": "Час, с",
      "W2": "Робота, Дж",
      "P": "Потужність, Вт",
      "P2": "Потужність, Вт",
      "t2": "Час, с",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "метри",
      "P": "потужність",
      "t": "час",
      "W": "роботу",
    },
    results: {
      "Мощность": "Потужність",
      "Работа": "Робота",
      "Время": "Час",
      "В метрических лошадиных силах": "У метричних кінських силах",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Вт": "Вт",
      "Дж": "Дж",
      "с": "с",
      "л.с.": "к.с.",
      "Время должно быть больше нуля": "Час має бути більшим за нуль",
      "Работа не может быть отрицательной": "Робота не може бути від’ємною",
      "Мощность должна быть больше нуля, иначе время не определено": "Потужність має бути більшою за нуль, інакше час не визначений",
      "Мощность не может быть отрицательной": "Потужність не може бути від’ємною",
    },
  },
};
