import type { CalculatorDef } from '../../lib/types';
type Copy = Pick<CalculatorDef, 'longDescription' | 'howToUse' | 'howItWorks' | 'example' | 'faq' | 'disclaimer'>;
export const contractContent: Record<'ru' | 'en' | 'uk' | 'de' | 'es', Copy> = {
  ru: {
    longDescription: 'Этот коэффициент делит суммарные действия на выбранную базу — охват публикации или число подписчиков. Действия могут включать лайки, комментарии, сохранения и распространения, причём один человек способен сделать несколько. Поэтому результат не является долей уникально вовлечённых людей и может превышать 100 %. Выбор базы указывается в ответе; он не даёт универсальной оценки качества публикации или здоровья аккаунта.',
    howToUse: ['Определите набор учитываемых действий и период; не меняйте их между сравниваемыми публикациями.', 'Введите целое неотрицательное количество действий.', 'Выберите положительную целую базу: уникальный охват публикации или число подписчиков на определённую дату. Неактивное поле не используется.', 'Сравнивайте одинаковые базы, периоды и наборы действий. Подписчики не означают, что каждый из них увидел публикацию.'],
    howItWorks: 'Для суммы действий E и выбранной базы B > 0 коэффициент = 100E/B процентов, действий на тысячу = 1000E/B. Повторные действия одного человека остаются в E. Ограничения E ≤ B нет: 150 действий и база 100 дают 150 %. Это не доля людей, которая должна укладываться в 100 %. Входные количества не округляются; обычный процент имеет два знака, показатель на тысячу — один.',
    example: '450 действий при охвате 9 000 дают 5,00 % и 50,0 действий на тысячу. Те же 450 при 4 000 подписчиках дают 11,25 % и 112,5 на тысячу: это другая база. При 150 действиях и охвате 100 результат 150 %, а при нуле действий и положительной базе — 0 %.',
    faq: [
      { q: 'Считает ли этот процент уникально вовлечённых людей?', a: 'Нет. В числителе сумма действий, в которой один человек может встречаться несколько раз. Для доли уникально вовлечённых нужен отдельный уникальный счётчик и согласованная база людей.' },
      { q: 'Как выбрать охват или подписчиков для сравнения?', a: 'Охват соотносит действия с людьми, получившими публикацию; подписчики — с размером выбранной базы аккаунта. Никто не гарантирует, что публикацию увидели все подписчики или только они. Между этими базами сравнивать проценты нельзя.' },
      { q: 'Что нужно зафиксировать в наборе действий?', a: 'Виды событий, период, включение повторов и правила фильтрации. Добавление сохранений или кликов меняет числитель. У разных платформ engagement может делиться на показы, поэтому название метрики само по себе не определяет формулу.' },
      { q: 'Доказывает ли рост коэффициента успешность публикации?', a: 'Он означает больше действий относительно выбранной базы, а не обязательно больше уникальных участников, заказов или прибыли. При неизменных действиях уменьшение базы тоже повышает коэффициент. Универсального хорошего процента здесь нет.' },
    ],
    disclaimer: 'Коэффициент событий по явно выбранной базе. Не доля уникальных людей, оценка здоровья аккаунта, универсальный стандарт платформы или показатель продаж.',
  },
  en: {
    longDescription: 'This ratio divides total actions by a selected base: post reach or follower count. Actions may include likes, comments, saves and shares, with one person able to make several. The result is therefore not the share of distinct engaged people and may exceed 100%. The selected base appears in the result; it does not establish post quality or account health.',
    howToUse: ['Define the included action types and reporting period and keep them fixed across posts.', 'Enter a nonnegative whole action count.', 'Choose a positive whole base: distinct post reach or followers at a defined date. The other base’s field is ignored.', 'Compare matched bases, periods and action definitions. Being a follower does not establish that the post was seen.'],
    howItWorks: 'For action count E and selected base B > 0: rate = 100E/B percent and actions per thousand = 1000E/B. Repeated actions by a person remain in E. There is no E ≤ B restriction: 150 actions with base 100 give 150%. This is not a unique-person share limited to 100%. Input counts are not rounded. Ordinary percentages use two decimal places and actions per thousand one.',
    example: '450 actions with reach 9,000 give 5.00% and 50.0 actions per thousand. The same 450 against 4,000 followers give 11.25% and 112.5 per thousand, using a different base. With 150 actions and reach 100 the result is 150%; zero actions with a positive base gives 0%.',
    faq: [
      { q: 'Does this percentage count distinct engaged people?', a: 'No. Its numerator sums actions, so a person may contribute several times. A distinct-person share requires its own deduplicated participant count and matched people denominator.' },
      { q: 'How should reach or followers be selected for comparison?', a: 'Reach relates actions to people reached by the post; followers relate them to an account base. Neither establishes that all followers saw it, or that only followers did. Percentages on these bases are not directly comparable.' },
      { q: 'Which parts of the action definition must stay fixed?', a: 'Event types, period, repeated-event treatment and filtering. Adding saves or clicks changes the numerator. Platforms can also define engagement over impressions, so the metric name alone does not establish its formula.' },
      { q: 'Does a rising rate prove a post is successful?', a: 'It means more actions relative to the selected base, not necessarily more unique participants, orders or profit. A smaller base also raises the rate with unchanged actions. No universal good percentage is assigned.' },
    ],
    disclaimer: 'An event ratio with an explicit base. Not a share of distinct people, an account-health score, a universal platform standard or sales performance.',
  },
  uk: {
    longDescription: 'Коефіцієнт ділить сумарні дії на обрану базу — охоплення публікації або кількість підписників. До дій можуть входити вподобання, коментарі, збереження й поширення; одна людина здатна зробити кілька дій. Тому це не частка унікально залучених людей, і результат може перевищувати 100 %. База вказується у відповіді, без універсальної оцінки якості публікації чи стану акаунта.',
    howToUse: ['Визначте типи дій та період і збережіть їх для всіх порівнюваних публікацій.', 'Введіть цілу невід’ємну кількість дій.', 'Оберіть додатну цілу базу: унікальне охоплення публікації або кількість підписників на визначену дату. Інше поле не використовується.', 'Порівнюйте однакові бази, періоди й визначення дій. Підписка не означає, що людина побачила публікацію.'],
    howItWorks: 'Для суми дій E та бази B > 0 коефіцієнт = 100E/B відсотків, дій на тисячу = 1000E/B. Повторні дії однієї людини лишаються в E. Умови E ≤ B немає: 150 дій за бази 100 дають 150 %. Це не частка унікальних людей, обмежена 100 %. Введені кількості не округлюються; звичайний відсоток має два знаки, показник на тисячу — один.',
    example: '450 дій за охоплення 9 000 дають 5,00 % та 50,0 дій на тисячу. Ті самі 450 за 4 000 підписників дають 11,25 % і 112,5 на тисячу — з іншою базою. За 150 дій і охоплення 100 результат 150 %, а за нуля дій та додатної бази — 0 %.',
    faq: [
      { q: 'Чи рахує цей відсоток унікально залучених людей?', a: 'Ні. Чисельник підсумовує дії, тому одна людина може бути врахована кілька разів. Для частки унікальних учасників потрібен окремий унікальний лічильник та узгоджена база людей.' },
      { q: 'Як обирати охоплення або підписників для порівняння?', a: 'Охоплення співвідносить дії з людьми, до яких дійшла публікація; підписники — з базою акаунта. Не гарантовано, що її бачили всі підписники або лише вони. Відсотки за різними базами напряму не порівнюють.' },
      { q: 'Що треба зберігати сталим у визначенні дій?', a: 'Типи подій, період, повтори та фільтрацію. Додавання збережень чи кліків змінює чисельник. Платформа також може ділити engagement на покази, тож сама назва не визначає формулу.' },
      { q: 'Чи доводить зростання коефіцієнта успіх публікації?', a: 'Воно означає більше дій відносно бази, а не обов’язково більше унікальних людей, замовлень чи прибутку. За сталих дій зменшення бази також підвищує результат. Універсального доброго відсотка тут немає.' },
    ],
    disclaimer: 'Коефіцієнт подій за явною базою. Не частка унікальних людей, оцінка стану акаунта, стандарт усіх платформ або показник продажів.',
  },
  de: {
    longDescription: 'Dieser Quotient teilt die Summe von Handlungen durch eine gewählte Basis: Beitragsreichweite oder Abonnentenzahl. Handlungen können Likes, Kommentare, Speicherungen und Weiterleitungen umfassen; eine Person kann mehrere auslösen. Das Ergebnis ist daher kein Anteil unterschiedlicher interagierender Personen und kann 100 % überschreiten. Die Basis wird genannt, ohne Beitragsqualität oder Kontozustand pauschal zu bewerten.',
    howToUse: ['Definiere Handlungstypen und Zeitraum und behalte sie für verglichene Beiträge bei.', 'Gib eine nicht negative ganze Anzahl von Handlungen ein.', 'Wähle eine positive ganze Basis: eindeutige Beitragsreichweite oder Abonnentenzahl zu einem festgelegten Datum. Das andere Feld bleibt unberücksichtigt.', 'Vergleiche gleiche Grundlagen, Zeiträume und Handlungsdefinitionen. Ein Abonnement belegt nicht, dass der Beitrag gesehen wurde.'],
    howItWorks: 'Bei Handlungen E und Basis B > 0 gilt Rate = 100E/B Prozent und Handlungen je tausend = 1000E/B. Wiederholte Handlungen einer Person bleiben in E. E ≤ B ist keine Bedingung: 150 Handlungen bei Basis 100 ergeben 150 %. Dies ist kein Personenanteil mit Obergrenze 100 %. Eingabezahlen bleiben ungerundet; übliche Prozente erhalten zwei Dezimalstellen, Handlungen je tausend eine.',
    example: '450 Handlungen bei Reichweite 9 000 ergeben 5,00 % und 50,0 je tausend. Dieselben 450 bei 4 000 Abonnenten ergeben 11,25 % und 112,5 je tausend auf einer anderen Basis. 150 Handlungen bei Reichweite 100 ergeben 150 %, null Handlungen bei positiver Basis 0 %.',
    faq: [
      { q: 'Zählt dieser Prozentsatz unterschiedliche interagierende Personen?', a: 'Nein. Der Zähler summiert Handlungen; eine Person kann mehrfach beitragen. Ein Personenanteil benötigt eine eigene deduplizierte Teilnehmerzahl und passenden Personennenner.' },
      { q: 'Wie wird Reichweite oder Abonnentenzahl für einen Vergleich gewählt?', a: 'Reichweite bezieht Handlungen auf erreichte Personen, Abonnenten auf eine Kontobasis. Weder haben zwingend alle Abonnenten den Beitrag gesehen, noch ausschließlich sie. Beide Prozentgrundlagen sind nicht direkt vergleichbar.' },
      { q: 'Was muss an der Handlungsdefinition gleich bleiben?', a: 'Ereignistypen, Zeitraum, Wiederholungen und Filter. Zusätzliche Speicherungen oder Klicks verändern den Zähler. Plattformen können Engagement auch durch Einblendungen teilen; der Name legt die Formel nicht fest.' },
      { q: 'Beweist eine steigende Rate den Erfolg eines Beitrags?', a: 'Sie bedeutet mehr Handlungen relativ zur Basis, nicht zwingend mehr verschiedene Personen, Bestellungen oder Gewinn. Eine kleinere Basis erhöht den Quotienten auch bei konstanten Handlungen. Ein allgemeines gutes Prozentziel wird nicht vergeben.' },
    ],
    disclaimer: 'Ereignisquotient mit ausdrücklicher Basis. Kein Anteil unterschiedlicher Personen, Kontozustandswert, allgemeiner Plattformstandard oder Verkaufsergebnis.',
  },
  es: {
    longDescription: 'Este cociente divide las acciones totales entre una base elegida: alcance de la publicación o número de seguidores. Las acciones pueden incluir me gusta, comentarios, guardados y compartidos, y una persona puede realizar varias. No es la proporción de personas distintas que interactuaron y puede superar 100 %. La base aparece en el resultado, sin valorar universalmente la calidad del contenido ni la salud de la cuenta.',
    howToUse: ['Define los tipos de acción y el periodo y mantenlos entre publicaciones comparadas.', 'Introduce un recuento entero no negativo de acciones.', 'Elige una base entera positiva: alcance único de la publicación o seguidores en una fecha definida. El otro campo no se utiliza.', 'Compara bases, periodos y definiciones iguales. Ser seguidor no demuestra haber visto la publicación.'],
    howItWorks: 'Para acciones E y base B > 0: tasa = 100E/B por ciento y acciones por mil = 1000E/B. Las acciones repetidas de una persona permanecen en E. No se exige E ≤ B: 150 acciones y base 100 dan 150 %. No es una proporción de personas con límite del 100 %. No se redondean recuentos de entrada; los porcentajes habituales tienen dos decimales y las acciones por mil uno.',
    example: '450 acciones con alcance 9 000 dan 5,00 % y 50,0 por mil. Las mismas 450 sobre 4 000 seguidores dan 11,25 % y 112,5 por mil, con otra base. Con 150 acciones y alcance 100 el resultado es 150 %; cero acciones con base positiva da 0 %.',
    faq: [
      { q: '¿Este porcentaje cuenta personas distintas que interactuaron?', a: 'No. El numerador suma acciones y una persona puede aportar varias. Una proporción de personas exige su propio recuento de participantes sin duplicados y un denominador coherente.' },
      { q: '¿Cómo se elige alcance o seguidores para comparar?', a: 'Alcance relaciona acciones con las personas alcanzadas; seguidores con una base de la cuenta. No garantiza que todos los seguidores vieran el contenido ni que solo ellos lo hicieran. Ambas bases no son directamente comparables.' },
      { q: '¿Qué debe mantenerse en la definición de acciones?', a: 'Tipos de evento, periodo, repeticiones y filtros. Añadir guardados o clics cambia el numerador. Las plataformas también pueden dividir engagement entre impresiones; el nombre no determina la fórmula.' },
      { q: '¿Una tasa creciente demuestra éxito de la publicación?', a: 'Indica más acciones respecto a la base, no necesariamente más personas únicas, pedidos ni beneficio. Una base menor también aumenta el cociente con acciones constantes. No se asigna un objetivo porcentual universal.' },
    ],
    disclaimer: 'Cociente de eventos con base explícita. No es proporción de personas únicas, puntuación de salud de cuenta, estándar universal ni resultado de ventas.',
  },
};
