import {fmtNumber}from '../format';
import {formatQuantity}from '../platform/measurement';
import {read,integer,decimal,dmul,dadd,ceilDecimal,type Decimal}from '../../calculators/beam-deflection/buildingWave13Numeric';
import {ratio}from '../platform/geometryNumericInput';
export{read,integer,decimal,dmul,dadd,ceilDecimal,type Decimal};
export const finite=(...xs:number[])=>xs.every(Number.isFinite);
export const positive=(...xs:number[])=>xs.every(x=>Number.isFinite(x)&&x>0);
export const optional=(raw:unknown,fallback=0)=>raw===undefined||typeof raw==='string'&&raw.trim()===''?fallback:read(raw);
export const mode=(raw:unknown,fallback:string,allowed:readonly string[])=>raw===undefined?fallback:typeof raw==='string'&&allowed.includes(raw)?raw:null;
export const div=(a:Decimal,b:Decimal):Decimal=>({n:a.n*b.d,d:a.d*b.n});
export const sub=(a:Decimal,b:Decimal):Decimal=>dadd(a,{n:-b.n,d:b.d});
export const factor=(reserve:number)=>div(dadd(decimal(100),decimal(reserve)),decimal(100));
export const value=(a:Decimal)=>ratio({coefficient:a.n,exponent:0},{coefficient:a.d,exponent:0});
export const ceiling=(a:Decimal,b:Decimal=decimal(1))=>a.n===0n?0:ceilDecimal(a,b);
export const flooring=(a:Decimal,b:Decimal)=>{const n=a.n*b.d,d=a.d*b.n;if(n<0n||d<=0n)return NaN;const q=n/d;return q<=BigInt(Number.MAX_SAFE_INTEGER)?Number(q):NaN;};
export const scalar=(x:number,digits=2)=>x!==0&&(Math.abs(x)<10**-digits||Math.abs(x)>=1e12)?formatQuantity(x,fmtNumber):fmtNumber(x,digits);
export const INPUT='Введите конечные числа во все активные поля';
export const MODE='Выберите поддерживаемый режим расчёта';
export const RANGE='Результат выходит за числовой диапазон; измените данные';
export const COUNTS='Количество окон, дверей и слоёв должно быть целым в допустимом диапазоне';
