import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was gesucht ist',
      'm': 'Masse, kg',
      'v': 'Geschwindigkeit, m/s',
      'p': 'Impuls, kg·m/s',
      'm2': 'Masse, kg',
      'p2': 'Impuls, kg·m/s',
      'v2': 'Geschwindigkeit, m/s',
    },
    options: {
      'mm': 'Millimeter',
      'cm': 'Zentimeter',
      'm': 'die Masse',
      'p': 'der Impuls',
      'v': 'die Geschwindigkeit',
    },
    results: {
      'Импульс': 'Impuls',
      'Масса': 'Masse',
      'Скорость': 'Geschwindigkeit',
      'Кинетическая энергия': 'Kinetische Energie',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'мм': 'mm',
      'см': 'cm',
      'м': 'm',
      'мм²': 'mm²',
      'см²': 'cm²',
      'м²': 'm²',
      'мм³': 'mm³',
      'см³': 'cm³',
      'м³': 'm³',
      'кг·м/с': 'kg·m/s',
      'кг': 'kg',
      'м/с': 'm/s',
      'Дж': 'J',
      'Масса должна быть больше нуля': 'Die Masse muss größer als null sein',
      'Скорость не может быть отрицательной': 'Die Geschwindigkeit kann nicht negativ sein',
      'Импульс не может быть отрицательным': 'Der Impuls kann nicht negativ sein',
      'Скорость должна быть больше нуля, иначе масса не определена': 'Die Geschwindigkeit muss größer als null sein, sonst ist die Masse nicht bestimmt',
    },
  },
  en: {
    fields: {
      "mode": "What to find",
      "m": "Mass, kg",
      "v": "Speed, m/s",
      "p": "Momentum, kg·m/s",
      "m2": "Mass, kg",
      "p2": "Momentum, kg·m/s",
      "v2": "Speed, m/s",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "the mass",
      "p": "the momentum",
      "v": "the speed",
    },
    results: {
      "Импульс": "Momentum",
      "Масса": "Mass",
      "Скорость": "Speed",
      "Кинетическая энергия": "Kinetic energy",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "кг·м/с": "kg·m/s",
      "кг": "kg",
      "м/с": "m/s",
      "Дж": "J",
      "Масса должна быть больше нуля": "The mass must be greater than zero",
      "Скорость не может быть отрицательной": "The speed cannot be negative",
      "Импульс не может быть отрицательным": "The momentum cannot be negative",
      "Скорость должна быть больше нуля, иначе масса не определена": "The speed must be greater than zero, otherwise the mass is undetermined",
    },
  },
  uk: {
    fields: {
      "mode": "Що знайти",
      "m": "Маса, кг",
      "v": "Швидкість, м/с",
      "p": "Імпульс, кг·м/с",
      "m2": "Маса, кг",
      "p2": "Імпульс, кг·м/с",
      "v2": "Швидкість, м/с",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "масу",
      "p": "імпульс",
      "v": "швидкість",
    },
    results: {
      "Импульс": "Імпульс",
      "Масса": "Маса",
      "Скорость": "Швидкість",
      "Кинетическая энергия": "Кінетична енергія",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "кг·м/с": "кг·м/с",
      "кг": "кг",
      "м/с": "м/с",
      "Дж": "Дж",
      "Масса должна быть больше нуля": "Маса має бути більшою за нуль",
      "Скорость не может быть отрицательной": "Швидкість не може бути від’ємною",
      "Импульс не может быть отрицательным": "Імпульс не може бути від’ємним",
      "Скорость должна быть больше нуля, иначе масса не определена": "Швидкість має бути більшою за нуль, інакше маса не визначена",
    },
  },
};
