import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'age': 'Alter, Jahre',
      'formula': 'Formel für die Schätzung',
      'restingHr': 'Ruhepuls, Schläge/min',
    },
    options: {
      '220-age': '220 − Alter, die klassische',
      'tanaka': 'Tanaka: 208 − 0,7 × Alter',
      'gulati': 'Gulati: 206 − 0,88 × Alter',
    },
    results: {
      'Максимальный пульс': 'Maximalpuls',
      'Резерв сердца': 'Herzfrequenzreserve',
      'Пульс покоя': 'Ruhepuls',
      'Аэробная зона 70–80 %': 'Aerober Bereich 70–80 %',
      'Жиросжигающая зона 60–70 %': 'Fettverbrennungsbereich 60–70 %',
      'Тренировочные зоны': 'Trainingsbereiche',
      'Зона': 'Bereich',
      'Доля резерва': 'Anteil der Reserve',
      'Пульс, уд/мин': 'Puls, Schläge/min',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'уд/мин': 'Schläge/min',
      'Разминка': 'Aufwärmen',
      'Жиросжигание': 'Fettverbrennung',
      'Аэробная': 'Aerob',
      'Анаэробная': 'Anaerob',
      'Максимальная': 'Maximal',
      'Зоны посчитаны по резерву сердца: доля берётся от разности максимума и пульса покоя.': 'Die Bereiche folgen der Herzfrequenzreserve: der Anteil wird aus dem Abstand zwischen Maximalpuls und Ruhepuls genommen.',
      'Пульс покоя не задан, поэтому зоны — прямые доли максимального пульса.': 'Es wurde kein Ruhepuls angegeben, die Bereiche sind deshalb unmittelbare Anteile des Maximalpulses.',
      'Возраст должен быть от 1 до 120 лет': 'Das Alter muss zwischen 1 und 120 Jahren liegen',
      'Пульс покоя не может быть отрицательным': 'Der Ruhepuls kann nicht negativ sein',
      'Пульс покоя не может быть выше максимального': 'Der Ruhepuls kann nicht über dem Maximalpuls liegen',
    },
  },
  en: {
    fields: {
      "age": "Age, years",
      "formula": "Estimation formula",
      "restingHr": "Resting heart rate, bpm",
    },
    options: {
      "220-age": "220 − age, the classic",
      "tanaka": "Tanaka: 208 − 0.7 × age",
      "gulati": "Gulati: 206 − 0.88 × age",
    },
    results: {
      "Максимальный пульс": "Maximum heart rate",
      "Резерв сердца": "Heart rate reserve",
      "Пульс покоя": "Resting heart rate",
      "Аэробная зона 70–80 %": "Aerobic zone 70–80%",
      "Жиросжигающая зона 60–70 %": "Fat-burning zone 60–70%",
      "Тренировочные зоны": "Training zones",
      "Зона": "Zone",
      "Доля резерва": "Share of reserve",
      "Пульс, уд/мин": "Heart rate, bpm",
      "Проверьте данные": "Check the values",
    },
    values: {
      "уд/мин": "bpm",
      "Разминка": "Warm-up",
      "Жиросжигание": "Fat burning",
      "Аэробная": "Aerobic",
      "Анаэробная": "Anaerobic",
      "Максимальная": "Maximum",
      "Зоны посчитаны по резерву сердца: доля берётся от разности максимума и пульса покоя.": "Zones follow heart rate reserve: the share is taken from the gap between the maximum and the resting rate.",
      "Пульс покоя не задан, поэтому зоны — прямые доли максимального пульса.": "No resting rate was given, so the zones are straight shares of the maximum.",
      "Возраст должен быть от 1 до 120 лет": "Age must be between 1 and 120",
      "Пульс покоя не может быть отрицательным": "The resting heart rate cannot be negative",
      "Пульс покоя не может быть выше максимального": "The resting rate cannot exceed the maximum",
    },
  },
  uk: {
    fields: {
      "age": "Вік, років",
      "formula": "Формула оцінки",
      "restingHr": "Пульс спокою, уд/хв",
    },
    options: {
      "220-age": "220 − вік, класична",
      "tanaka": "Танака: 208 − 0,7 × вік",
      "gulati": "Гулаті: 206 − 0,88 × вік",
    },
    results: {
      "Максимальный пульс": "Максимальний пульс",
      "Резерв сердца": "Резерв серця",
      "Пульс покоя": "Пульс спокою",
      "Аэробная зона 70–80 %": "Аеробна зона 70–80 %",
      "Жиросжигающая зона 60–70 %": "Жироспалювальна зона 60–70 %",
      "Тренировочные зоны": "Тренувальні зони",
      "Зона": "Зона",
      "Доля резерва": "Частка резерву",
      "Пульс, уд/мин": "Пульс, уд/хв",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "уд/мин": "уд/хв",
      "Разминка": "Розминка",
      "Жиросжигание": "Жироспалювання",
      "Аэробная": "Аеробна",
      "Анаэробная": "Анаеробна",
      "Максимальная": "Максимальна",
      "Зоны посчитаны по резерву сердца: доля берётся от разности максимума и пульса покоя.": "Зони пораховані за резервом серця: частка береться від різниці максимуму та пульсу спокою.",
      "Пульс покоя не задан, поэтому зоны — прямые доли максимального пульса.": "Пульс спокою не задано, тож зони — прямі частки максимального пульсу.",
      "Возраст должен быть от 1 до 120 лет": "Вік має бути від 1 до 120 років",
      "Пульс покоя не может быть отрицательным": "Пульс спокою не може бути від'ємним",
      "Пульс покоя не может быть выше максимального": "Пульс спокою не може бути вищим за максимальний",
    },
  },
};
