import type { CalculatorDef } from '../../lib/types';
type Copy = Pick<CalculatorDef, 'longDescription' | 'howToUse' | 'howItWorks' | 'example' | 'faq' | 'disclaimer'>;
export const contractContent: Record<'ru' | 'en' | 'uk' | 'de' | 'es', Copy> = {
  ru: {
    longDescription: 'MRR здесь описывает текущий месячный темп повторяющейся выручки: число учитываемых подписчиков умножается на их среднюю месячную сумму. ARR переводит этот темп в годовой масштаб умножением на 12. Ни MRR, ни ARR не равны автоматически деньгам, поступившим за календарный период. Отдельный процент задаёт ваш сценарий изменения MRR на следующий месяц, без прогнозирования продаж на год.',
    howToUse: ['Возьмите положительное целое число подписчиков, включённых в расчёт регулярной выручки, и положительную среднюю месячную сумму для той же базы.', 'Годовой регулярный тариф предварительно разделите на 12; разовые платежи исключите.', 'Задайте предполагаемое изменение MRR за один месяц: отрицательное для снижения, не ниже −100 %. Если меняется только число клиентов, этот сценарий предполагает постоянную среднюю сумму.', 'Используйте одну валюту без обмена и заранее определите учёт скидок, возвратов, налогов и неоплаченных подписок.'],
    howItWorks: 'При числе подписчиков N и среднем месячном регулярном доходе A: MRR = N × A, ARR = 12 × MRR. Для изменения g в долях: следующий MRR = MRR × (1 + g), разница = MRR × g. −100 % даёт нулевой следующий MRR. Никакой суммы за прошедшие или будущие 12 месяцев эта формула не собирает. Промежуточные значения не округляются, обычные денежные результаты имеют два знака.',
    example: '420 подписчиков по 1 490 денежных единиц в месяц: MRR 625 800, ARR 7 509 600. Сценарий +4 % даёт следующий MRR 650 832 и прирост 25 032. Сценарий −100 % даёт следующий MRR 0 и разницу −625 800. Отдельный исторический пример: шесть месяцев по 100 и шесть по 200 дают годовую выручку 1 800, хотя ARR последнего месяца равна 2 400.',
    faq: [
      { q: 'Почему ARR последнего месяца не равна выручке года?', a: 'ARR берёт один текущий месячный темп и умножает его на 12. Фактический год складывается из разных месяцев. Даже удвоение MRR к декабрю не означает удвоения полученной выручки за год.' },
      { q: 'Включать ли установку и другие разовые платежи в MRR?', a: 'Нет. Они относятся к общей выручке или поступлениям, но не создают повторяющийся месячный темп. Разовые суммы не следует делить на 12, чтобы искусственно добавить их в MRR.' },
      { q: 'Как учитывать оплату годового регулярного тарифа?', a: 'Нормализуйте сумму к месяцу: 12 000 за год дают 1 000 в месяц. Месяц получения всей оплаты и месячный темп остаются разными величинами; скидки учитывают по заранее выбранным правилам.' },
      { q: 'Предсказывает ли введённое изменение число клиентов?', a: 'Нет. Оно задаёт сценарий месячной выручки. Новые клиенты, уход, изменения тарифа и скидки могут давать одинаковую суммарную динамику; калькулятор не определяет её причины.' },
      { q: 'Чем этот MRR отличается от ценности одного клиента?', a: 'MRR относится ко всей текущей базе за условный месяц. LTV относится к одному клиенту за его срок жизни и может учитывать маржу, отток и время. MRR сам по себе не показывает прибыль или окупаемость привлечения.' },
    ],
    disclaimer: 'Регулярный месячный темп и сценарий следующего месяца. Не бухгалтерское признание выручки, денежный поток, годовой прогноз или оценка прибыли.',
  },
  en: {
    longDescription: 'MRR here describes the current monthly recurring revenue rate: included subscribers multiplied by their average monthly recurring amount. ARR expresses that rate annually by multiplying it by twelve. Neither automatically equals cash received during a calendar period. A separate percentage supplies your scenario for next month’s MRR, without forecasting a full year of sales.',
    howToUse: ['Use a positive whole count of subscribers included in recurring revenue and their positive average monthly amount on the same basis.', 'Normalize annual recurring plans by dividing by twelve; exclude one-off payments.', 'Set an assumed one-month MRR change, negative for contraction and no lower than −100%. If only customer count changes, this scenario assumes the average amount stays fixed.', 'Use one currency without conversion and define discounts, refunds, taxes and unpaid-subscription treatment in advance.'],
    howItWorks: 'For included subscribers N and average monthly recurring amount A: MRR = N × A and ARR = 12 × MRR. With change share g, next MRR = MRR × (1 + g) and difference = MRR × g. A −100% change leaves next MRR zero. The formula does not sum twelve past or future months. Intermediate values stay unrounded; ordinary monetary outputs use two decimal places.',
    example: '420 subscribers at 1,490 monetary units monthly give MRR 625,800 and ARR 7,509,600. A +4% scenario gives next MRR 650,832 and change 25,032. A −100% scenario gives next MRR 0 and change −625,800. In a separate historical example, six months at 100 and six at 200 total 1,800 revenue, although the last month’s ARR is 2,400.',
    faq: [
      { q: 'Why is the final month’s ARR different from annual revenue?', a: 'ARR annualizes one current monthly rate. Actual annual revenue combines different months. Even doubling MRR by December does not imply doubling the year’s realized revenue.' },
      { q: 'Do setup fees and other one-off payments belong in MRR?', a: 'No. They belong to total revenue or cash receipts, but do not create a recurring monthly rate. Dividing a one-off amount by twelve does not turn it into MRR.' },
      { q: 'How does an annual recurring plan enter this monthly model?', a: 'Normalize its amount: 12,000 a year becomes 1,000 a month. Receiving the full payment and earning the monthly recurring rate are separate measures; apply a defined discount policy.' },
      { q: 'Does the entered change predict the customer count?', a: 'No. It sets a monthly revenue scenario. New customers, churn, plan changes and discounts can produce the same aggregate change; this calculator does not identify its cause.' },
      { q: 'How does this MRR differ from one customer’s lifetime value?', a: 'MRR covers the current base for a normalized month. LTV covers one customer’s lifetime and can include margin, churn and timing. MRR alone does not establish profit or acquisition payback.' },
    ],
    disclaimer: 'Current recurring rate and a next-month scenario. Not accounting revenue recognition, cash flow, a yearly forecast or profit.',
  },
  uk: {
    longDescription: 'MRR тут означає поточний місячний темп регулярного виторгу: кількість врахованих передплатників множиться на їхню середню місячну суму. ARR переводить цей темп у річний масштаб множенням на 12. Це не автоматично кошти, отримані за календарний період. Окремий відсоток задає ваш сценарій MRR наступного місяця, без прогнозу продажів на рік.',
    howToUse: ['Введіть додатну цілу кількість передплатників бази регулярного виторгу та додатну середню місячну суму для тієї самої бази.', 'Річний регулярний тариф поділіть на 12; разові платежі виключіть.', 'Задайте припущену зміну MRR за місяць: від’ємну для зменшення, не нижчу за −100 %. Якщо змінюється лише кількість клієнтів, середню суму вважають сталою.', 'Валюта спільна без обміну. Заздалегідь визначте правила знижок, повернень, податків та неоплачених передплат.'],
    howItWorks: 'За кількості передплатників N і середньої місячної регулярної суми A: MRR = N × A, ARR = 12 × MRR. Для частки зміни g: наступний MRR = MRR × (1 + g), різниця = MRR × g. Зміна −100 % дає наступний MRR 0. Формула не підсумовує 12 минулих чи майбутніх місяців. Проміжні числа не округлюються; звичайні грошові результати мають два знаки.',
    example: '420 передплатників по 1 490 грошових одиниць на місяць: MRR 625 800, ARR 7 509 600. Сценарій +4 % дає наступний MRR 650 832 і приріст 25 032. За −100 % наступний MRR 0, різниця −625 800. Окремий історичний приклад: шість місяців по 100 і шість по 200 дають річний виторг 1 800, хоча ARR останнього місяця 2 400.',
    faq: [
      { q: 'Чому ARR останнього місяця не дорівнює виторгу року?', a: 'ARR множить один поточний місячний темп на 12. Реальний рік складається з різних місяців. Навіть подвоєння MRR до грудня не означає подвоєння фактичного річного виторгу.' },
      { q: 'Чи входять встановлення та разові платежі до MRR?', a: 'Ні. Вони належать до загального виторгу чи надходжень, але не створюють регулярного місячного темпу. Ділення разової суми на 12 не робить її частиною MRR.' },
      { q: 'Як річний регулярний тариф входить до місячного розрахунку?', a: 'Суму нормалізують: 12 000 за рік означають 1 000 на місяць. Місяць отримання повної оплати та місячний темп — різні величини. Для знижок застосовуйте визначені правила.' },
      { q: 'Чи прогнозує задана зміна кількість клієнтів?', a: 'Ні. Це сценарій місячного виторгу. Нові клієнти, відтік, зміни тарифів і знижок можуть давати однаковий загальний результат; причини калькулятор не визначає.' },
      { q: 'Чим MRR бази відрізняється від цінності одного клієнта?', a: 'MRR стосується поточної бази за умовний місяць. LTV — одного клієнта за строк його життя з можливим урахуванням маржі й відтоку. MRR не визначає прибуток або окупність залучення.' },
    ],
    disclaimer: 'Регулярний місячний темп та сценарій наступного місяця. Не бухгалтерське визнання виторгу, грошовий потік, річний прогноз або прибуток.',
  },
  de: {
    longDescription: 'MRR beschreibt hier die aktuelle monatliche Rate wiederkehrender Umsätze: berücksichtigte Abonnenten mal mittlerem monatlichem Vertragsbetrag. ARR rechnet diese Rate mit dem Faktor zwölf auf ein Jahr hoch. Beide entsprechen nicht automatisch den Geldzuflüssen eines Kalenderzeitraums. Ein eigener Prozentsatz setzt dein Szenario für den nächsten Monat, ohne Jahresverkäufe vorherzusagen.',
    howToUse: ['Nutze eine positive ganze Abonnentenzahl der berücksichtigten Umsatzbasis und einen positiven mittleren Monatsbetrag derselben Basis.', 'Teile jährliche wiederkehrende Tarife durch zwölf; Einmalzahlungen bleiben außen vor.', 'Setze eine angenommene MRR-Änderung für einen Monat, negativ bei Rückgang, mindestens −100 %. Bei reiner Kundenzahländerung bleibt der Durchschnittsbetrag annahmegemäß konstant.', 'Eine gemeinsame Währung wird nicht umgerechnet. Definiere Rabatte, Erstattungen, Steuern und unbezahlte Verträge vorab.'],
    howItWorks: 'Für Abonnenten N und mittleren monatlichen Vertragsbetrag A gilt MRR = N × A und ARR = 12 × MRR. Mit Änderungsanteil g: nächster MRR = MRR × (1 + g), Differenz = MRR × g. −100 % lässt den nächsten MRR null werden. Die Formel summiert keine zwölf vergangenen oder zukünftigen Monate. Zwischenwerte bleiben ungerundet; übliche Geldbeträge erhalten zwei Dezimalstellen.',
    example: '420 Abonnenten zu 1 490 Geldeinheiten monatlich ergeben MRR 625 800 und ARR 7 509 600. Das Szenario +4 % ergibt nächsten MRR 650 832 und Zuwachs 25 032. Bei −100 % sind nächster MRR 0 und Differenz −625 800. Sechs historische Monate zu 100 und sechs zu 200 ergeben 1 800 Jahresumsatz, obwohl der letzte Monats-ARR 2 400 beträgt.',
    faq: [
      { q: 'Warum unterscheidet sich der letzte Monats-ARR vom Jahresumsatz?', a: 'ARR annualisiert eine aktuelle Monatsrate. Der tatsächliche Jahresumsatz besteht aus unterschiedlichen Monaten. Ein bis Dezember verdoppelter MRR bedeutet keinen verdoppelten realisierten Jahresumsatz.' },
      { q: 'Gehören Einrichtungskosten und Einmalzahlungen in den MRR?', a: 'Nein. Sie gehören zu Gesamtumsatz oder Geldzuflüssen, erzeugen aber keine wiederkehrende Monatsrate. Eine Einmalzahlung durch zwölf zu teilen macht sie nicht zum MRR.' },
      { q: 'Wie wird ein jährlicher wiederkehrender Tarif berücksichtigt?', a: 'Normalisiere den Betrag: 12 000 jährlich werden 1 000 monatlich. Die vollständige Zahlung und die monatliche Vertragsrate sind unterschiedliche Größen. Rabatte benötigen eine festgelegte Behandlung.' },
      { q: 'Sagt die eingegebene Änderung die Kundenzahl voraus?', a: 'Nein. Sie legt ein Monatsumsatzszenario fest. Neue Kunden, Abwanderung, Tarifwechsel und Rabatte können dieselbe Gesamtänderung erzeugen; ihre Ursache wird nicht berechnet.' },
      { q: 'Wie unterscheidet sich der MRR der Basis vom Wert eines Kunden?', a: 'MRR betrifft die aktuelle Basis für einen normierten Monat. LTV betrifft einen Kunden über seine Laufzeit und kann Marge und Abwanderung einbeziehen. MRR bestimmt weder Gewinn noch Akquisitionsamortisation.' },
    ],
    disclaimer: 'Wiederkehrende Monatsrate und Szenario für den nächsten Monat. Keine bilanzielle Umsatzrealisierung, kein Zahlungsstrom, keine Jahresprognose oder Gewinnrechnung.',
  },
  es: {
    longDescription: 'MRR describe aquí el ritmo mensual actual de ingresos recurrentes: suscriptores incluidos por importe recurrente mensual medio. ARR anualiza ese ritmo multiplicándolo por doce. Ninguno equivale automáticamente al efectivo cobrado en un periodo del calendario. Otro porcentaje define tu escenario para el MRR del siguiente mes, sin pronosticar un año completo de ventas.',
    howToUse: ['Usa un número entero positivo de suscriptores incluidos y su importe mensual recurrente medio positivo sobre la misma base.', 'Divide las tarifas anuales recurrentes entre doce y excluye los pagos únicos.', 'Fija una variación supuesta del MRR para un mes, negativa para descensos y no inferior a −100 %. Si solo cambia el número de clientes, se supone constante el importe medio.', 'Usa una moneda sin conversión. Define previamente descuentos, devoluciones, impuestos y suscripciones sin pagar.'],
    howItWorks: 'Con suscriptores N e importe recurrente mensual medio A: MRR = N × A y ARR = 12 × MRR. Para una fracción de variación g: siguiente MRR = MRR × (1 + g), diferencia = MRR × g. −100 % deja el siguiente MRR en cero. La fórmula no suma doce meses pasados ni futuros. No se redondean valores intermedios; los importes habituales usan dos decimales.',
    example: '420 suscriptores a 1 490 unidades monetarias mensuales dan MRR 625 800 y ARR 7 509 600. Un escenario +4 % da siguiente MRR 650 832 y aumento 25 032. Con −100 %, siguiente MRR es 0 y diferencia −625 800. Seis meses históricos a 100 y seis a 200 totalizan 1 800 de ingresos anuales, aunque el ARR del último mes es 2 400.',
    faq: [
      { q: '¿Por qué el ARR del último mes difiere de los ingresos anuales?', a: 'ARR anualiza un ritmo mensual actual. Los ingresos reales del año combinan meses diferentes. Duplicar MRR hasta diciembre no implica duplicar el ingreso realizado del año.' },
      { q: '¿Las cuotas de alta y pagos únicos pertenecen al MRR?', a: 'No. Son ingresos totales o cobros, pero no crean un ritmo recurrente mensual. Dividir un pago único entre doce no lo convierte en MRR.' },
      { q: '¿Cómo se incluye una tarifa anual recurrente?', a: 'Normaliza el importe: 12 000 al año son 1 000 al mes. El cobro completo y el ritmo mensual son medidas diferentes. Los descuentos necesitan una política definida.' },
      { q: '¿La variación introducida predice cuántos clientes habrá?', a: 'No. Define un escenario de ingresos mensuales. Clientes nuevos, bajas, cambios de tarifa y descuentos pueden producir igual variación agregada; no se identifica la causa.' },
      { q: '¿En qué difiere este MRR del valor de un cliente?', a: 'MRR corresponde a la base actual durante un mes normalizado. LTV corresponde a un cliente durante su permanencia y puede incluir margen y abandono. MRR no determina beneficio ni recuperación de captación.' },
    ],
    disclaimer: 'Ritmo recurrente mensual y escenario del próximo mes. No es reconocimiento contable, flujo de caja, previsión anual ni beneficio.',
  },
};
