import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was gesucht ist',
      'f': 'Brennweite, cm',
      'do': 'Gegenstandsweite, cm',
      'di': 'Bildweite, cm',
    },
    options: {
      'image': 'die Bildweite',
      'focal': 'die Brennweite',
    },
    results: {
      'Расстояние до изображения': 'Bildweite',
      'Фокусное расстояние': 'Brennweite',
      'Увеличение': 'Abbildungsmaßstab',
      'Тип изображения': 'Bildart',
      'Оптическая сила': 'Brechkraft',
      'Расстояние до предмета': 'Gegenstandsweite',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'см': 'cm',
      'дптр': 'dpt',
      'действительное перевёрнутое': 'reell und umgekehrt',
      'мнимое прямое': 'virtuell und aufrecht',
      'Выберите режим расчёта из списка': 'Wähle einen Rechenmodus aus der Liste',
      'Расстояние до предмета должно быть больше нуля': 'Die Gegenstandsweite muss größer als null sein',
      'Фокусное расстояние не может быть нулевым': 'Die Brennweite kann nicht null sein',
      'Предмет в фокусе — изображения нет': 'Der Gegenstand steht im Brennpunkt — es entsteht kein Bild',
      'Расстояние до изображения не может быть нулевым': 'Die Bildweite kann nicht null sein',
      'Такая пара расстояний фокуса не задаёт': 'Dieses Paar von Abständen legt keine Brennweite fest',
    },
  },
  en: {
    fields: {
      mode: 'What to find', f: 'Focal length, cm',
      do: 'Object distance, cm', di: 'Image distance, cm',
    },
    options: { image: 'image distance', focal: 'focal length' },
    results: {
      'Расстояние до изображения': 'Image distance', 'Фокусное расстояние': 'Focal length',
      'Увеличение': 'Magnification', 'Тип изображения': 'Image type',
      'Оптическая сила': 'Optical power', 'Расстояние до предмета': 'Object distance',
      'Проверьте данные': 'Check the values',
    },
    values: {
      'см': 'cm', 'дптр': 'D',
      'действительное перевёрнутое': 'real and inverted',
      'мнимое прямое': 'virtual and upright',
      'Выберите режим расчёта из списка': 'Choose a calculation mode from the list',
      'Расстояние до предмета должно быть больше нуля': 'The object distance must be greater than zero',
      'Фокусное расстояние не может быть нулевым': 'The focal length cannot be zero',
      'Предмет в фокусе — изображения нет': 'The object sits at the focus — no image is formed',
      'Расстояние до изображения не может быть нулевым': 'The image distance cannot be zero',
      'Такая пара расстояний фокуса не задаёт': 'This pair of distances does not define a focal length',
    },
  },
  uk: {
    fields: {
      mode: 'Що шукаємо', f: 'Фокусна відстань, см',
      do: 'Відстань до предмета, см', di: 'Відстань до зображення, см',
    },
    options: { image: 'відстань до зображення', focal: 'фокусна відстань' },
    results: {
      'Расстояние до изображения': 'Відстань до зображення', 'Фокусное расстояние': 'Фокусна відстань',
      'Увеличение': 'Збільшення', 'Тип изображения': 'Тип зображення',
      'Оптическая сила': 'Оптична сила', 'Расстояние до предмета': 'Відстань до предмета',
      'Проверьте данные': 'Перевірте дані',
    },
    values: {
      'см': 'см', 'дптр': 'дптр',
      'действительное перевёрнутое': 'дійсне перевернуте',
      'мнимое прямое': 'уявне пряме',
      'Выберите режим расчёта из списка': 'Оберіть режим розрахунку зі списку',
      'Расстояние до предмета должно быть больше нуля': 'Відстань до предмета має бути більшою за нуль',
      'Фокусное расстояние не может быть нулевым': 'Фокусна відстань не може дорівнювати нулю',
      'Предмет в фокусе — изображения нет': 'Предмет у фокусі — зображення не утворюється',
      'Расстояние до изображения не может быть нулевым': 'Відстань до зображення не може дорівнювати нулю',
      'Такая пара расстояний фокуса не задаёт': 'Така пара відстаней фокуса не задає',
    },
  },
  es: {
    fields: {
      "mode": "Qué hallar",
      "f": "Distancia focal, cm",
      "do": "Distancia al objeto, cm",
      "di": "Distancia a la imagen, cm",
    },
    options: {
      "image": "distancia a la imagen",
      "focal": "distancia focal",
    },
    results: {
      "Расстояние до изображения": "Distancia a la imagen",
      "Фокусное расстояние": "Distancia focal",
      "Увеличение": "Aumento",
      "Тип изображения": "Tipo de imagen",
      "Оптическая сила": "Potencia óptica",
      "Расстояние до предмета": "Distancia al objeto",
      "Проверьте данные": "Revisa los datos",
    },
    values: {
      "см": "cm",
      "дптр": "dioptrías",
      "действительное перевёрнутое": "real e invertida",
      "мнимое прямое": "virtual y derecha",
      "Выберите режим расчёта из списка": "Elige un modo de cálculo de la lista",
      "Расстояние до предмета должно быть больше нуля": "La distancia al objeto debe ser mayor que cero",
      "Фокусное расстояние не может быть нулевым": "La distancia focal no puede ser cero",
      "Предмет в фокусе — изображения нет": "El objeto está en el foco: no se forma imagen",
      "Расстояние до изображения не может быть нулевым": "La distancia a la imagen no puede ser cero",
      "Такая пара расстояний фокуса не задаёт": "Este par de distancias no define ninguna distancia focal",
    },
  },
};
