import type { CalculatorDef } from '../../lib/types';
type Copy = Pick<CalculatorDef, 'longDescription' | 'howToUse' | 'howItWorks' | 'example' | 'faq' | 'disclaimer'>;
export const contractContent: Record<'ru' | 'en' | 'uk' | 'de' | 'es', Copy> = {
  ru: {
    longDescription: 'Здесь одна введённая выручка делится на две базы: всех учитываемых пользователей и платящих среди них. Это позволяет сравнить средние величины и долю платящих при одинаковом периоде и составе выручки. В аналитических системах числители ARPU и ARPPU иногда различаются, например рекламная выручка может входить только в ARPU. Такие показатели нельзя автоматически сверять по тождеству этого калькулятора.',
    howToUse: ['Определите одну базу выручки и один период. Для покупок используйте согласованный учёт возвратов.', 'Введите положительную выручку и положительное целое число уникальных пользователей выбранной базы.', 'Число платящих — целое от 0 до общего числа пользователей; один человек с несколькими покупками считается одним платящим.', 'Денежная единица общая, обмена валют нет. Если нужны разные виды выручки для двух метрик, рассчитывайте их отдельно.'],
    howItWorks: 'При выручке R > 0, пользователях U > 0 и платящих P: ARPU = R/U. Если P > 0, ARPPU = R/P, доля платящих = P/U и ARPU = ARPPU × P/U до округления. При P = 0 строка ARPPU отсутствует, доля равна 0. Количества — точные целые, а не дробные кредиты атрибуции. Обычные суммы и проценты отображаются с двумя знаками.',
    example: 'Выручка 500 000 денежных единиц, 12 500 пользователей и 900 платящих: ARPU 40,00, ARPPU 555,56, доля 7,20 %. При 2 000 пользователях, каждый из которых платит, и выручке 300 000 обе величины равны 150,00. Снижение доли не требует уменьшения числа людей: R=100, U=100, P=10 дают долю 10 %, а R=200, U=1000, P=15 — 1,5 %, хотя платящих стало больше.',
    faq: [
      { q: 'Почему общий числитель важно проверить в аналитическом отчёте?', a: 'При разных видах выручки связь через долю платящих меняется. Например, в GA4 ARPPU использует выручку покупок, а ARPU может включать рекламу. Здесь оба отношения используют одну введённую сумму; это отдельная явная модель.' },
      { q: 'Что означает рост ARPPU при падении ARPU?', a: 'При одном положительном числителе и согласованных базах уменьшается доля платящих. Их абсолютное число может одновременно вырасти, если общая аудитория растёт быстрее. По двум средним нельзя определить число людей без баз.' },
      { q: 'Почему ARPPU не отображается при нуле платящих?', a: 'Для него нет положительного знаменателя. Положительная выручка при нуле платящих может относиться к рекламе или другой базе; ARPU рассчитает введённое отношение, но выручку на платящего вычислить нельзя.' },
      { q: 'Всегда ли ARPU больше среднего чека?', a: 'Нет. Средний чек делит выручку на число заказов, ARPU — на число пользователей. Соотношение зависит от заказов на пользователя и включения непокупателей; несколько заказов одного человека не создают универсального неравенства.' },
      { q: 'Какие пользователи должны входить в знаменатель?', a: 'Задайте определение заранее: например, активные пользователи того же периода, а не все регистрации за историю. Платящие должны быть подмножеством этой базы. Не смешивайте пользователей, аккаунты, заказы и разные интервалы.' },
    ],
    disclaimer: 'Два средних с общим введённым числителем. Не рассчитывает прибыль, не восстанавливает разные составы выручки аналитической платформы и не прогнозирует количество платящих.',
  },
  en: {
    longDescription: 'One supplied revenue amount is divided by two populations: all included users and their paying subset. This compares averages and payer share on a common period and revenue basis. Analytics platforms can use different numerators for ARPU and ARPPU, such as including advertising revenue only in ARPU. Their dashboard figures cannot automatically be reconciled using this calculator’s identity.',
    howToUse: ['Define one revenue basis and one period, including a consistent refund policy for purchases.', 'Enter positive revenue and a positive whole count of distinct users in that population.', 'Paying users are a whole count from 0 to total users. Multiple purchases by one person still make one paying user.', 'Use a common currency without conversion. If the two metrics need different revenue types, calculate them separately.'],
    howItWorks: 'For revenue R > 0, users U > 0 and payers P: ARPU = R/U. With P > 0, ARPPU = R/P, payer share = P/U, and ARPU = ARPPU × P/U before rounding. With P = 0, the ARPPU row is omitted and payer share is 0. Counts are actual whole users, not fractional attribution credits. Ordinary amounts and percentages use two decimal places.',
    example: 'Revenue 500,000 monetary units, 12,500 users and 900 payers give ARPU 40.00, ARPPU 555.56 and payer share 7.20%. With 2,000 users who all pay and revenue 300,000, both averages are 150.00. A falling share need not mean fewer people: R=100, U=100, P=10 gives 10%; R=200, U=1000, P=15 gives 1.5%, although payers increased.',
    faq: [
      { q: 'Why check whether a dashboard uses a common numerator?', a: 'Different revenue types alter the payer-share identity. GA4 ARPPU uses purchase revenue, whereas ARPU can include advertising. Both ratios here deliberately use one supplied amount, which is a separate model.' },
      { q: 'What does rising ARPPU alongside falling ARPU imply?', a: 'With a common positive numerator and matched populations, payer share declines. The absolute payer count may still rise if total users grow faster. Two averages alone do not determine a head count.' },
      { q: 'Why is ARPPU omitted when paying users are zero?', a: 'It lacks a positive denominator. Positive revenue with no payers could be advertising revenue or another basis; ARPU can describe the entered ratio, but revenue per payer cannot be calculated.' },
      { q: 'Is ARPU always higher than average order value?', a: 'No. Order value divides revenue by orders; ARPU divides by users. The relationship depends on orders per user and inclusion of nonbuyers. Multiple orders by one person do not establish a universal inequality.' },
      { q: 'Which user population belongs in the denominator?', a: 'Define it in advance, for example active users in the same period rather than all historical registrations. Payers must be a subset of that population. Avoid mixing users, accounts, orders and reporting intervals.' },
    ],
    disclaimer: 'Two averages sharing an entered numerator. No profit calculation, reconstruction of platform-specific revenue types or payer-count forecast.',
  },
  uk: {
    longDescription: 'Одна введена сума виторгу ділиться на дві бази: всіх врахованих користувачів та платних серед них. Порівнюються середні величини й частка платних за спільного періоду та складу виторгу. В аналітичних системах чисельники ARPU й ARPPU можуть різнитися: рекламний виторг, наприклад, входить лише до ARPU. Для таких метрик тотожність цього калькулятора не діє автоматично.',
    howToUse: ['Визначте одну базу виторгу та один період, з узгодженими правилами повернень для покупок.', 'Введіть додатний виторг та додатну цілу кількість унікальних користувачів обраної бази.', 'Платні — ціла кількість від 0 до всіх користувачів. Кілька покупок однієї людини не створюють кількох платних користувачів.', 'Валюта спільна, обміну немає. Для різних видів виторгу у двох метриках потрібні окремі розрахунки.'],
    howItWorks: 'За виторгу R > 0, користувачів U > 0 та платних P: ARPU = R/U. За P > 0: ARPPU = R/P, частка платних = P/U, ARPU = ARPPU × P/U до округлення. За P = 0 рядка ARPPU немає, частка 0. Кількості — фактичні цілі користувачі, не дробові кредити атрибуції. Звичайні суми й відсотки показано з двома знаками.',
    example: 'Виторг 500 000 грошових одиниць, 12 500 користувачів і 900 платних дають ARPU 40,00, ARPPU 555,56, частку 7,20 %. За 2 000 користувачів, які всі платять, і виторгу 300 000 обидва середні дорівнюють 150,00. Частка може зменшитись без втрати платних: R=100, U=100, P=10 дають 10 %, а R=200, U=1000, P=15 — 1,5 %, хоча платних побільшало.',
    faq: [
      { q: 'Навіщо перевіряти спільний чисельник у звіті?', a: 'Різні види виторгу змінюють зв’язок через частку платних. У GA4 ARPPU використовує виторг покупок, а ARPU може включати рекламу. Тут обидва відношення використовують одну введену суму — окрему явну модель.' },
      { q: 'Що означає зростання ARPPU за падіння ARPU?', a: 'За спільного додатного чисельника та узгоджених баз зменшується частка платних. Їхнє число може зростати, якщо загальна аудиторія росте швидше. Два середні без баз не визначають кількість людей.' },
      { q: 'Чому ARPPU немає за нуля платних користувачів?', a: 'Немає додатного дільника. Додатний виторг за нуля платних може бути рекламним або мати іншу базу. ARPU ділить введену суму, але виторг на платного обчислити неможливо.' },
      { q: 'Чи завжди ARPU вищий за середню суму замовлення?', a: 'Ні. Середній чек ділить виторг на замовлення, ARPU — на користувачів. Співвідношення залежить від замовлень на користувача та врахування тих, хто не купує; універсального нерівного відношення немає.' },
      { q: 'Які користувачі мають становити знаменник?', a: 'Визначте базу заздалегідь: наприклад, активні за той самий період, а не всі реєстрації за історію. Платні повинні бути частиною цієї бази. Не змішуйте користувачів, облікові записи, замовлення та різні інтервали.' },
    ],
    disclaimer: 'Два середні зі спільним введеним чисельником. Не обчислює прибуток, не відновлює різні види виторгу платформи та не прогнозує число платних.',
  },
  de: {
    longDescription: 'Ein eingegebener Umsatzbetrag wird durch zwei Nutzergruppen geteilt: alle berücksichtigten Nutzer und deren zahlende Teilmenge. So werden Durchschnittswerte und Zahleranteil bei gleichem Zeitraum und Umsatzumfang verglichen. Analyseplattformen können unterschiedliche Zähler verwenden, etwa Werbeumsatz nur für ARPU. Solche Dashboardwerte erfüllen die Identität dieses Rechners nicht automatisch.',
    howToUse: ['Lege eine Umsatzbasis und einen Zeitraum samt einheitlicher Erstattungsbehandlung fest.', 'Umsatz und ganze Anzahl unterschiedlicher Nutzer dieser Basis müssen positiv sein.', 'Die Zahl der Zahlenden ist ganz, zwischen 0 und allen Nutzern. Mehrere Käufe einer Person ergeben weiterhin einen zahlenden Nutzer.', 'Nutze eine gemeinsame Währung ohne Umrechnung. Bei unterschiedlichen Umsatzarten müssen die beiden Kennzahlen getrennt berechnet werden.'],
    howItWorks: 'Für Umsatz R > 0, Nutzer U > 0 und Zahlende P gilt ARPU = R/U. Bei P > 0 gilt ARPPU = R/P, Zahleranteil = P/U und ARPU = ARPPU × P/U vor Rundung. Bei P = 0 fehlt die ARPPU-Zeile, der Anteil ist 0. Anzahlen sind tatsächliche ganze Nutzer, keine anteiligen Attributionsgutschriften. Übliche Beträge und Prozente erhalten zwei Dezimalstellen.',
    example: '500 000 Geldeinheiten Umsatz, 12 500 Nutzer und 900 Zahlende ergeben ARPU 40,00, ARPPU 555,56 und Anteil 7,20 %. Bei 2 000 ausschließlich zahlenden Nutzern und 300 000 Umsatz sind beide Mittelwerte 150,00. Ein sinkender Anteil verlangt keinen Personenschwund: R=100, U=100, P=10 ergibt 10 %, R=200, U=1000, P=15 ergibt 1,5 %, obwohl mehr Personen zahlen.',
    faq: [
      { q: 'Warum muss die gemeinsame Umsatzbasis im Dashboard geprüft werden?', a: 'Andere Umsatzarten ändern die Beziehung über den Zahleranteil. GA4-ARPPU verwendet Kaufumsatz, ARPU kann Werbung enthalten. Hier nutzen beide Quotienten ausdrücklich denselben eingegebenen Betrag.' },
      { q: 'Was bedeutet steigender ARPPU bei sinkendem ARPU?', a: 'Bei gemeinsamem positivem Zähler und abgestimmten Gruppen sinkt der Zahleranteil. Die absolute Zahl kann dennoch steigen, wenn die gesamte Nutzerbasis schneller wächst. Zwei Mittelwerte bestimmen keine Personenzahl.' },
      { q: 'Warum fehlt ARPPU bei null Zahlenden?', a: 'Es fehlt ein positiver Nenner. Umsatz ohne Zahlende kann aus Werbung oder einer anderen Basis stammen. ARPU bildet den eingegebenen Quotienten, Umsatz je Zahlendem ist dann nicht berechenbar.' },
      { q: 'Ist ARPU immer größer als der mittlere Bestellwert?', a: 'Nein. Bestellwert teilt Umsatz durch Bestellungen, ARPU durch Nutzer. Bestellungen je Nutzer und die Einbeziehung von Nichtkäufern bestimmen das Verhältnis; mehrere Käufe schaffen keine allgemeine Ungleichung.' },
      { q: 'Welche Nutzer gehören in den Nenner?', a: 'Definiere die Basis vorher, etwa aktive Nutzer desselben Zeitraums statt aller historischen Registrierungen. Zahlende müssen zu dieser Gruppe gehören. Nutzer, Konten, Bestellungen und Zeitintervalle dürfen nicht vermischt werden.' },
    ],
    disclaimer: 'Zwei Mittelwerte mit gemeinsamem eingegebenem Zähler. Keine Gewinnrechnung, Rekonstruktion plattformspezifischer Umsatzarten oder Prognose der Zahlerzahl.',
  },
  es: {
    longDescription: 'Un importe de ingresos se divide entre dos poblaciones: todos los usuarios incluidos y los pagadores dentro de ellos. Se comparan medias y proporción de pagadores con el mismo periodo y base de ingresos. Las plataformas pueden emplear numeradores diferentes, por ejemplo publicidad solo en ARPU. Esas métricas no cumplen automáticamente la identidad de esta calculadora.',
    howToUse: ['Define una base de ingresos y un periodo con un tratamiento coherente de devoluciones.', 'Introduce ingresos positivos y un recuento entero positivo de usuarios distintos de esa población.', 'Los pagadores son un entero entre 0 y el total. Varias compras de una persona siguen contando como un pagador.', 'Usa una moneda sin conversión. Si las métricas necesitan distintas clases de ingresos, calcúlalas por separado.'],
    howItWorks: 'Para ingresos R > 0, usuarios U > 0 y pagadores P: ARPU = R/U. Con P > 0: ARPPU = R/P, proporción de pagadores = P/U y ARPU = ARPPU × P/U antes del redondeo. Con P = 0 se omite ARPPU y la proporción es 0. Son recuentos enteros de usuarios reales, no créditos fraccionarios de atribución. Los importes y porcentajes habituales tienen dos decimales.',
    example: 'Ingresos 500 000 unidades monetarias, 12 500 usuarios y 900 pagadores dan ARPU 40,00, ARPPU 555,56 y proporción 7,20 %. Con 2 000 usuarios que pagan todos e ingresos 300 000, ambas medias son 150,00. La proporción puede caer mientras crecen los pagadores: R=100, U=100, P=10 da 10 %; R=200, U=1000, P=15 da 1,5 %, aunque paga más gente.',
    faq: [
      { q: '¿Por qué comprobar un numerador común en el panel?', a: 'Distintas clases de ingresos cambian la identidad de proporción. ARPPU de GA4 usa ingresos de compras, mientras ARPU puede incluir publicidad. Aquí ambos cocientes utilizan expresamente un importe común.' },
      { q: '¿Qué indica ARPPU creciente junto a ARPU decreciente?', a: 'Con numerador positivo común y poblaciones coherentes, cae la proporción de pagadores. Su cantidad absoluta puede crecer si la audiencia total aumenta más deprisa. Dos medias no determinan cuántas personas pagan.' },
      { q: '¿Por qué no aparece ARPPU cuando no hay pagadores?', a: 'No existe denominador positivo. Los ingresos sin pagadores podrían ser publicitarios o de otra base; ARPU describe el cociente introducido, pero no se pueden calcular ingresos por pagador.' },
      { q: '¿ARPU siempre supera el valor medio de pedido?', a: 'No. El valor de pedido divide ingresos entre pedidos; ARPU entre usuarios. La relación depende de pedidos por usuario y de incluir no compradores. Compras repetidas no establecen una desigualdad universal.' },
      { q: '¿Qué población de usuarios debe formar el denominador?', a: 'Defínela antes, por ejemplo usuarios activos del mismo periodo en lugar de todas las altas históricas. Los pagadores deben ser parte de esa población. No mezcles usuarios, cuentas, pedidos ni intervalos.' },
    ],
    disclaimer: 'Dos medias con un numerador común indicado. No calcula beneficio, reconstruye clases de ingresos del panel ni pronostica el número de pagadores.',
  },
};
