import { describe, expect, it } from 'vitest';
import type { CalcResult } from '../src/lib/types';
import { definition as d0 } from '../src/calculators/home-equity/definition';
import { definition as d1 } from '../src/calculators/installment/definition';
import { definition as d2 } from '../src/calculators/leverage/definition';
import { definition as d3 } from '../src/calculators/market-cap/definition';
import { definition as d4 } from '../src/calculators/max-loan/definition';
import { definition as d5 } from '../src/calculators/overtime/definition';
import { definition as d6 } from '../src/calculators/position-size/definition';
import { definition as d7 } from '../src/calculators/rental-yield/definition';
import { definition as d8 } from '../src/calculators/risk-reward/definition';
import { definition as d9 } from '../src/calculators/salary-convert/definition';
import { definition as d10 } from '../src/calculators/salary-raise/definition';
import { definition as d11 } from '../src/calculators/vacation-accrual/definition';
import { definition as d12 } from '../src/calculators/workday-cost/definition';
const definitions=[d0,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12];
const defaults: Record<string,Record<string,unknown>>={"home-equity": {"value": 9000000, "balance": 3200000, "ltv": 80, "rate": 18, "years": 10}, "installment": {"price": 60000, "down": 10000, "months": 6, "markup": 12}, "leverage": {"equity": 50000, "leverage": 5, "entry": 2400, "maintenancePct": 0.5}, "market-cap": {"mode": "cap", "shares": 1000000, "price": 250, "cap": 250000000}, "max-loan": {"income": 120000, "dtiPct": 40, "rate": 18, "years": 20}, "overtime": {"rate": 650, "normalHours": 160, "overtimeHours": 14, "multiplier": 1.5}, "position-size": {"deposit": 100000, "riskPct": 1, "entry": 250, "stop": 240}, "rental-yield": {"price": 10000000, "rentMode": "annual", "annualRent": 600000, "monthlyRent": 50000, "annualCosts": 0}, "risk-reward": {"direction": "long", "entry": 250, "stop": 240, "target": 280, "qty": 100}, "salary-convert": {"amount": 180000, "fromPeriod": "month", "toPeriod": "year"}, "salary-raise": {"mode": "fromNew", "oldSalary": 120000, "newSalary": 148000, "raisePct": 15}, "vacation-accrual": {"daysPerYear": 28, "monthsWorked": 7, "daysUsed": 5}, "workday-cost": {"salary": 80000, "days": 21, "hours": 8}};
const active: Record<string,string[]>={"home-equity": ["value", "balance", "ltv", "rate", "years"], "installment": ["price", "down", "months", "markup"], "leverage": ["equity", "leverage", "entry", "maintenancePct"], "market-cap": ["shares", "price"], "max-loan": ["income", "dtiPct", "rate", "years"], "overtime": ["rate", "normalHours", "overtimeHours", "multiplier"], "position-size": ["deposit", "riskPct", "entry", "stop"], "rental-yield": ["price", "annualRent", "annualCosts"], "risk-reward": ["entry", "stop", "target", "qty"], "salary-convert": ["amount"], "salary-raise": ["oldSalary", "newSalary"], "vacation-accrual": ["daysPerYear", "monthsWorked", "daysUsed"], "workday-cost": ["salary", "days", "hours"]};
const engines=Object.fromEntries(definitions.map(d=>[d.id,d.compute]));
const clean=(value:string)=>value.replace(/[  ]/g,' ');
const run=(id:string,patch:Record<string,unknown>={})=>engines[id]({...defaults[id],...patch}as never);
const row=(r:CalcResult,label:string)=>clean(r.secondary.find(x=>x.label===label)!.value);
const fail=(r:CalcResult)=>{expect(r.primary.value).toBe('—');expect(r.secondary[0].accent).toBe('red');expect(JSON.stringify(r)).not.toMatch(/NaN|Infinity/);};
describe('Finance14 retains55 original independent references without altering their source',()=>{
 for(const d of definitions)for(const ref of d.referenceCases!)it(`${d.id}: ${ref.name}`,()=>{const r=d.compute(ref.inputs);expect(clean(r.primary.value)).toBe(clean(ref.expectPrimary));for(const v of ref.expectSecondary??[])expect(row(r,v.label)).toBe(clean(v.value));});
});
describe('Finance14 strict active financial inputs and inactive scope',()=>{
 const invalid:unknown[]=[true,false,null,{},[],NaN,Infinity,-Infinity,'broken','1xyz','1e309','1e-9999'];
 for(const[id,names]of Object.entries(active))for(const name of names)for(const[index,value]of invalid.entries())it(`${id}/${name} rejects malformed${index}`,()=>fail(run(id,{[name]:value})));
 const enums:Record<string,string[]>={'market-cap':['mode'],'rental-yield':['rentMode'],'risk-reward':['direction'],'salary-convert':['fromPeriod','toPeriod'],'salary-raise':['mode']};
 for(const[id,names]of Object.entries(enums))for(const name of names)for(const value of ['unknown','',true,false,null,{},0,'constructor','toString'])it(`${id}/${name} rejects unknown supplied choice${JSON.stringify(value)}`,()=>fail(run(id,{[name]:value})));
 for(const[id,name]of [['installment','months'],['market-cap','shares'],['workday-cost','days']])for(const value of [1.5,'1.00000000000000001','1.00000000000000001e0',Number.MAX_SAFE_INTEGER+1])it(`${id}/${name} rejects exact fractional or unsafe counts${value}`,()=>fail(run(id,{[name]:value})));
 it('market cap modes ignore malformed hidden monetary inputs',()=>{expect(run('market-cap',{mode:'cap',cap:true}).primary.value).toBe(run('market-cap').primary.value);expect(run('market-cap',{mode:'price',price:'bad'}).primary.value).toBe('250,00 ₽');fail(run('market-cap',{mode:'price',cap:true}));});
 it('rental monthly and annual modes ignore the other rent input',()=>{expect(run('rental-yield',{rentMode:'annual',monthlyRent:true}).primary.value).toBe('6,00%');expect(run('rental-yield',{rentMode:'monthly',annualRent:'bad'}).primary.value).toBe('6,00%');fail(run('rental-yield',{rentMode:'monthly',monthlyRent:true}));});
 it('salary raise modes validate only the active new salary or percentage',()=>{expect(run('salary-raise',{mode:'fromNew',raisePct:true}).primary.value).toBe('23,33%');expect(run('salary-raise',{mode:'fromPct',raisePct:15,newSalary:'bad'}).primary.value).toBe('138 000,00 ₽');fail(run('salary-raise',{mode:'fromPct',raisePct:true}));});
 it('blank optional financial values mean zero and negative values remain errors',()=>{for(const[id,name]of [['installment','down'],['rental-yield','annualCosts'],['risk-reward','qty']]){expect(run(id,{[name]:''}).primary.value).toBe(run(id,{[name]:0}).primary.value);fail(run(id,{[name]:-1}));}});
});
describe('Finance14 fixed independent boundary arithmetic',()=>{
 it('home loan zero interest on600overone wholemonth gives600 payment',()=>{const r=run('home-equity',{value:1000,balance:200,ltv:80,rate:0,years:1/12});expect(r.primary.value).toBe('600 ₽');expect(row(r,'Собственный капитал в жилье')).toBe('800 ₽');expect(row(r,'Платёж по такому кредиту')).toBe('600 ₽');});
 it('tiny nominal rate retains the zero-interest limit rather than cancellation31,275',()=>{const r=run('home-equity',{rate:1e-12});expect(row(r,'Платёж по такому кредиту')).toBe('33 333,33 ₽');});
 it('unselected collateral capacity produces zero available and zero new-loan payment',()=>{const r=run('home-equity',{value:1000,balance:900,ltv:80});expect(r.primary.value).toBe('0 ₽');expect(row(r,'Платёж по такому кредиту')).toBe('0 ₽');});
 it('loan percentage multiplication avoids unnecessary value-times100 overflow',()=>{const r=run('home-equity',{value:1e308,balance:0,ltv:50,rate:0,years:1});expect(r.primary.value).not.toBe('—');});
 it('four cents over6months never create a negative instalment or balance',()=>{const r=run('installment',{price:.04,down:0,months:6,markup:0});expect(r.primary.value).toBe('0,00 ₽');expect(row(r,'Последний платёж')).toBe('0,04 ₽');expect(r.table!.rows.map(x=>clean(x[1]))).toEqual(['0,00 ₽','0,00 ₽','0,00 ₽','0,00 ₽','0,00 ₽','0,04 ₽']);expect(r.table!.rows.some(x=>x[1].startsWith('-')||x[2].startsWith('-'))).toBe(false);expect(r.table!.rows[5][2]).toBe('0,00 ₽');});
 it('one cent over2months preserves inherited valid1cent then0cent schedule',()=>{const r=run('installment',{price:.01,down:0,months:2,markup:0});expect(r.table!.rows.map(x=>x[1])).toEqual(['0,01 ₽','0,00 ₽']);});
 it('subcent total and unsafe cent ledger are explicit numeric limits',()=>{fail(run('installment',{price:.001,down:0}));fail(run('installment',{price:1e20,down:0}));});
 it('fixed entry-notional maintenance model5x/0.5percent gives1932 and19.5percent',()=>{const r=run('leverage');expect(row(r,'Цена ликвидации')).toBe('1 932,00 ₽');expect(row(r,'Падение до ликвидации')).toBe('19,50%');});
 it('maintenance cannot consume the whole initial collateral at entry',()=>{fail(run('leverage',{leverage:5,maintenancePct:20}));fail(run('leverage',{leverage:200,maintenancePct:1}));expect(run('leverage',{leverage:1,maintenancePct:0}).primary.value).not.toBe('—');});
 it('max-loan tiny positive rate never creates a principal above total scheduled payments',()=>{const r=run('max-loan',{rate:1e-12});expect(clean(r.primary.value)).toBe('11 520 000,00 ₽');expect(row(r,'Переплата')).toBe('0,0000012 ₽');});
 it('max-loan one-month0percent onincome1000 at30percent is300',()=>{const r=run('max-loan',{income:1000,dtiPct:30,rate:0,years:1/12});expect(r.primary.value).toBe('300,00 ₽');expect(row(r,'Платежей')).toBe('1');});
 it('fractional years consistently round to the same whole payment count',()=>{const r=run('max-loan',{income:1000,dtiPct:30,rate:0,years:.1});expect(r.primary.value).toBe('300,00 ₽');expect(row(r,'Платежей')).toBe('1');fail(run('max-loan',{years:.001}));});
 it('overtime1.5regular+0.5overtime at100and1.5 equals225/112.5average',()=>{const r=run('overtime',{rate:100,normalHours:1.5,overtimeHours:.5,multiplier:1.5});expect(r.primary.value).toBe('225,00 ₽');expect(row(r,'Средняя ставка за час')).toBe('112,50 ₽');});
 it('zero worked hours omit the average0/0 rather than claim an hourly wage0',()=>{const r=run('overtime',{normalHours:0,overtimeHours:0});expect(r.primary.value).toBe('0,00 ₽');expect(r.secondary.some(x=>x.label==='Средняя ставка за час')).toBe(false);});
 it('Spanish existing position example10000at1percent anddistance10 gives10units2500value',()=>{const r=run('position-size',{deposit:10000,riskPct:1,entry:250,stop:240});expect(r.primary.value).toBe('10 шт');expect(row(r,'Стоимость позиции')).toBe('2 500,00 ₽');});
 it('fractional position2.5units at4stopdistance fits10risk and wholeunits round2',()=>{const r=run('position-size',{deposit:1000,riskPct:1,entry:100,stop:96});expect(r.primary.value).toBe('2,5 шт');expect(row(r,'Целых единиц')).toBe('2 шт');});
 it('risk above100percent is outside the displayed model range',()=>fail(run('position-size',{riskPct:100.01})));
 it('rental losses are real:700000cost against600000rent gives−1percentnet',()=>{const r=run('rental-yield',{annualCosts:700000});expect(r.primary.value).toBe('6,00%');expect(row(r,'Чистая доходность')).toBe('-1,00%');expect(row(r,'Простая валовая окупаемость')).toBe('16,7 лет');});
 it('rental zero revenue withcost1000 is negative net and has no finitegrosspayback',()=>{const r=run('rental-yield',{annualRent:0,annualCosts:1000});expect(r.primary.value).toBe('0,00%');expect(row(r,'Чистая доходность')).toBe('-0,01%');expect(r.secondary.some(x=>x.label==='Простая валовая окупаемость')).toBe(false);});
 it('same rental120000cost gives4.8percentnet and16.7gross years, not20.8netyears',()=>{const r=run('rental-yield',{annualCosts:120000});expect(row(r,'Чистая доходность')).toBe('4,80%');expect(row(r,'Простая валовая окупаемость')).toBe('16,7 лет');});
 it('risk-reward with omitted quantity keeps3and25percent without money totals',()=>{const r=run('risk-reward',{qty:''});expect(r.primary.value).toBe('3');expect(row(r,'Безубыточная доля сделок')).toBe('25,00%');expect(r.secondary.some(x=>x.label==='Риск в деньгах'||x.label==='Прибыль в деньгах')).toBe(false);expect(r.secondary.find(x=>x.label==='Безубыточная доля сделок')!.accent).toBe('neutral');});
 it('inconsistent long prices retain the explicit direction warning, never a healthy green',()=>{const r=run('risk-reward',{target:230});expect(row(r,'Внимание')).toContain('В лонге');expect(r.secondary.some(x=>x.accent==='green')).toBe(false);});
 it('fixed salary periods use2016model hours, not an annual calendar52weeks',()=>{const r=run('salary-convert',{amount:40,fromPeriod:'week',toPeriod:'year'});expect(clean(r.primary.value)).toBe('2 016,00 ₽');expect(row(r,'В час')).toBe('1,00 ₽');});
 it('same salary period roundtrip retains the entered amount',()=>expect(run('salary-convert',{amount:95000,fromPeriod:'month',toPeriod:'month'}).primary.value).toBe('95 000,00 ₽'));
 it('salary percentage decrease−50 yieldshalfnewincome andnegative delta',()=>{const r=run('salary-raise',{mode:'fromPct',oldSalary:100,raisePct:-50});expect(r.primary.value).toBe('50,00 ₽');expect(row(r,'Разница')).toBe('-50,00 ₽');expect(row(r,'Множитель')).toBe('0,5');});
 it('salary reduction tozero is outside positive-salary model',()=>fail(run('salary-raise',{mode:'fromPct',raisePct:-100})));
 it('vacation pro-rata supports fractionalmonths and negativebalances without legal claims',()=>{expect(run('vacation-accrual',{daysPerYear:24,monthsWorked:7.5,daysUsed:5}).primary.value).toBe('10 дн.');expect(run('vacation-accrual',{daysPerYear:24,monthsWorked:1,daysUsed:5}).primary.value).toBe('-3 дн.');fail(run('vacation-accrual',{monthsWorked:13}));});
 it('workday fractionalshift length preserves157.5monthlyhours rather than rounding158',()=>{const r=run('workday-cost',{salary:3150,days:21,hours:7.5});expect(r.primary.value).toBe('150,00 ₽');expect(row(r,'Стоимость часа')).toBe('20,00 ₽');expect(row(r,'Рабочих часов в месяце')).toBe('157,5');});
 it('monthlyday andshift domains are explicitand finiteoutput overflow is rejected',()=>{fail(run('workday-cost',{days:32}));fail(run('workday-cost',{hours:25}));for(const[id,patch]of [['overtime',{rate:1e308}],['salary-convert',{amount:1e308,fromPeriod:'hour',toPeriod:'year'}],['leverage',{equity:1e308}],['market-cap',{price:1e308}]]as const)fail(run(id,patch));});
});

// Independent nonzero changes below Number resolution must not be reported as zero.
it("salary positive tiny change cannot be represented as an unchanged salary",()=>fail(run("salary-raise",{mode:"fromPct",oldSalary:100,raisePct:1e-20})));
it("extreme leverage cannot claim a threshold identical to entry",()=>fail(run("leverage",{equity:1,entry:100,leverage:1e20,maintenancePct:0})));
