import{it,expect}from'vitest';
import{getCalculatorById}from'../src/lib/i18n';import{getCalculatorEditorial}from'../src/data/calculatorEditorial';import{getConverterWave10MethodSources}from'../src/data/converterWave10MethodSources';
import{contractContent as coordinates}from'../src/calculators/coordinate-convert/contractContent';import{contractContent as names}from'../src/calculators/number-scale-names/contractContent';import{contractContent as words}from'../src/calculators/number-to-words/contractContent';import{contractContent as paper}from'../src/calculators/paper-quantity/contractContent';import{contractContent as model}from'../src/calculators/scale-model/contractContent';
import{isFieldVisible}from'../src/lib/fieldVisibility';import before from'./fixtures/originalityConverterWave10Before.json';
const content={'coordinate-convert':coordinates,'number-scale-names':names,'number-to-words':words,'paper-quantity':paper,'scale-model':model};
for(const row of before.pages){
 it(`${row.id}/${row.locale}: published native body equals reviewed owned body`,()=>{const c=getCalculatorById(row.id,row.locale as 'ru')!;expect(c).toBeTruthy();expect(c.fullPath).toBe(row.path);const body=content[row.id as keyof typeof content] as Record<string,typeof coordinates.ru>;for(const key of ['longDescription','howItWorks','howToUse','example','faq']as const)expect(c[key]).toEqual(body[row.locale][key]);});
 it(`${row.id}/${row.locale}: exact actual source links visible in method`,()=>{const c=getCalculatorById(row.id,row.locale as 'ru')!;const e=getCalculatorEditorial(c,row.locale as 'ru');for(const source of getConverterWave10MethodSources(row.id,row.locale))expect(e.sources).toContainEqual(source);});
 it(`${row.id}/${row.locale}: field units agree with declared physical or scalar input`,()=>{const c=getCalculatorById(row.id,row.locale as 'ru')!;if(row.id==='coordinate-convert')expect(c.fields.filter(f=>f.unit).map(f=>f.unit)).toEqual(['°','′','″','°']);if(row.id==='paper-quantity')expect(c.fields.find(f=>f.name==='grammage')!.unit).toBe(row.locale==='ru'||row.locale==='uk'?'г/м²':'g/m²');if(row.id==='number-scale-names')expect(c.fields.find(f=>f.name==='value')!.unit).toBeTruthy();});
}
for(const locale of ['ru','en','uk','de','es']as const)for(const mode of ['toModel','toReal','findScale'])it(`scale/${locale}/${mode}: two known numeric controls, no stale unknown`,()=>{const c=getCalculatorById('scale-model',locale)!;const values={mode};expect(c.fields.filter(f=>f.type==='number'&&isFieldVisible(f,values))).toHaveLength(2);});
for(const locale of ['de','es']as const)it(`words/${locale}: historical unpublished boundary`,()=>expect(getCalculatorById('number-to-words',locale)).toBeUndefined());
