import {describe,expect,it} from 'vitest';
import type {CalcResult} from '../src/lib/types';
import {isCompleteCalculatorCopy} from '../src/lib/platform/types';
import {localizeResult} from '../src/components/islands/calculator/resultLocalization';
import {definition as d0} from '../src/calculators/air-density/definition';
import {localization as l0} from '../src/calculators/air-density/localization';
import {definition as d1} from '../src/calculators/air-pressure-at-altitude/definition';
import {localization as l1} from '../src/calculators/air-pressure-at-altitude/localization';
import {definition as d2} from '../src/calculators/boiling-point/definition';
import {localization as l2} from '../src/calculators/boiling-point/localization';
import {definition as d3} from '../src/calculators/decibel/definition';
import {localization as l3} from '../src/calculators/decibel/localization';
import {definition as d4} from '../src/calculators/dew-point/definition';
import {localization as l4} from '../src/calculators/dew-point/localization';
import {definition as d5} from '../src/calculators/heat-index/definition';
import {localization as l5} from '../src/calculators/heat-index/localization';
import {definition as d6} from '../src/calculators/humidity-convert/definition';
import {localization as l6} from '../src/calculators/humidity-convert/localization';
import {definition as d7} from '../src/calculators/mach-number/definition';
import {localization as l7} from '../src/calculators/mach-number/localization';
import {definition as d8} from '../src/calculators/speed-of-sound/definition';
import {localization as l8} from '../src/calculators/speed-of-sound/localization';
import {definition as d9} from '../src/calculators/wind-chill/definition';
import {localization as l9} from '../src/calculators/wind-chill/localization';
import {definition as d10} from '../src/calculators/wind-power/definition';
import {localization as l10} from '../src/calculators/wind-power/localization';
const defs=[d0,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10],locs=[l0,l1,l2,l3,l4,l5,l6,l7,l8,l9,l10],locales=['ru','en','uk','de','es'] as const;
const numeric=(text:string)=>{const t=text.replace(/[\s\u00a0\u202f]/g,'').replace(',','.');const m=/^([+-]?[\d.]+)·10\^(-?\d+)/.exec(t);return m?Number(m[1])*10**Number(m[2]):parseFloat(t);};
const row=(r:CalcResult,l:string)=>r.secondary.find(x=>x.label===l)?.value??'';
const close=(s:string,n:number)=>{const x=numeric(s);expect(Number.isFinite(x)).toBe(true);if(!n)expect(x).toBe(0);else expect(Math.abs(x/n-1)).toBeLessThan(.0006);};
const defaults=(d:typeof defs[number])=>Object.fromEntries(d.presentation.fields.map(f=>[f.name,f.defaultValue])) as Parameters<typeof d.compute>[0];
const bad:unknown[]=[undefined,null,true,false,'',' ','bad','NaN','Infinity',NaN,Infinity,-Infinity,'0x10','1e-999',{},[]];
for(let i=0;i<defs.length;i++){
 const d=defs[i],input=defaults(d);
 for(const r of d.referenceCases??[])it(d.id+': preserved independently established reference '+r.name,()=>{const a=d.compute(r.inputs);expect(a.primary.value).toBe(r.expectPrimary);for(const x of r.expectSecondary??[])expect(a.secondary).toContainEqual(expect.objectContaining(x));});
 it(d.id+': original published example',()=>{for(const x of d.publishedExample?.expected??[])expect(JSON.stringify(d.compute(d.publishedExample!.inputs))).toContain(x);});
 const fields=d.presentation.fields.filter(f=>f.type==='number'&&(d.id!=='decibel'||f.showIf?.equals==='sum'));
 for(const f of fields)for(const[n,v]of bad.entries())it(d.id+': finite active '+f.name+'/'+n,()=>expect(d.compute({...input,[f.name]:v} as Parameters<typeof d.compute>[0]).primary.value).toBe('—'));
 for(const locale of locales)it(d.id+'/'+locale+': full owned subject copy and native error/result',()=>{
  const c=locale==='ru'?d.presentation:d.copy![locale];if(!isCompleteCalculatorCopy(c))throw new Error('Incomplete owned copy');expect(c.faq).toHaveLength(4);expect(c.disclaimer!.length).toBeGreaterThan(40);expect(c.howToUse!.length).toBeGreaterThanOrEqual(3);
  if(locale==='ru')expect(JSON.stringify(c)).not.toMatch(/[іїєґІЇЄҐ]/);
  const first=d.id==='decibel'?'levels':fields[0].name;const error=localizeResult(d.compute({...input,[first]:true}),locale,d.id,{compute:d.compute,localization:locs[i]});expect(error.primary.value).toBe('—');
  const result=localizeResult(d.compute(input),locale,d.id,{compute:d.compute,localization:locs[i]});
  if(locale==='en'||locale==='de'||locale==='es')expect(JSON.stringify([error,result])).not.toMatch(/[А-Яа-яЁё]/);
 });
 it(d.id+': explicit numeric field units',()=>{for(const f of d.presentation.fields.filter(f=>f.type==='number'))expect(f.unit).toBeTruthy();});
}
describe('Independent literal atmospheric/model oracles',()=>{
 it('moist density: corrected example1.1988, not1.1997',()=>{const r=d0.compute({t:20,pressure:1013.25,humidity:50});close(r.primary.value,1.1988337356809313);close(row(r,'Плотность сухого воздуха'),1.2040847588826422);});
 it('dry mixture, RH0 is legitimate',()=>{const r=d0.compute({t:15,pressure:1013.25,humidity:0});expect(row(r,'Давление водяного пара')).toBe('0 гПа');close(r.primary.value,1.2249781262066513);});
 it('pressure layer2000 metres independently Decimal80',()=>{const r=d1.compute({h:2000});close(r.primary.value,79.49639219652705);close(row(r,'Температура по стандартной атмосфере'),2);});
 it('boiling1500m independently Decimal80',()=>{const r=d2.compute({h:1500});close(r.primary.value,94.918916672949585);close(row(r,'Ниже обычных 100 °C на'),5.081083327050415);});
 it('Magnus saturation is exactly Td=t',()=>{for(const t of [-60,0,20,60]){const r=d4.compute({t,rh:100});close(r.primary.value,t);expect(row(r,'Разрыв с температурой')).toBe('0 °C');}});
 it('dew near RH100 retains its positive gap',()=>{const r=d4.compute({t:20,rh:99.99999999999999});expect(numeric(row(r,'Разрыв с температурой'))).toBeGreaterThan(0);});
 it('MIN RH logarithm remains finite instead of log0',()=>{const r=d4.compute({t:20,rh:Number.MIN_VALUE});expect(r.primary.value).not.toBe('—');expect(numeric(r.primary.value)).toBeLessThan(-230);});
 it('Rothfusz32/70 retains numerical model, fixes Fahrenheit category',()=>{const r=d5.compute({t:32,rh:70});close(r.primary.value,40.40927367955559);expect(row(r,'Категория индекса')).toBe('опасность');expect(d5.presentation.resultLabels?.risk).toBe('Категория индекса');});
 it('humidity RH0 has zero mass density/mixing ratio, not zero saturation',()=>{const r=d6.compute({t:20,rh:0,pressure:1013.25});expect(r.primary.value).toBe('0 г/м³');expect(row(r,'Влагосодержание')).toBe('0 г/кг');close(row(r,'Давление насыщения'),23.380935143417695);});
 it('Mach900kmh/−50°C independently Decimal80',()=>{close(d7.compute({v:900,t:-50}).primary.value,.8348736027342964);});
 it('Mach small positive speed remains nonzero',()=>{close(d7.compute({v:1e-300,t:20}).primary.value,8.093899938638711e-304);});
 it('sound t0 exactly331.3, one kilometre ratio',()=>{const r=d8.compute({t:0});close(r.primary.value,331.3);close(row(r,'Километр звук пройдёт за'),3.018412315122246);});
 it('tiny positive sound-temperature difference is not cancelled to0',()=>expect(numeric(row(d8.compute({t:1e-200}),'Отклонение от значения при 0 °C'))).toBeGreaterThan(0));
 it('rounded wind-chill boundary10/4.8 retained',()=>{const r=d9.compute({t:10,v:4.8});close(r.primary.value,9.817478030736018);});
 it('Betz exact16/27 independently Decimal80',()=>{close(row(d10.compute({d:3,v:7,rho:1.225,cp:.4}),'Предел Бетца'),.8800124621480608);close(row(d10.compute({d:50,v:12,rho:1.2,cp:.45}),'Предел Бетца'),1206.3715789784805);});
 it('Betz rejects formerly accepted .5929',()=>expect(d10.compute({d:3,v:7,rho:1.225,cp:.5929}).primary.value).toBe('—'));
 it('Betz accepts represented boundary16/27',()=>expect(d10.compute({d:3,v:7,rho:1.225,cp:16/27}).primary.value).not.toBe('—'));
 it('wind exact products cancel Dsquare/VCube scales before overflow',()=>{const r=d10.compute({d:1e100,v:1e-100,rho:1e100,cp:.4});close(r.primary.value,Math.PI/20000);close(row(r,'Ометаемая площадь'),Math.PI*1e200/4);});
});
for(const[d,input]of [[d0,{t:-237.3,pressure:1013.25,humidity:0}],[d0,{t:-250,pressure:1013.25,humidity:0}],[d6,{t:-237.3,pressure:1013.25,rh:0}],[d4,{t:-61,rh:60}],[d4,{t:61,rh:60}],[d9,{t:-273.15,v:20}],[d7,{v:Number.MIN_VALUE,t:20}]] as const)it(d.id+': bounded domain '+JSON.stringify(input),()=>expect(d.compute(input).primary.value).toBe('—'));
for(const[n,v]of bad.entries())for(const key of ['p1','p2'])it('decibel ratio strict '+key+'/'+n,()=>expect(d3.compute({mode:'ratio',p1:1,p2:2,kind:'power',[key]:v} as unknown as Parameters<typeof d3.compute>[0]).primary.value).toBe('—'));
for(const key of ['mode','kind'])for(const v of [null,true,false,1,{},[],['sum'],'bad'])it('decibel closed enum '+key+JSON.stringify(v),()=>expect(d3.compute({mode:'ratio',kind:'power',p1:1,p2:2,[key]:v} as unknown as Parameters<typeof d3.compute>[0]).primary.value).toBe('—'));
describe('Decibel stable logarithms and input semantics',()=>{
 it('two4000 dB sources stay finite',()=>{const r=d3.compute({mode:'sum',levels:'4000;4000',p1:false});close(r.primary.value,4003.01029995664);close(row(r,'Прибавка к самому громкому'),3.010299956639812);});
 it('weak incoherent source retains small correction without1+tail cancellation',()=>{const r=d3.compute({mode:'sum',levels:'0 -1000'});close(row(r,'Прибавка к самому громкому'),4.342944819032518e-100);});
 it('two−4000 dB sources remain finite',()=>close(d3.compute({mode:'sum',levels:'-4000 -4000'}).primary.value,-3996.98970004336));
 it('comma separates levels, decimal point belongs to a number',()=>{expect(row(d3.compute({mode:'sum',levels:'80,80'}),'Источников')).toBe('2');expect(row(d3.compute({mode:'sum',levels:'80.5;80.5'}),'Источников')).toBe('2');});
 it('list malformed token is not silently zero',()=>expect(d3.compute({mode:'sum',levels:'80 bad 80'}).primary.value).toBe('—'));
 it('more than10000 levels fails before unbounded aggregation',()=>expect(d3.compute({mode:'sum',levels:'80 '.repeat(10001)}).primary.value).toBe('—'));
 it('sum permits negative dB and a single0 level',()=>expect(d3.compute({mode:'sum',levels:'0'}).primary.value).toBe('0 дБ'));
 it('inactive ratio/list fields do not poison active mode',()=>{expect(d3.compute({mode:'sum',levels:'80 80',p1:false,p2:NaN,kind:'bad'}).primary.value).toBe('83,01 дБ');expect(d3.compute({mode:'ratio',p1:1,p2:2,kind:'power',levels:false}).primary.value).not.toBe('—');});
 it('amplitude2 means power4 under declared shared proportionality',()=>{const r=d3.compute({mode:'ratio',kind:'amplitude',p1:1,p2:2});close(r.primary.value,6.020599913279624);expect(row(r,'Во сколько раз по мощности')).toBe('4');});
 it('ratio near unity preserves positive logarithm',()=>expect(numeric(d3.compute({mode:'ratio',kind:'power',p1:1e200,p2:1.0000000000000001e200}).primary.value)).toBeGreaterThan(0));
 it('required unrepresentable power ratio has an honest range error',()=>expect(d3.compute({mode:'ratio',p1:1e-300,p2:1e300,kind:'power'}).primary.value).toBe('—'));
});
for(const locale of locales)it('decibel/'+locale+': ratio field has native chosen-unit semantics',()=>{for(const name of ['p1','p2']){const f=d3.presentation.fields.find(f=>f.name===name)!;const native=d3.contextualField!(f,{},locale);expect(native.unit?.length).toBeGreaterThan(3);if(locale==='en'||locale==='de'||locale==='es')expect(JSON.stringify(native)).not.toContain('общая единица');}});
