import{it,expect}from'vitest';
import{definition as coordinates}from'../src/calculators/coordinate-convert/definition';import{localization as c}from'../src/calculators/coordinate-convert/localization';
import{definition as names}from'../src/calculators/number-scale-names/definition';import{localization as n}from'../src/calculators/number-scale-names/localization';
import{definition as words}from'../src/calculators/number-to-words/definition';import{localization as w}from'../src/calculators/number-to-words/localization';
import{definition as paper}from'../src/calculators/paper-quantity/definition';import{localization as p}from'../src/calculators/paper-quantity/localization';
import{definition as model}from'../src/calculators/scale-model/definition';import{localization as m}from'../src/calculators/scale-model/localization';
import{localizeResult}from'../src/components/islands/calculator/resultLocalization';import{isCompleteCalculatorCopy}from'../src/lib/platform/types';import{isFieldVisible}from'../src/lib/fieldVisibility';
import{buildCalculatorQueryString,readValuesFromSearch}from'../src/lib/shareLink';import{validateValues}from'../src/components/islands/calculator/validation';import{getConverterWave10MethodSources}from'../src/data/converterWave10MethodSources';
import before from'./fixtures/originalityConverterWave10Before.json';
const tools=[coordinates,names,words,paper,model],bundles=[c,n,w,p,m];const locales=['ru','en','uk','de','es']as const;
const defaults=(i:number)=>Object.fromEntries(tools[i].presentation.fields.map(f=>[f.name,f.defaultValue??'']));const runtime=(i:number)=>({compute:tools[i].compute,validate:tools[i].validate,contextualField:tools[i].contextualField,localization:bundles[i]});const foreign=(l:string)=>l==='uk'?/[ЁёЫыЭэЪъ]/u:/[А-Яа-яЁё]/u;
for(const row of before.pages)it(`${row.id}/${row.locale}: actual authored native identity, complete body and retained FAQ floor`,()=>{
 const d=tools.find(t=>t.id===row.id)!;const copy=row.locale==='ru'?d.presentation:d.copy![row.locale as 'en'|'uk'|'de'|'es']!;expect(isCompleteCalculatorCopy(copy)).toBe(true);if(!isCompleteCalculatorCopy(copy))throw Error('Missing native body');
 for(const key of ['name','h1','seoTitle']as const)expect(copy[key]).toBe(row.id==='number-scale-names'&&row.locale==='uk'&&['name','h1'].includes(key)?row[key].replace('кророрів','крорів'):row[key]);if(row.id!=='number-to-words'&&!(row.locale==='uk'&&['number-scale-names','paper-quantity'].includes(row.id)))expect(copy.seoDescription).toBe(row.seoDescription);expect(row.path.endsWith('/'+copy.slug+'/')).toBe(true);
 expect(copy.faq.length).toBeGreaterThanOrEqual(row.effectiveBody.faq.length);expect(copy.howItWorks).toBeTruthy();expect(copy.howToUse?.length).toBeGreaterThan(0);expect(copy.example).toBeTruthy();expect(copy.longDescription?.length).toBeGreaterThan(60);
 expect(d.presentation.fields.map(f=>({name:f.name,type:f.type,defaultValue:f.defaultValue}))).toEqual(row.fields.map(f=>({name:f.name,type:f.type,defaultValue:f.defaultValue})));
 if(row.locale!=='ru')expect(JSON.stringify([copy.longDescription,copy.howToUse,copy.howItWorks,copy.example,copy.faq])).not.toMatch(foreign(row.locale));
});
it('German andSpanish word converter stay unpublished,3 actual native copies only',()=>expect(Object.keys(words.copy!)).toEqual(['en','uk']));
for(const[i,d]of tools.entries())for(const l of locales.filter(l=>d.id!=='number-to-words'||['ru','en','uk'].includes(l))){
 it(`${d.id}/${l}: default native result and exact published example`,()=>{const raw=d.compute(defaults(i));expect(raw.primary.value).not.toBe('—');const r=localizeResult(raw,l,d.id,runtime(i));expect(JSON.stringify(r)).not.toMatch(/NaN|Infinity|undefined/);if(l!=='ru')expect(JSON.stringify(r)).not.toMatch(foreign(l));for(const x of d.publishedExample!.expected)expect(JSON.stringify(d.compute(d.publishedExample!.inputs))).toContain(x);});
 it(`${d.id}/${l}: malformed active value has native feedback`,()=>{const field=d.id==='coordinate-convert'?'deg':d.id==='paper-quantity'?'sheets':d.id==='scale-model'?'real':'value';const r=localizeResult(d.compute({...defaults(i),[field]:true}),l,d.id,runtime(i));expect(r.primary.value).toBe('—');if(l!=='ru')expect(JSON.stringify(r)).not.toMatch(foreign(l));});
}
const spelled=[
 [0,'ноль','zero','нуль'],[1,'один','one','один'],[2,'два','two','два'],[11,'одиннадцать','eleven','одинадцять'],[21,'двадцать один','twenty one','двадцять один'],[100,'сто','one hundred','сто'],[101,'сто один','one hundred one','сто один'],[1000,'одна тысяча','one thousand','одна тисяча'],[2000,'две тысячи','two thousand','дві тисячі'],[2000000,'два миллиона','two million','два мільйони'],[2000000000,'два миллиарда','two billion','два мільярди'],[1234,'одна тысяча двести тридцать четыре','one thousand two hundred thirty four','одна тисяча двісті тридцять чотири'],[-2000105,'минус два миллиона сто пять','minus two million one hundred five','мінус два мільйони сто п’ять'],
]as const;
for(const[value,ru,en,uk]of spelled)for(const[l,expected]of [['ru',ru],['en',en],['uk',uk]]as const)it(`words/${value}/${l}: independent native spelling literal`,()=>expect(localizeResult(words.compute({value}),l,words.id,runtime(2)).primary.value).toBe(expected));
for(const[value,ending]of [[1,'рубль 00 копійок'],[2,'рублі 00 копійок'],[11,'рублів 00 копійок'],[21,'рубль 00 копійок']]as const)it(`Ukrainian RUB${value}: correct explicit native plural withoutUAH`,()=>expect(localizeResult(words.compute({value}),'uk',words.id,runtime(2)).secondary[0].value).toContain(ending));
for(const locale of ['en','uk','de','es']as const){
 for(const[i,inputs]of [[1,{value:1e308,from:'billion',to:'billion'}],[3,{format:'a4',grammage:1e-308,sheets:1}]]as const)it(`${tools[i].id}/${locale}: auxiliary range stays native and finite primary preserved`,()=>{const r=localizeResult(tools[i].compute(inputs),locale,tools[i].id,runtime(i));expect(r.primary.value).not.toBe('—');expect(JSON.stringify(r)).not.toMatch(foreign(locale));});
}
for(const mode of ['toModel','toReal','findScale'])for(const l of locales)it(`scale/${mode}/${l}: onlyknown fields share/reload with inactive garbage omitted`,()=>{
 const values={mode,real:4350,model:50,scale:87};const unknown=mode==='toModel'?'model':mode==='toReal'?'real':'scale';const fields=model.presentation.fields;
 expect(fields.filter(f=>isFieldVisible(f,values)).map(f=>f.name)).not.toContain(unknown);const withGarbage={...values,[unknown]:'malformed'};expect(model.compute(withGarbage)).toEqual(model.compute(values));const q=buildCalculatorQueryString(fields,withGarbage,l);expect(new URLSearchParams(q).has(unknown)).toBe(false);expect(model.compute(readValuesFromSearch(fields,defaults(4),q,l))).toEqual(model.compute(values));
});
for(const[i,field]of [[0,'deg'],[0,'minutes'],[2,'value'],[3,'sheets']]as const)for(const l of locales.filter(l=>i!==2||['ru','en','uk'].includes(l)))it(`${tools[i].id}/${field}/${l}: original fractional count lexical text validated`,()=>{
 const values={...defaults(i),[field]:l==='en'?'3.00000000000000001':'3,00000000000000001'};
 const errors=validateValues(tools[i].id,tools[i].presentation.fields,values,l,runtime(i));expect(errors[field]).toBeTruthy();if(l!=='ru')expect(errors[field]).not.toMatch(foreign(l));
});
for(const row of before.pages)it(`${row.id}/${row.locale}: primarylinks boundtospecificmethod and retained simple identity without decorative references`,()=>{const s=getConverterWave10MethodSources(row.id,row.locale);expect(s).toHaveLength(row.id==='number-scale-names'?2:['paper-quantity','coordinate-convert'].includes(row.id)?1:0);for(const r of s){expect(r.href?.startsWith('https://')).toBe(true);if(row.locale!=='ru')expect(r.label).not.toMatch(foreign(row.locale));}});
for(const[value,expected]of [[1,'one RUB 00 kopecks'],[21,'twenty one RUB 00 kopecks'],[101,'one hundred one RUB 00 kopecks'],[1001,'one thousand one RUB 00 kopecks'],[-1,'minus one RUB 00 kopecks']]as const)it(`ENmoney${value}: currency code does not inheritRUplural`,()=>expect(localizeResult(words.compute({value}),'en',words.id,runtime(2)).secondary[0].value).toBe(expected));
for(const locale of ['en','uk','de','es']as const)it(`coordinate/${locale}: actual underflow error is native`,()=>{const r=localizeResult(coordinates.compute({deg:0,minutes:0,seconds:Number.MIN_VALUE}),locale,coordinates.id,runtime(0));expect(r.primary.value).toBe('—');expect(r.secondary[0].value).toBe({en:'A nonzero angle is below the numerical range',uk:'Ненульовий кут менший за числовий діапазон',de:'Ein Winkel ungleich null liegt unterhalb des Zahlenbereichs',es:'Un ángulo no nulo queda por debajo del rango numérico'}[locale]);});
for(const i of [1,3])it(`${tools[i].id}: ownUKmetadata meets existing project floor`,()=>expect(tools[i].copy!.uk!.seoDescription!.length).toBeGreaterThanOrEqual(80));

it('UK number-scale title uses крорів without inherited duplicated syllable',()=>{expect(names.copy!.uk!.name).toBe('Калькулятор лакхів і крорів');expect(names.copy!.uk!.h1).toBe('Калькулятор лакхів і крорів');});
it('EN coordinate direction convention is explicitly this form, not universal DMS',()=>{const copy=coordinates.copy!.en!;expect(isCompleteCalculatorCopy(copy)).toBe(true);if(isCompleteCalculatorCopy(copy)){expect(copy.longDescription).toContain('this form accepts unsigned DMS');expect(copy.longDescription).not.toContain('DMS never');}});
