import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { localizeResult } from '../src/components/islands/calculator/resultLocalization';
import { parseLocalizedNumber } from '../src/lib/format';
import { isCompleteCalculatorCopy } from '../src/lib/platform/types';
import { getComputerWave9MethodSources } from '../src/data/computerWave9MethodSources';
import type { CalcResult } from '../src/lib/types';
import { definition as c0 } from '../src/calculators/aspect-ratio/definition';
import { localization as l0 } from '../src/calculators/aspect-ratio/localization';
import { definition as c1 } from '../src/calculators/color-convert/definition';
import { localization as l1 } from '../src/calculators/color-convert/localization';
import { definition as c2 } from '../src/calculators/css-units/definition';
import { localization as l2 } from '../src/calculators/css-units/localization';
import { definition as c3 } from '../src/calculators/download-time/definition';
import { localization as l3 } from '../src/calculators/download-time/localization';
import { definition as c4 } from '../src/calculators/files-on-disk/definition';
import { localization as l4 } from '../src/calculators/files-on-disk/localization';
import { definition as c5 } from '../src/calculators/fps-frametime/definition';
import { localization as l5 } from '../src/calculators/fps-frametime/localization';
import { definition as c6 } from '../src/calculators/internet-traffic/definition';
import { localization as l6 } from '../src/calculators/internet-traffic/localization';
import { definition as c7 } from '../src/calculators/ipv4-subnet/definition';
import { localization as l7 } from '../src/calculators/ipv4-subnet/localization';
import { definition as c8 } from '../src/calculators/modular-scale/definition';
import { localization as l8 } from '../src/calculators/modular-scale/localization';
import { definition as c9 } from '../src/calculators/network-bandwidth/definition';
import { localization as l9 } from '../src/calculators/network-bandwidth/localization';
import { definition as c10 } from '../src/calculators/password-entropy/definition';
import { localization as l10 } from '../src/calculators/password-entropy/localization';
import { definition as c11 } from '../src/calculators/ppi-dpi/definition';
import { localization as l11 } from '../src/calculators/ppi-dpi/localization';
import { definition as c12 } from '../src/calculators/raid/definition';
import { localization as l12 } from '../src/calculators/raid/localization';
import { definition as c13 } from '../src/calculators/tv-monitor-viewing-distance/definition';
import { localization as l13 } from '../src/calculators/tv-monitor-viewing-distance/localization';
import { definition as c14 } from '../src/calculators/unix-timestamp/definition';
import { localization as l14 } from '../src/calculators/unix-timestamp/localization';
import { definition as c15 } from '../src/calculators/video-file-size/definition';
import { localization as l15 } from '../src/calculators/video-file-size/localization';
const tools = [c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15];
const locs = [l0,l1,l2,l3,l4,l5,l6,l7,l8,l9,l10,l11,l12,l13,l14,l15];
const languages=['ru','en','uk','de','es'] as const;
const norm=(s:string)=>s.replace(/[\u00a0\u202f]/g,' ');
const number=(s:string)=>{const t=s.replace(/[\s\u00a0\u202f]/g,'').replace(',','.');const m=/^([+-]?[\d.]+)·10\^(-?\d+)/.exec(t);return m?Number(m[1]+'e'+m[2]):parseFloat(t);};
const error=(r:CalcResult)=>{expect(r.primary.value).toBe('—');expect(r.secondary.some(x=>x.accent==='red')).toBe(true);};
const row=(r:CalcResult,k:string)=>r.secondary.find(x=>x.label===k)?.value??'';

describe('Computer16 independent arithmetic and bounded semantics',()=>{
 it('aspect reduction and pixel product are exact safe integer arithmetic',()=>{const r=c0.compute({mode:'reduce',width:2560,height:1080});expect(r.primary.value).toBe('64:27');expect(number(row(r,'Наибольший общий делитель'))).toBe(40);expect(norm(row(r,'Всего пикселей'))).toBe('2 764 800');});
 it('aspect inverse cancels a huge ratio before conversion',()=>{const r=c0.compute({mode:'side',known:'width',side:1280,ratioW:1e308,ratioH:1e308});expect(r.primary.value).toBe('1 280 пикс');});
 it('exact huge pixel count is displayed without pretending unsafe multiplication is exact',()=>{const r=c0.compute({mode:'reduce',width:9007199254740991,height:9007199254740991});expect(r.primary.value).toBe('1:1');expect(norm(row(r,'Всего пикселей')).replace(/ /g,'')).toBe('81129638414606663681390495662081');});
 it('HSL primary colours and gray convention are independent bytes',()=>{const r=c1.compute({hex:'#0F0'});expect(r.primary.value).toBe('rgb(0, 255, 0)');expect(row(r,'HSL')).toBe('hsl(120, 100.00%, 50.00%)');expect(row(c1.compute({hex:'#808080'}),'HSL')).toBe('hsl(0, 0.00%, 50.20%)');});
 it('em uses supplied context, relative bases and signed CSS lengths',()=>{expect(c2.compute({value:2,fromUnit:'em',toUnit:'px',rootSize:16,parentSize:20}).primary.value).toBe('40');expect(c2.compute({value:-16,fromUnit:'px',toUnit:'rem',rootSize:16,parentSize:16}).primary.value).toBe('-1');expect(c2.compute({value:0,fromUnit:'in',toUnit:'mm',rootSize:16,parentSize:16}).primary.value).toBe('0');});
 it('CSS target unit is explicit while ordinary values retain precision',()=>{const r=c2.compute({value:24,fromUnit:'px',toUnit:'rem',rootSize:16,parentSize:16});expect(r.primary.label).toBe('Результат в rem');expect(r.primary.value).toBe('1,5');});
 it('download bit/byte and decimal/binary ratios',()=>{const a=c3.compute({size:1,sizeUnit:'gb',speed:100,speedUnit:'mbit'}),b=c3.compute({size:1,sizeUnit:'gib',speed:100,speedUnit:'mbit'}),c=c3.compute({size:1,sizeUnit:'gb',speed:12.5,speedUnit:'mbyte'});expect(number(row(a,'Всего секунд'))).toBe(80);expect(number(row(b,'Всего секунд'))).toBe(85.90);expect(number(row(c,'Всего секунд'))).toBe(80);});
 it('download duration carries sixty seconds to next minute',()=>expect(c3.compute({size:119.9,sizeUnit:'mb',speed:8,speedUnit:'mbit'}).primary.value).toBe('2:00'));
 it('decimal file quotients do not lose a file to binary representation of0.1',()=>{expect(c4.compute({capacity:1,capacityUnit:'gb',fileSize:0.1,fileUnit:'gb',reserved:0}).primary.value).toBe('10');expect(c4.compute({capacity:1,capacityUnit:'gb',fileSize:0.3,fileUnit:'gb',reserved:0}).primary.value).toBe('3');expect(c4.compute({capacity:1,capacityUnit:'gb',fileSize:0.10000000000000002,fileUnit:'gb',reserved:0}).primary.value).toBe('9');expect(c4.compute({capacity:1,capacityUnit:'gb',fileSize:0.09999999999999999,fileUnit:'gb',reserved:0}).primary.value).toBe('10');});
 it('file-size unit factors, reserve and zero fit',()=>{expect(c4.compute({capacity:1,capacityUnit:'gib',fileSize:1,fileUnit:'mib',reserved:0}).primary.value).toBe('1 024');expect(c4.compute({capacity:1,capacityUnit:'gb',fileSize:100,fileUnit:'mb',reserved:10}).primary.value).toBe('9');expect(c4.compute({capacity:1,capacityUnit:'gb',fileSize:2,fileUnit:'gb',reserved:0}).primary.value).toBe('0');});
 it('fps reciprocal does not read the inactive unknown',()=>{expect(number(c5.compute({mode:'fps',fps:50,frameTime:NaN}).primary.value)).toBe(20);expect(number(c5.compute({mode:'ms',frameTime:20,fps:NaN}).primary.value)).toBe(50);});
 it('small nonzero frame intervals are not displayed as zero',()=>{const r=c5.compute({mode:'ms',frameTime:1e-10});expect(number(row(r,'Время кадра'))).toBe(1e-10);expect(number(r.primary.value)).toBe(1e13);});
 it('traffic total and literal quota days',()=>{const r=c6.compute({mbps:5,hoursPerDay:3,days:30,quotaGb:100});expect(number(r.primary.value)).toBe(202.5);expect(number(row(r,'В день'))).toBe(6.75);expect(number(row(r,'В час'))).toBe(2.25);expect(number(row(r,'Превышение лимита'))).toBe(102.5);});
 it('traffic changes with actual period rather than a hardcoded month',()=>expect(number(c6.compute({mbps:8,hoursPerDay:1,days:2.5,quotaGb:0}).primary.value)).toBe(9));
 for(const[prefix,network,hosts,broadcast]of[[0,'0.0.0.0',4294967294,'255.255.255.255'],[20,'192.168.0.0',4094,'192.168.15.255'],[30,'192.168.1.8',2,'192.168.1.11'],[31,'192.168.1.10',2,'нет'],[32,'192.168.1.11',1,'нет']]as const)it(`IPv4/${prefix} literal independent bit boundaries`,()=>{const r=c7.compute({address:'192.168.1.11',prefix});expect(r.primary.value).toBe(network);expect(number(row(r,'Узлов в сети'))).toBe(hosts);expect(row(r,'Широковещательный')).toBe(broadcast);});
 it('modular scale zero counts include base and both endpoints',()=>{const r=c8.compute({base:16,ratio:1.25,stepsUp:5,stepsDown:2});expect(number(r.primary.value)).toBe(48.828);expect(number(row(r,'Наименьший размер'))).toBe(10.24);expect(number(row(r,'Ступеней'))).toBe(8);expect(c8.compute({base:16,ratio:1.25,stepsUp:0,stepsDown:0}).table!.rows).toEqual([['0','16']]);});
 it('scale preview12 does not reduce full count41',()=>{const r=c8.compute({base:16,ratio:1.25,stepsUp:20,stepsDown:20});expect(r.table!.rows).toHaveLength(12);expect(number(row(r,'Ступеней'))).toBe(41);expect(r.table!.note).toBeTruthy();});
 it('network total/share/headroom arithmetic and zero active share',()=>{const r=c9.compute({users:50,perUser:5,concurrency:20,overhead:20});expect(number(r.primary.value)).toBe(60);expect(number(row(r,'Без запаса'))).toBe(50);expect(number(row(r,'Добавлено запасом'))).toBe(10);expect(number(c9.compute({users:50,perUser:5,concurrency:0,overhead:20}).primary.value)).toBe(0);});
 it('network fractional active expectation is not rounded before rate',()=>{const r=c9.compute({users:3,perUser:10,concurrency:50,overhead:0});expect(number(r.primary.value)).toBe(15);expect(row(r,'Одновременно активны')).toBe('1,5 из 3');});
 it('uniform four digits entropy and explicit M/2 midpoint approximation',()=>{const r=c10.compute({length:4,charset:'digits',rate:1});expect(number(row(r,'Вариантов пароля'))).toBe(10000);expect(number(row(r,'Средний перебор'))).toBe(5e-6);expect(number(r.primary.value)).toBe(13.288);const one=c10.compute({length:1,charset:'digits',rate:1});expect(number(row(one,'Средний перебор'))).toBe(5e-9);});
 it('password rate product does not overflow into false zero',()=>{const r=c10.compute({length:12,charset:'alnum',rate:1e308});expect(number(row(r,'Средний перебор'))).toBeCloseTo(1.613e-296,298);expect(r.primary.value).not.toBe('—');});
 it('ppi equal physical grid and independent inch conversion',()=>{const r=c11.compute({w:1920,h:1080,diagonal:15.6});expect(number(r.primary.value)).toBe(141.21);expect(number(row(r,'Размер пикселя'))).toBe(0.180);expect(number(row(r,'Всего пикселей'))).toBe(2.07);});
 it('RAID1 n-way mirror does not universally reserve half',()=>{const r=c12.compute({level:'1',disks:3,sizeTb:4});expect(number(r.primary.value)).toBe(4);expect(number(row(r,'Сырая ёмкость'))).toBe(12);expect(number(row(r,'Допустимо отказов'))).toBe(2);expect(number(row(r,'Эффективность'))).toBe(33.33);});
 it('RAID10 paired guarantee1 and RAID6 capacity remain distinct',()=>{expect(number(row(c12.compute({level:'10',disks:8,sizeTb:4}),'Допустимо отказов'))).toBe(1);expect(number(c12.compute({level:'6',disks:8,sizeTb:4}).primary.value)).toBe(24);});
 it('TV geometric40/30 and literal1arcminute approximation',()=>{const r=c13.compute({diag:55,ratio:'16:9',lines:2160});expect(number(r.primary.value)).toBe(1.673);expect(number(r.secondary[0].value)).toBe(2.272);expect(number(r.secondary[1].value)).toBe(121.76);expect(number(r.secondary[2].value)).toBe(68.489);expect(number(r.secondary[3].value)).toBe(1.09);});
 for(const [date,timestamp]of [['0001-01-01',-62135596800],['0099-01-01',-59042995200],['0100-01-01',-59011459200],['1900-03-01',-2203891200],['2000-02-29',951782400],['9999-12-31',253402214400]]as const)it(`Unix independent Python Gregorian oracle${date}`,()=>{expect(c14.compute({mode:'toTimestamp',date,hour:0,minute:0,second:0}).primary.value).toBe(String(timestamp));expect(c14.compute({mode:'toDate',timestamp}).primary.value).toBe(`${date} 00:00:00 UTC`);expect(row(c14.compute({mode:'toDate',timestamp}),'Дата в ISO 8601')).toBe(`${date}T00:00:00Z`);});
 it('Unix maximum supported second and signed32 transition',()=>{expect(c14.compute({mode:'toDate',timestamp:253402300799}).primary.value).toBe('9999-12-31 23:59:59 UTC');expect(c14.compute({mode:'toDate',timestamp:2147483647}).primary.value).toBe('2038-01-19 03:14:07 UTC');expect(c14.compute({mode:'toDate',timestamp:2147483648}).primary.value).toBe('2038-01-19 03:14:08 UTC');});
 it('video streams summed in bits, binary row is MiB',()=>{const r=c15.compute({videoMbps:8,audioKbps:128,minutes:10});expect(number(r.primary.value)).toBe(0.6096);expect(number(row(r,'В мебибайтах'))).toBe(581.36);expect(number(row(r,'Суммарный битрейт'))).toBe(8128);});
 it('fixed audio prevents half video rate from halving the file',()=>{const r=c15.compute({videoMbps:4,audioKbps:128,minutes:10});expect(number(r.primary.value)).toBe(0.3096);expect(number(c15.compute({videoMbps:8,audioKbps:128,minutes:5}).primary.value)).toBe(0.3048);});
 it('zero audio is valid and malformed audio is not silence',()=>{expect(number(c15.compute({videoMbps:8,audioKbps:0,minutes:10}).primary.value)).toBe(0.6);error(c15.compute({videoMbps:8,audioKbps:'not-a-number',minutes:10}));});
});
