import { definition as d0 } from '../src/calculators/air-exchange/definition';
import { definition as d1 } from '../src/calculators/baluster-spacing/definition';
import { definition as d2 } from '../src/calculators/beam-deflection/definition';
import { definition as d3 } from '../src/calculators/beam-stress/definition';
import { definition as d4 } from '../src/calculators/board-volume/definition';
import { definition as d5 } from '../src/calculators/bulk-material-volume/definition';
import { definition as d6 } from '../src/calculators/cladding-boards/definition';
import { definition as d7 } from '../src/calculators/concrete/definition';
import { definition as d8 } from '../src/calculators/drywall/definition';
import { definition as d9 } from '../src/calculators/epoxy-volume/definition';
import { definition as d10 } from '../src/calculators/fence/definition';
import { definition as d11 } from '../src/calculators/insulation/definition';
import { definition as d12 } from '../src/calculators/linoleum/definition';
import { definition as d13 } from '../src/calculators/metal-weight/definition';
import { definition as d14 } from '../src/calculators/miter-angle/definition';
import { definition as d15 } from '../src/calculators/pile-foundation/definition';
import { definition as d16 } from '../src/calculators/pipe-weight/definition';
import { definition as d17 } from '../src/calculators/plaster/definition';
import { describe, expect, it } from 'vitest';
import oracle from './originalityBuildingWave13Oracle.json';
const definitions=[d0,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17];
const byId=Object.fromEntries(definitions.map(d=>[d.id,d]));
const bases:Record<string,Record<string,any>>={"air-exchange": {"area": 20, "height": 2.7, "ach": 3}, "baluster-spacing": {"run": 3000, "baluster_width": 40, "max_gap": 100}, "beam-deflection": {"scheme": "uniform", "load": 2, "span": 3, "e": 10, "inertia": 1000}, "beam-stress": {"moment": 4500, "section": "rect", "b": 100, "h": 200, "d": 100}, "board-volume": {"length": 6, "width": 150, "thickness": 25, "count": 50, "pricePerM3": 0}, "bulk-material-volume": {"length": 5, "width": 4, "depth": 10, "density": 1.6, "waste": 5}, "cladding-boards": {"wall_area": 30, "board_len": 3, "board_width": 0.19, "overlap": 0.02, "waste": 10}, "concrete": {"mode": "slab", "length": 6, "width": 4, "thickness": 0.2, "perimeter": 40, "stripWidth": 0.4, "depth": 0.8, "sectionArea": 0.09, "height": 2, "count": 12, "waste": 5}, "drywall": {"area": 40, "sheetLength": 2.5, "sheetWidth": 1.2, "layers": 1, "profileStep": 0.6, "waste": 10}, "epoxy-volume": {"length": 100, "width": 50, "thickness": 5, "density": 1.1, "ratio": 2}, "fence": {"length": 40, "span": 2.5, "height": 1.8, "rails": 2, "gates": 1}, "insulation": {"area": 60, "thickness": 100, "slabArea": 0.72, "perPack": 6}, "linoleum": {"length": 5, "width": 3.5, "rollWidth": 3, "reserve": 5}, "metal-weight": {"shape": "round", "a": 20, "b": 4, "length": 6, "density": 7.85}, "miter-angle": {"corner": 90}, "pile-foundation": {"count": 12, "diameter": 0.3, "depth": 1.8, "grillageLength": 32, "grillageWidth": 0.4, "grillageHeight": 0.4, "waste": 5}, "pipe-weight": {"d": 108, "wall": 4, "len": 6, "rho": 7850}, "plaster": {"mode": "area", "area": 20, "length": 5, "height": 2.7, "thickness": 10, "consumption": 8.5, "bagWeight": 30}};
const run=(id:string,input:Record<string,any>)=>byId[id].compute(input);
const row=(r:ReturnType<typeof run>, label:string)=>r.secondary?.find(x=>x.label===label)?.value;

function parsed(text:string):{value:number,precision:number} {
  const scientific=text.match(/([+-]?\d+(?:,\d+)?)·10\^([+-]?\d+)/);
  if(scientific){const exponent=Number(scientific[2]);return {value:Number(scientific[1].replace(',','.'))*10**exponent,precision:10**(exponent-3)};}
  const m=text.match(/^[+-]?[\d\s ]+(?:,\d+)?/);
  if(!m)throw Error('numeric output '+text);
  const token=m[0].trim(), places=token.split(',')[1]?.length??0;
  return {value:Number(token.replace(/[\s ]/g,'').replace(',','.')),precision:10**(-places)};
}
describe('121 independent Decimal2500 engine fixture sets, all displayed physical quantities',()=>{
 for(const f of oracle.records) it(`${f.id}: ${f.name}`,()=>{
   const r=run(f.id,f.inputs);expect(r.primary.value).not.toBe('—');
   for(const [label,expected] of Object.entries(f.expected)) {
     const text=label==='primary'?r.primary.value:row(r,label);
     expect(text,label).toBeDefined();const actual=parsed(text!);
     // The established display rounds ordinary measures to 2–6 decimal places;
     // this checks the final decimal interval, not an expected value generated by the implementation.
     expect(Number.isFinite(actual.value),label).toBe(true);
     expect(Math.abs(actual.value-expected),`${label}: ${text}`).toBeLessThanOrEqual(actual.precision*.501 + Math.abs(expected)*1e-14);
     if(expected!==0)expect(actual.value,label).not.toBe(0);
   }
 });
});
