import { describe, expect, it } from 'vitest';
import { GET } from '../src/pages/sitemap.xml';

describe('i18n sitemap endpoint', () => {
  it('exposes localized URLs with hreflang alternates', async () => {
    const response = await GET({} as Parameters<typeof GET>[0]);
    const body = await response.text();

    expect(response.headers.get('Content-Type')).toContain('application/xml');
    expect(body).toContain('<urlset');
    expect(body).toContain('xmlns:xhtml="http://www.w3.org/1999/xhtml"');
    expect(body).toContain('<loc>http://localhost:3000/ru/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/en/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/pl/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/nl/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/ro/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/id/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/tr/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/vi/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/cs/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/uk/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/sk/</loc>');
    expect(body).toContain('<loc>http://localhost:3000/hu/</loc>');
    expect(body).toContain('hreflang="ru"');
    expect(body).toContain('hreflang="en"');
    expect(body).toContain('hreflang="pl"');
    expect(body).toContain('hreflang="nl"');
    expect(body).toContain('hreflang="ro"');
    expect(body).toContain('hreflang="id"');
    expect(body).toContain('hreflang="tr"');
    expect(body).toContain('hreflang="vi"');
    expect(body).toContain('hreflang="cs"');
    expect(body).toContain('hreflang="uk"');
    expect(body).toContain('hreflang="sk"');
    expect(body).toContain('hreflang="hu"');
    expect(body).toContain('hreflang="x-default"');
    expect(body).toContain('/en/finance/loan-calculator/');
    expect(body).toContain('/pl/finanse/kalkulator-kredytu/');
    expect(body).toContain('/nl/financien/lening-calculator/');
    expect(body).toContain('/ro/finante/calculator-credit/');
    expect(body).toContain('/id/keuangan/kalkulator-pinjaman/');
    expect(body).toContain('/tr/finans/kredi-hesaplayici/');
    expect(body).toContain('/vi/tai-chinh/may-tinh-khoan-vay/');
    expect(body).toContain('/cs/finance/kalkulacka-pujcky/');
    expect(body).toContain('/uk/finansy/kalkulyator-kredytu/');
    expect(body).toContain('/sk/financie/kalkulacka-pozicky/');
    expect(body).toContain('/hu/penzugyek/hitelkalkulator/');
    expect(body).toContain('/ru/finance/vat-calculator/');
    expect(body).not.toContain('/en/finance/vat-calculator/');
    expect(body).not.toContain('/pl/finanse/vat-calculator/');
    expect(body).not.toContain('/nl/financien/vat-calculator/');
    expect(body).not.toContain('/ro/finante/vat-calculator/');
    expect(body).not.toContain('/id/keuangan/vat-calculator/');
    expect(body).not.toContain('/tr/finans/vat-calculator/');
    expect(body).not.toContain('/vi/tai-chinh/vat-calculator/');
    expect(body).not.toContain('/cs/finance/vat-calculator/');
    expect(body).not.toContain('/uk/finansy/vat-calculator/');
    expect(body).not.toContain('/sk/financie/vat-calculator/');
    expect(body).not.toContain('/hu/penzugyek/vat-calculator/');
    expect(body).not.toContain('/en/finance/income-tax-calculator/');
    expect(body).not.toContain('/pl/finanse/income-tax-calculator/');
    expect(body).not.toContain('/nl/financien/income-tax-calculator/');
    expect(body).not.toContain('/ro/finante/income-tax-calculator/');
    expect(body).not.toContain('/id/keuangan/income-tax-calculator/');
    expect(body).not.toContain('/tr/finans/income-tax-calculator/');
    expect(body).not.toContain('/vi/tai-chinh/income-tax-calculator/');
    expect(body).not.toContain('/cs/finance/income-tax-calculator/');
    expect(body).not.toContain('/uk/finansy/income-tax-calculator/');
    expect(body).not.toContain('/sk/financie/income-tax-calculator/');
    expect(body).not.toContain('/hu/penzugyek/income-tax-calculator/');
  });
});
