import type { CalculatorLocalization } from '../../lib/platform/types';

// Единицы принадлежат калькулятору: центральный словарь единиц трогать нельзя,
// это вернуло бы ручную регистрацию. Подстановка идёт по самому длинному ключу,
// поэтому « моль/л» выигрывает у « моль», а « г/моль» — у « г».
const RESULTS_EN = {
  'Конечный объём': 'Final volume',
  'Исходный объём': 'Initial volume',
  'Добавить растворителя': 'Solvent to add',
  'Результат': 'Result',
  'Проверьте данные': 'Check the values',
};
const RESULTS_UK = {
  'Конечный объём': 'Кінцевий об’єм',
  'Исходный объём': 'Початковий об’єм',
  'Добавить растворителя': 'Додати розчинника',
  'Результат': 'Результат',
  'Проверьте данные': 'Перевірте дані',
};

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'solve': 'Was gesucht ist',
      'c1': 'Ausgangskonzentration',
      'v1': 'Ausgangsvolumen, ml',
      'c2': 'Endkonzentration',
      'v2': 'Endvolumen, ml',
    },
    options: {
      'v2': 'das Endvolumen',
      'v1': 'das Ausgangsvolumen',
    },
    results: {
      'Конечный объём': 'Endvolumen',
      'Исходный объём': 'Ausgangsvolumen',
      'Добавить растворителя': 'Lösungsmittel zugeben',
      'Результат': 'Ergebnis',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      ' моль/л': ' mol/l',
      ' г/моль': ' g/mol',
      ' моль': ' mol',
      ' г/л': ' g/l',
      ' г': ' g',
      ' мл': ' ml',
      ' л': ' l',
      ' кПа': ' kPa',
      ' атм': ' atm',
      ' Па': ' Pa',
      ' К': ' K',
      ' ppm': ' ppm',
      'Дж/(моль·К)': 'J/(mol·K)',
      'Все три известные величины должны быть больше нуля': 'Alle drei bekannten Größen müssen größer als null sein',
      'Конечная концентрация не может быть выше исходной': 'Die Endkonzentration kann nicht höher als die Ausgangskonzentration sein',
    },
  },
  en: {
    fields: { solve: 'What to find', c1: 'Initial concentration', v1: 'Initial volume, mL', c2: 'Final concentration', v2: 'Final volume, mL', },
    options: { v2: 'the final volume', v1: 'the initial volume', },
    results: RESULTS_EN,
    values: {
      ' моль/л': ' mol/L',
      ' г/моль': ' g/mol',
      ' моль': ' mol',
      ' г/л': ' g/L',
      ' г': ' g',
      ' мл': ' mL',
      ' л': ' L',
      ' кПа': ' kPa',
      ' атм': ' atm',
      ' Па': ' Pa',
      ' К': ' K',
      ' ppm': ' ppm',
      'Дж/(моль·К)': 'J/(mol·K)',
      'Все три известные величины должны быть больше нуля': 'All three known quantities must be greater than zero',
      'Конечная концентрация не может быть выше исходной': 'The final concentration cannot be higher than the initial one',
    },
  },
  uk: {
    fields: { solve: 'Що знайти', c1: 'Початкова концентрація', v1: 'Початковий об’єм, мл', c2: 'Кінцева концентрація', v2: 'Кінцевий об’єм, мл', },
    options: { v2: 'кінцевий об’єм', v1: 'початковий об’єм', },
    results: RESULTS_UK,
    values: {
      ' моль/л': ' моль/л',
      ' г/моль': ' г/моль',
      ' моль': ' моль',
      ' г/л': ' г/л',
      ' мл': ' мл',
      ' кПа': ' кПа',
      ' атм': ' атм',
      ' Па': ' Па',
      ' К': ' К',
      'Дж/(моль·К)': 'Дж/(моль·К)',
      'Все три известные величины должны быть больше нуля': 'Усі три відомі величини мають бути більшими за нуль',
      'Конечная концентрация не может быть выше исходной': 'Кінцева концентрація не може бути вищою за початкову',
    },
  },
};
