// СГЕНЕРИРОВАНО. Не редактировать руками.
// Общие фразы результата, отобранные под наследственный калькулятор body-fat-calculator.
// Перегенерировать: npm run calculators:generate

import type { CalculatorLocalization } from '../../../../lib/platform/types';

export const shared: CalculatorLocalization = {
  en: {
    results: {
      'Процент жира': 'Body fat percentage',
      'Метод расчёта': 'Method',
      'Обхват талии': 'Waist circumference',
      'Обхват шеи': 'Neck circumference',
      'Обхват бёдер': 'Hip circumference',
      'Талия минус шея': 'Waist minus neck',
      'Талия плюс бёдра минус шея': 'Waist plus hips minus neck',
      'Проверьте данные': 'Check inputs',
      'Результат': 'Result',
      'В': 'To',
      'Рост': 'Height',
    },
    values: {
      'Обхваты, метод ВМС США': 'U.S. Navy circumference method',
      'Это оценка по обхватам, а не измерение. Погрешность метода составляет несколько процентных пунктов и растёт при неточных замерах ленты. Результат не является медицинским заключением.': 'This is an estimate from circumferences, not a measurement. The method is accurate to within a few percentage points, and the error grows with imprecise tape work. The result is not a medical assessment.',
      'Обхват талии должен быть больше обхвата шеи': 'The waist circumference must be larger than the neck circumference',
      'Сумма обхватов талии и бёдер должна быть больше обхвата шеи': 'Waist plus hip circumference must be larger than the neck circumference',
      'Сочетание обхватов выходит за пределы применимости метода — проверьте измерения': 'This combination of circumferences falls outside the range where the method applies — check the measurements',
      'Введите рост больше нуля': 'Enter a height greater than zero',
      'Введите обхват шеи больше нуля': 'Enter a neck circumference greater than zero',
      'Введите обхват талии больше нуля': 'Enter a waist circumference greater than zero',
      'Введите обхват бёдер больше нуля': 'Enter a hip circumference greater than zero',
    },
  },
  uk: {
    results: {
      'Процент жира': 'Відсоток жиру',
      'Метод расчёта': 'Метод розрахунку',
      'Обхват талии': 'Обхват талії',
      'Обхват шеи': 'Обхват шиї',
      'Обхват бёдер': 'Обхват стегон',
      'Талия минус шея': 'Талія мінус шия',
      'Талия плюс бёдра минус шея': 'Талія плюс стегна мінус шия',
      'Проверьте данные': 'Перевірте дані',
      'Результат': 'Результат',
      'В': 'У',
      'Рост': 'Зріст',
    },
    values: {
      'Обхваты, метод ВМС США': 'Метод ВМС США за обхватами',
      'Это оценка по обхватам, а не измерение. Погрешность метода составляет несколько процентных пунктов и растёт при неточных замерах ленты. Результат не является медицинским заключением.': 'Це оцінка за обхватами, а не вимірювання. Похибка методу становить кілька відсоткових пунктів і зростає за неточних замірів стрічкою. Результат не є медичним висновком.',
      'Обхват талии должен быть больше обхвата шеи': 'Обхват талії має бути більшим за обхват шиї',
      'Сумма обхватов талии и бёдер должна быть больше обхвата шеи': 'Сума обхватів талії та стегон має бути більшою за обхват шиї',
      'Сочетание обхватов выходит за пределы применимости метода — проверьте измерения': 'Поєднання обхватів виходить за межі застосовності методу — перевірте виміри',
      'Введите рост больше нуля': 'Введіть зріст більший за нуль',
      'Введите обхват шеи больше нуля': 'Введіть обхват шиї більший за нуль',
      'Введите обхват талии больше нуля': 'Введіть обхват талії більший за нуль',
      'Введите обхват бёдер больше нуля': 'Введіть обхват стегон більший за нуль',
    },
  },
  de: {
    results: {
      'Процент жира': 'Körperfettanteil',
      'Метод расчёта': 'Rechenweg',
      'Обхват талии': 'Taillenumfang',
      'Обхват шеи': 'Halsumfang',
      'Обхват бёдер': 'Hüftumfang',
      'Талия минус шея': 'Taille minus Hals',
      'Талия плюс бёдра минус шея': 'Taille plus Hüfte minus Hals',
      'Проверьте данные': 'Prüfe die Werte',
      'Результат': 'Ergebnis',
      'В': 'Nach',
      'Рост': 'Körpergröße',
    },
    values: {
      'Обхваты, метод ВМС США': 'Umfänge, Methode der US Navy',
      'Это оценка по обхватам, а не измерение. Погрешность метода составляет несколько процентных пунктов и растёт при неточных замерах ленты. Результат не является медицинским заключением.': 'Das ist eine Schätzung aus Umfängen und keine Messung. Die Methode trifft auf wenige Prozentpunkte genau, und der Fehler wächst bei ungenauem Anlegen des Maßbands. Das Ergebnis ist kein medizinischer Befund.',
      'Обхват талии должен быть больше обхвата шеи': 'Der Taillenumfang muss größer als der Halsumfang sein',
      'Сумма обхватов талии и бёдер должна быть больше обхвата шеи': 'Taillen- und Hüftumfang zusammen müssen größer als der Halsumfang sein',
      'Сочетание обхватов выходит за пределы применимости метода — проверьте измерения': 'Diese Kombination von Umfängen liegt außerhalb des Bereichs, in dem die Methode gilt — prüfe die Messungen',
      'Введите рост больше нуля': 'Trage eine Größe über null ein',
      'Введите обхват шеи больше нуля': 'Trage einen Halsumfang über null ein',
      'Введите обхват талии больше нуля': 'Trage einen Taillenumfang über null ein',
      'Введите обхват бёдер больше нуля': 'Trage einen Hüftumfang über null ein',
    },
  },
  es: {
    results: {
      'Процент жира': 'Porcentaje de grasa',
      'Метод расчёта': 'Método de cálculo',
      'Обхват талии': 'Perímetro de la cintura',
      'Обхват шеи': 'Perímetro del cuello',
      'Обхват бёдер': 'Perímetro de la cadera',
      'Талия минус шея': 'Cintura menos cuello',
      'Талия плюс бёдра минус шея': 'Cintura más cadera menos cuello',
      'Проверьте данные': 'Revisa los datos',
      'Результат': 'Resultado',
      'Рост': 'Estatura',
    },
    values: {
      'Обхваты, метод ВМС США': 'Perímetros, método de la Marina de EE. UU.',
      'Это оценка по обхватам, а не измерение. Погрешность метода составляет несколько процентных пунктов и растёт при неточных замерах ленты. Результат не является медицинским заключением.': 'Es una estimación a partir de perímetros, no una medida. El error del método es de unos pocos puntos porcentuales y crece con mediciones imprecisas con la cinta. El resultado no es un diagnóstico médico.',
      'Обхват талии должен быть больше обхвата шеи': 'El perímetro de la cintura debe ser mayor que el del cuello',
      'Сумма обхватов талии и бёдер должна быть больше обхвата шеи': 'La suma de los perímetros de cintura y cadera debe ser mayor que el del cuello',
      'Сочетание обхватов выходит за пределы применимости метода — проверьте измерения': 'La combinación de perímetros queda fuera del rango en el que se aplica el método: revisa las medidas',
      'Введите рост больше нуля': 'Introduce una estatura mayor que cero',
      'Введите обхват шеи больше нуля': 'Introduce un perímetro de cuello mayor que cero',
      'Введите обхват талии больше нуля': 'Introduce un perímetro de cintura mayor que cero',
      'Введите обхват бёдер больше нуля': 'Introduce un perímetro de cadera mayor que cero',
    },
  },
};
