// СГЕНЕРИРОВАНО. Не редактировать руками.
// Общие фразы результата, отобранные под наследственный калькулятор body-fat-calculator.
// Перегенерировать: npm run calculators:generate

import type { CalculatorLocalization } from '../../../../lib/platform/types';

export const shared: CalculatorLocalization = {
  en: {
    results: {
      'Обхват живота': 'Abdomen circumference',
      'Живот минус шея': 'Abdomen minus neck',
      'Процент жира': 'Body fat percentage',
      'Метод расчёта': 'Method',
      'Обхват талии': 'Waist circumference',
      'Обхват шеи': 'Neck circumference',
      'Обхват бёдер': 'Hip circumference',
      'Талия плюс бёдра минус шея': 'Waist plus hips minus neck',
      'Проверьте данные': 'Check inputs',
      'В': 'To',
      'Рост': 'Height',
    },
    values: {
      'Выберите мужскую или женскую формулу': 'Select the male or female equation',
      'Историческая оценка по обхватам. У мужчин измеряют живот на уровне пупка, у женщин — естественную талию. Универсальная погрешность не гарантируется; результат не является медицинским заключением.': 'Historical circumference estimate. Measure male abdomen at the navel and female natural waist. No universal error margin is guaranteed; the result is not a medical conclusion.',
      'Обхваты, метод ВМС США': 'U.S. Navy circumference method',
      'Введите обхват живота больше нуля': 'Enter an abdomen circumference greater than zero',
      'Обхват живота должен быть больше обхвата шеи': 'The abdomen circumference must exceed the neck circumference',
      'Сумма обхватов талии и бёдер должна быть больше обхвата шеи': 'Waist plus hip circumference must be larger than the neck circumference',
      'Сочетание обхватов выходит за пределы применимости метода — проверьте измерения': 'This combination of circumferences falls outside the range where the method applies — check the measurements',
      'Введите рост больше нуля': 'Enter a height greater than zero',
      'Введите обхват шеи больше нуля': 'Enter a neck circumference greater than zero',
      'Введите обхват талии больше нуля': 'Enter a waist circumference greater than zero',
      'Введите обхват бёдер больше нуля': 'Enter a hip circumference greater than zero',
    },
  },
  uk: {
    results: {
      'Обхват живота': 'Обхват живота',
      'Живот минус шея': 'Живіт мінус шия',
      'Процент жира': 'Відсоток жиру',
      'Метод расчёта': 'Метод розрахунку',
      'Обхват талии': 'Обхват талії',
      'Обхват шеи': 'Обхват шиї',
      'Обхват бёдер': 'Обхват стегон',
      'Талия плюс бёдра минус шея': 'Талія плюс стегна мінус шия',
      'Проверьте данные': 'Перевірте дані',
      'В': 'У',
      'Рост': 'Зріст',
    },
    values: {
      'Выберите мужскую или женскую формулу': 'Оберіть чоловічу або жіночу формулу',
      'Историческая оценка по обхватам. У мужчин измеряют живот на уровне пупка, у женщин — естественную талию. Универсальная погрешность не гарантируется; результат не является медицинским заключением.': 'Історична оцінка обхватів. Чоловічий живіт вимірюють через пупок, жіночу природну талію. Універсальна похибка не гарантується; це не медичний висновок.',
      'Обхваты, метод ВМС США': 'Метод ВМС США за обхватами',
      'Введите обхват живота больше нуля': 'Введіть обхват живота більше нуля',
      'Обхват живота должен быть больше обхвата шеи': 'Обхват живота має бути більшим за обхват шиї',
      'Сумма обхватов талии и бёдер должна быть больше обхвата шеи': 'Сума обхватів талії та стегон має бути більшою за обхват шиї',
      'Сочетание обхватов выходит за пределы применимости метода — проверьте измерения': 'Поєднання обхватів виходить за межі застосовності методу — перевірте виміри',
      'Введите рост больше нуля': 'Введіть зріст більший за нуль',
      'Введите обхват шеи больше нуля': 'Введіть обхват шиї більший за нуль',
      'Введите обхват талии больше нуля': 'Введіть обхват талії більший за нуль',
      'Введите обхват бёдер больше нуля': 'Введіть обхват стегон більший за нуль',
    },
  },
  de: {
    results: {
      'Обхват живота': 'Bauchumfang',
      'Живот минус шея': 'Bauch minus Hals',
      'Процент жира': 'Körperfettanteil',
      'Метод расчёта': 'Rechenweg',
      'Обхват талии': 'Taillenumfang',
      'Обхват шеи': 'Halsumfang',
      'Обхват бёдер': 'Hüftumfang',
      'Талия плюс бёдра минус шея': 'Taille plus Hüfte minus Hals',
      'Проверьте данные': 'Prüfe die Werte',
      'В': 'Nach',
      'Рост': 'Körpergröße',
    },
    values: {
      'Выберите мужскую или женскую формулу': 'Männliche oder weibliche Formel wählen',
      'Историческая оценка по обхватам. У мужчин измеряют живот на уровне пупка, у женщин — естественную талию. Универсальная погрешность не гарантируется; результат не является медицинским заключением.': 'Historische Umfangsschätzung. Männlichen Bauch am Nabel, weibliche natürliche Taille messen. Keine universelle Fehlerspanne; keine medizinische Schlussfolgerung.',
      'Обхваты, метод ВМС США': 'Umfänge, Methode der US Navy',
      'Введите обхват живота больше нуля': 'Gib einen Bauchumfang größer als null ein',
      'Обхват живота должен быть больше обхвата шеи': 'Der Bauchumfang muss größer als der Halsumfang sein',
      'Сумма обхватов талии и бёдер должна быть больше обхвата шеи': 'Taillen- und Hüftumfang zusammen müssen größer als der Halsumfang sein',
      'Сочетание обхватов выходит за пределы применимости метода — проверьте измерения': 'Diese Kombination von Umfängen liegt außerhalb des Bereichs, in dem die Methode gilt — prüfe die Messungen',
      'Введите рост больше нуля': 'Trage eine Größe über null ein',
      'Введите обхват шеи больше нуля': 'Trage einen Halsumfang über null ein',
      'Введите обхват талии больше нуля': 'Trage einen Taillenumfang über null ein',
      'Введите обхват бёдер больше нуля': 'Trage einen Hüftumfang über null ein',
    },
  },
  es: {
    results: {
      'Обхват живота': 'Perímetro abdominal',
      'Живот минус шея': 'Abdomen menos cuello',
      'Процент жира': 'Porcentaje de grasa',
      'Метод расчёта': 'Método de cálculo',
      'Обхват талии': 'Perímetro de la cintura',
      'Обхват шеи': 'Perímetro del cuello',
      'Обхват бёдер': 'Perímetro de la cadera',
      'Талия плюс бёдра минус шея': 'Cintura más cadera menos cuello',
      'Проверьте данные': 'Revisa los datos',
      'В': 'A',
      'Рост': 'Estatura',
    },
    values: {
      'Выберите мужскую или женскую формулу': 'Selecciona fórmula masculina o femenina',
      'Историческая оценка по обхватам. У мужчин измеряют живот на уровне пупка, у женщин — естественную талию. Универсальная погрешность не гарантируется; результат не является медицинским заключением.': 'Estimación histórica por perímetros. Abdomen masculino al ombligo y cintura natural femenina. Sin error universal garantizado; no es conclusión médica.',
      'Обхваты, метод ВМС США': 'Perímetros, método de la Marina de EE. UU.',
      'Введите обхват живота больше нуля': 'Introduce un perímetro abdominal mayor que cero',
      'Обхват живота должен быть больше обхвата шеи': 'El perímetro abdominal debe superar el perímetro del cuello',
      'Сумма обхватов талии и бёдер должна быть больше обхвата шеи': 'La suma de los perímetros de cintura y cadera debe ser mayor que el del cuello',
      'Сочетание обхватов выходит за пределы применимости метода — проверьте измерения': 'La combinación de perímetros queda fuera del rango en el que se aplica el método: revisa las medidas',
      'Введите рост больше нуля': 'Introduce una estatura mayor que cero',
      'Введите обхват шеи больше нуля': 'Introduce un perímetro de cuello mayor que cero',
      'Введите обхват талии больше нуля': 'Introduce un perímetro de cintura mayor que cero',
      'Введите обхват бёдер больше нуля': 'Introduce un perímetro de cadera mayor que cero',
    },
  },
};
