// СГЕНЕРИРОВАНО. Не редактировать руками.
// Общие фразы результата, отобранные под наследственный калькулятор credit-calculator.
// Перегенерировать: npm run calculators:generate

import type { CalculatorLocalization } from '../../../../lib/platform/types';

export const shared: CalculatorLocalization = {
  en: {
    results: {
      'Ежемесячный платеж': 'Monthly payment',
      'Общая сумма выплат': 'Total repayment',
      'Переплата': 'Overpayment',
      'Сумма процентов': 'Interest amount',
      'Срок': 'Term',
      'Проверьте данные': 'Check inputs',
      'Введите положительные значения': 'Enter positive values',
      'В': 'To',
      'Последний платеж': 'Final payment',
      'Средний платеж': 'Average payment',
      'График первых платежей': 'Payment schedule',
      'Месяц': 'Month',
      'Платеж': 'Payment',
      'Основной долг': 'Principal',
      'Проценты': 'Interest',
      'Остаток': 'Balance',
      'Плановый платеж с доплатой': 'Planned payment with extra',
      'Разовая комиссия': 'One-time fee',
      'Сокращение срока': 'Term reduction',
    },
    values: {
      'Показан размер первого (наибольшего) платежа. Далее платёж снижается.': 'The first and largest payment is shown. Later payments gradually decrease.',
      'Показан размер первого (наибольшего) платежа.': 'The first and largest payment is shown.',
      'Показаны первые 12 месяцев и последний платеж.': 'The first 12 months and the final payment are shown.',
      'Введите положительные значения': 'Enter positive values',
      'Проценты': 'Percentages',
    },
  },
  uk: {
    results: {
      'Ежемесячный платеж': 'Щомісячний платіж',
      'Общая сумма выплат': 'Загальна сума виплат',
      'Переплата': 'Переплата',
      'Сумма процентов': 'Сума відсотків',
      'Срок': 'Строк',
      'Проверьте данные': 'Перевірте дані',
      'В': 'У',
      'Последний платеж': 'Останній платіж',
      'Средний платеж': 'Середній платіж',
      'График первых платежей': 'Графік платежів',
      'Месяц': 'Місяць',
      'Платеж': 'Платіж',
      'Основной долг': 'Основний борг',
      'Проценты': 'Відсотки',
      'Остаток': 'Залишок',
      'Плановый платеж с доплатой': 'Плановий платіж із доплатою',
      'Разовая комиссия': 'Разова комісія',
      'Сокращение срока': 'Скорочення строку',
    },
    values: {
      'Показан размер первого (наибольшего) платежа. Далее платёж снижается.': 'Показано перший і найбільший платіж. Наступні платежі поступово зменшуються.',
      'Показан размер первого (наибольшего) платежа.': 'Показано перший і найбільший платіж.',
      'Показаны первые 12 месяцев и последний платеж.': 'Показано перші 12 місяців і останній платіж.',
      'Введите положительные значения': 'Введіть додатні значення',
      'Проценты': 'Відсотки',
    },
  },
  de: {
    results: {
      'Ежемесячный платеж': 'Monatliche Rate',
      'Общая сумма выплат': 'Summe aller Zahlungen',
      'Переплата': 'Mehrkosten',
      'Сумма процентов': 'Zinsen insgesamt',
      'Срок': 'Laufzeit',
      'Проверьте данные': 'Prüfe die Werte',
      'В': 'Nach',
      'Последний платеж': 'Letzte Rate',
      'Средний платеж': 'Durchschnittliche Rate',
      'График первых платежей': 'Plan der ersten Raten',
      'Месяц': 'Monat',
      'Платеж': 'Rate',
      'Основной долг': 'Tilgung',
      'Проценты': 'Zinsen',
      'Остаток': 'Restschuld',
      'Плановый платеж с доплатой': 'Rate samt Sondertilgung',
      'Разовая комиссия': 'Einmalige Gebühr',
      'Сокращение срока': 'Verkürzung der Laufzeit',
    },
    values: {
      'Показан размер первого (наибольшего) платежа. Далее платёж снижается.': 'Gezeigt ist die erste und höchste Rate. Danach sinkt die Rate allmählich.',
      'Показан размер первого (наибольшего) платежа.': 'Gezeigt ist die erste und höchste Rate.',
      'Показаны первые 12 месяцев и последний платеж.': 'Gezeigt sind die ersten 12 Monate und die letzte Rate.',
      'Введите положительные значения': 'Trage positive Werte ein',
      'Проценты': 'Prozent',
    },
  },
  es: {
    results: {
      'Ежемесячный платеж': 'Cuota mensual',
      'Общая сумма выплат': 'Total a devolver',
      'Переплата': 'Intereses totales',
      'Сумма процентов': 'Total de intereses',
      'Срок': 'Plazo',
      'Проверьте данные': 'Revisa los datos',
      'Введите положительные значения': 'Introduce valores positivos',
      'В': 'A',
      'Последний платеж': 'Última cuota',
      'Средний платеж': 'Cuota media',
      'График первых платежей': 'Cuadro de las primeras cuotas',
      'Месяц': 'Mes',
      'Платеж': 'Cuota',
      'Основной долг': 'Capital amortizado',
      'Проценты': 'Intereses',
      'Остаток': 'Pendiente',
      'Плановый платеж с доплатой': 'Cuota prevista con amortización adicional',
      'Разовая комиссия': 'Comisión única',
      'Сокращение срока': 'Reducción del plazo',
    },
    values: {
      'Показан размер первого (наибольшего) платежа. Далее платёж снижается.': 'Se muestra el importe de la primera cuota, la mayor. Después la cuota va bajando.',
      'Показан размер первого (наибольшего) платежа.': 'Se muestra el importe de la primera cuota, la mayor.',
      'Показаны первые 12 месяцев и последний платеж.': 'Se muestran los 12 primeros meses y la última cuota.',
      'Введите положительные значения': 'Introduce valores positivos',
    },
  },
};
