import type { CalculatorDef } from '../../lib/types';
type Copy = Pick<CalculatorDef, 'longDescription' | 'howToUse' | 'howItWorks' | 'example' | 'faq' | 'disclaimer'>;
export const contractContent: Record<'ru' | 'en' | 'uk' | 'de' | 'es', Copy> = {
  ru: {
    longDescription: 'Это оценка ценности клиента по постоянной месячной выручке и валовой марже. Средний срок жизни можно задать в месяцах или вывести из постоянной вероятности ухода за месяц. Результат относится к сумме до CAC и неучтённых накладных расходов, а не к чистой прибыли. Для продукта с меняющимися тарифами, оттоком или доходом по возрасту когорты нужен отдельный помесячный анализ.',
    howToUse: ['Выберите известный средний срок или месячный отток; поле другого режима не используется.', 'Задайте положительную месячную выручку с клиента и маржу больше 0, не выше 100 %. Срок может быть дробным средним значением.', 'В режиме оттока используйте месячную долю ушедших клиентов, не годовой отток и не отток выручки.', 'CAC необязателен: пусто или 0 отключает отношение и простой срок покрытия. Все суммы имеют одну валюту без обмена.'],
    howItWorks: 'LTV = месячная выручка A × средний срок L × доля маржи m. При постоянном месячном оттоке c: L = 1/c. Геометрическая модель включает первый оплаченный месяц: L = 1 + (1−c) + (1−c)² + … . Для CAC > 0 отношение = LTV/CAC; простой срок покрытия = CAC/(A × m). Этот срок не учитывает уход клиентов до покрытия, дисконтирование или дату платежа. Вычисления выполняются до округления; обычные суммы и месяцы имеют два знака.',
    example: '800 денежных единиц в месяц, отток 12 %, маржа 70 %: срок 8,3333… месяца, LTV 4 666,67. CAC 2 800 даёт отношение 1,67× и простой срок покрытия 5,00 месяцев. При оттоке 100 % оплаченный первый месяц остаётся: 500 в месяц и маржа 100 % дают LTV 500. Нулевой отток не даёт конечного срока в этой модели.',
    faq: [
      { q: 'Почему при полном месячном оттоке остаётся один месяц?', a: 'Клиент уже оплатил первый месяц, а к следующему уходит с вероятностью 100 %. Сумма будущих оплаченных периодов здесь начинается с первого периода, а не после него.' },
      { q: 'Что исключает LTV после умножения на валовую маржу?', a: 'CAC, неучтённые накладные расходы и стоимость времени. Маржа убирает лишь затраты своей определённой базы. Такое LTV нельзя автоматически назвать чистой прибылью клиента.' },
      { q: 'Можно ли годовой отток подставить как месячный?', a: 'Нет. Периоды должны совпадать. При постоянной вероятности ухода годовой отток 12 % соответствует месячному 1 − 0,88^(1/12), а не 12 % и не просто 1 %. Отток выручки также не заменяет отток клиентов.' },
      { q: 'Почему нулевой отток требует другой модели?', a: 'При отсутствии ухода бесконечная сумма постоянной положительной выручки не даёт конечного срока. Выберите обоснованный срок вручную или отдельный ограниченный горизонт; автоматического срока 60 месяцев здесь нет.' },
      { q: 'Гарантирует ли простой срок покрытия CAC возврат затрат?', a: 'Нет. Он делит CAC на неизменный месячный маржинальный доход без снижения числа оставшихся клиентов. Для ожидаемого покрытия по когорте нужны выживаемость, сроки поступлений и дополнительные расходы.' },
    ],
    disclaimer: 'Постоянная месячная модель без дисконтирования. LTV до CAC и неучтённых расходов; отношение не получает универсальную оценку, простой срок покрытия не является обещанием окупаемости.',
  },
  en: {
    longDescription: 'This estimate uses constant monthly revenue per customer and a gross margin. Average lifetime is supplied in months or derived from a constant monthly probability of customer churn. The value is before CAC and any overhead excluded from the supplied margin; it is not net customer profit. Changing prices, churn or cohort-age revenue require a separate monthly cash-flow model.',
    howToUse: ['Choose known average lifetime or monthly churn; the other mode’s field is ignored.', 'Enter positive monthly revenue per customer and margin above 0 up to 100%. Lifetime can be a fractional average.', 'Use monthly customer churn, not annual churn or revenue churn, in the churn mode.', 'CAC is optional: blank or 0 omits the ratio and simple coverage time. Keep all money in one currency; no exchange occurs.'],
    howItWorks: 'LTV = monthly revenue A × average lifetime L × margin share m. With constant monthly customer churn c: L = 1/c. The geometric model includes the first paid month: L = 1 + (1−c) + (1−c)² + … . For CAC > 0, ratio = LTV/CAC and simple coverage time = CAC/(A × m). This time excludes churn before coverage, discounting and payment dates. Intermediate figures remain unrounded; ordinary amounts and months use two decimal places.',
    example: 'Monthly revenue 800 monetary units, churn 12% and margin 70% give lifetime 8.3333… months and LTV 4,666.67. CAC 2,800 gives ratio 1.67× and simple coverage time 5.00 months. At 100% churn the first paid month remains: revenue 500 and margin 100% give LTV 500. Zero churn has no finite lifetime under this model.',
    faq: [
      { q: 'Why does complete monthly churn still leave one month?', a: 'The customer has paid for the first month and leaves before the next one with probability 100%. This sum starts with that first paid period, rather than after it.' },
      { q: 'What remains excluded after applying the gross margin?', a: 'CAC, overhead excluded from the supplied margin and time value. The margin removes only the costs belonging to its defined basis. The resulting LTV is not automatically net customer profit.' },
      { q: 'Can annual churn be entered as monthly churn?', a: 'No. The periods must match. Under a constant probability of departure, annual churn 12% corresponds to monthly churn 1 − 0.88^(1/12), rather than 12% or simply 1%. Revenue churn is also a different measure.' },
      { q: 'Why does zero churn need a different lifetime model?', a: 'Without departures, an endless sum of positive constant monthly revenue has no finite lifetime. Supply a justified lifetime or use a separate bounded horizon; no automatic sixty-month fallback is applied.' },
      { q: 'Does the simple CAC coverage time guarantee payback?', a: 'No. It divides CAC by constant monthly margin-adjusted revenue without reducing the surviving customer count. Expected cohort coverage requires survival, receipt timing and other costs.' },
    ],
    disclaimer: 'Constant monthly model without discounting. LTV is before CAC and other costs excluded from the margin. The ratio has no universal rating and simple coverage time does not guarantee payback.',
  },
  uk: {
    longDescription: 'Оцінка використовує сталий місячний виторг із клієнта та валову маржу. Середній строк задається в місяцях або визначається зі сталої місячної ймовірності відтоку клієнтів. Значення отримано до CAC і неврахованих накладних витрат, а не як чистий прибуток. Зміни ціни, відтоку або виторгу з віком когорти потребують окремої помісячної моделі.',
    howToUse: ['Оберіть відомий середній строк або місячний відтік; поле іншого режиму не використовується.', 'Введіть додатний місячний виторг із клієнта та маржу більшу за 0 і не вищу за 100 %. Середній строк може бути дробовим.', 'Відтік має бути місячною часткою клієнтів, що пішли, а не річним відтоком чи відтоком виторгу.', 'CAC необов’язковий: порожньо або 0 вимикає відношення та простий строк покриття. Валюта спільна, обміну немає.'],
    howItWorks: 'LTV = місячний виторг A × середній строк L × частка маржі m. За сталого місячного відтоку c: L = 1/c. Перший оплачений місяць включено: L = 1 + (1−c) + (1−c)² + … . За CAC > 0 відношення = LTV/CAC, простий строк покриття = CAC/(A × m). Цей строк не враховує відтік до покриття, дисконтування та дати оплати. Проміжні числа не округлюються; звичайні суми й місяці мають два знаки.',
    example: '800 грошових одиниць на місяць, відтік 12 % і маржа 70 % дають строк 8,3333… місяця та LTV 4 666,67. CAC 2 800 дає відношення 1,67× і простий строк покриття 5,00 місяців. За відтоку 100 % перший оплачений місяць лишається: виторг 500 і маржа 100 % дають LTV 500. Нульовий відтік не дає скінченного строку.',
    faq: [
      { q: 'Чому повний місячний відтік залишає один місяць?', a: 'Клієнт уже оплатив перший місяць і з імовірністю 100 % йде до наступного. Сума починається з першого оплаченого періоду, а не після нього.' },
      { q: 'Що не враховано після застосування валової маржі?', a: 'CAC, невраховані накладні витрати та вартість часу. Маржа віднімає лише витрати своєї визначеної бази. Таке LTV не є автоматично чистим прибутком клієнта.' },
      { q: 'Чи можна підставити річний відтік замість місячного?', a: 'Ні. Періоди мають збігатися. За сталої ймовірності припинення передплати річним 12 % відповідає місячна частка 1 − 0,88^(1/12), а не 12 % і не просто 1 %. Відтік виторгу також має інше визначення.' },
      { q: 'Чому за нульового відтоку потрібна інша модель строку?', a: 'Без відтоку нескінченна сума додатного сталого місячного виторгу не має скінченного строку. Введіть обґрунтований строк вручну або використайте окремий обмежений горизонт; автоматичних 60 місяців немає.' },
      { q: 'Чи гарантує простий строк покриття CAC повернення витрат?', a: 'Ні. Він ділить CAC на сталий місячний маржинальний дохід без скорочення кількості клієнтів, що лишилися. Для очікуваного покриття когорти потрібні виживання, час надходжень та інші витрати.' },
    ],
    disclaimer: 'Стала місячна модель без дисконтування. LTV до CAC та неврахованих витрат; універсальної оцінки відношення чи гарантії окупності немає.',
  },
  de: {
    longDescription: 'Die Schätzung verwendet gleichbleibenden Monatsumsatz je Kunde und eine Rohmarge. Die mittlere Laufzeit wird in Monaten eingegeben oder aus einer konstanten monatlichen Abwanderungswahrscheinlichkeit abgeleitet. Der Wert liegt vor CAC und nicht berücksichtigten Gemeinkosten, nicht als Nettogewinn des Kunden vor. Änderungen von Preis, Abwanderung oder Kohortenumsatz verlangen ein eigenes Monatsmodell.',
    howToUse: ['Wähle bekannte mittlere Laufzeit oder monatliche Abwanderung; das Feld des anderen Modus bleibt unberücksichtigt.', 'Monatsumsatz je Kunde ist positiv, die Marge größer als 0 und höchstens 100 %. Die mittlere Laufzeit darf Bruchteile enthalten.', 'Nutze monatliche Kundenabwanderung, nicht jährliche Abwanderung oder Umsatzverlust.', 'CAC ist optional: leer oder 0 lässt Verhältnis und einfache Deckungszeit weg. Alle Beträge nutzen eine Währung ohne Umrechnung.'],
    howItWorks: 'LTV = Monatsumsatz A × mittlere Laufzeit L × Margenanteil m. Bei konstanter monatlicher Kundenabwanderung c gilt L = 1/c. Der erste bezahlte Monat zählt: L = 1 + (1−c) + (1−c)² + … . Für CAC > 0 gilt Verhältnis = LTV/CAC und einfache Deckungszeit = CAC/(A × m). Diese Zeit ignoriert Abwanderung vor der Deckung, Abzinsung und Zahlungstermine. Übliche Beträge und Monate erhalten zwei Dezimalstellen; Zwischenwerte bleiben ungerundet.',
    example: '800 Geldeinheiten Monatsumsatz, 12 % Abwanderung und 70 % Marge ergeben 8,3333… Monate und LTV 4 666,67. CAC 2 800 ergibt Verhältnis 1,67× und einfache Deckungszeit 5,00 Monate. Bei 100 % Abwanderung bleibt der erste bezahlte Monat: Umsatz 500 bei 100 % Marge ergibt LTV 500. Null Abwanderung ergibt keine endliche Laufzeit.',
    faq: [
      { q: 'Warum bleibt bei vollständiger monatlicher Abwanderung ein Monat?', a: 'Der erste Monat wurde bezahlt; vor dem nächsten verlässt der Kunde das Produkt mit Wahrscheinlichkeit 100 %. Die Summe beginnt mit diesem ersten bezahlten Zeitraum.' },
      { q: 'Welche Kosten fehlen nach Anwendung der Rohmarge?', a: 'CAC, nicht berücksichtigte Gemeinkosten und Zeitwert. Die Marge entfernt nur Kosten ihrer festgelegten Basis. Der errechnete LTV ist damit nicht automatisch Nettogewinn.' },
      { q: 'Kann jährliche Abwanderung als monatliche eingegeben werden?', a: 'Nein. Bei konstanter Austrittswahrscheinlichkeit entsprechen 12 % jährlich einer Monatsrate 1 − 0,88^(1/12), nicht 12 % oder einfach 1 %. Umsatzabwanderung ist ebenfalls eine andere Messgröße.' },
      { q: 'Warum benötigt null Abwanderung ein anderes Laufzeitmodell?', a: 'Ohne Abwanderung liefert eine endlose Summe positiver Monatsumsätze keine endliche Laufzeit. Gib eine begründete Laufzeit vor oder nutze einen begrenzten Horizont; ein automatischer Ersatz durch sechzig Monate erfolgt nicht.' },
      { q: 'Garantiert die einfache CAC-Deckungszeit eine Amortisation?', a: 'Nein. Sie teilt CAC durch konstanten margengewichteten Monatsumsatz und reduziert nicht die Zahl verbleibender Kunden. Erwartete Kohortendeckung benötigt Verbleibwahrscheinlichkeit, Zahlungstermine und weitere Kosten.' },
    ],
    disclaimer: 'Konstantes Monatsmodell ohne Abzinsung. LTV vor CAC und nicht enthaltenen Kosten; kein allgemeiner Zielquotient und keine garantierte Amortisation.',
  },
  es: {
    longDescription: 'Esta estimación utiliza ingresos mensuales constantes por cliente y margen bruto. La permanencia media se indica en meses o se deriva de una probabilidad mensual constante de abandono de clientes. El valor es anterior al CAC y a gastos generales no incluidos, no beneficio neto del cliente. Cambios de precio, abandono o ingresos según la edad de la cohorte requieren otro modelo mensual.',
    howToUse: ['Elige permanencia media conocida o abandono mensual; el campo del otro modo no se utiliza.', 'Introduce ingresos mensuales positivos por cliente y margen mayor que 0, hasta 100 %. La permanencia media puede ser fraccionaria.', 'Usa abandono mensual de clientes, no anual ni pérdida de ingresos.', 'CAC es opcional: vacío o 0 omite el cociente y el plazo simple de cobertura. Mantén una sola moneda, sin conversión.'],
    howItWorks: 'LTV = ingresos mensuales A × permanencia media L × fracción del margen m. Con abandono mensual constante c: L = 1/c. Se incluye el primer mes pagado: L = 1 + (1−c) + (1−c)² + … . Para CAC > 0, cociente = LTV/CAC y plazo simple de cobertura = CAC/(A × m). Este plazo excluye abandonos anteriores a la cobertura, descuento y fechas de pago. Importes y meses habituales usan dos decimales; no se redondean valores intermedios.',
    example: 'Ingresos mensuales 800 unidades monetarias, abandono 12 % y margen 70 % dan permanencia 8,3333… meses y LTV 4 666,67. CAC 2 800 da cociente 1,67× y plazo simple 5,00 meses. Con abandono 100 % queda el primer mes pagado: ingresos 500 y margen 100 % dan LTV 500. Abandono cero no produce permanencia finita.',
    faq: [
      { q: '¿Por qué el abandono mensual completo aún deja un mes?', a: 'El cliente ha pagado el primer mes y se marcha antes del siguiente con probabilidad del 100 %. La suma comienza con ese primer periodo pagado.' },
      { q: '¿Qué queda excluido después de aplicar el margen bruto?', a: 'CAC, gastos generales no incluidos y valor temporal. El margen elimina solo los costes de su base definida. Ese LTV no equivale automáticamente a beneficio neto.' },
      { q: '¿Se puede introducir abandono anual como mensual?', a: 'No. Con probabilidad constante de salida, un abandono anual del 12 % corresponde a una tasa mensual 1 − 0,88^(1/12), no 12 % ni simplemente 1 %. La pérdida de ingresos también es otra medida.' },
      { q: '¿Por qué el abandono cero exige otro modelo de permanencia?', a: 'Sin abandono, una suma interminable de ingresos mensuales positivos no tiene permanencia finita. Introduce una duración justificada o usa un horizonte limitado; no se aplica una sustitución automática por sesenta meses.' },
      { q: '¿El plazo simple de cobertura del CAC garantiza recuperación?', a: 'No. Divide CAC entre ingresos mensuales constantes ajustados por margen sin reducir los clientes supervivientes. La cobertura esperada de una cohorte exige permanencia, fechas de cobro y otros costes.' },
    ],
    disclaimer: 'Modelo mensual constante sin descuento. LTV anterior al CAC y costes no incluidos; no ofrece un cociente objetivo universal ni recuperación garantizada.',
  },
};
