import type { CalculatorCopy } from '../../lib/platform/types';

type Body = Pick<CalculatorCopy, 'longDescription' | 'howToUse' | 'howItWorks' | 'example' | 'faq'> & { disclaimer: string };

export const exchangeFeeContractContent: Record<'ru' | 'en' | 'uk' | 'de' | 'es', Body> = {
  ru: {
    longDescription: 'Сравните условия обмена при вручную заданном базовом курсе, спреде и сборах. При продаже сумма — количество иностранной валюты; при покупке — бюджет в местных деньгах. Курс всегда задаётся как местные деньги за одну единицу иностранной валюты. Если вводите уже предложенный обменником курс, поставьте спред 0%, чтобы не учесть его второй раз.',
    howToUse: ['Выберите продажу или покупку: подпись и единица суммы изменятся.', 'Введите базовый курс в местных деньгах за одну единицу иностранной валюты.', 'Задайте спред относительно этого базового курса и процентную комиссию.', 'Фиксированный сбор вводите в местных деньгах при обоих направлениях. Сравните сумму к получению и потери относительно базового курса.'],
    howItWorks: 'Обозначим сумму A, базовый курс r, долю спреда s, долю комиссии c и фиксированный сбор F в местных деньгах; проценты делятся на 100. Продажа: Q = A × r × (1 − s) × (1 − c) − F. Покупка: Q = (A − F) × (1 − c) / [r × (1 + s)]. При покупке сбор сначала уменьшает бюджет, затем с остатка берётся процент. Это заявленный порядок модели, а не универсальное правило банков. Потери равны разнице между A × r (продажа) или A / r (покупка) и Q. Денежные строки обычно округляются отдельно до двух знаков; результат без сборов и спреда равен базовому обмену.',
    example: 'Учебные условия: базовый курс 2 местных единицы за одну иностранную, спред 10%, комиссия 5%, сбор 20 местных единиц. Продажа 1000: 1000 × 2 × 0,9 = 1800; комиссия 90; к получению 1800 − 90 − 20 = 1690 ₽, потери 310 / 2000 = 15,5%. Покупка на бюджет 2000: (2000 − 20) × 0,95 / 2,2 = 855 единиц валюты, потери 145 / 1000 = 14,5%. Это не текущий рыночный курс.',
    faq: [
      { q: 'Какой курс вводить, чтобы не посчитать спред дважды?', a: 'Введите базовый курс до спреда. Если знаете только конечный курс обменника, используйте его со спредом 0%; тогда сравнение потерь будет относительно этого введённого курса.' },
      { q: 'В каких деньгах вводится фиксированный сбор?', a: 'В местных деньгах и при продаже, и при покупке. При покупке строка результата переводит сбор в иностранную валюту по курсу со спредом, чтобы её можно было сопоставить с суммой к получению.' },
      { q: 'Почему покупка и продажа используют разный порядок сбора?', a: 'Продажа получает местные деньги, из которых вычитается сбор. Покупка сначала платит сбор из местного бюджета, и комиссия применяется к оставшемуся бюджету. Если договор предусматривает другой порядок или валюту комиссии, эта модель ему не соответствует.' },
      { q: 'Может ли сумма к получению быть отрицательной?', a: 'Нет: если сборы превышают доступную сумму, показывается ошибка. Ровно нулевая выплата допустима и означает, что сборы поглотили всю сумму; доля потерь тогда 100%.' },
      { q: 'Какие расходы и данные здесь не учитываются автоматически?', a: 'Рыночные курсы, налоги, ограничения и комиссии перевода не загружаются. Добавлять плату за перевод к F можно только если она взимается в тех же местных деньгах и в указанном порядке модели.' },
    ],
    disclaimer: 'Справочная учебная модель вручную введённых условий. Символ местных денег в интерфейсе не определяет страну, валютную пару или правила договора. Проверяйте валюту и порядок каждого сбора у своего провайдера.',
  },
  en: {
    longDescription: 'Compare exchange terms using a manually entered baseline rate, spread and charges. For a sale, the amount is foreign currency; for a purchase, it is a budget in local money. The rate always means local money per one foreign currency unit. Set the spread to 0% when entering a final quoted rate, so its markup is not counted twice.',
    howToUse: ['Choose selling or buying; the amount label and unit change.', 'Enter the baseline rate in local money per foreign currency unit.', 'Enter the spread relative to that baseline and the percentage commission.', 'Enter the fixed charge in local money in both directions. Compare the payout and the loss relative to the baseline.'],
    howItWorks: 'Let A be the amount, r the baseline rate, s the spread fraction, c the commission fraction, and F the fixed charge in local money; divide percentages by 100. Selling: Q = A × r × (1 − s) × (1 − c) − F. Buying: Q = (A − F) × (1 − c) / [r × (1 + s)]. Buying first deducts the fixed charge from the budget, then charges commission on the remainder. This is the stated model order, not a rule all banks follow. Loss is A × r (selling) or A / r (buying), minus Q. Monetary rows are normally rounded independently to two decimals; with no spread or charges, the payout equals the baseline exchange.',
    example: 'Teaching inputs: baseline rate 2 local units per foreign unit, spread 10%, commission 5%, fixed charge 20 local units. Selling 1000: 1000 × 2 × 0.9 = 1800; commission 90; payout 1800 − 90 − 20 = $1690, loss 310 / 2000 = 15.5%. Buying with a budget of 2000: (2000 − 20) × 0.95 / 2.2 = 855 currency units, loss 145 / 1000 = 14.5%. This is not a current market rate.',
    faq: [
      { q: 'Which rate avoids counting the spread twice?', a: 'Enter the baseline rate before the spread. If you only know a final quoted rate, use it with a 0% spread; the loss comparison will then use that entered rate as its baseline.' },
      { q: 'Which currency is the fixed charge in?', a: 'Local money, for both selling and buying. For a purchase, the result converts the charge into foreign currency at the spread-adjusted rate so it can be compared with the payout.' },
      { q: 'Why is the fixed charge handled differently for a purchase?', a: 'A sale receives local money and then pays the fixed charge. A purchase pays that charge from the local budget first and commission applies to the remaining budget. A contract using a different order or fee currency needs a different model.' },
      { q: 'Can the payout be negative?', a: 'No. Charges exceeding the available amount produce an error. A zero payout is allowed when charges consume the entire amount; the loss share is then 100%.' },
      { q: 'What is not included automatically?', a: 'Market quotes, taxes, restrictions and transfer charges are not loaded. Only add a transfer charge to F if it uses the same local money and follows the stated model order.' },
    ],
    disclaimer: 'Teaching model of manually entered terms. The local money symbol does not establish a country, currency pair or contract rules. Check the currency and order of each charge with your provider.',
  },
  uk: {
    longDescription: 'Порівняйте умови обміну за вручну введеним базовим курсом, спредом і зборами. Під час продажу сума — кількість іноземної валюти; під час купівлі — бюджет у місцевих грошах. Курс завжди означає місцеві гроші за одну одиницю іноземної валюти. Якщо вводите вже запропонований обмінником курс, задайте спред 0%, щоб не врахувати його вдруге.',
    howToUse: ['Виберіть продаж або купівлю: підпис та одиниця суми зміняться.', 'Введіть базовий курс у місцевих грошах за одиницю іноземної валюти.', 'Задайте спред щодо цього базового курсу та відсоткову комісію.', 'Фіксований збір вводьте в місцевих грошах за обох напрямків. Порівняйте виплату та втрати щодо базового курсу.'],
    howItWorks: 'Позначимо суму A, базовий курс r, частку спреду s, частку комісії c та фіксований збір F у місцевих грошах; відсотки діляться на 100. Продаж: Q = A × r × (1 − s) × (1 − c) − F. Купівля: Q = (A − F) × (1 − c) / [r × (1 + s)]. Під час купівлі збір спочатку зменшує бюджет, а комісія береться із залишку. Це заявлений порядок моделі, а не загальне правило банків. Втрати — різниця між A × r (продаж) або A / r (купівля) та Q. Грошові рядки зазвичай округлюються окремо до двох знаків; без спреду та зборів виплата дорівнює базовому обміну.',
    example: 'Навчальні умови: базовий курс 2 місцеві одиниці за іноземну, спред 10%, комісія 5%, збір 20 місцевих одиниць. Продаж 1000: 1000 × 2 × 0,9 = 1800; комісія 90; виплата 1800 − 90 − 20 = 1690 ₴, втрати 310 / 2000 = 15,5%. Купівля на бюджет 2000: (2000 − 20) × 0,95 / 2,2 = 855 одиниць валюти, втрати 145 / 1000 = 14,5%. Це не поточний ринковий курс.',
    faq: [
      { q: 'Який курс вводити, щоб не врахувати спред двічі?', a: 'Введіть базовий курс до спреда. Якщо знаєте лише кінцевий курс обмінника, використайте його зі спредом 0%; тоді втрати порівнюються саме з цим введеним курсом.' },
      { q: 'У яких грошах вводиться фіксований збір?', a: 'У місцевих грошах і під час продажу, і під час купівлі. Для купівлі рядок результату переводить збір в іноземну валюту за курсом зі спредом, щоб порівняти його з виплатою.' },
      { q: 'Чому під час купівлі збір враховується в іншому порядку?', a: 'Продаж отримує місцеві гроші, з яких сплачується збір. Купівля спочатку платить збір із місцевого бюджету, а комісія застосовується до залишку. Договір з іншим порядком або валютою зборів потребує іншої моделі.' },
      { q: 'Чи може виплата бути від’ємною?', a: 'Ні: якщо збори перевищують доступну суму, показується помилка. Рівно нульова виплата допустима, коли збори поглинули всю суму; частка втрат тоді 100%.' },
      { q: 'Що не враховується автоматично?', a: 'Ринкові курси, податки, обмеження та плата за переказ не завантажуються. Додавати плату за переказ до F можна лише в тих самих місцевих грошах і за описаним порядком моделі.' },
    ],
    disclaimer: 'Навчальна модель вручну введених умов. Символ місцевих грошей не визначає країну, валютну пару чи правила договору. Перевіряйте валюту та порядок кожного збору у свого провайдера.',
  },
  de: {
    longDescription: 'Vergleiche Wechselbedingungen mit einem von dir eingegebenen Basiskurs, Spread und Gebühren. Beim Verkauf ist der Betrag Fremdwährung, beim Kauf ein Budget in örtlichem Geld. Der Kurs bedeutet immer örtliches Geld je Fremdwährungseinheit. Trägst du einen bereits angebotenen Endkurs ein, setze den Spread auf 0%, damit sein Aufschlag nicht zweimal zählt.',
    howToUse: ['Wähle Verkauf oder Kauf; Bezeichnung und Einheit des Betrags ändern sich.', 'Trage den Basiskurs in örtlichem Geld je Fremdwährungseinheit ein.', 'Trage den Spread gegenüber diesem Basiskurs und die prozentuale Gebühr ein.', 'Die feste Gebühr wird in beiden Richtungen in örtlichem Geld eingegeben. Vergleiche Auszahlung und Verlust gegenüber dem Basiskurs.'],
    howItWorks: 'A bezeichnet den Betrag, r den Basiskurs, s den Spreadanteil, c den Gebührenanteil und F die feste Gebühr in örtlichem Geld; Prozentwerte werden durch 100 geteilt. Verkauf: Q = A × r × (1 − s) × (1 − c) − F. Kauf: Q = (A − F) × (1 − c) / [r × (1 + s)]. Beim Kauf wird zuerst die feste Gebühr vom Budget abgezogen; die Prozentgebühr gilt für den Rest. Das ist die erklärte Modellreihenfolge, keine allgemeine Bankregel. Der Verlust ist A × r beim Verkauf beziehungsweise A / r beim Kauf, jeweils minus Q. Geldbeträge werden normalerweise einzeln auf zwei Dezimalstellen gerundet; ohne Spread und Gebühren entspricht die Auszahlung dem Basisumtausch.',
    example: 'Rechenbeispiel: Basiskurs 2 örtliche Einheiten je Fremdwährungseinheit, Spread 10%, Gebühr 5%, Festgebühr 20 örtliche Einheiten. Verkauf von 1000: 1000 × 2 × 0,9 = 1800; Gebühr 90; Auszahlung 1800 − 90 − 20 = 1690 €, Verlust 310 / 2000 = 15,5%. Kauf mit Budget 2000: (2000 − 20) × 0,95 / 2,2 = 855 Währungseinheiten, Verlust 145 / 1000 = 14,5%. Dies ist kein aktueller Marktkurs.',
    faq: [
      { q: 'Welcher Kurs verhindert einen doppelt berechneten Spread?', a: 'Trage den Basiskurs vor dem Spread ein. Kennst du nur einen endgültig angebotenen Kurs, verwende ihn mit 0% Spread; der Verlustvergleich bezieht sich dann auf diesen eingegebenen Kurs.' },
      { q: 'In welcher Währung steht die feste Gebühr?', a: 'In örtlichem Geld, beim Verkauf und beim Kauf. Beim Kauf rechnet die Ergebniszeile die Gebühr zum Kurs mit Spread in Fremdwährung um, damit sie mit der Auszahlung vergleichbar ist.' },
      { q: 'Warum wird die feste Gebühr beim Kauf zuerst abgezogen?', a: 'Ein Verkauf erhält örtliches Geld und bezahlt daraus die feste Gebühr. Ein Kauf bezahlt sie zuerst aus dem örtlichen Budget; die Prozentgebühr gilt für den Rest. Ein Vertrag mit anderer Reihenfolge oder Gebührenwährung braucht ein anderes Modell.' },
      { q: 'Kann die Auszahlung negativ sein?', a: 'Nein. Übersteigen die Gebühren den verfügbaren Betrag, erscheint ein Fehler. Eine Auszahlung von genau null ist zulässig, wenn die Gebühren alles verbrauchen; der Verlustanteil beträgt dann 100%.' },
      { q: 'Welche Daten und Kosten werden nicht automatisch berücksichtigt?', a: 'Marktkurse, Steuern, Einschränkungen und Überweisungsgebühren werden nicht geladen. Eine Überweisungsgebühr darf nur zu F addiert werden, wenn sie in demselben örtlichen Geld und in der beschriebenen Reihenfolge erhoben wird.' },
    ],
    disclaimer: 'Rechenmodell für selbst eingegebene Bedingungen. Das örtliche Geldsymbol legt kein Land, Währungspaar oder Vertragsregeln fest. Prüfe Währung und Reihenfolge jeder Gebühr bei deinem Anbieter.',
  },
  es: {
    longDescription: 'Compara las condiciones de cambio con un tipo base, diferencial y cargos introducidos por ti. Al vender, el importe es divisa; al comprar, es un presupuesto en moneda local. El tipo siempre significa moneda local por una unidad de divisa. Si introduces un tipo final ya ofrecido, fija el diferencial en 0% para no contar dos veces su margen.',
    howToUse: ['Elige venta o compra; cambian la etiqueta y la unidad del importe.', 'Introduce el tipo base en moneda local por una unidad de divisa.', 'Introduce el diferencial respecto a ese tipo base y la comisión porcentual.', 'El cargo fijo se introduce en moneda local en ambos sentidos. Compara lo recibido y la pérdida respecto al tipo base.'],
    howItWorks: 'A es el importe, r el tipo base, s la fracción del diferencial, c la fracción de comisión y F el cargo fijo en moneda local; los porcentajes se dividen entre 100. Venta: Q = A × r × (1 − s) × (1 − c) − F. Compra: Q = (A − F) × (1 − c) / [r × (1 + s)]. Al comprar, primero se resta el cargo fijo del presupuesto y la comisión se aplica al resto. Es el orden declarado del modelo, no una regla de todos los bancos. La pérdida es A × r al vender o A / r al comprar, menos Q. Los importes suelen redondearse por separado a dos decimales; sin diferencial ni cargos, lo recibido coincide con el cambio base.',
    example: 'Ejemplo didáctico: tipo base 2 unidades locales por unidad de divisa, diferencial 10%, comisión 5% y cargo fijo 20 unidades locales. Venta de 1000: 1000 × 2 × 0,9 = 1800; comisión 90; recibes 1800 − 90 − 20 = 1690 €, pérdida 310 / 2000 = 15,5%. Compra con presupuesto 2000: (2000 − 20) × 0,95 / 2,2 = 855 unidades de divisa, pérdida 145 / 1000 = 14,5%. No es un tipo de mercado actual.',
    faq: [
      { q: '¿Qué tipo evita contar dos veces el diferencial?', a: 'Introduce el tipo base anterior al diferencial. Si solo conoces un tipo final ofrecido, úsalo con un diferencial de 0%; la comparación de pérdidas tendrá ese tipo como base.' },
      { q: '¿En qué moneda se introduce el cargo fijo?', a: 'En moneda local, tanto al vender como al comprar. Al comprar, la fila del resultado convierte el cargo en divisa con el tipo que incluye el diferencial, para compararlo con lo recibido.' },
      { q: '¿Por qué se resta primero el cargo fijo al comprar?', a: 'La venta recibe moneda local y de ahí paga el cargo fijo. La compra lo paga primero del presupuesto local y aplica la comisión al resto. Un contrato con otro orden o moneda de cargos necesita otro modelo.' },
      { q: '¿Puede ser negativo el importe recibido?', a: 'No. Si los cargos superan el importe disponible, aparece un error. Se admite un resultado de cero cuando los cargos consumen todo; la proporción de pérdida es entonces 100%.' },
      { q: '¿Qué datos y gastos no se incluyen automáticamente?', a: 'No se cargan cotizaciones de mercado, impuestos, restricciones ni cargos por transferencias. Solo añade un cargo de transferencia a F si se cobra en la misma moneda local y siguiendo el orden del modelo.' },
    ],
    disclaimer: 'Modelo didáctico de condiciones introducidas por ti. El símbolo de moneda local no establece un país, par de divisas ni reglas contractuales. Consulta con tu proveedor la moneda y el orden de cada cargo.',
  },
};
