import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  en: {
    fields: {
      "direction": "What you are doing",
      "amount": "Amount to exchange",
      "rate": "Exchange rate",
      "spreadPct": "Spread on the rate, %",
      "feePct": "Commission, %",
      "feeFixed": "Flat charge",
    },
    options: {
      "sell": "selling currency for local money",
      "buy": "buying currency with local money",
    },
    results: {
      "К получению": "You receive",
      "Курс с учётом спреда": "Rate after the spread",
      "По номинальному курсу": "At the nominal rate",
      "Комиссия": "Commission",
      "Фиксированный сбор": "Flat charge",
      "Потери на спреде": "Lost to the spread",
      "Полная стоимость обмена": "Total cost of the exchange",
      "Доля потерь": "Share of loss",
      "Проверьте данные": "Check the values",
    },
    values: {
      "₽": "$",
      "ед. валюты": "currency units",
      "Сумма должна быть больше нуля": "The amount must be greater than zero",
      "Курс должен быть больше нуля": "The rate must be greater than zero",
      "Комиссия и спред не могут быть отрицательными": "Commission and spread cannot be negative",
      "Комиссия должна быть меньше 100 %": "The commission must be below 100%",
      "Спред должен быть меньше 100 %": "The spread must be below 100%",
    },
  },
  uk: {
    fields: {
      "direction": "Що робимо",
      "amount": "Сума обміну",
      "rate": "Курс обміну",
      "spreadPct": "Спред до курсу, %",
      "feePct": "Комісія, %",
      "feeFixed": "Фіксований збір",
    },
    options: {
      "sell": "продаємо валюту за гривні",
      "buy": "купуємо валюту за гривні",
    },
    results: {
      "К получению": "До отримання",
      "Курс с учётом спреда": "Курс з урахуванням спреду",
      "По номинальному курсу": "За номінальним курсом",
      "Комиссия": "Комісія",
      "Фиксированный сбор": "Фіксований збір",
      "Потери на спреде": "Втрати на спреді",
      "Полная стоимость обмена": "Повна вартість обміну",
      "Доля потерь": "Частка втрат",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "₽": "₴",
      "ед. валюты": "од. валюти",
      "Сумма должна быть больше нуля": "Сума має бути більшою за нуль",
      "Курс должен быть больше нуля": "Курс має бути більшим за нуль",
      "Комиссия и спред не могут быть отрицательными": "Комісія і спред не можуть бути від'ємними",
      "Комиссия должна быть меньше 100 %": "Комісія має бути меншою за 100 %",
      "Спред должен быть меньше 100 %": "Спред має бути меншим за 100 %",
    },
  },
  de: {
      fields: {
        'direction': 'Was du vorhast',
        'amount': 'Umzutauschender Betrag',
        'rate': 'Wechselkurs',
        'spreadPct': 'Spread auf den Kurs, %',
        'feePct': 'Gebühr, %',
        'feeFixed': 'Festbetrag',
      },
      options: {
        'sell': 'Währung verkaufen',
        'buy': 'Währung kaufen',
      },
      results: {
        'К получению': 'Auszahlung',
        'Курс с учётом спреда': 'Kurs nach Spread',
        'По номинальному курсу': 'Zum Nominalkurs',
        'Комиссия': 'Gebühr',
        'Потери на спреде': 'Verlust durch den Spread',
        'Полная стоимость обмена': 'Gesamtkosten des Umtauschs',
        'Доля потерь': 'Anteil der Kosten',
        'Проверьте данные': 'Prüfe die Werte',
              'Фиксированный сбор': 'Feste Gebühr',
      },
      values: {
        '₽': '€',
        'ед. валюты': 'Währungseinheiten',
        'Сумма должна быть больше нуля': 'Der Betrag muss größer als null sein',
        'Курс должен быть больше нуля': 'Der Kurs muss größer als null sein',
        'Комиссия и спред не могут быть отрицательными': 'Gebühr und Spread dürfen nicht negativ sein',
        'Комиссия должна быть меньше 100 %': 'Die Gebühr muss unter 100 % liegen',
        'Спред должен быть меньше 100 %': 'Der Spread muss unter 100 % liegen',
      },
  },
  es: {
    fields: {
      "direction": "Qué vas a hacer",
      "amount": "Importe a cambiar",
      "rate": "Tipo de cambio",
      "spreadPct": "Diferencial sobre el tipo, %",
      "feePct": "Comisión, %",
      "feeFixed": "Cargo fijo",
    },
    options: {
      "sell": "vender divisa a cambio de moneda local",
      "buy": "comprar divisa con moneda local",
    },
    results: {
      "К получению": "Recibes",
      "Курс с учётом спреда": "Tipo con el diferencial aplicado",
      "По номинальному курсу": "Al tipo nominal",
      "Комиссия": "Comisión",
      "Фиксированный сбор": "Cargo fijo",
      "Потери на спреде": "Pérdida por el diferencial",
      "Полная стоимость обмена": "Coste total del cambio",
      "Доля потерь": "Porcentaje de pérdida",
      "Проверьте данные": "Revisa los datos",
    },
    values: {
      "₽": "€",
      "ед. валюты": "unidades de divisa",
      "Сумма должна быть больше нуля": "El importe debe ser mayor que cero",
      "Курс должен быть больше нуля": "El tipo de cambio debe ser mayor que cero",
      "Комиссия и спред не могут быть отрицательными": "Ni la comisión ni el diferencial pueden ser negativos",
      "Комиссия должна быть меньше 100 %": "La comisión debe ser inferior al 100 %",
      "Спред должен быть меньше 100 %": "El diferencial debe ser inferior al 100 %",
    },
  },
};
