import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  en: {
    fields: {
      "mode": "What is known",
      "unit": "Length unit",
      "a": "Leg a",
      "b": "Leg b",
      "c": "Hypotenuse",
    },
    options: {
      mm: "millimetres",
      cm: "centimetres",
      m: "metres",
      "legs": "two legs",
      "legHyp": "a leg and the hypotenuse",
    },
    results: {
      "Гипотенуза": "Hypotenuse",
      "Второй катет": "Missing leg",
      "Площадь": "Area",
      "Периметр": "Perimeter",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Катеты должны быть больше нуля": "The legs must be greater than zero",
      "Катет и гипотенуза должны быть больше нуля": "The leg and the hypotenuse must be greater than zero",
      "Гипотенуза должна быть длиннее катета": "The hypotenuse must be longer than the leg",
      "Значение слишком велико для расчёта": "The value is too large to calculate",
    },
  },
  uk: {
    fields: {
      "mode": "Що відомо",
      "unit": "Одиниця довжини",
      "a": "Катет a",
      "b": "Катет b",
      "c": "Гіпотенуза",
    },
    options: {
      mm: "міліметри",
      cm: "сантиметри",
      m: "метри",
      "legs": "два катети",
      "legHyp": "катет і гіпотенуза",
    },
    results: {
      "Гипотенуза": "Гіпотенуза",
      "Второй катет": "Другий катет",
      "Площадь": "Площа",
      "Периметр": "Периметр",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Катеты должны быть больше нуля": "Катети мають бути більшими за нуль",
      "Катет и гипотенуза должны быть больше нуля": "Катет і гіпотенуза мають бути більшими за нуль",
      "Гипотенуза должна быть длиннее катета": "Гіпотенуза має бути довшою за катет",
      "Значение слишком велико для расчёта": "Значення завелике для розрахунку",
    },
  },
};
