import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  en: {
    fields: {
      "mode": "What is known",
      "unit": "Length unit",
      "a": "First side",
      "b": "Second side",
      "area": "Area",
    },
    options: {
      mm: "millimetres",
      cm: "centimetres",
      m: "metres",
      "sides": "both sides",
      "areaSide": "the area and one side",
    },
    results: {
      "Площадь": "Area",
      "Первая сторона": "First side",
      "Вторая сторона": "Second side",
      "Периметр": "Perimeter",
      "Диагональ": "Diagonal",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Обе стороны должны быть больше нуля": "Both sides must be greater than zero",
      "Площадь должна быть больше нуля": "The area must be greater than zero",
      "Известная сторона должна быть больше нуля": "The known side must be greater than zero",
      "Значение слишком велико для расчёта": "The value is too large to calculate",
    },
  },
  uk: {
    fields: {
      "mode": "Що відомо",
      "unit": "Одиниця довжини",
      "a": "Перша сторона",
      "b": "Друга сторона",
      "area": "Площа",
    },
    options: {
      mm: "міліметри",
      cm: "сантиметри",
      m: "метри",
      "sides": "обидві сторони",
      "areaSide": "площа й одна сторона",
    },
    results: {
      "Площадь": "Площа",
      "Первая сторона": "Перша сторона",
      "Вторая сторона": "Друга сторона",
      "Периметр": "Периметр",
      "Диагональ": "Діагональ",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Обе стороны должны быть больше нуля": "Обидві сторони мають бути більшими за нуль",
      "Площадь должна быть больше нуля": "Площа має бути більшою за нуль",
      "Известная сторона должна быть больше нуля": "Відома сторона має бути більшою за нуль",
      "Значение слишком велико для расчёта": "Значення завелике для розрахунку",
    },
  },
};
