// СГЕНЕРИРОВАНО. Не редактировать руками.
// Общие фразы результата, отобранные под наследственный калькулятор mortgage-calculator.
// Перегенерировать: npm run calculators:generate

import type { CalculatorLocalization } from '../../../../lib/platform/types';

export const shared: CalculatorLocalization = {
  en: {
    results: {
      'Ежемесячный платеж': 'Monthly payment',
      'Общая сумма выплат': 'Total repayment',
      'Переплата': 'Overpayment',
      'Сумма процентов': 'Interest amount',
      'Срок': 'Term',
      'Проверьте данные': 'Check inputs',
      'Введите положительные значения': 'Enter positive values',
      'Сумма кредита': 'Loan amount',
      'Общая стоимость с взносом': 'Total cost with down payment',
      'Общая стоимость': 'Total cost',
      'В': 'To',
      'Последний платеж': 'Final payment',
      'Средний платеж': 'Average payment',
      'Первоначальный взнос': 'Down payment',
      'График первых платежей': 'Payment schedule',
      'Месяц': 'Month',
      'Платеж': 'Payment',
      'Основной долг': 'Principal',
      'Проценты': 'Interest',
      'Остаток': 'Balance',
      'Плановый платеж с доплатой': 'Planned payment with extra',
      'Разовая комиссия': 'One-time fee',
      'Сокращение срока': 'Term reduction',
      'Расход в месяц со страховкой': 'Monthly cost with insurance',
      'Страховка и расходы за срок': 'Insurance and costs over the term',
    },
    values: {
      'Выберите допустимый режим расчёта.': 'Choose a supported calculation mode.',
      'Срок должен составлять от 1 до 1200 целых месяцев.': 'The term must be between 1 and 1200 whole months.',
      'Расчёт выходит за пределы числовой точности. Уменьшите сумму, ставку или срок.': 'The calculation exceeds numerical precision. Reduce the amount, rate or term.',
      'Показан размер первого (наибольшего) платежа. Далее платёж снижается.': 'The first and largest payment is shown. Later payments gradually decrease.',
      'Показан размер первого (наибольшего) платежа.': 'The first and largest payment is shown.',
      'Показаны первые 12 месяцев и последний платеж.': 'The first 12 months and the final payment are shown.',
      'Введите положительные значения': 'Enter positive values',
      'Проценты': 'Percentages',
    },
  },
  uk: {
    results: {
      'Ежемесячный платеж': 'Щомісячний платіж',
      'Общая сумма выплат': 'Загальна сума виплат',
      'Переплата': 'Переплата',
      'Сумма процентов': 'Сума відсотків',
      'Срок': 'Строк',
      'Проверьте данные': 'Перевірте дані',
      'Сумма кредита': 'Сума кредиту',
      'Общая стоимость с взносом': 'Загальна вартість із внеском',
      'Общая стоимость': 'Загальна вартість',
      'В': 'У',
      'Последний платеж': 'Останній платіж',
      'Средний платеж': 'Середній платіж',
      'Первоначальный взнос': 'Перший внесок',
      'График первых платежей': 'Графік платежів',
      'Месяц': 'Місяць',
      'Платеж': 'Платіж',
      'Основной долг': 'Основний борг',
      'Проценты': 'Відсотки',
      'Остаток': 'Залишок',
      'Плановый платеж с доплатой': 'Плановий платіж із доплатою',
      'Разовая комиссия': 'Разова комісія',
      'Сокращение срока': 'Скорочення строку',
      'Расход в месяц со страховкой': 'Щомісячні витрати зі страхуванням',
      'Страховка и расходы за срок': 'Страхування та витрати за весь строк',
    },
    values: {
      'Выберите допустимый режим расчёта.': 'Оберіть допустимий режим розрахунку.',
      'Срок должен составлять от 1 до 1200 целых месяцев.': 'Строк має становити від 1 до 1200 цілих місяців.',
      'Расчёт выходит за пределы числовой точности. Уменьшите сумму, ставку или срок.': 'Розрахунок виходить за межі числової точності. Зменште суму, ставку або строк.',
      'Показан размер первого (наибольшего) платежа. Далее платёж снижается.': 'Показано перший і найбільший платіж. Наступні платежі поступово зменшуються.',
      'Показан размер первого (наибольшего) платежа.': 'Показано перший і найбільший платіж.',
      'Показаны первые 12 месяцев и последний платеж.': 'Показано перші 12 місяців і останній платіж.',
      'Введите положительные значения': 'Введіть додатні значення',
      'Проценты': 'Відсотки',
    },
  },
  de: {
    results: {
      'Ежемесячный платеж': 'Monatliche Rate',
      'Общая сумма выплат': 'Summe aller Zahlungen',
      'Переплата': 'Mehrkosten',
      'Сумма процентов': 'Zinsen insgesamt',
      'Срок': 'Laufzeit',
      'Проверьте данные': 'Prüfe die Werte',
      'Сумма кредита': 'Darlehensbetrag',
      'Общая стоимость с взносом': 'Gesamtkosten samt Anzahlung',
      'Общая стоимость': 'Gesamtkosten',
      'В': 'Nach',
      'Последний платеж': 'Letzte Rate',
      'Средний платеж': 'Durchschnittliche Rate',
      'Первоначальный взнос': 'Anzahlung',
      'График первых платежей': 'Plan der ersten Raten',
      'Месяц': 'Monat',
      'Платеж': 'Rate',
      'Основной долг': 'Tilgung',
      'Проценты': 'Zinsen',
      'Остаток': 'Restschuld',
      'Плановый платеж с доплатой': 'Rate samt Sondertilgung',
      'Разовая комиссия': 'Einmalige Gebühr',
      'Сокращение срока': 'Verkürzung der Laufzeit',
      'Расход в месяц со страховкой': 'Monatliche Ausgabe samt Versicherung',
      'Страховка и расходы за срок': 'Versicherung und Kosten über die Laufzeit',
    },
    values: {
      'Выберите допустимый режим расчёта.': 'Wähle eine unterstützte Rechenart.',
      'Срок должен составлять от 1 до 1200 целых месяцев.': 'Die Laufzeit muss zwischen 1 und 1200 ganzen Monaten liegen.',
      'Расчёт выходит за пределы числовой точности. Уменьшите сумму, ставку или срок.': 'Die Berechnung überschreitet die Zahlengenauigkeit. Verringere Betrag, Zinssatz oder Laufzeit.',
      'Показан размер первого (наибольшего) платежа. Далее платёж снижается.': 'Gezeigt ist die erste und höchste Rate. Danach sinkt die Rate allmählich.',
      'Показан размер первого (наибольшего) платежа.': 'Gezeigt ist die erste und höchste Rate.',
      'Показаны первые 12 месяцев и последний платеж.': 'Gezeigt sind die ersten 12 Monate und die letzte Rate.',
      'Введите положительные значения': 'Trage positive Werte ein',
      'Проценты': 'Prozent',
    },
  },
  es: {
    results: {
      'Ежемесячный платеж': 'Cuota mensual',
      'Общая сумма выплат': 'Total a devolver',
      'Переплата': 'Coste adicional',
      'Сумма процентов': 'Total de intereses',
      'Срок': 'Plazo',
      'Проверьте данные': 'Revisa los datos',
      'Введите положительные значения': 'Introduce valores positivos',
      'Сумма кредита': 'Importe del préstamo',
      'Общая стоимость с взносом': 'Coste total con la entrada',
      'Общая стоимость': 'Coste total',
      'В': 'A',
      'Последний платеж': 'Última cuota',
      'Средний платеж': 'Cuota media',
      'Первоначальный взнос': 'Entrada',
      'График первых платежей': 'Cuadro de las primeras cuotas',
      'Месяц': 'Mes',
      'Платеж': 'Cuota',
      'Основной долг': 'Capital amortizado',
      'Проценты': 'Intereses',
      'Остаток': 'Pendiente',
      'Плановый платеж с доплатой': 'Cuota prevista con amortización adicional',
      'Разовая комиссия': 'Comisión única',
      'Сокращение срока': 'Reducción del plazo',
      'Расход в месяц со страховкой': 'Gasto mensual con seguro',
      'Страховка и расходы за срок': 'Seguro y gastos del plazo',
    },
    values: {
      'Выберите допустимый режим расчёта.': 'Elige un modo de cálculo válido.',
      'Срок должен составлять от 1 до 1200 целых месяцев.': 'El plazo debe ser de entre 1 y 1200 meses completos.',
      'Расчёт выходит за пределы числовой точности. Уменьшите сумму, ставку или срок.': 'El cálculo supera la precisión numérica. Reduce el importe, el tipo o el plazo.',
      'Показан размер первого (наибольшего) платежа. Далее платёж снижается.': 'Se muestra el importe de la primera cuota, la mayor. Después la cuota va bajando.',
      'Показан размер первого (наибольшего) платежа.': 'Se muestra el importe de la primera cuota, la mayor.',
      'Показаны первые 12 месяцев и последний платеж.': 'Se muestran los 12 primeros meses y la última cuota.',
      'Введите положительные значения': 'Introduce valores positivos',
    },
  },
};
