import { expect, test, type Page } from '@playwright/test';
import { cases, locales, type BrowserCase, type Locale, type Values } from './originality-business-wave-9.fixtures';

// Browser-only evidence: no MAIN registry/runtime imports and no calculated oracle.
// The app's clipboard argument supplies the copied URL; tests do not substitute
// their query constructor for the application's serialization.
const viewports=[{width:390,height:844},{width:1365,height:900}]as const;
const money:Record<Locale,string>={ru:'₽',en:'$',uk:'₴',de:'€',es:'€'};
const turns:Record<Locale,string>={ru:'раз',en:'times',uk:'разів',de:'mal',es:'veces'};
const hours:Record<Locale,string>={ru:'ч',en:'h',uk:'год',de:'h',es:'h'};
const takt:Record<Locale,string>={ru:'мин/шт',en:'min/unit',uk:'хв/шт',de:'min/Stk',es:'min/ud.'};
const leak=/\b(?:NaN|Infinity|undefined)\b/;
const foreign=/[А-Яа-яЁёІіЇїЄєҐґ]/;
const unrelated='not-a-calculator-field';
function numeric(text:string,locale:Locale){const token=text.match(/[-−]?\d[\d\s\u00a0\u202f.,]*/)?.[0];if(!token)return NaN;const raw=token.replace(/[\s\u00a0\u202f]/g,'').replace('−','-');return Number(locale==='en'?raw.replaceAll(',',''):raw.replaceAll('.','').replace(',','.'));}
function url(sample:BrowserCase,locale:Locale,values:Values){for(const key of Object.keys(values))if(!sample.fieldNames.includes(key)&&key!==unrelated)throw new Error(`Unknown fixture key ${key}`);return`${sample.pages[locale].path}?${new URLSearchParams(Object.entries(values).map(([k,v])=>[k,String(v)]))}`;}
async function primary(page:Page,locale:Locale,value:number){await expect(page.getByTestId('calc-result-primary')).toBeVisible();await expect.poll(async()=>numeric((await page.getByTestId('calc-result-primary').allTextContents())[0]??'',locale)).toBeCloseTo(value,3);}
async function rows(page:Page,locale:Locale,values:readonly number[]){for(const[index,value]of values.entries())await expect.poll(async()=>numeric((await page.getByTestId(`calc-result-row-${index}`).locator('dd').allTextContents())[0]??'',locale)).toBeCloseTo(value,3);}
async function fields(page:Page,sample:BrowserCase,values:Values,inactive:readonly string[]){for(const name of sample.fieldNames){const field=page.getByTestId(`field-${name}`);if(inactive.includes(name))await expect(field).toHaveCount(0);else{await expect(field).toBeVisible();if(name in values)await expect(field).toHaveValue(String(values[name]));}}}
async function native(page:Page,locale:Locale){const text=await page.getByTestId('calc-result-wrap').innerText();expect(text).not.toMatch(leak);if(['en','de','es'].includes(locale))expect(text).not.toMatch(foreign);}
async function failure(page:Page,locale:Locale){await expect.poll(async()=>await page.locator('[data-testid^="field-error-"]:visible').count()>0||(await page.getByTestId('calc-result-primary').allTextContents()).some(v=>v.trim()==='—')).toBe(true);if(await page.locator('[data-testid^="field-error-"]:visible').count()){await expect(page.getByTestId('calc-result-invalid')).toBeVisible();await expect(page.getByTestId('calc-result-primary')).toHaveCount(0);}const text=[await page.getByTestId('calc-result-wrap').innerText(),...await page.locator('[data-testid^="field-error-"]:visible').allTextContents()].join('\n');expect(text).not.toMatch(leak);if(['en','de','es'].includes(locale))expect(text).not.toMatch(foreign);}
async function layout(page:Page,sample:BrowserCase,width:number,inactive:readonly string[]){expect(await page.evaluate(()=>Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)<=window.innerWidth+1)).toBe(true);for(const name of sample.fieldNames.filter(name=>!inactive.includes(name))){const box=await page.getByTestId(`field-${name}`).boundingBox();expect(box).not.toBeNull();expect(box!.x).toBeGreaterThanOrEqual(-1);expect(box!.x+box!.width).toBeLessThanOrEqual(width+1);}for(const id of ['calc-form','calc-result-wrap']){const box=await page.getByTestId(id).boundingBox();expect(box).not.toBeNull();expect(box!.width).toBeGreaterThan(100);expect(box!.x).toBeGreaterThanOrEqual(-1);expect(box!.x+box!.width).toBeLessThanOrEqual(width+1);}}
async function units(page:Page,sample:BrowserCase,locale:Locale){for(const field of sample.moneyFields.filter(name=>!sample.inactive.includes(name)))await expect(page.getByTestId(`field-label-${field}`)).toContainText(`(${money[locale]})`);const symbol=sample.primaryUnit==='money'?money[locale]:sample.primaryUnit==='percent'?'%':sample.primaryUnit==='turns'?turns[locale]:sample.primaryUnit==='hours'?hours[locale]:takt[locale];await expect(page.getByTestId('calc-result-primary')).toContainText(symbol);for(const index of sample.moneyRows)await expect(page.getByTestId(`calc-result-row-${index}`).locator('dd')).toContainText(money[locale]);}
async function body(page:Page,sample:BrowserCase,locale:Locale){const copy=sample.pages[locale];await expect(page.locator('h1')).toHaveText(copy.h1);for(const text of [copy.longDescription,...copy.howToUse,copy.howItWorks,copy.example])await expect(page.locator('main')).toContainText(text);await expect(page.getByTestId('calc-form')).toContainText(copy.disclaimer);const faq=page.getByTestId('calculator-faq');await expect(faq.locator('details')).toHaveCount(copy.faq.length);for(const[index,item]of copy.faq.entries()){await expect(faq.getByTestId(`faq-item-${index}`).locator('summary')).toContainText(item.q);await expect(faq.getByTestId(`faq-item-${index}`).locator('p')).toHaveText(item.a);}for(const source of copy.sources)await expect(page.locator('main').locator(`a[href="${source}"]`)).toBeVisible();}
async function captureShare(page:Page){await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{(window as Window&{business9Share?:string}).business9Share=text;}}}));}
async function copied(page:Page,sample:BrowserCase,locale:Locale,values:Values,inactive:readonly string[]){await page.evaluate(()=>{delete(window as Window&{business9Share?:string}).business9Share;});await page.getByTestId('calc-share-btn').click();await expect(page.getByTestId('calc-share-warning')).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>(window as Window&{business9Share?:string}).business9Share??'')).not.toBe('');const raw=await page.evaluate(()=>(window as Window&{business9Share?:string}).business9Share!);const actual=new URL(raw);expect(actual.origin).toBe(new URL(page.url()).origin);expect(actual.pathname).toBe(sample.pages[locale].path);expect(actual.hash).toBe('#calculator');const expected=Object.fromEntries(Object.entries(values).filter(([key,value])=>key!==unrelated&&!inactive.includes(key)&&value!==sample.defaults[key]).map(([key,value])=>[key,String(value)]));expect(Object.fromEntries(actual.searchParams)).toEqual(expected);for(const key of [...inactive,unrelated])expect(actual.searchParams.has(key)).toBe(false);return raw;}

for(const viewport of viewports)for(const sample of cases)for(const locale of locales)test.describe(`${viewport.width}px ${locale} ${sample.id}`,()=>{
 test.use({viewport});
 test('fixed independent model, native60body, units, actual clipboard, reload and reset',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await captureShare(page);await page.goto(url(sample,locale,{...sample.inputs,[unrelated]:'ignored'}));
  await primary(page,locale,sample.expected);await rows(page,locale,sample.rows);await fields(page,sample,sample.inputs,sample.inactive);await native(page,locale);await body(page,sample,locale);await units(page,sample,locale);await layout(page,sample,viewport.width,sample.inactive);
  if(['en','de','es'].includes(locale))await expect(page.getByTestId('calc-form')).not.toContainText(foreign);
  await expect(page.getByTestId('calc-result').locator('[data-testid^="calc-result-row-"]')).toHaveCount(sample.rowCount);
  if(sample.id==='timesheet-week'){const cells=page.locator('main table tbody tr').first().locator('td');await expect(cells.nth(0)).toHaveText('22:00');await expect(cells.nth(1)).toHaveText('06:00');await expect(cells.nth(2)).toHaveText('30');await expect.poll(async()=>numeric(await cells.nth(3).innerText(),locale)).toBe(7.5);const minuteUnit=locale==='ru'?'мин':locale==='uk'?'хв':'min';await expect(page.getByTestId('calc-result-row-1').locator('dd')).toHaveText(`7 ${hours[locale]} 30 ${minuteUnit}`);}
  const shared=await copied(page,sample,locale,sample.inputs,sample.inactive);expect(new URL(shared).search).not.toBe('');await page.goto(shared);await primary(page,locale,sample.expected);await rows(page,locale,sample.rows);await page.reload();await primary(page,locale,sample.expected);await fields(page,sample,sample.inputs,sample.inactive);
  await page.getByTestId('calc-reset-btn').click();await primary(page,locale,sample.defaultExpected);expect(new URL(page.url()).search).toBe('');const defaultInactive=sample.id==='inventory-turnover'?['beginInventory','endInventory']:[];await fields(page,sample,sample.defaults,defaultInactive);await page.reload();await primary(page,locale,sample.defaultExpected);const defaultLink=await copied(page,sample,locale,sample.defaults,defaultInactive);expect(new URL(defaultLink).search).toBe('');expect(errors).toEqual([]);
 });
 test('active malformed/domain recovery, exact counts, scoped omissions and independent boundary',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await captureShare(page);await page.goto(url(sample,locale,sample.inputs));await primary(page,locale,sample.expected);
  const required=page.getByTestId(`field-${sample.blankField}`);await required.fill('');await expect(page.getByTestId(`field-error-${sample.blankField}`)).toBeVisible();await failure(page,locale);await required.fill('broken-value');await expect(page.getByTestId(`field-error-${sample.blankField}`)).toBeVisible();await failure(page,locale);await required.fill(String(sample.inputs[sample.blankField]));await primary(page,locale,sample.expected);
  await page.getByTestId(`field-${sample.domainField}`).fill(String(sample.domainInvalid));await failure(page,locale);await page.goto(url(sample,locale,{...sample.inputs,[sample.domainField]:sample.domainInvalid}));await failure(page,locale);await page.reload();await failure(page,locale);await page.getByTestId(`field-${sample.domainField}`).fill(String(sample.inputs[sample.domainField]));await primary(page,locale,sample.expected);
  for(const countField of sample.countFields){const raw=locale==='de'||locale==='es'?'1,00000000000000001':'1.00000000000000001';await page.getByTestId(`field-${countField}`).fill(raw);await expect(page.getByTestId(`field-error-${countField}`)).toBeVisible();await failure(page,locale);await page.getByTestId(`field-${countField}`).fill(String(sample.inputs[countField]));await primary(page,locale,sample.expected);}
  if(sample.countFields.length){const countField=sample.countFields[0];const raw='1.00000000000000001e0';await page.goto(url(sample,locale,{...sample.inputs,[countField]:raw}));await failure(page,locale);await expect(page.getByTestId(`field-${countField}`)).toHaveValue(raw);await page.reload();await failure(page,locale);await expect(page.getByTestId(`field-${countField}`)).toHaveValue(raw);}
  if(sample.optionalAmount){await page.goto(url(sample,locale,sample.inputs));await primary(page,locale,sample.expected);await page.getByTestId(`field-${sample.optionalAmount}`).fill('');await primary(page,locale,sample.expected);await expect(page.locator('[data-testid^="field-error-"]:visible')).toHaveCount(0);const link=await copied(page,sample,locale,{...sample.inputs,[sample.optionalAmount]:''},sample.inactive);expect(new URL(link).searchParams.has(sample.optionalAmount)).toBe(true);expect(new URL(link).searchParams.get(sample.optionalAmount)).toBe('');await page.goto(link);await primary(page,locale,sample.expected);await expect(page.getByTestId(`field-${sample.optionalAmount}`)).toHaveValue('');}
  await page.goto(url(sample,locale,sample.boundary.inputs));await primary(page,locale,sample.boundary.expected);await rows(page,locale,sample.boundary.rows);await fields(page,sample,sample.boundary.inputs,sample.boundary.inactive);await expect(page.getByTestId('calc-result').locator('[data-testid^="calc-result-row-"]')).toHaveCount(sample.boundary.rowCount);await native(page,locale);await layout(page,sample,viewport.width,sample.boundary.inactive);
  if(sample.id==='timesheet-week'){await page.getByTestId('field-lines').fill('09:00,18:00,1.00000000000000001');await failure(page,locale);await page.getByTestId('field-lines').fill(String(sample.boundary.inputs.lines));await primary(page,locale,0);}
  const boundaryLink=await copied(page,sample,locale,sample.boundary.inputs,sample.boundary.inactive);await page.goto(boundaryLink);await primary(page,locale,sample.boundary.expected);await page.reload();await primary(page,locale,sample.boundary.expected);
  if(sample.id==='inventory-turnover'){await page.goto(url(sample,locale,{...sample.boundary.inputs,mode:'not-a-mode'}));await primary(page,locale,4);await expect(page.getByTestId('field-mode')).toHaveValue('direct');await fields(page,sample,sample.boundary.inputs,sample.boundary.inactive);}
  expect(errors).toEqual([]);
 });
});
