import{test,expect,type Page}from '@playwright/test';
import fixture from '../reports/originality-wave-8-tail-browser-fixtures.json' with{type:'json'};
type Locale='ru'|'en'|'uk'|'de'|'es';
const numeric=(s:string,l:Locale)=>{const raw=s.trim().replace(/[\s\u00a0\u202f]/g,'').match(/^[+-]?\d+(?:[.,]\d+)*(?:·10\^[+-]?\d+)?/)?.[0];if(!raw)throw Error('Missing number:'+s);return Number((l==='en'?raw.replaceAll(',',''):raw.replace(',','.')).replace('·10^','e'));};
const record=(id:string,l:string)=>fixture.actualPageRecords.find(p=>p.id===id&&p.locale===l)!;
async function clean(page:Page,l:Locale){const text=(await page.getByTestId('calc-result-wrap').allTextContents()).join(' ');expect(text).not.toMatch(/NaN|Infinity|undefined/);if(['en','de','es'].includes(l))expect(text).not.toMatch(/[А-Яа-яЁёІіЇїЄє]/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}
async function verify(page:Page,s:typeof fixture.independentSamples[number],locale:Locale){const result=page.getByTestId('calc-result-primary');if(s.kind==='number'||s.kind==='pay'){await expect.poll(async()=>{const n=numeric(await result.innerText(),locale);return Math.abs(n/Number(s.expected)-1);}).toBeLessThanOrEqual(s.tolerance);if(s.kind==='pay'){const row=page.locator('[data-testid^="calc-result-row-"] dd').filter({hasText:{ru:'ден. ед.',en:'currency units',uk:'гр. од.',de:'Geldeinheiten',es:'unidades monetarias'}[locale]});await expect.poll(async()=>numeric(await row.innerText(),locale)).toBe(84000);await expect(row).toContainText({ru:'ден. ед.',en:'currency units',uk:'гр. од.',de:'Geldeinheiten',es:'unidades monetarias'}[locale]);}}else if(s.kind==='clock'||s.kind==='date')await expect(result).toHaveText(String(s.expected));else if(s.kind==='age')await expect(result).toHaveText(/^36\D+1\D+0\D*$/);else if(s.kind==='duration')await expect(result).toHaveText(/^8\D+30\D*$/);else if(s.kind==='leap'){await expect(result).toHaveText({ru:'Нет',en:'No',uk:'Ні',de:'Nein',es:'No'}[locale]);await expect(page.getByTestId('calc-result-row-0').locator('dd')).toHaveText('365');}}
async function share(page:Page,sensitive=false){await page.evaluate(()=>(window as unknown as{wave8Link:string}).wave8Link='');await page.getByTestId('calc-share-btn').click();if(sensitive){await expect(page.getByTestId('calc-share-warning')).toBeVisible();expect(await page.evaluate(()=>(window as unknown as{wave8Link:string}).wave8Link)).toBe('');await page.getByTestId('calc-share-confirm').click();}await expect.poll(()=>page.evaluate(()=>(window as unknown as{wave8Link:string}).wave8Link)).not.toBe('');const u=new URL(await page.evaluate(()=>(window as unknown as{wave8Link:string}).wave8Link));expect(u.origin).toBe(new URL(page.url()).origin);expect(u.pathname).toBe(new URL(page.url()).pathname);expect(u.hash).toBe('#calculator');return u;}
test.beforeEach(async({context})=>{await context.route('**/*',r=>{const u=new URL(r.request().url());return ['127.0.0.1','localhost','::1'].includes(u.hostname)||['data:','blob:'].includes(u.protocol)?r.continue():r.abort();});await context.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(t:string)=>{(window as unknown as{wave8Link:string}).wave8Link=t;}}}));});
for(const s of fixture.independentSamples)for(const width of[390,1365])test(`wave8tail ${s.id}/${s.locale}/${width} independent result native unit blank and share reload`,async({page})=>{const locale=s.locale as Locale;const p=record(s.id,locale);const query=new URLSearchParams(Object.entries(s.input).map(([k,v])=>[k,String(v)]));const url=p.url+'?'+query;await page.setViewportSize({width,height:900});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await verify(page,s,locale);await expect(page.locator('h1')).toHaveText(p.h1);await clean(page,locale);const link=await share(page,p.group==='finance');await page.goto(link.href);await verify(page,s,locale);await page.reload();await verify(page,s,locale);
 if(s.id==='resistor-color'){const select=page.getByTestId('field-b1');await select.evaluate(e=>{const o=document.createElement('option');o.value='toString';o.textContent='unsupported QA';e.appendChild(o);});await select.selectOption('toString');await expect(page.getByTestId('calc-result-primary')).toHaveText('—');}else{const input=page.locator('input[data-testid^="field-"]').first();await expect(input).toBeVisible();await input.fill('');await expect(input).toHaveAttribute('aria-invalid','true');await expect(page.getByTestId('calc-result')).toHaveCount(0);}
 await clean(page,locale);await page.goto(url);await verify(page,s,locale);expect(errors).toEqual([]);
});
for(const locale of['ru','en','uk','de','es']as const)for(const [mode,expected,hidden]of[['add','11:30','endHour'],['subtract','06:30','endHour']]as const)test(`wave8tail duration/${locale}/${mode} secondary mode hides end clock`,async({page})=>{const url=record('time-duration',locale).url+'?'+new URLSearchParams({mode,startHour:'9',startMinute:'0',spanHour:'2',spanMinute:'30'});await page.goto(url);await expect(page.getByTestId('calc-result-primary')).toHaveText(expected);await expect(page.getByTestId('field-'+hidden)).toHaveCount(0);const link=await share(page);expect(link.searchParams.has(hidden)).toBe(false);await page.goto(link.href);await expect(page.getByTestId('calc-result-primary')).toHaveText(expected);await clean(page,locale);});
