import {test,expect,type Page} from '@playwright/test';
import fixture from '../reports/originality-building-wave-17-browser-fixtures.json' with {type:'json'};
type Locale='ru'|'en'|'uk'|'de'|'es';
const numeric=(s:string,l:Locale)=>{const raw=s.trim().replace(/[\s\u00a0\u202f]/g,'').match(/^[+-]?\d+(?:[.,]\d+)*(?:·10\^[+-]?\d+)?/)?.[0];if(!raw)throw Error('Missing number:'+s);return Number((l==='en'?raw.replaceAll(',',''):raw.replace(',','.')).replace('·10^','e'));};
const query=(input:Record<string,unknown>)=>new URLSearchParams(Object.entries(input).map(([k,v])=>[k,String(v)]));
async function clean(page:Page,l:Locale){const text=(await page.getByTestId('calc-result-wrap').allTextContents()).join(' ');expect(text).not.toMatch(/NaN|Infinity|undefined/);if(['en','de','es'].includes(l))expect(text).not.toMatch(/[А-Яа-яЁёІіЇїЄє]/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}
async function verify(page:Page,p:typeof fixture.records[number]){const l=p.locale as Locale;await expect.poll(async()=>numeric(await page.getByTestId('calc-result-primary').innerText(),l)).toBe(p.expectedPrimary);const cost=page.locator('[data-testid^="calc-result-row-"] dd').filter({hasText:l==='ru'?'₽':'RUB'});await expect.poll(async()=>numeric(await cost.innerText(),l)).toBe(p.expectedCost);await clean(page,l);}
async function share(page:Page){await page.evaluate(()=>(window as unknown as{b6link:string}).b6link='');await page.getByTestId('calc-share-btn').click();await expect.poll(()=>page.evaluate(()=>(window as unknown as{b6link:string}).b6link)).not.toBe('');const u=new URL(await page.evaluate(()=>(window as unknown as{b6link:string}).b6link));expect(u.origin).toBe(new URL(page.url()).origin);expect(u.hash).toBe('#calculator');return u;}
test.beforeEach(async({context})=>{await context.route('**/*',r=>{const u=new URL(r.request().url());return ['127.0.0.1','localhost','::1'].includes(u.hostname)||['data:','blob:'].includes(u.protocol)?r.continue():r.abort();});await context.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(t:string)=>{(window as unknown as{b6link:string}).b6link=t;}}}));});
for(const p of fixture.records)for(const width of [390,1365])test(`building6 ${p.id}/${p.locale}/${width} whole purchases RUB active inputs and share reload`,async({page})=>{
 const l=p.locale as Locale,url=p.url+'?'+query(p.input);await page.setViewportSize({width,height:900});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await expect(page.locator('h1')).toHaveText(p.h1);await verify(page,p);
 const link=await share(page);for(const name of p.id==='paint-calculator'?['length','width','height','windows','doors']:p.id==='tile-calculator'||p.id==='screed-calculator'?['length','width']:p.id==='brick-calculator'?['wallLength','wallHeight']:[])expect(link.searchParams.has(name)).toBe(false);
 await page.goto(link.href);await verify(page,p);await page.reload();await verify(page,p);
 const input=page.locator('input[data-testid^="field-"]').first();await input.fill('');await expect(input).toHaveAttribute('aria-invalid','true');await expect(page.getByTestId('calc-result')).toHaveCount(0);await clean(page,l);await page.goto(url);await verify(page,p);expect(errors).toEqual([]);
});
for(const l of ['ru','en','uk','de','es'] as const){
 for(const id of ['wallpaper-calculator','paint-calculator'])for(const raw of ['1.5','9007199254740990.5'])test(`building6 ${id}/${l} raw count ${raw}`,async({page})=>{const p=fixture.records.find(p=>p.id===id&&p.locale===l)!;await page.goto(p.url+'?'+query({...p.input,mode:'room',windows:raw}));await expect(page.getByTestId('field-windows')).toHaveAttribute('aria-invalid','true');await expect(page.getByTestId('calc-result')).toHaveCount(0);await clean(page,l);});
 test(`building6 tile/${l} exact tiny glue remains nonzero`,async({page})=>{const p=fixture.records.find(p=>p.id==='tile-calculator'&&p.locale===l)!;await page.goto(p.url+'?'+query({...p.input,manualArea:.001,glueConsumption:.1,packPrice:0}));await expect.poll(async()=>numeric(await page.getByTestId('calc-result-row-3').locator('dd').innerText(),l)).toBe(.0001);await clean(page,l);});
 test(`building6 wallpaper/${l} no complete strip is a native bounded error`,async({page})=>{const p=fixture.records.find(p=>p.id==='wallpaper-calculator'&&p.locale===l)!;await page.goto(p.url+'?'+query({...p.input,height:12}));await expect(page.getByTestId('calc-result-primary')).toHaveText('—');await clean(page,l);});
 test(`building6 paint/${l} unused fractional opening counts do not block manual mode`,async({page})=>{const p=fixture.records.find(p=>p.id==='paint-calculator'&&p.locale===l)!;await page.goto(p.url+'?'+query({...p.input,windows:1.5,doors:1.5}));await expect(page.getByTestId('field-windows')).toHaveCount(0);await verify(page,p);});
}
