import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'target': 'Zielgewicht',
      'bar': 'Gewicht der Stange',
      'plates': 'Vorhandene Scheiben, ein Gewicht je Eintrag',
    },
    results: {
      'Блины на сторону': 'Scheiben je Seite',
      'Фактический вес': 'Tatsächliches Gewicht',
      'Недобор': 'Fehlbetrag',
      'На сторону': 'Je Seite',
      'Блинов на сторону': 'Zahl der Scheiben je Seite',
      'Набор на одну сторону': 'Beladung für eine Seite',
      'Блин': 'Scheibe',
      'Штук на сторону': 'Stück je Seite',
      'Всего': 'Insgesamt',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      "Без дополнительных блинов": "Keine zusätzlichen Scheiben",
      "Вес цели и грифа: от 0 до 1000 кг, не более трёх знаков после запятой": "Ziel- und Stangenmasse:0–1000 kg, höchstens drei Nachkommastellen",
      "Вес блина: до 1000 кг, не более трёх знаков после запятой": "Scheibenmasse: bis 1000 kg, höchstens drei Nachkommastellen",
      "Введите не более 32 разных весов блинов": "Höchstens 32 verschiedene Scheibenmassen eingeben",
      "Количество блинов каждого веса не ограничено. Для показанного набора нужны одинаковые пары; проверьте их наличие и вместимость грифа.": "Jeder Nennwert ist unbegrenzt verfügbar. Passende Paare und Platz auf der Stange prüfen.",

      'кг': 'kg',
      'Вес блина должен быть числом:': 'Das Scheibengewicht muss eine Zahl sein:',
      'Вес блина должен быть больше нуля': 'Das Scheibengewicht muss größer als null sein',
      'Введите доступные блины': 'Trage die vorhandenen Scheiben ein',
      'Вес грифа не может быть отрицательным': 'Das Gewicht der Stange kann nicht negativ sein',
      'Целевой вес меньше грифа': 'Das Zielgewicht liegt unter dem Gewicht der Stange',
    },
  },
  en: {
    fields: {
      "target": "Target weight",
      "bar": "Bar weight",
      "plates": "Available plates, one weight per token",
    },
    options: {},
    results: {
      "Блины на сторону": "Plates per side",
      "Фактический вес": "Actual weight",
      "Недобор": "Short by",
      "На сторону": "Per side",
      "Блинов на сторону": "Plates per side, count",
      "Набор на одну сторону": "Loading for one side",
      "Блин": "Plate",
      "Штук на сторону": "Count per side",
      "Всего": "Total",
      "Проверьте данные": "Check the values",
    },
    values: {
      "Без дополнительных блинов": "No additional plates",
      "Вес цели и грифа: от 0 до 1000 кг, не более трёх знаков после запятой": "Target and bar mass: 0–1000 kg, at most three decimal places",
      "Вес блина: до 1000 кг, не более трёх знаков после запятой": "Plate mass: up to 1000 kg, at most three decimal places",
      "Введите не более 32 разных весов блинов": "Enter at most 32 different plate masses",
      "Количество блинов каждого веса не ограничено. Для показанного набора нужны одинаковые пары; проверьте их наличие и вместимость грифа.": "Each plate denomination has unlimited quantity. The shown combination needs matching pairs; check availability and sleeve capacity.",

      "кг": "kg",
      "Вес блина должен быть числом:": "The plate weight must be a number:",
      "Вес блина должен быть больше нуля": "The plate weight must be greater than zero",
      "Введите доступные блины": "Enter the plates you have",
      "Вес грифа не может быть отрицательным": "The bar weight cannot be negative",
      "Целевой вес меньше грифа": "The target weight is lighter than the bar",
    },
  },
  uk: {
    fields: {
      "target": "Цільова вага",
      "bar": "Вага грифа",
      "plates": "Доступні млинці, по одній вазі на токен",
    },
    options: {},
    results: {
      "Блины на сторону": "Млинці на сторону",
      "Фактический вес": "Фактична вага",
      "Недобор": "Не вистачає",
      "На сторону": "На сторону",
      "Блинов на сторону": "Млинців на сторону, штук",
      "Набор на одну сторону": "Набір на одну сторону",
      "Блин": "Млинець",
      "Штук на сторону": "Штук на сторону",
      "Всего": "Усього",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "Без дополнительных блинов": "Без додаткових млинців",
      "Вес цели и грифа: от 0 до 1000 кг, не более трёх знаков после запятой": "Маса цілі й грифа:0–1000 кг, не більше трьох десяткових знаків",
      "Вес блина: до 1000 кг, не более трёх знаков после запятой": "Маса млинця: до 1000 кг, не більше трьох десяткових знаків",
      "Введите не более 32 разных весов блинов": "Введіть не більше 32 різних мас млинців",
      "Количество блинов каждого веса не ограничено. Для показанного набора нужны одинаковые пары; проверьте их наличие и вместимость грифа.": "Кількість кожного номіналу необмежена. Потрібні однакові пари; перевірте наявність і місце на грифі.",

      "кг": "кг",
      "Вес блина должен быть числом:": "Вага млинця має бути числом:",
      "Вес блина должен быть больше нуля": "Вага млинця має бути більшою за нуль",
      "Введите доступные блины": "Введіть наявні млинці",
      "Вес грифа не может быть отрицательным": "Вага грифа не може бути від'ємною",
      "Целевой вес меньше грифа": "Цільова вага менша за гриф",
    },
  },
  es: {
    fields: {
      "target": "Peso objetivo",
      "bar": "Peso de la barra",
      "plates": "Discos disponibles, un peso por elemento",
    },
    options: {},
    results: {
      "Блины на сторону": "Discos por lado",
      "Фактический вес": "Peso real",
      "Недобор": "Faltan",
      "На сторону": "Por lado",
      "Блинов на сторону": "Número de discos por lado",
      "Набор на одну сторону": "Carga de un lado",
      "Блин": "Disco",
      "Штук на сторону": "Unidades por lado",
      "Всего": "Total",
      "Проверьте данные": "Revisa los datos",
    },
    values: {
      "Без дополнительных блинов": "Sin discos adicionales",
      "Вес цели и грифа: от 0 до 1000 кг, не более трёх знаков после запятой": "Masa objetivo y barra:0–1000 kg, máximo tres decimales",
      "Вес блина: до 1000 кг, не более трёх знаков после запятой": "Masa del disco: hasta 1000 kg, máximo tres decimales",
      "Введите не более 32 разных весов блинов": "Introduce como máximo 32 masas distintas de discos",
      "Количество блинов каждого веса не ограничено. Для показанного набора нужны одинаковые пары; проверьте их наличие и вместимость грифа.": "Cada denominación tiene cantidad ilimitada. Comprueba pares iguales disponibles y espacio en la barra.",

      "кг": "kg",
      "Вес блина должен быть числом:": "El peso del disco debe ser un número:",
      "Вес блина должен быть больше нуля": "El peso del disco debe ser mayor que cero",
      "Введите доступные блины": "Introduce los discos de que dispones",
      "Вес грифа не может быть отрицательным": "El peso de la barra no puede ser negativo",
      "Целевой вес меньше грифа": "El peso objetivo es menor que el de la barra",
    },
  },
};
