import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was bekannt ist',
      'unit': 'Längeneinheit',
      'r': 'Radius',
      'd': 'Durchmesser',
      'volume': 'Volumen',
    },
    options: {
      'mm': 'Millimeter',
      'cm': 'Zentimeter',
      'm': 'Meter',
      'radius': 'der Radius',
      'diameter': 'der Durchmesser',
      'volume': 'das Volumen',
    },
    results: {
      'Объём': 'Volumen',
      'Площадь поверхности': 'Oberfläche',
      'Радиус': 'Radius',
      'Диаметр': 'Durchmesser',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'мм': 'mm',
      'см': 'cm',
      'м': 'm',
      'мм²': 'mm²',
      'см²': 'cm²',
      'м²': 'm²',
      'мм³': 'mm³',
      'см³': 'cm³',
      'м³': 'm³',
      'Радиус должен быть больше нуля': 'Der Radius muss größer als null sein',
      'Диаметр должен быть больше нуля': 'Der Durchmesser muss größer als null sein',
      'Объём должен быть больше нуля': 'Das Volumen muss größer als null sein',
    },
  },
  en: {
    fields: {
      "mode": "What is known",
      "unit": "Length unit",
      "r": "Radius",
      "d": "Diameter",
      "volume": "Volume",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "metres",
      "radius": "the radius",
      "diameter": "the diameter",
      "volume": "the volume",
    },
    results: {
      "Объём": "Volume",
      "Площадь поверхности": "Surface area",
      "Радиус": "Radius",
      "Диаметр": "Diameter",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Радиус должен быть больше нуля": "The radius must be greater than zero",
      "Диаметр должен быть больше нуля": "The diameter must be greater than zero",
      "Объём должен быть больше нуля": "The volume must be greater than zero",
    },
  },
  uk: {
    fields: {
      "mode": "Що відомо",
      "unit": "Одиниця довжини",
      "r": "Радіус",
      "d": "Діаметр",
      "volume": "Об’єм",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "метри",
      "radius": "радіус",
      "diameter": "діаметр",
      "volume": "об’єм",
    },
    results: {
      "Объём": "Об’єм",
      "Площадь поверхности": "Площа поверхні",
      "Радиус": "Радіус",
      "Диаметр": "Діаметр",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Радиус должен быть больше нуля": "Радіус має бути більшим за нуль",
      "Диаметр должен быть больше нуля": "Діаметр має бути більшим за нуль",
      "Объём должен быть больше нуля": "Об’єм має бути більшим за нуль",
    },
  },
};
