import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'parts': 'Glieder des Verhältnisses — mit Leerzeichen oder Doppelpunkten getrennt',
      'total': 'Aufzuteilender Betrag',
    },
    results: {
      'Отношение': 'Verhältnis',
      'Сумма частей': 'Summe der Glieder',
      'Доля первой части': 'Anteil des ersten Gliedes',
      'Частей': 'Glieder',
      'Сокращено на': 'Gekürzt durch',
      'Разбиение суммы': 'Aufteilung des Betrags',
      'Разбор по частям': 'Aufschlüsselung nach Gliedern',
      'Часть': 'Glied',
      'Значение': 'Wert',
      'Доля': 'Anteil',
      'Сумма': 'Betrag',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'Не число:': 'Keine Zahl:',
      'Каждая часть должна быть больше нуля': 'Jedes Glied muss größer als null sein',
      'Нужно хотя бы две части': 'Es werden mindestens zwei Glieder gebraucht',
    },
  },
  en: {
    fields: { "parts": "Ratio parts — separated by spaces or colons", "total": "Amount to divide" },
    options: {},
    results: {
      "Отношение": "Ratio",
      "Сумма частей": "Sum of the parts",
      "Доля первой части": "Share of the first part",
      "Частей": "Parts",
      "Сокращено на": "Reduced by",
      "Разбиение суммы": "Amount split",
      "Разбор по частям": "Breakdown by part",
      "Часть": "Part",
      "Значение": "Value",
      "Доля": "Share",
      "Сумма": "Amount",
      "Проверьте данные": "Check the values",
    },
    values: {
      "Не число:": "Not a number:",
      "Каждая часть должна быть больше нуля": "Every part must be greater than zero",
      "Нужно хотя бы две части": "At least two parts are needed",
    },
  },
  uk: {
    fields: { "parts": "Частини відношення — через пробіл або двокрапку", "total": "Сума для розподілу" },
    options: {},
    results: {
      "Отношение": "Відношення",
      "Сумма частей": "Сума частин",
      "Доля первой части": "Частка першої частини",
      "Частей": "Частин",
      "Сокращено на": "Скорочено на",
      "Разбиение суммы": "Розподіл суми",
      "Разбор по частям": "Розбір за частинами",
      "Часть": "Частина",
      "Значение": "Значення",
      "Доля": "Частка",
      "Сумма": "Сума",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "Не число:": "Не число:",
      "Каждая часть должна быть больше нуля": "Кожна частина має бути більшою за нуль",
      "Нужно хотя бы две части": "Потрібно щонайменше дві частини",
    },
  },
};
