import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was gesucht ist',
      'm': 'Masse, kg',
      'h': 'Höhe, m',
      'E': 'Energie, J',
      'm2': 'Masse, kg',
      'E2': 'Energie, J',
      'h2': 'Höhe, m',
    },
    options: {
      'mm': 'Millimeter',
      'cm': 'Zentimeter',
      'm': 'die Masse',
      'E': 'die Energie',
      'h': 'die Höhe',
    },
    results: {
      'Потенциальная энергия': 'Potentielle Energie',
      'Масса': 'Masse',
      'Высота': 'Höhe',
      'Ускорение свободного падения': 'Fallbeschleunigung',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'мм': 'mm',
      'см': 'cm',
      'м': 'm',
      'мм²': 'mm²',
      'см²': 'cm²',
      'м²': 'm²',
      'мм³': 'mm³',
      'см³': 'cm³',
      'м³': 'm³',
      'Дж': 'J',
      'кг': 'kg',
      'м/с²': 'm/s²',
      'Масса должна быть больше нуля': 'Die Masse muss größer als null sein',
      'Высота не может быть отрицательной': 'Die Höhe kann nicht negativ sein',
      'Энергия не может быть отрицательной': 'Die Energie kann nicht negativ sein',
      'Высота должна быть больше нуля, иначе масса не определена': 'Die Höhe muss größer als null sein, sonst ist die Masse nicht bestimmt',
    },
  },
  en: {
    fields: {
      "mode": "What to find",
      "m": "Mass, kg",
      "h": "Height, m",
      "E": "Energy, J",
      "m2": "Mass, kg",
      "E2": "Energy, J",
      "h2": "Height, m",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "the mass",
      "E": "the energy",
      "h": "the height",
    },
    results: {
      "Потенциальная энергия": "Potential energy",
      "Масса": "Mass",
      "Высота": "Height",
      "Ускорение свободного падения": "Acceleration of free fall",
      "Проверьте данные": "Check the values",
    },
    values: {
      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Дж": "J",
      "кг": "kg",
      "м/с²": "m/s²",
      "Масса должна быть больше нуля": "The mass must be greater than zero",
      "Высота не может быть отрицательной": "The height cannot be negative",
      "Энергия не может быть отрицательной": "The energy cannot be negative",
      "Высота должна быть больше нуля, иначе масса не определена": "The height must be greater than zero, otherwise the mass is undetermined",
    },
  },
  uk: {
    fields: {
      "mode": "Що знайти",
      "m": "Маса, кг",
      "h": "Висота, м",
      "E": "Енергія, Дж",
      "m2": "Маса, кг",
      "E2": "Енергія, Дж",
      "h2": "Висота, м",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "масу",
      "E": "енергію",
      "h": "висоту",
    },
    results: {
      "Потенциальная энергия": "Потенціальна енергія",
      "Масса": "Маса",
      "Высота": "Висота",
      "Ускорение свободного падения": "Прискорення вільного падіння",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Дж": "Дж",
      "кг": "кг",
      "м/с²": "м/с²",
      "Масса должна быть больше нуля": "Маса має бути більшою за нуль",
      "Высота не может быть отрицательной": "Висота не може бути від’ємною",
      "Энергия не может быть отрицательной": "Енергія не може бути від’ємною",
      "Высота должна быть больше нуля, иначе масса не определена": "Висота має бути більшою за нуль, інакше маса не визначена",
    },
  },
};
