import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was gesucht ist',
      'm': "Masse",
      'h': "Höhe",
      'E': "Energie",
      'm2': "Masse",
      'E2': "Energie",
      'h2': "Höhe",
    },
    options: {
      'mm': 'Millimeter',
      'cm': 'Zentimeter',
      'm': "die Masse",
      'E': "die Energie",
      'h': "die Höhe",
    },
    results: {
      'Потенциальная энергия': 'Potentielle Energie',
      'Масса': 'Masse',
      'Высота': 'Höhe',
      'Ускорение свободного падения': 'Fallbeschleunigung',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      "Неизвестный режим расчёта": "Unbekannter Berechnungsmodus",
      "Введите конечные числа для выбранного режима": "Gib endliche Zahlen für den gewählten Modus ein",
      "Результат выходит за числовой диапазон": "Das Ergebnis überschreitet den Zahlenbereich",

      'мм': 'mm',
      'см': 'cm',
      'м': 'm',
      'мм²': 'mm²',
      'см²': 'cm²',
      'м²': 'm²',
      'мм³': 'mm³',
      'см³': 'cm³',
      'м³': 'm³',
      'Дж': 'J',
      'кг': 'kg',
      'м/с²': 'm/s²',
      'Масса должна быть больше нуля': 'Die Masse muss größer als null sein',
      'Высота не может быть отрицательной': 'Die Höhe kann nicht negativ sein',
      'Энергия не может быть отрицательной': 'Die Energie kann nicht negativ sein',
      'Высота должна быть больше нуля, иначе масса не определена': 'Die Höhe muss größer als null sein, sonst ist die Masse nicht bestimmt',
    },
  },
  en: {
    fields: {
      "mode": "What to find",
      "m": "Mass",
      "h": "Height",
      "E": "Energy",
      "m2": "Mass",
      "E2": "Energy",
      "h2": "Height",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "the mass",
      "E": "the energy",
      "h": "the height",
    },
    results: {
      "Потенциальная энергия": "Potential energy",
      "Масса": "Mass",
      "Высота": "Height",
      "Ускорение свободного падения": "Acceleration of free fall",
      "Проверьте данные": "Check the values",
    },
    values: {
      "Неизвестный режим расчёта": "Unknown calculation mode",
      "Введите конечные числа для выбранного режима": "Enter finite numbers for the selected mode",
      "Результат выходит за числовой диапазон": "The result exceeds the numerical range",

      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Дж": "J",
      "кг": "kg",
      "м/с²": "m/s²",
      "Масса должна быть больше нуля": "The mass must be greater than zero",
      "Высота не может быть отрицательной": "The height cannot be negative",
      "Энергия не может быть отрицательной": "The energy cannot be negative",
      "Высота должна быть больше нуля, иначе масса не определена": "The height must be greater than zero, otherwise the mass is undetermined",
    },
  },
  uk: {
    fields: {
      "mode": "Що знайти",
      "m": "Маса",
      "h": "Висота",
      "E": "Енергія",
      "m2": "Маса",
      "E2": "Енергія",
      "h2": "Висота",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "масу",
      "E": "енергію",
      "h": "висоту",
    },
    results: {
      "Потенциальная энергия": "Потенціальна енергія",
      "Масса": "Маса",
      "Высота": "Висота",
      "Ускорение свободного падения": "Прискорення вільного падіння",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "Неизвестный режим расчёта": "Невідомий режим розрахунку",
      "Введите конечные числа для выбранного режима": "Введіть скінченні числа для обраного режиму",
      "Результат выходит за числовой диапазон": "Результат виходить за числовий діапазон",

      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Дж": "Дж",
      "кг": "кг",
      "м/с²": "м/с²",
      "Масса должна быть больше нуля": "Маса має бути більшою за нуль",
      "Высота не может быть отрицательной": "Висота не може бути від’ємною",
      "Энергия не может быть отрицательной": "Енергія не може бути від’ємною",
      "Высота должна быть больше нуля, иначе масса не определена": "Висота має бути більшою за нуль, інакше маса не визначена",
    },
  },
  es: {
    fields: {
      "mode": "Qué hallar",
      "m": "Masa",
      "h": "Altura",
      "E": "Energía",
      "m2": "Masa",
      "E2": "Energía",
      "h2": "Altura",
    },
    options: {
      "E": "la energía",
      "h": "la altura",
      "m": "la masa",
      "mm": "milímetros",
      "cm": "centímetros",
    },
    results: {
      "Потенциальная энергия": "Energía potencial",
      "Масса": "Masa",
      "Высота": "Altura",
      "Ускорение свободного падения": "Aceleración de la gravedad",
      "Проверьте данные": "Revisa los datos",
    },
    values: {
      "Неизвестный режим расчёта": "Modo de cálculo desconocido",
      "Введите конечные числа для выбранного режима": "Introduce números finitos para el modo elegido",
      "Результат выходит за числовой диапазон": "El resultado supera el rango numérico",

      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Дж": "J",
      "кг": "kg",
      "м/с²": "m/s²",
      "Масса должна быть больше нуля": "La masa debe ser mayor que cero",
      "Высота не может быть отрицательной": "La altura no puede ser negativa",
      "Энергия не может быть отрицательной": "La energía no puede ser negativa",
      "Высота должна быть больше нуля, иначе масса не определена": "La altura debe ser mayor que cero; de lo contrario la masa queda indeterminada",
    },
  },
};
