// Статические таблицы UI-текстов острова калькулятора и чистые аксессоры к ним.
// Здесь нет ни состояния, ни эффектов, ни DOM — только данные и выбор локали.
//
// Модуль сознательно не импортирует lib/i18n: там лежат build-time таблицы на
// тысячи строк, и любой их импорт из клиентского острова утащил бы их в браузерный
// бандл. Клиентская часть локалей живёт в lib/clientI18n.

import type { Locale } from '../../../lib/clientI18n';

export type CalculatorCopy = {
  enterNumber: string;
  minimum: (value: number) => string;
  maximum: (value: number) => string;
  note: string;
  dateHelp: string;
  textareaHelp: string;
  rateHelp: string;
  amountHelp: string;
  integerHelp: string;
  unitHelp: string;
  reserveHelp: string;
  editInputs: string;
  printResult: string;
  resultCopied: string;
  copyResult: string;
  tableCaption: string;
  inputs: string;
  fieldCounter: (count: number) => string;
  calculate: string;
  reset: string;
  linkCopied: string;
  copyLink: string;
  checkValues: string;
  result: string;
  unavailableTitle: string;
  unavailableText: string;
  emptyText: string;
};

const calculatorCopyByLocale: Record<Locale, CalculatorCopy> = {
  ru: {
    enterNumber: 'Введите число.',
    minimum: (value) => `Минимум ${value}.`,
    maximum: (value) => `Максимум ${value}.`,
    note: 'Примечание',
    dateHelp: 'Можно выбрать дату вручную или ввести с клавиатуры.',
    textareaHelp: 'Указывайте значения в формате, показанном в подписи поля.',
    rateHelp: 'Укажите годовую или выбранную в списке ставку без лишних символов.',
    amountHelp: 'Можно использовать пробелы для тысяч и запятую или точку для дробной части.',
    integerHelp: 'Используйте целое значение, если в поле не указано другое.',
    unitHelp: 'Проверьте единицы измерения: они указаны в названии или рядом с полем.',
    reserveHelp: 'Обычно для запаса используют 5-15%, в зависимости от задачи.',
    editInputs: 'Изменить исходные данные',
    printResult: 'Распечатать результат',
    resultCopied: 'Результат скопирован',
    copyResult: 'Скопировать результат',
    tableCaption: 'Таблица результата расчета',
    inputs: 'Исходные данные',
    fieldCounter: (count) => `${count} полей`,
    calculate: 'Рассчитать',
    reset: 'Сбросить',
    linkCopied: 'Ссылка скопирована',
    copyLink: 'Скопировать ссылку',
    checkValues: 'Проверьте значения',
    result: 'Результат',
    unavailableTitle: 'Расчёт временно недоступен',
    unavailableText: 'Исправьте значения в полях формы, и результат появится автоматически.',
    emptyText: 'Заполните поля — результат появится здесь автоматически.',
  },
  en: {
    enterNumber: 'Enter a number.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maximum ${value}.`,
    note: 'Note',
    dateHelp: 'Choose a date or type it manually.',
    textareaHelp: 'Use the format shown in the field description.',
    rateHelp: 'Enter the annual or selected rate without extra symbols.',
    amountHelp: 'Thousands separators and either a decimal point or comma are accepted.',
    integerHelp: 'Use a whole number unless the field says otherwise.',
    unitHelp: 'Check the measurement units shown in or near the field.',
    reserveHelp: 'A reserve of 5-15% is common, depending on the task.',
    editInputs: 'Edit inputs',
    printResult: 'Print result',
    resultCopied: 'Result copied',
    copyResult: 'Copy result',
    tableCaption: 'Calculation result table',
    inputs: 'Inputs',
    fieldCounter: (count) => `${count} fields`,
    calculate: 'Calculate',
    reset: 'Reset',
    linkCopied: 'Link copied',
    copyLink: 'Copy link',
    checkValues: 'Check values',
    result: 'Result',
    unavailableTitle: 'Calculation is temporarily unavailable',
    unavailableText: 'Fix the form values and the result will appear automatically.',
    emptyText: 'Fill in the fields and the result will appear here automatically.',
  },
  es: {
    enterNumber: 'Introduce un número.',
    minimum: (value) => `Mínimo ${value}.`,
    maximum: (value) => `Máximo ${value}.`,
    note: 'Nota',
    dateHelp: 'Elige una fecha o escríbela manualmente.',
    textareaHelp: 'Usa el formato indicado en la descripción del campo.',
    rateHelp: 'Introduce la tasa anual o seleccionada sin símbolos adicionales.',
    amountHelp: 'Introduce el valor base sin separadores de miles.',
    integerHelp: 'Usa un número entero salvo que el campo indique otra cosa.',
    unitHelp: 'Comprueba las unidades de medida que aparecen junto al campo.',
    reserveHelp: 'Una reserva del 5-15% suele ser habitual, según la tarea.',
    editInputs: 'Editar datos',
    printResult: 'Imprimir resultado',
    resultCopied: 'Resultado copiado',
    copyResult: 'Copiar resultado',
    tableCaption: 'Tabla del resultado del cálculo',
    inputs: 'Datos de entrada',
    fieldCounter: (count) => `${count} campos`,
    calculate: 'Calcular',
    reset: 'Restablecer',
    linkCopied: 'Enlace copiado',
    copyLink: 'Copiar enlace',
    checkValues: 'Comprueba los valores',
    result: 'Resultado',
    unavailableTitle: 'El cálculo no está disponible temporalmente',
    unavailableText: 'Corrige los valores del formulario y el resultado aparecerá automáticamente.',
    emptyText: 'Rellena los campos y el resultado aparecerá aquí automáticamente.',
  },
  de: {
    enterNumber: 'Bitte eine Zahl eingeben.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maximum ${value}.`,
    note: 'Hinweis',
    dateHelp: 'Wähle ein Datum aus oder gib es manuell ein.',
    textareaHelp: 'Nutze das Format aus der Feldbeschreibung.',
    rateHelp: 'Gib den jährlichen oder gewählten Satz ohne zusätzliche Zeichen ein.',
    amountHelp: 'Gib den Basiswert ohne Tausendertrennzeichen ein.',
    integerHelp: 'Nutze eine ganze Zahl, sofern das Feld nichts anderes angibt.',
    unitHelp: 'Prüfe die Maßeinheiten, die am Feld angezeigt werden.',
    reserveHelp: 'Eine Reserve von 5-15% ist je nach Aufgabe üblich.',
    editInputs: 'Eingaben bearbeiten',
    printResult: 'Ergebnis drucken',
    resultCopied: 'Ergebnis kopiert',
    copyResult: 'Ergebnis kopieren',
    tableCaption: 'Tabelle mit dem Berechnungsergebnis',
    inputs: 'Eingaben',
    fieldCounter: (count) => `${count} Felder`,
    calculate: 'Berechnen',
    reset: 'Zurücksetzen',
    linkCopied: 'Link kopiert',
    copyLink: 'Link kopieren',
    checkValues: 'Werte prüfen',
    result: 'Ergebnis',
    unavailableTitle: 'Berechnung vorübergehend nicht verfügbar',
    unavailableText: 'Korrigiere die Formularwerte, dann erscheint das Ergebnis automatisch.',
    emptyText: 'Fülle die Felder aus, dann erscheint das Ergebnis hier automatisch.',
  },
  fr: {
    enterNumber: 'Saisissez un nombre.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maximum ${value}.`,
    note: 'Note',
    dateHelp: 'Choisissez une date ou saisissez-la manuellement.',
    textareaHelp: 'Utilisez le format indiqué dans la description du champ.',
    rateHelp: 'Saisissez le taux annuel ou sélectionné sans symboles supplémentaires.',
    amountHelp: 'Saisissez la valeur de base sans séparateurs de milliers.',
    integerHelp: 'Utilisez un nombre entier sauf indication contraire du champ.',
    unitHelp: 'Vérifiez les unités de mesure affichées près du champ.',
    reserveHelp: 'Une réserve de 5-15% est courante selon la tâche.',
    editInputs: 'Modifier les données',
    printResult: 'Imprimer le résultat',
    resultCopied: 'Résultat copié',
    copyResult: 'Copier le résultat',
    tableCaption: 'Tableau du résultat du calcul',
    inputs: 'Données de départ',
    fieldCounter: (count) => `${count} champs`,
    calculate: 'Calculer',
    reset: 'Réinitialiser',
    linkCopied: 'Lien copié',
    copyLink: 'Copier le lien',
    checkValues: 'Vérifiez les valeurs',
    result: 'Résultat',
    unavailableTitle: 'Le calcul est temporairement indisponible',
    unavailableText: 'Corrigez les valeurs du formulaire et le résultat apparaîtra automatiquement.',
    emptyText: 'Remplissez les champs et le résultat apparaîtra ici automatiquement.',
  },
  pt: {
    enterNumber: 'Introduza um número.',
    minimum: (value) => `Mínimo ${value}.`,
    maximum: (value) => `Máximo ${value}.`,
    note: 'Nota',
    dateHelp: 'Escolha uma data ou introduza-a manualmente.',
    textareaHelp: 'Use o formato indicado na descrição do campo.',
    rateHelp: 'Introduza a taxa anual ou selecionada sem símbolos adicionais.',
    amountHelp: 'Introduza o valor base sem separadores de milhares.',
    integerHelp: 'Use um número inteiro salvo indicação em contrário.',
    unitHelp: 'Verifique as unidades de medida apresentadas junto ao campo.',
    reserveHelp: 'Uma reserva de 5-15% é comum, dependendo da tarefa.',
    editInputs: 'Editar dados',
    printResult: 'Imprimir resultado',
    resultCopied: 'Resultado copiado',
    copyResult: 'Copiar resultado',
    tableCaption: 'Tabela do resultado do cálculo',
    inputs: 'Dados de entrada',
    fieldCounter: (count) => `${count} campos`,
    calculate: 'Calcular',
    reset: 'Repor',
    linkCopied: 'Link copiado',
    copyLink: 'Copiar link',
    checkValues: 'Verifique os valores',
    result: 'Resultado',
    unavailableTitle: 'O cálculo está temporariamente indisponível',
    unavailableText: 'Corrija os valores do formulário e o resultado aparecerá automaticamente.',
    emptyText: 'Preencha os campos e o resultado aparecerá aqui automaticamente.',
  },
  it: {
    enterNumber: 'Inserisci un numero.',
    minimum: (value) => `Minimo ${value}.`,
    maximum: (value) => `Massimo ${value}.`,
    note: 'Nota',
    dateHelp: 'Scegli una data o inseriscila manualmente.',
    textareaHelp: 'Usa il formato indicato nella descrizione del campo.',
    rateHelp: 'Inserisci il tasso annuale o selezionato senza simboli aggiuntivi.',
    amountHelp: 'Inserisci il valore di base senza separatori delle migliaia.',
    integerHelp: 'Usa un numero intero salvo diversa indicazione del campo.',
    unitHelp: 'Controlla le unità di misura mostrate vicino al campo.',
    reserveHelp: 'Una riserva del 5-15% è comune, a seconda dell’attività.',
    editInputs: 'Modifica dati',
    printResult: 'Stampa risultato',
    resultCopied: 'Risultato copiato',
    copyResult: 'Copia risultato',
    tableCaption: 'Tabella del risultato del calcolo',
    inputs: 'Dati di partenza',
    fieldCounter: (count) => `${count} campi`,
    calculate: 'Calcola',
    reset: 'Reimposta',
    linkCopied: 'Link copiato',
    copyLink: 'Copia link',
    checkValues: 'Controlla i valori',
    result: 'Risultato',
    unavailableTitle: 'Il calcolo è temporaneamente non disponibile',
    unavailableText: 'Correggi i valori del modulo e il risultato apparirà automaticamente.',
    emptyText: 'Compila i campi e il risultato apparirà qui automaticamente.',
  },
  pl: {
    enterNumber: 'Wpisz liczbe.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maksimum ${value}.`,
    note: 'Uwaga',
    dateHelp: 'Wybierz date albo wpisz ja recznie.',
    textareaHelp: 'Uzyj formatu pokazanego w opisie pola.',
    rateHelp: 'Wpisz roczna lub wybrana stawke bez dodatkowych symboli.',
    amountHelp: 'Wpisz wartosc bazowa bez separatorow tysiecy.',
    integerHelp: 'Uzyj liczby calkowitej, jesli pole nie wskazuje inaczej.',
    unitHelp: 'Sprawdz jednostki miary pokazane przy polu.',
    reserveHelp: 'Zapas 5-15% jest typowy, zalezy od zadania.',
    editInputs: 'Edytuj dane',
    printResult: 'Drukuj wynik',
    resultCopied: 'Wynik skopiowany',
    copyResult: 'Kopiuj wynik',
    tableCaption: 'Tabela wyniku obliczenia',
    inputs: 'Dane wejsciowe',
    fieldCounter: (count) => `${count} pol`,
    calculate: 'Oblicz',
    reset: 'Resetuj',
    linkCopied: 'Link skopiowany',
    copyLink: 'Kopiuj link',
    checkValues: 'Sprawdz wartosci',
    result: 'Wynik',
    unavailableTitle: 'Obliczenie jest tymczasowo niedostepne',
    unavailableText: 'Popraw wartosci w formularzu, a wynik pojawi sie automatycznie.',
    emptyText: 'Wypelnij pola, a wynik pojawi sie tutaj automatycznie.',
  },
  nl: {
    enterNumber: 'Voer een getal in.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maximum ${value}.`,
    note: 'Opmerking',
    dateHelp: 'Kies een datum of typ deze handmatig.',
    textareaHelp: 'Gebruik het formaat uit de veldbeschrijving.',
    rateHelp: 'Voer het jaarlijkse of gekozen tarief in zonder extra symbolen.',
    amountHelp: 'Voer de basiswaarde in zonder scheidingstekens voor duizenden.',
    integerHelp: 'Gebruik een geheel getal tenzij het veld iets anders aangeeft.',
    unitHelp: 'Controleer de meeteenheden bij het veld.',
    reserveHelp: 'Een reserve van 5-15% is gebruikelijk, afhankelijk van de taak.',
    editInputs: 'Invoer aanpassen',
    printResult: 'Resultaat printen',
    resultCopied: 'Resultaat gekopieerd',
    copyResult: 'Resultaat kopieren',
    tableCaption: 'Tabel met berekeningsresultaat',
    inputs: 'Invoer',
    fieldCounter: (count) => `${count} velden`,
    calculate: 'Berekenen',
    reset: 'Resetten',
    linkCopied: 'Link gekopieerd',
    copyLink: 'Link kopieren',
    checkValues: 'Controleer waarden',
    result: 'Resultaat',
    unavailableTitle: 'Berekening is tijdelijk niet beschikbaar',
    unavailableText: 'Corrigeer de formulierwaarden en het resultaat verschijnt automatisch.',
    emptyText: 'Vul de velden in en het resultaat verschijnt hier automatisch.',
  },
  ro: {
    enterNumber: 'Introdu un numar.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maximum ${value}.`,
    note: 'Nota',
    dateHelp: 'Alege o data sau introdu-o manual.',
    textareaHelp: 'Foloseste formatul indicat in descrierea campului.',
    rateHelp: 'Introdu rata anuala sau selectata fara simboluri suplimentare.',
    amountHelp: 'Introdu valoarea de baza fara separatoare de mii.',
    integerHelp: 'Foloseste un numar intreg daca nu este indicat altfel.',
    unitHelp: 'Verifica unitatile de masura afisate langa camp.',
    reserveHelp: 'O rezerva de 5-15% este obisnuita, in functie de situatie.',
    editInputs: 'Editeaza datele',
    printResult: 'Printeaza rezultatul',
    resultCopied: 'Rezultat copiat',
    copyResult: 'Copiaza rezultatul',
    tableCaption: 'Tabel cu rezultatul calculului',
    inputs: 'Date introduse',
    fieldCounter: (count) => `${count} campuri`,
    calculate: 'Calculeaza',
    reset: 'Reseteaza',
    linkCopied: 'Link copiat',
    copyLink: 'Copiaza linkul',
    checkValues: 'Verifica valorile',
    result: 'Rezultat',
    unavailableTitle: 'Calculul este temporar indisponibil',
    unavailableText: 'Corecteaza valorile formularului si rezultatul va aparea automat.',
    emptyText: 'Completeaza campurile si rezultatul va aparea aici automat.',
  },
  id: {
    enterNumber: 'Masukkan angka.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maksimum ${value}.`,
    note: 'Catatan',
    dateHelp: 'Pilih tanggal atau masukkan secara manual.',
    textareaHelp: 'Gunakan format yang ditunjukkan pada deskripsi kolom.',
    rateHelp: 'Masukkan suku bunga tahunan atau pilihan tanpa simbol tambahan.',
    amountHelp: 'Masukkan nilai dasar tanpa pemisah ribuan.',
    integerHelp: 'Gunakan bilangan bulat kecuali kolom menyatakan lain.',
    unitHelp: 'Periksa satuan ukuran yang ditampilkan di dekat kolom.',
    reserveHelp: 'Cadangan 5-15% umum digunakan, tergantung kebutuhan.',
    editInputs: 'Ubah input',
    printResult: 'Cetak hasil',
    resultCopied: 'Hasil disalin',
    copyResult: 'Salin hasil',
    tableCaption: 'Tabel hasil perhitungan',
    inputs: 'Input',
    fieldCounter: (count) => `${count} kolom`,
    calculate: 'Hitung',
    reset: 'Reset',
    linkCopied: 'Link disalin',
    copyLink: 'Salin link',
    checkValues: 'Periksa nilai',
    result: 'Hasil',
    unavailableTitle: 'Perhitungan sementara tidak tersedia',
    unavailableText: 'Perbaiki nilai formulir dan hasil akan muncul otomatis.',
    emptyText: 'Isi kolom dan hasil akan muncul otomatis di sini.',
  },
  tr: {
    enterNumber: 'Bir sayı girin.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maksimum ${value}.`,
    note: 'Not',
    dateHelp: 'Bir tarih seçin veya manuel girin.',
    textareaHelp: 'Alan açıklamasında gösterilen formatı kullanın.',
    rateHelp: 'Yıllık veya seçili oranı ek sembol olmadan girin.',
    amountHelp: 'Temel değeri binlik ayırıcı olmadan girin.',
    integerHelp: 'Alan aksini belirtmiyorsa tam sayı kullanın.',
    unitHelp: 'Alanın yanında gösterilen ölçü birimlerini kontrol edin.',
    reserveHelp: 'İhtiyaca göre %5-15 pay bırakmak yaygındır.',
    editInputs: 'Girdileri düzenle',
    printResult: 'Sonucu yazdır',
    resultCopied: 'Sonuç kopyalandı',
    copyResult: 'Sonucu kopyala',
    tableCaption: 'Hesaplama sonucu tablosu',
    inputs: 'Girdiler',
    fieldCounter: (count) => `${count} alan`,
    calculate: 'Hesapla',
    reset: 'Sıfırla',
    linkCopied: 'Bağlantı kopyalandı',
    copyLink: 'Bağlantıyı kopyala',
    checkValues: 'Değerleri kontrol edin',
    result: 'Sonuç',
    unavailableTitle: 'Hesaplama geçici olarak kullanılamıyor',
    unavailableText: 'Form değerlerini düzeltin, sonuç otomatik olarak görünecektir.',
    emptyText: 'Alanları doldurun, sonuç burada otomatik olarak görünecektir.',
  },
  vi: {
    enterNumber: 'Nhập một số.',
    minimum: (value) => `Tối thiểu ${value}.`,
    maximum: (value) => `Tối đa ${value}.`,
    note: 'Ghi chú',
    dateHelp: 'Chọn ngày hoặc nhập thủ công.',
    textareaHelp: 'Dùng định dạng được mô tả trong trường.',
    rateHelp: 'Nhập lãi suất năm hoặc giá trị đã chọn không kèm ký hiệu thêm.',
    amountHelp: 'Nhập giá trị gốc không dùng dấu phân cách hàng nghìn.',
    integerHelp: 'Dùng số nguyên nếu trường không yêu cầu khác.',
    unitHelp: 'Kiểm tra đơn vị đo hiển thị cạnh trường.',
    reserveHelp: 'Dự phòng 5-15% thường được dùng, tùy tình huống.',
    editInputs: 'Sửa dữ liệu',
    printResult: 'In kết quả',
    resultCopied: 'Đã sao chép kết quả',
    copyResult: 'Sao chép kết quả',
    tableCaption: 'Bảng kết quả tính toán',
    inputs: 'Dữ liệu nhập',
    fieldCounter: (count) => `${count} trường`,
    calculate: 'Tính',
    reset: 'Đặt lại',
    linkCopied: 'Đã sao chép liên kết',
    copyLink: 'Sao chép liên kết',
    checkValues: 'Kiểm tra giá trị',
    result: 'Kết quả',
    unavailableTitle: 'Phép tính tạm thời không khả dụng',
    unavailableText: 'Sửa giá trị trong biểu mẫu và kết quả sẽ tự động xuất hiện.',
    emptyText: 'Điền các trường và kết quả sẽ tự động xuất hiện ở đây.',
  },
  cs: {
    enterNumber: 'Zadejte číslo.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maximum ${value}.`,
    note: 'Poznámka',
    dateHelp: 'Vyberte datum nebo jej zadejte ručně.',
    textareaHelp: 'Použijte formát uvedený v popisu pole.',
    rateHelp: 'Zadejte roční nebo vybranou sazbu bez dalších symbolů.',
    amountHelp: 'Zadejte základní hodnotu bez oddělovačů tisíců.',
    integerHelp: 'Použijte celé číslo, pokud pole neuvádí jinak.',
    unitHelp: 'Zkontrolujte jednotky zobrazené u pole.',
    reserveHelp: 'Rezerva 5-15% se používá často, podle situace.',
    editInputs: 'Upravit vstupy',
    printResult: 'Vytisknout výsledek',
    resultCopied: 'Výsledek zkopírován',
    copyResult: 'Kopírovat výsledek',
    tableCaption: 'Tabulka výsledku výpočtu',
    inputs: 'Vstupy',
    fieldCounter: (count) => `${count} polí`,
    calculate: 'Spočítat',
    reset: 'Resetovat',
    linkCopied: 'Odkaz zkopírován',
    copyLink: 'Kopírovat odkaz',
    checkValues: 'Zkontrolujte hodnoty',
    result: 'Výsledek',
    unavailableTitle: 'Výpočet je dočasně nedostupný',
    unavailableText: 'Opravte hodnoty ve formuláři a výsledek se zobrazí automaticky.',
    emptyText: 'Vyplňte pole a výsledek se zde zobrazí automaticky.',
  },
  uk: {
    enterNumber: 'Введіть число.',
    minimum: (value) => `Мінімум ${value}.`,
    maximum: (value) => `Максимум ${value}.`,
    note: 'Примітка',
    dateHelp: 'Оберіть дату або введіть її вручну.',
    textareaHelp: 'Використовуйте формат, показаний в описі поля.',
    rateHelp: 'Введіть річну або вибрану ставку без зайвих символів.',
    amountHelp: 'Можна використовувати пробіли для тисяч і кому або крапку для дробової частини.',
    integerHelp: 'Використовуйте ціле число, якщо поле не вимагає іншого.',
    unitHelp: 'Перевірте одиниці вимірювання, показані біля поля.',
    reserveHelp: 'Запас 5-15% часто використовують залежно від ситуації.',
    editInputs: 'Змінити дані',
    printResult: 'Надрукувати результат',
    resultCopied: 'Результат скопійовано',
    copyResult: 'Скопіювати результат',
    tableCaption: 'Таблиця результату розрахунку',
    inputs: 'Вхідні дані',
    fieldCounter: (count) => `${count} полів`,
    calculate: 'Розрахувати',
    reset: 'Скинути',
    linkCopied: 'Посилання скопійовано',
    copyLink: 'Скопіювати посилання',
    checkValues: 'Перевірте значення',
    result: 'Результат',
    unavailableTitle: 'Розрахунок тимчасово недоступний',
    unavailableText: 'Виправте значення у формі, і результат зʼявиться автоматично.',
    emptyText: 'Заповніть поля, і результат автоматично зʼявиться тут.',
  },
  sk: {
    enterNumber: 'Zadajte číslo.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maximum ${value}.`,
    note: 'Poznámka',
    dateHelp: 'Vyberte dátum alebo ho zadajte ručne.',
    textareaHelp: 'Použite formát uvedený v popise poľa.',
    rateHelp: 'Zadajte ročnú alebo vybranú sadzbu bez ďalších symbolov.',
    amountHelp: 'Zadajte základnú hodnotu bez oddeľovačov tisícov.',
    integerHelp: 'Použite celé číslo, ak pole neuvádza inak.',
    unitHelp: 'Skontrolujte jednotky zobrazené pri poli.',
    reserveHelp: 'Rezerva 5-15% sa používa často podľa situácie.',
    editInputs: 'Upraviť vstupy',
    printResult: 'Vytlačiť výsledok',
    resultCopied: 'Výsledok skopírovaný',
    copyResult: 'Kopírovať výsledok',
    tableCaption: 'Tabuľka výsledku výpočtu',
    inputs: 'Vstupy',
    fieldCounter: (count) => `${count} polí`,
    calculate: 'Vypočítať',
    reset: 'Resetovať',
    linkCopied: 'Odkaz skopírovaný',
    copyLink: 'Kopírovať odkaz',
    checkValues: 'Skontrolujte hodnoty',
    result: 'Výsledok',
    unavailableTitle: 'Výpočet je dočasne nedostupný',
    unavailableText: 'Opravte hodnoty vo formulári a výsledok sa zobrazí automaticky.',
    emptyText: 'Vyplňte polia a výsledok sa tu zobrazí automaticky.',
  },
  hu: {
    enterNumber: 'Adjon meg egy számot.',
    minimum: (value) => `Minimum ${value}.`,
    maximum: (value) => `Maximum ${value}.`,
    note: 'Megjegyzés',
    dateHelp: 'Válasszon dátumot, vagy írja be kézzel.',
    textareaHelp: 'Használja a mező leírásában megadott formátumot.',
    rateHelp: 'Adja meg az éves vagy kiválasztott kamatlábat extra jelek nélkül.',
    amountHelp: 'Adja meg az alapértéket ezres elválasztók nélkül.',
    integerHelp: 'Használjon egész számot, hacsak a mező mást nem jelez.',
    unitHelp: 'Ellenőrizze a mező mellett látható mértékegységeket.',
    reserveHelp: 'Feladattól függően gyakori az 5-15% tartalék.',
    editInputs: 'Bemenetek módosítása',
    printResult: 'Eredmény nyomtatása',
    resultCopied: 'Eredmény másolva',
    copyResult: 'Eredmény másolása',
    tableCaption: 'Számítási eredmény táblázata',
    inputs: 'Bemenetek',
    fieldCounter: (count) => `${count} mező`,
    calculate: 'Számítás',
    reset: 'Visszaállítás',
    linkCopied: 'Link másolva',
    copyLink: 'Link másolása',
    checkValues: 'Ellenőrizze az értékeket',
    result: 'Eredmény',
    unavailableTitle: 'A számítás átmenetileg nem érhető el',
    unavailableText: 'Javítsa a mezőértékeket, és az eredmény automatikusan megjelenik.',
    emptyText: 'Töltse ki a mezőket, és az eredmény automatikusan itt jelenik meg.',
  },
};

const shareWarningCopyByLocale: Partial<Record<Locale, {
  title: string;
  text: string;
  confirm: string;
  cancel: string;
}>> = {
  ru: {
    title: 'Проверьте данные перед копированием',
    text: 'Ссылка будет содержать введённые параметры. Не отправляйте её людям, которым не хотите раскрывать эти значения.',
    confirm: 'Скопировать',
    cancel: 'Отмена',
  },
  en: {
    title: 'Check the data before copying',
    text: 'The link will contain the entered parameters. Do not send it to people you do not want to share these values with.',
    confirm: 'Copy link',
    cancel: 'Cancel',
  },
  uk: {
    title: 'Перевірте дані перед копіюванням',
    text: 'Посилання міститиме введені параметри. Не надсилайте його людям, яким не хочете розкривати ці значення.',
    confirm: 'Скопіювати',
    cancel: 'Скасувати',
  },
};

export function shareWarningCopy(locale: Locale) {
  return shareWarningCopyByLocale[locale] ?? shareWarningCopyByLocale.en!;
}

export function calculatorCopy(locale: Locale): CalculatorCopy {
  return calculatorCopyByLocale[locale];
}

export function swapCopy(locale: Locale): string {
  if (locale === 'uk') return 'Поміняти валюти місцями';
  if (locale === 'ru') return 'Поменять валюты местами';
  return 'Swap currencies';
}

export function excludedDatesCopy(locale: Locale) {
  if (locale === 'ru') {
    return {
      help: 'Выберите дату и добавьте её в список. Каждую дату можно удалить отдельно.',
      add: 'Добавить дату',
      list: 'Исключаемые даты',
      remove: 'Удалить дату',
    };
  }
  if (locale === 'uk') {
    return {
      help: 'Виберіть дату й додайте її до списку. Кожну дату можна видалити окремо.',
      add: 'Додати дату',
      list: 'Виключені дати',
      remove: 'Видалити дату',
    };
  }
  return {
    help: 'Choose a date and add it to the list. Each date can be removed separately.',
    add: 'Add date',
    list: 'Excluded dates',
    remove: 'Remove date',
  };
}
