import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'total': 'Zu teilender Betrag',
      'incomes': 'Beteiligte: Name und Einkommen je Zeile',
      'mode': 'Wie geteilt wird',
    },
    options: {
      'equal': 'Zu gleichen Teilen',
      'income': 'Im Verhältnis der Einkommen',
    },
    results: {
      'Наибольший взнос': 'Größter Anteil',
      'Наименьший взнос': 'Kleinster Anteil',
      'Участников': 'Beteiligte',
      'Сумма к делению': 'Zu teilender Betrag',
      'Проверка суммы': 'Anteile ergeben zusammen',
      'Кто сколько вносит': 'Wer wie viel zahlt',
      'Участник': 'Beteiligter',
      'Доход': 'Einkommen',
      'Доля': 'Anteil',
      'Взнос': 'Beitrag',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      'Нужны имя и доход в строке:': 'In der Zeile werden Name und Einkommen gebraucht:',
      'Доход должен быть числом в строке:': 'Das Einkommen muss eine Zahl sein, in der Zeile:',
      '₽': '€',
      'Сумма к делению должна быть больше нуля': 'Der zu teilende Betrag muss größer als null sein',
      'Доход не может быть отрицательным': 'Das Einkommen kann nicht negativ sein',
      'Введите хотя бы одного участника': 'Trage mindestens einen Beteiligten ein',
      'Суммарный доход равен нулю: делить пропорционально нечему': 'Das Gesamteinkommen ist null: es gibt nichts, wonach sich anteilig teilen ließe',
    },
  },
  en: {
    fields: {
      "total": "Amount to split",
      "incomes": "Participants: name and income per line",
      "mode": "How to split",
    },
    options: { "equal": "Equally", "income": "In proportion to income" },
    results: {
      "Наибольший взнос": "Largest share",
      "Наименьший взнос": "Smallest share",
      "Участников": "Participants",
      "Сумма к делению": "Amount to split",
      "Проверка суммы": "Shares add up to",
      "Кто сколько вносит": "Who pays what",
      "Участник": "Participant",
      "Доход": "Income",
      "Доля": "Share",
      "Взнос": "Contribution",
      "Проверьте данные": "Check the values",
    },
    values: {
      "Нужны имя и доход в строке:": "Name and income are required on the line:",
      "Доход должен быть числом в строке:": "The income must be a number on the line:",
      "₽": "$",
      "Сумма к делению должна быть больше нуля": "The amount to split must be greater than zero",
      "Доход не может быть отрицательным": "Income cannot be negative",
      "Введите хотя бы одного участника": "Enter at least one participant",
      "Суммарный доход равен нулю: делить пропорционально нечему": "Total income is zero, so there is nothing to split in proportion to",
    },
  },
  uk: {
    fields: {
      "total": "Сума до поділу",
      "incomes": "Учасники: ім'я і дохід у рядку",
      "mode": "Як ділити",
    },
    options: { "equal": "Порівну", "income": "Пропорційно доходу" },
    results: {
      "Наибольший взнос": "Найбільший внесок",
      "Наименьший взнос": "Найменший внесок",
      "Участников": "Учасників",
      "Сумма к делению": "Сума до поділу",
      "Проверка суммы": "Сума внесків",
      "Кто сколько вносит": "Хто скільки вносить",
      "Участник": "Учасник",
      "Доход": "Дохід",
      "Доля": "Частка",
      "Взнос": "Внесок",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "Нужны имя и доход в строке:": "Потрібні ім'я і дохід у рядку:",
      "Доход должен быть числом в строке:": "Дохід має бути числом у рядку:",
      "₽": "₴",
      "Сумма к делению должна быть больше нуля": "Сума до поділу має бути більшою за нуль",
      "Доход не может быть отрицательным": "Дохід не може бути від'ємним",
      "Введите хотя бы одного участника": "Введіть хоча б одного учасника",
      "Суммарный доход равен нулю: делить пропорционально нечему": "Сумарний дохід дорівнює нулю, тож ділити пропорційно немає чого",
    },
  },
};
