// СГЕНЕРИРОВАНО. Не редактировать руками.
// Общие фразы результата, отобранные под наследственный калькулятор eur-to-mdl.
// Перегенерировать: npm run calculators:generate

import type { CalculatorLocalization } from '../../../../lib/platform/types';

export const shared: CalculatorLocalization = {
  en: {
    results: {
      'Результат': 'Result',
      'Курс': 'Rate',
      'Из': 'From',
      'В': 'To',
      'Тип курса': 'Rate type',
      'Дата обновления': 'Update date',
      'Статус обновления': 'Update status',
      'Последняя попытка обновления': 'Last update attempt',
      'Источник': 'Source',
      'Резервный источник': 'Fallback source',
      'Ошибка': 'Error',
    },
    values: {
      'сохранённый справочный курс': 'saved reference rate',
      'Это не курс в реальном времени. Используются сохранённые справочные курсы указанных источников; резервный источник отмечен отдельно. Банки и обменные пункты могут использовать другие курсы и комиссии.': 'These are not real-time rates. The calculation uses saved reference rates from the listed sources; any fallback source is marked separately. Banks and exchange services may use different rates and fees.',
      'Сохранённые курсы прошли последнюю проверку источников.': 'The saved rates passed the latest source check.',
      'Курсы одного или нескольких источников могут быть устаревшими. Проверьте даты источников.': 'One or more source rates may be stale. Check the source dates.',
      'Последняя проверка источников не удалась. Используются последние сохранённые курсы.': 'The latest source check failed. The last saved rates are being used.',
      'Европейский центральный банк': 'European Central Bank',
      'Национальный банк Украины': 'National Bank of Ukraine',
      'Национальный банк Молдовы': 'National Bank of Moldova',
      'Exchange Rate API': 'Exchange Rate API',
      'Основной источник был недоступен, курс получен из резервного.': 'The primary source was unavailable, so this rate came from the fallback source.',
      'Сохранённые курсы проверены; часть валют получена из резервного источника.': 'The saved rates were checked; some currencies came from a fallback source.',
      'Доллар США': 'US dollar',
      'Евро': 'Euro',
      'Молдавский лей': 'Moldovan leu',
      'Румынский лей': 'Romanian leu',
      'Гривна': 'Ukrainian hryvnia',
      'Польский злотый': 'Polish zloty',
      'Фунт стерлингов': 'Pound sterling',
      'Швейцарский франк': 'Swiss franc',
      'Турецкая лира': 'Turkish lira',
      'Неизвестная валюта': 'Unknown currency',
    },
  },
  uk: {
    results: {
      'Результат': 'Результат',
      'Курс': 'Курс',
      'Из': 'З',
      'В': 'У',
      'Тип курса': 'Тип курсу',
      'Дата обновления': 'Дата оновлення',
      'Статус обновления': 'Статус оновлення',
      'Последняя попытка обновления': 'Остання спроба оновлення',
      'Источник': 'Джерело',
      'Резервный источник': 'Резервне джерело',
      'Ошибка': 'Помилка',
    },
    values: {
      'сохранённый справочный курс': 'збережений довідковий курс',
      'Это не курс в реальном времени. Используются сохранённые справочные курсы указанных источников; резервный источник отмечен отдельно. Банки и обменные пункты могут использовать другие курсы и комиссии.': 'Це не курс у реальному часі. Використовуються збережені довідкові курси зазначених джерел; резервне джерело позначено окремо. Банки та обмінні сервіси можуть застосовувати інші курси й комісії.',
      'Сохранённые курсы прошли последнюю проверку источников.': 'Збережені курси пройшли останню перевірку джерел.',
      'Курсы одного или нескольких источников могут быть устаревшими. Проверьте даты источников.': 'Курси одного або кількох джерел можуть бути застарілими. Перевірте дати джерел.',
      'Последняя проверка источников не удалась. Используются последние сохранённые курсы.': 'Остання перевірка джерел не вдалася. Використовуються останні збережені курси.',
      'Европейский центральный банк': 'Європейський центральний банк',
      'Национальный банк Украины': 'Національний банк України',
      'Национальный банк Молдовы': 'Національний банк Молдови',
      'Exchange Rate API': 'Exchange Rate API',
      'Основной источник был недоступен, курс получен из резервного.': 'Основне джерело було недоступне, тому курс отримано з резервного.',
      'Сохранённые курсы проверены; часть валют получена из резервного источника.': 'Збережені курси перевірено; частину валют отримано з резервного джерела.',
      'Доллар США': 'Долар США',
      'Евро': 'Євро',
      'Молдавский лей': 'Молдовський лей',
      'Румынский лей': 'Румунський лей',
      'Гривна': 'Українська гривня',
      'Польский злотый': 'Польський злотий',
      'Фунт стерлингов': 'Фунт стерлінгів',
      'Швейцарский франк': 'Швейцарський франк',
      'Турецкая лира': 'Турецька ліра',
      'Неизвестная валюта': 'Невідома валюта',
    },
  },
  de: {
    results: {
      'Результат': 'Ergebnis',
      'Курс': 'Wechselkurs',
      'Из': 'Von',
      'В': 'Nach',
      'Тип курса': 'Art des Kurses',
      'Дата обновления': 'Stand vom',
      'Статус обновления': 'Stand der Aktualisierung',
      'Последняя попытка обновления': 'Letzter Aktualisierungsversuch',
      'Источник': 'Quelle',
      'Резервный источник': 'Ersatzquelle',
      'Ошибка': 'Fehler',
    },
    values: {
      'сохранённый справочный курс': 'gespeicherter Referenzkurs',
      'Это не курс в реальном времени. Используются сохранённые справочные курсы указанных источников; резервный источник отмечен отдельно. Банки и обменные пункты могут использовать другие курсы и комиссии.': 'Das sind keine Echtzeitkurse. Verwendet werden gespeicherte Referenzkurse der genannten Quellen; eine Ersatzquelle ist gesondert gekennzeichnet. Banken und Wechselstuben können andere Kurse und Gebühren ansetzen.',
      'Сохранённые курсы прошли последнюю проверку источников.': 'Die gespeicherten Kurse haben die letzte Quellenprüfung bestanden.',
      'Курсы одного или нескольких источников могут быть устаревшими. Проверьте даты источников.': 'Ein oder mehrere Quellkurse könnten veraltet sein. Prüfe die Daten der Quellen.',
      'Последняя проверка источников не удалась. Используются последние сохранённые курсы.': 'Die letzte Quellenprüfung ist fehlgeschlagen. Die zuletzt gespeicherten Kurse werden verwendet.',
      'Европейский центральный банк': 'Europäische Zentralbank',
      'Национальный банк Украины': 'Nationalbank der Ukraine',
      'Национальный банк Молдовы': 'Nationalbank der Republik Moldau',
      'Exchange Rate API': 'Exchange Rate API',
      'Основной источник был недоступен, курс получен из резервного.': 'Die Hauptquelle war nicht erreichbar, der Kurs stammt aus der Ersatzquelle.',
      'Сохранённые курсы проверены; часть валют получена из резервного источника.': 'Die gespeicherten Kurse wurden geprüft; ein Teil der Währungen stammt aus einer Ersatzquelle.',
      'Доллар США': 'US-Dollar',
      'Евро': 'Euro',
      'Молдавский лей': 'Moldauischer Leu',
      'Румынский лей': 'Rumänischer Leu',
      'Гривна': 'Hrywnja',
      'Польский злотый': 'Polnischer Złoty',
      'Фунт стерлингов': 'Pfund Sterling',
      'Швейцарский франк': 'Schweizer Franken',
      'Турецкая лира': 'Türkische Lira',
      'Неизвестная валюта': 'Unbekannte Währung',
    },
  },
  es: {
    results: {
      'Результат': 'Resultado',
      'Курс': 'Tipo de cambio',
      'Из': 'De',
      'В': 'A',
      'Тип курса': 'Tipo de referencia',
      'Дата обновления': 'Fecha de actualización',
      'Статус обновления': 'Estado de la actualización',
      'Последняя попытка обновления': 'Último intento de actualización',
      'Источник': 'Fuente',
      'Резервный источник': 'Fuente de reserva',
      'Ошибка': 'Error',
    },
    values: {
      'сохранённый справочный курс': 'tipo de referencia guardado',
      'Это не курс в реальном времени. Используются сохранённые справочные курсы указанных источников; резервный источник отмечен отдельно. Банки и обменные пункты могут использовать другие курсы и комиссии.': 'Estos no son tipos en tiempo real. Se usan tipos de referencia guardados de las fuentes indicadas; cualquier fuente de reserva se señala por separado. Los bancos y las casas de cambio pueden aplicar otros tipos y comisiones.',
      'Сохранённые курсы прошли последнюю проверку источников.': 'Los tipos guardados superaron la última comprobación de fuentes.',
      'Курсы одного или нескольких источников могут быть устаревшими. Проверьте даты источников.': 'Uno o varios tipos pueden estar desactualizados. Comprueba las fechas de las fuentes.',
      'Последняя проверка источников не удалась. Используются последние сохранённые курсы.': 'La última comprobación de fuentes falló. Se utilizan los últimos tipos guardados.',
      'Европейский центральный банк': 'Banco Central Europeo',
      'Национальный банк Украины': 'Banco Nacional de Ucrania',
      'Национальный банк Молдовы': 'Banco Nacional de Moldavia',
      'Exchange Rate API': 'Exchange Rate API',
      'Основной источник был недоступен, курс получен из резервного.': 'La fuente principal no estaba disponible; el tipo se obtuvo de la de reserva.',
      'Сохранённые курсы проверены; часть валют получена из резервного источника.': 'Se comprobaron los tipos guardados; parte de las monedas procede de una fuente de reserva.',
      'Доллар США': 'Dólar estadounidense',
      'Евро': 'Euro',
      'Молдавский лей': 'Leu moldavo',
      'Румынский лей': 'Leu rumano',
      'Гривна': 'Grivna ucraniana',
      'Польский злотый': 'Esloti polaco',
      'Фунт стерлингов': 'Libra esterlina',
      'Швейцарский франк': 'Franco suizo',
      'Турецкая лира': 'Lira turca',
      'Неизвестная валюта': 'Moneda desconocida',
    },
  },
};
