import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was gesucht ist',
      'm': "Masse",
      'v': "Geschwindigkeit",
      'E': "Energie",
      'm2': "Masse",
      'E2': "Energie",
      'v2': "Geschwindigkeit",
    },
    options: {
      'mm': 'Millimeter',
      'cm': 'Zentimeter',
      'm': "die Masse",
      'E': "die Energie",
      'v': "die Geschwindigkeit",
    },
    results: {
      'Кинетическая энергия': 'Kinetische Energie',
      'Масса': 'Masse',
      'Скорость': 'Geschwindigkeit',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      "Неизвестный режим расчёта": "Unbekannter Berechnungsmodus",
      "Введите конечные числа для выбранного режима": "Gib endliche Zahlen für den gewählten Modus ein",
      "Результат выходит за числовой диапазон": "Das Ergebnis überschreitet den Zahlenbereich",

      'мм': 'mm',
      'см': 'cm',
      'м': 'm',
      'мм²': 'mm²',
      'см²': 'cm²',
      'м²': 'm²',
      'мм³': 'mm³',
      'см³': 'cm³',
      'м³': 'm³',
      'Дж': 'J',
      'кг': 'kg',
      'м/с': 'm/s',
      'Масса должна быть больше нуля': 'Die Masse muss größer als null sein',
      'Скорость не может быть отрицательной': 'Die Geschwindigkeit kann nicht negativ sein',
      'Энергия не может быть отрицательной': 'Die Energie kann nicht negativ sein',
      'Скорость должна быть больше нуля, иначе масса не определена': 'Die Geschwindigkeit muss größer als null sein, sonst ist die Masse nicht bestimmt',
    },
  },
  en: {
    fields: {
      "mode": "What to find",
      "m": "Mass",
      "v": "Speed",
      "E": "Energy",
      "m2": "Mass",
      "E2": "Energy",
      "v2": "Speed",
    },
    options: {
      "mm": "millimetres",
      "cm": "centimetres",
      "m": "the mass",
      "E": "the energy",
      "v": "the speed",
    },
    results: {
      "Кинетическая энергия": "Kinetic energy",
      "Масса": "Mass",
      "Скорость": "Speed",
      "Проверьте данные": "Check the values",
    },
    values: {
      "Неизвестный режим расчёта": "Unknown calculation mode",
      "Введите конечные числа для выбранного режима": "Enter finite numbers for the selected mode",
      "Результат выходит за числовой диапазон": "The result exceeds the numerical range",

      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Дж": "J",
      "кг": "kg",
      "м/с": "m/s",
      "Масса должна быть больше нуля": "The mass must be greater than zero",
      "Скорость не может быть отрицательной": "The speed cannot be negative",
      "Энергия не может быть отрицательной": "The energy cannot be negative",
      "Скорость должна быть больше нуля, иначе масса не определена": "The speed must be greater than zero, otherwise the mass is undetermined",
    },
  },
  uk: {
    fields: {
      "mode": "Що знайти",
      "m": "Маса",
      "v": "Швидкість",
      "E": "Енергія",
      "m2": "Маса",
      "E2": "Енергія",
      "v2": "Швидкість",
    },
    options: {
      "mm": "міліметри",
      "cm": "сантиметри",
      "m": "масу",
      "E": "енергію",
      "v": "швидкість",
    },
    results: {
      "Кинетическая энергия": "Кінетична енергія",
      "Масса": "Маса",
      "Скорость": "Швидкість",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "Неизвестный режим расчёта": "Невідомий режим розрахунку",
      "Введите конечные числа для выбранного режима": "Введіть скінченні числа для обраного режиму",
      "Результат выходит за числовой диапазон": "Результат виходить за числовий діапазон",

      "мм": "мм",
      "см": "см",
      "м": "м",
      "мм²": "мм²",
      "см²": "см²",
      "м²": "м²",
      "мм³": "мм³",
      "см³": "см³",
      "м³": "м³",
      "Дж": "Дж",
      "кг": "кг",
      "м/с": "м/с",
      "Масса должна быть больше нуля": "Маса має бути більшою за нуль",
      "Скорость не может быть отрицательной": "Швидкість не може бути від’ємною",
      "Энергия не может быть отрицательной": "Енергія не може бути від’ємною",
      "Скорость должна быть больше нуля, иначе масса не определена": "Швидкість має бути більшою за нуль, інакше маса не визначена",
    },
  },
  es: {
    fields: {
      "mode": "Qué hallar",
      "m": "Masa",
      "v": "Velocidad",
      "E": "Energía",
      "m2": "Masa",
      "E2": "Energía",
      "v2": "Velocidad",
    },
    options: {
      "E": "la energía",
      "v": "la velocidad",
      "m": "la masa",
      "mm": "milímetros",
      "cm": "centímetros",
    },
    results: {
      "Кинетическая энергия": "Energía cinética",
      "Масса": "Masa",
      "Скорость": "Velocidad",
      "Проверьте данные": "Revisa los datos",
    },
    values: {
      "Неизвестный режим расчёта": "Modo de cálculo desconocido",
      "Введите конечные числа для выбранного режима": "Introduce números finitos para el modo elegido",
      "Результат выходит за числовой диапазон": "El resultado supera el rango numérico",

      "мм": "mm",
      "см": "cm",
      "м": "m",
      "мм²": "mm²",
      "см²": "cm²",
      "м²": "m²",
      "мм³": "mm³",
      "см³": "cm³",
      "м³": "m³",
      "Дж": "J",
      "кг": "kg",
      "м/с": "m/s",
      "Масса должна быть больше нуля": "La masa debe ser mayor que cero",
      "Скорость не может быть отрицательной": "La velocidad no puede ser negativa",
      "Энергия не может быть отрицательной": "La energía no puede ser negativa",
      "Скорость должна быть больше нуля, иначе масса не определена": "La velocidad debe ser mayor que cero; de lo contrario la masa queda indeterminada",
    },
  },
};
