import type { CalculatorLocalization } from '../../lib/platform/types';

export const localization: CalculatorLocalization = {
  de: {
    fields: {
      'mode': 'Was berechnet wird',
      'favourable': 'Günstige Ausgänge',
      'total': 'Ausgänge insgesamt',
      'favourable2': 'Günstige Ausgänge',
      'total2': 'Ausgänge insgesamt',
      'p1': 'Wahrscheinlichkeit des ersten Ereignisses',
      'p2': 'Wahrscheinlichkeit des zweiten Ereignisses',
      'p3': 'Wahrscheinlichkeit des ersten Ereignisses',
      'p4': 'Wahrscheinlichkeit des zweiten Ereignisses',
    },
    options: {
      'single': 'Wahrscheinlichkeit eines Ereignisses',
      'complement': 'Wahrscheinlichkeit des Gegenereignisses',
      'independentBoth': 'beide unabhängigen Ereignisse',
      'independentEither': 'mindestens eines der beiden',
    },
    results: {
      'Вероятность': 'Wahrscheinlichkeit',
      'В процентах': 'In Prozent',
      'Шансы': 'Chancen',
      'Противоположное событие': 'Gegenereignis',
      'Проверьте данные': 'Prüfe die Werte',
    },
    values: {
      '%': '%',
      'к 1': 'zu 1',
      'Всего исходов должно быть больше нуля': 'Die Zahl der Ausgänge insgesamt muss größer als null sein',
      'Благоприятных исходов не может быть больше общего числа': 'Es kann nicht mehr günstige Ausgänge als Ausgänge insgesamt geben',
      'Исходы должны быть целыми': 'Die Ausgänge müssen ganze Zahlen sein',
      'Вероятность должна быть от 0 до 1': 'Eine Wahrscheinlichkeit muss zwischen 0 und 1 liegen',
    },
  },
  en: {
    fields: {
      "mode": "What to compute",
      "favourable": "Favourable outcomes",
      "total": "Total outcomes",
      "favourable2": "Favourable outcomes",
      "total2": "Total outcomes",
      "p1": "Probability of the first event",
      "p2": "Probability of the second event",
      "p3": "Probability of the first event",
      "p4": "Probability of the second event",
    },
    options: {
      "single": "probability of an event",
      "complement": "probability of the complement",
      "independentBoth": "both independent events",
      "independentEither": "at least one of the two",
    },
    results: {
      "Вероятность": "Probability",
      "В процентах": "As a percentage",
      "Шансы": "Odds",
      "Противоположное событие": "Complement",
      "Проверьте данные": "Check the values",
    },
    values: {
      "%": "%",
      "к 1": "to 1",
      "Всего исходов должно быть больше нуля": "The total number of outcomes must be greater than zero",
      "Благоприятных исходов не может быть больше общего числа": "There cannot be more favourable outcomes than outcomes in total",
      "Исходы должны быть целыми": "The outcomes must be whole numbers",
      "Вероятность должна быть от 0 до 1": "A probability must be between 0 and 1",
    },
  },
  uk: {
    fields: {
      "mode": "Що рахуємо",
      "favourable": "Сприятливих результатів",
      "total": "Усього результатів",
      "favourable2": "Сприятливих результатів",
      "total2": "Усього результатів",
      "p1": "Ймовірність першої події",
      "p2": "Ймовірність другої події",
      "p3": "Ймовірність першої події",
      "p4": "Ймовірність другої події",
    },
    options: {
      "single": "ймовірність події",
      "complement": "ймовірність протилежної",
      "independentBoth": "обидві незалежні події",
      "independentEither": "хоча б одна з двох",
    },
    results: {
      "Вероятность": "Ймовірність",
      "В процентах": "У відсотках",
      "Шансы": "Шанси",
      "Противоположное событие": "Протилежна подія",
      "Проверьте данные": "Перевірте дані",
    },
    values: {
      "%": "%",
      "к 1": "до 1",
      "Всего исходов должно быть больше нуля": "Усього результатів має бути більше нуля",
      "Благоприятных исходов не может быть больше общего числа": "Сприятливих результатів не може бути більше за загальну кількість",
      "Исходы должны быть целыми": "Результати мають бути цілими",
      "Вероятность должна быть от 0 до 1": "Ймовірність має бути від 0 до 1",
    },
  },
  es: {
    fields: {
      "mode": "Qué calcular",
      "favourable": "Casos favorables",
      "total": "Casos totales",
      "favourable2": "Casos favorables",
      "total2": "Casos totales",
      "p1": "Probabilidad del primer suceso",
      "p2": "Probabilidad del segundo suceso",
      "p3": "Probabilidad del primer suceso",
      "p4": "Probabilidad del segundo suceso",
    },
    options: {
      "single": "probabilidad de un suceso",
      "complement": "probabilidad del complementario",
      "independentBoth": "ambos sucesos independientes",
      "independentEither": "al menos uno de los dos",
    },
    results: {
      "Вероятность": "Probabilidad",
      "В процентах": "En porcentaje",
      "Шансы": "Probabilidades en contra",
      "Противоположное событие": "Suceso complementario",
      "Проверьте данные": "Revisa los datos",
    },
    values: {
      "%": "%",
      "к 1": "a 1",
      "Всего исходов должно быть больше нуля": "El número total de casos debe ser mayor que cero",
      "Благоприятных исходов не может быть больше общего числа": "No puede haber más casos favorables que casos en total",
      "Исходы должны быть целыми": "Los casos deben ser números enteros",
      "Вероятность должна быть от 0 до 1": "La probabilidad debe estar entre 0 y 1",
    },
  },
};
