// СГЕНЕРИРОВАНО. Не редактировать руками.
// Общие фразы результата, отобранные под наследственный калькулятор age-calculator.
// Перегенерировать: npm run calculators:generate

import type { CalculatorLocalization } from '../../../../lib/platform/types';

export const shared: CalculatorLocalization = {
  en: {
    results: {
      'Проверьте данные': 'Check inputs',
      'В': 'To',
      'Возраст': 'Age',
      'Полных лет': 'Full years',
      'Месяцев (сверх лет)': 'Months after years',
      'Месяцев': 'Months',
      'Дней (сверх месяцев)': 'Days after months',
      'Дней': 'Days',
      'Всего прожито дней': 'Total days lived',
      'День недели': 'Day of the week',
      'Ошибка': 'Error',
      'Месяц': 'Month',
      'День недели рождения': 'Birth weekday',
      'Следующий день рождения': 'Next birthday',
      'До дня рождения': 'Days until birthday',
    },
    values: {
      'Выберите дату рождения': 'Select a birth date',
      'Дата расчёта раньше даты рождения': 'The calculation date is before the birth date',
      'Воскресенье': 'Sunday',
      'Понедельник': 'Monday',
      'Вторник': 'Tuesday',
      'Среда': 'Wednesday',
      'Четверг': 'Thursday',
      'Пятница': 'Friday',
      'Суббота': 'Saturday',
    },
  },
  uk: {
    results: {
      'Проверьте данные': 'Перевірте дані',
      'В': 'У',
      'Возраст': 'Вік',
      'Полных лет': 'Повних років',
      'Месяцев (сверх лет)': 'Місяців понад повні роки',
      'Месяцев': 'Місяців',
      'Дней (сверх месяцев)': 'Днів понад повні місяці',
      'Дней': 'Днів',
      'Всего прожито дней': 'Усього прожито днів',
      'День недели': 'День тижня',
      'Ошибка': 'Помилка',
      'Месяц': 'Місяць',
      'День недели рождения': 'День тижня народження',
      'Следующий день рождения': 'Наступний день народження',
      'До дня рождения': 'До дня народження',
    },
    values: {
      'Выберите дату рождения': 'Оберіть дату народження',
      'Дата расчёта раньше даты рождения': 'Дата розрахунку передує даті народження',
      'Воскресенье': 'Неділя',
      'Понедельник': 'Понеділок',
      'Вторник': 'Вівторок',
      'Среда': 'Середа',
      'Четверг': 'Четвер',
      'Пятница': 'П’ятниця',
      'Суббота': 'Субота',
    },
  },
  de: {
    results: {
      'Проверьте данные': 'Prüfe die Werte',
      'В': 'Nach',
      'Возраст': 'Alter',
      'Полных лет': 'Volle Jahre',
      'Месяцев (сверх лет)': 'Monate (über die Jahre hinaus)',
      'Месяцев': 'Monate',
      'Дней (сверх месяцев)': 'Tage (über die Monate hinaus)',
      'Дней': 'Tage',
      'Всего прожито дней': 'Gelebte Tage insgesamt',
      'День недели': 'Wochentag',
      'Ошибка': 'Fehler',
      'Месяц': 'Monat',
      'День недели рождения': 'Wochentag der Geburt',
      'Следующий день рождения': 'Nächster Geburtstag',
      'До дня рождения': 'Bis zum Geburtstag',
    },
    values: {
      'Выберите дату рождения': 'Wähle ein Geburtsdatum',
      'Дата расчёта раньше даты рождения': 'Das Rechendatum liegt vor dem Geburtsdatum',
      'Воскресенье': 'Sonntag',
      'Понедельник': 'Montag',
      'Вторник': 'Dienstag',
      'Среда': 'Mittwoch',
      'Четверг': 'Donnerstag',
      'Пятница': 'Freitag',
      'Суббота': 'Samstag',
    },
  },
  es: {
    results: {
      'Проверьте данные': 'Revisa los datos',
      'Возраст': 'Edad',
      'Полных лет': 'Años cumplidos',
      'Месяцев (сверх лет)': 'Meses (además de los años)',
      'Месяцев': 'Meses',
      'Дней (сверх месяцев)': 'Días (además de los meses)',
      'Дней': 'Días',
      'Всего прожито дней': 'Días vividos en total',
      'День недели': 'Día de la semana',
      'Ошибка': 'Error',
      'Месяц': 'Mes',
      'День недели рождения': 'Día de la semana del nacimiento',
      'Следующий день рождения': 'Próximo cumpleaños',
      'До дня рождения': 'Faltan para el cumpleaños',
    },
    values: {
      'Воскресенье': 'domingo',
      'Понедельник': 'lunes',
      'Вторник': 'martes',
      'Среда': 'miércoles',
      'Четверг': 'jueves',
      'Пятница': 'viernes',
      'Суббота': 'sábado',
    },
  },
};
